using TheTechIdea.Beep.Vis.Modules;
using TheTechIdea.Beep.Winform.Controls;
using TheTechIdea.Beep.Winform.Controls.Models;

namespace TheTechIdea.Beep.Winform.Default.Views.Configuration
{
    partial class uc_diagraming
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_diagraming));
            beepSimpleTextBox1 = new BeepSimpleTextBox();
            beepMultiChipGroup1 = new BeepMultiChipGroup();
            beepTextBox1 = new BeepTextBox();
            MainTemplatePanel.SuspendLayout();
            SuspendLayout();
            // 
            // MainTemplatePanel
            // 
            MainTemplatePanel.Controls.Add(beepTextBox1);
            MainTemplatePanel.Controls.Add(beepMultiChipGroup1);
            MainTemplatePanel.Controls.Add(beepSimpleTextBox1);
            MainTemplatePanel.DrawingRect = new Rectangle(0, 0, 1005, 654);
            MainTemplatePanel.Size = new Size(1005, 654);
            // 
            // beepSimpleTextBox1
            // 
            beepSimpleTextBox1.AcceptsReturn = false;
            beepSimpleTextBox1.AcceptsTab = false;
            beepSimpleTextBox1.AnimationDuration = 500;
            beepSimpleTextBox1.AnimationType = DisplayAnimationType.None;
            beepSimpleTextBox1.ApplyThemeToChilds = false;
            beepSimpleTextBox1.ApplyThemeToImage = false;
            beepSimpleTextBox1.AutoCompleteCaseSensitive = false;
            beepSimpleTextBox1.AutoCompleteDelay = 300;
            beepSimpleTextBox1.AutoCompleteList = (List<string>)resources.GetObject("beepSimpleTextBox1.AutoCompleteList");
            beepSimpleTextBox1.AutoCompleteMaxSuggestions = 10;
            beepSimpleTextBox1.AutoCompleteMinimumLength = 1;
            beepSimpleTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            beepSimpleTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            beepSimpleTextBox1.AutoIndentEnabled = true;
            beepSimpleTextBox1.AutoScaleImage = true;
            beepSimpleTextBox1.AutoScroll = true;
            beepSimpleTextBox1.BackColor = Color.White;
            beepSimpleTextBox1.BadgeBackColor = Color.Red;
            beepSimpleTextBox1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepSimpleTextBox1.BadgeForeColor = Color.White;
            beepSimpleTextBox1.BadgeShape = BadgeShape.Circle;
            beepSimpleTextBox1.BadgeText = "";
            beepSimpleTextBox1.BlockID = null;
            beepSimpleTextBox1.BorderColor = Color.FromArgb(200, 200, 200);
            beepSimpleTextBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSimpleTextBox1.BorderRadius = 3;
            beepSimpleTextBox1.BorderStyle = BorderStyle.FixedSingle;
            beepSimpleTextBox1.BorderThickness = 1;
            beepSimpleTextBox1.BottomoffsetForDrawingRect = 0;
            beepSimpleTextBox1.BoundProperty = "Text";
            beepSimpleTextBox1.BracketMatchingEnabled = true;
            beepSimpleTextBox1.CanBeFocused = true;
            beepSimpleTextBox1.CanBeHovered = false;
            beepSimpleTextBox1.CanBePressed = true;
            beepSimpleTextBox1.Category = Utilities.DbFieldCategory.String;
            beepSimpleTextBox1.CodeFoldingEnabled = false;
            beepSimpleTextBox1.ComponentName = "BeepControl";
            beepSimpleTextBox1.CustomMask = "";
            beepSimpleTextBox1.DataSourceProperty = null;
            beepSimpleTextBox1.DateFormat = "MM/dd/yyyy";
            beepSimpleTextBox1.DisabledBackColor = Color.White;
            beepSimpleTextBox1.DisabledBorderColor = Color.Empty;
            beepSimpleTextBox1.DisabledForeColor = Color.Black;
            beepSimpleTextBox1.DrawingRect = new Rectangle(1, 1, 263, 26);
            beepSimpleTextBox1.Easing = EasingType.Linear;
            beepSimpleTextBox1.EnableRippleEffect = false;
            beepSimpleTextBox1.ExternalDrawingLayer = BeepControl.DrawingLayer.AfterAll;
            beepSimpleTextBox1.FieldID = null;
            beepSimpleTextBox1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepSimpleTextBox1.FloatingLabel = true;
            beepSimpleTextBox1.FocusBackColor = Color.White;
            beepSimpleTextBox1.FocusBorderColor = Color.RoyalBlue;
            beepSimpleTextBox1.FocusForeColor = Color.Black;
            beepSimpleTextBox1.FocusIndicatorColor = Color.Blue;
            beepSimpleTextBox1.Form = null;
            beepSimpleTextBox1.GlassmorphismBlur = 10F;
            beepSimpleTextBox1.GlassmorphismOpacity = 0.1F;
            beepSimpleTextBox1.GradientAngle = 0F;
            beepSimpleTextBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSimpleTextBox1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepSimpleTextBox1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepSimpleTextBox1.GridMode = false;
            beepSimpleTextBox1.GuidID = "2427efef-bb1c-41c8-914c-349d446b60a8";
            beepSimpleTextBox1.HelperText = "";
            beepSimpleTextBox1.HitAreaEventOn = false;
            beepSimpleTextBox1.HitTestControl = null;
            beepSimpleTextBox1.HoverBackColor = Color.White;
            beepSimpleTextBox1.HoverBorderColor = Color.Gray;
            beepSimpleTextBox1.HoveredBackcolor = Color.Wheat;
            beepSimpleTextBox1.HoverForeColor = Color.Black;
            beepSimpleTextBox1.Id = -1;
            beepSimpleTextBox1.ImageAlign = ContentAlignment.MiddleLeft;
            beepSimpleTextBox1.ImageAlignmentFixed = true;
            beepSimpleTextBox1.ImageMargin = new Padding(2);
            beepSimpleTextBox1.ImagePath = "";
            beepSimpleTextBox1.ImageTintColor = Color.Transparent;
            beepSimpleTextBox1.ImageVisible = true;
            beepSimpleTextBox1.InactiveBorderColor = Color.Gray;
            beepSimpleTextBox1.IsAcceptButton = false;
            beepSimpleTextBox1.IsApplyingMask = false;
            beepSimpleTextBox1.IsBorderAffectedByTheme = false;
            beepSimpleTextBox1.IsCancelButton = false;
            beepSimpleTextBox1.IsChild = false;
            beepSimpleTextBox1.IsCustomeBorder = false;
            beepSimpleTextBox1.IsDefault = false;
            beepSimpleTextBox1.IsDeleted = false;
            beepSimpleTextBox1.IsDirty = false;
            beepSimpleTextBox1.IsEditable = false;
            beepSimpleTextBox1.IsFocused = false;
            beepSimpleTextBox1.IsFrameless = false;
            beepSimpleTextBox1.IsHovered = false;
            beepSimpleTextBox1.IsNew = false;
            beepSimpleTextBox1.IsPressed = false;
            beepSimpleTextBox1.IsReadOnly = false;
            beepSimpleTextBox1.IsRequired = false;
            beepSimpleTextBox1.IsRounded = true;
            beepSimpleTextBox1.IsRoundedAffectedByTheme = true;
            beepSimpleTextBox1.IsSelected = false;
            beepSimpleTextBox1.IsSelectedOptionOn = false;
            beepSimpleTextBox1.IsShadowAffectedByTheme = false;
            beepSimpleTextBox1.IsVisible = false;
            beepSimpleTextBox1.Items = (List<object>)resources.GetObject("beepSimpleTextBox1.Items");
            beepSimpleTextBox1.LabelText = "";
            beepSimpleTextBox1.LeftoffsetForDrawingRect = 0;
            beepSimpleTextBox1.LineNumberBackColor = Color.FromArgb(240, 240, 240);
            beepSimpleTextBox1.LineNumberFont = new Font("Arial", 16F);
            beepSimpleTextBox1.LineNumberForeColor = Color.Gray;
            beepSimpleTextBox1.LineNumberMarginWidth = 20;
            beepSimpleTextBox1.LinkedProperty = null;
            beepSimpleTextBox1.Location = new Point(52, 73);
            beepSimpleTextBox1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepSimpleTextBox1.MaxImageSize = new Size(20, 20);
            beepSimpleTextBox1.ModernGradientType = ModernGradientType.Subtle;
            beepSimpleTextBox1.Multiline = false;
            beepSimpleTextBox1.Name = "beepSimpleTextBox1";
            beepSimpleTextBox1.OnlyCharacters = false;
            beepSimpleTextBox1.OnlyDigits = false;
            beepSimpleTextBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepSimpleTextBox1.ParentBackColor = Color.Empty;
            beepSimpleTextBox1.ParentControl = null;
            beepSimpleTextBox1.PasswordChar = '\0';
            beepSimpleTextBox1.PlaceholderText = "Enter Text Here";
            beepSimpleTextBox1.PlaceholderTextColor = Color.Gray;
            beepSimpleTextBox1.PlaceholderTextFont = "Color [Gray]";
            beepSimpleTextBox1.PressedBackColor = Color.White;
            beepSimpleTextBox1.PressedBorderColor = Color.Gray;
            beepSimpleTextBox1.PressedForeColor = Color.Gray;
            beepSimpleTextBox1.RadialCenter = (PointF)resources.GetObject("beepSimpleTextBox1.RadialCenter");
            beepSimpleTextBox1.ReadOnly = false;
            beepSimpleTextBox1.RightoffsetForDrawingRect = 0;
            beepSimpleTextBox1.SavedGuidID = null;
            beepSimpleTextBox1.SavedID = null;
            beepSimpleTextBox1.SelectedBackColor = Color.White;
            beepSimpleTextBox1.SelectedBorderColor = Color.Empty;
            beepSimpleTextBox1.SelectedForeColor = Color.Black;
            beepSimpleTextBox1.SelectedValue = null;
            beepSimpleTextBox1.SelectionBackColor = SystemColors.Highlight;
            beepSimpleTextBox1.SelectionLength = 0;
            beepSimpleTextBox1.SelectionStart = 0;
            beepSimpleTextBox1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepSimpleTextBox1.ShadowOffset = 0;
            beepSimpleTextBox1.ShadowOpacity = 0.5F;
            beepSimpleTextBox1.ShowAllBorders = true;
            beepSimpleTextBox1.ShowBottomBorder = true;
            beepSimpleTextBox1.ShowFocusIndicator = false;
            beepSimpleTextBox1.ShowLeftBorder = true;
            beepSimpleTextBox1.ShowRightBorder = true;
            beepSimpleTextBox1.ShowShadow = false;
            beepSimpleTextBox1.ShowTopBorder = true;
            beepSimpleTextBox1.ShowWhitespace = false;
            beepSimpleTextBox1.Size = new Size(265, 28);
            beepSimpleTextBox1.SlideFrom = SlideDirection.Left;
            beepSimpleTextBox1.StaticNotMoving = false;
            beepSimpleTextBox1.SyntaxHighlightingEnabled = false;
            beepSimpleTextBox1.SyntaxLanguage = Winform.Controls.Helpers.SyntaxLanguage.PlainText;
            beepSimpleTextBox1.TabIndex = 0;
            beepSimpleTextBox1.Tag = MainTemplatePanel;
            beepSimpleTextBox1.TempBackColor = Color.Empty;
            beepSimpleTextBox1.TextAlignment = HorizontalAlignment.Left;
            beepSimpleTextBox1.TextFont = new Font("Arial", 16F);
            beepSimpleTextBox1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepSimpleTextBox1.Theme = null;
            beepSimpleTextBox1.TimeFormat = "HH:mm:ss";
            beepSimpleTextBox1.ToolTipText = "";
            beepSimpleTextBox1.TopoffsetForDrawingRect = 0;
            beepSimpleTextBox1.UIAnimation = ReactUIAnimation.None;
            beepSimpleTextBox1.UIColor = ReactUIColor.Primary;
            beepSimpleTextBox1.UICustomElevation = 0;
            beepSimpleTextBox1.UIDensity = ReactUIDensity.Standard;
            beepSimpleTextBox1.UIDisabled = false;
            beepSimpleTextBox1.UIElevation = ReactUIElevation.None;
            beepSimpleTextBox1.UIFullWidth = false;
            beepSimpleTextBox1.UIShape = ReactUIShape.Rounded;
            beepSimpleTextBox1.UISize = ReactUISize.Medium;
            beepSimpleTextBox1.UIVariant = ReactUIVariant.Default;
            beepSimpleTextBox1.UseGlassmorphism = false;
            beepSimpleTextBox1.UseGradientBackground = true;
            beepSimpleTextBox1.UseSystemPasswordChar = false;
            beepSimpleTextBox1.UseThemeFont = true;
            beepSimpleTextBox1.WordWrap = false;
            // 
            // beepMultiChipGroup1
            // 
            beepMultiChipGroup1.AnimationDuration = 500;
            beepMultiChipGroup1.AnimationType = DisplayAnimationType.Fade;
            beepMultiChipGroup1.ApplyThemeToChilds = false;
            beepMultiChipGroup1.BackColor = Color.White;
            beepMultiChipGroup1.BadgeBackColor = Color.Red;
            beepMultiChipGroup1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepMultiChipGroup1.BadgeForeColor = Color.White;
            beepMultiChipGroup1.BadgeShape = BadgeShape.Circle;
            beepMultiChipGroup1.BadgeText = "";
            beepMultiChipGroup1.BlockID = null;
            beepMultiChipGroup1.BorderColor = Color.Black;
            beepMultiChipGroup1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepMultiChipGroup1.BorderRadius = 8;
            beepMultiChipGroup1.BorderStyle = BorderStyle.FixedSingle;
            beepMultiChipGroup1.BorderThickness = 1;
            beepMultiChipGroup1.BottomoffsetForDrawingRect = 0;
            beepMultiChipGroup1.BoundProperty = null;
            beepMultiChipGroup1.CanBeFocused = false;
            beepMultiChipGroup1.CanBeHovered = true;
            beepMultiChipGroup1.CanBePressed = false;
            beepMultiChipGroup1.Category = Utilities.DbFieldCategory.String;
            beepMultiChipGroup1.ComponentName = "BeepControl";
            beepMultiChipGroup1.DataSourceProperty = null;
            beepMultiChipGroup1.DisabledBackColor = Color.White;
            beepMultiChipGroup1.DisabledBorderColor = Color.Empty;
            beepMultiChipGroup1.DisabledForeColor = Color.Black;
            beepMultiChipGroup1.DrawingRect = new Rectangle(8, 8, 309, 71);
            beepMultiChipGroup1.Easing = EasingType.Linear;
            beepMultiChipGroup1.EnableRippleEffect = false;
            beepMultiChipGroup1.ExternalDrawingLayer = BeepControl.DrawingLayer.AfterAll;
            beepMultiChipGroup1.FieldID = null;
            beepMultiChipGroup1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepMultiChipGroup1.FloatingLabel = true;
            beepMultiChipGroup1.FocusBackColor = Color.White;
            beepMultiChipGroup1.FocusBorderColor = Color.RoyalBlue;
            beepMultiChipGroup1.FocusForeColor = Color.Black;
            beepMultiChipGroup1.FocusIndicatorColor = Color.Blue;
            beepMultiChipGroup1.Form = null;
            beepMultiChipGroup1.GlassmorphismBlur = 10F;
            beepMultiChipGroup1.GlassmorphismOpacity = 0.1F;
            beepMultiChipGroup1.GradientAngle = 0F;
            beepMultiChipGroup1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepMultiChipGroup1.GradientEndColor = Color.Gray;
            beepMultiChipGroup1.GradientStartColor = Color.Gray;
            beepMultiChipGroup1.GridMode = false;
            beepMultiChipGroup1.GuidID = "1738e5a2-c7aa-4f07-9e0e-cbf13559dec1";
            beepMultiChipGroup1.HelperText = "";
            beepMultiChipGroup1.HitAreaEventOn = false;
            beepMultiChipGroup1.HitTestControl = null;
            beepMultiChipGroup1.HoverBackColor = Color.White;
            beepMultiChipGroup1.HoverBorderColor = Color.Gray;
            beepMultiChipGroup1.HoveredBackcolor = Color.Wheat;
            beepMultiChipGroup1.HoverForeColor = Color.Black;
            beepMultiChipGroup1.Id = -1;
            beepMultiChipGroup1.InactiveBorderColor = Color.Gray;
            beepMultiChipGroup1.IsAcceptButton = false;
            beepMultiChipGroup1.IsBorderAffectedByTheme = true;
            beepMultiChipGroup1.IsCancelButton = false;
            beepMultiChipGroup1.IsChild = false;
            beepMultiChipGroup1.IsCustomeBorder = false;
            beepMultiChipGroup1.IsDefault = false;
            beepMultiChipGroup1.IsDeleted = false;
            beepMultiChipGroup1.IsDirty = false;
            beepMultiChipGroup1.IsEditable = false;
            beepMultiChipGroup1.IsFocused = false;
            beepMultiChipGroup1.IsFrameless = false;
            beepMultiChipGroup1.IsHovered = false;
            beepMultiChipGroup1.IsNew = false;
            beepMultiChipGroup1.IsPressed = false;
            beepMultiChipGroup1.IsReadOnly = false;
            beepMultiChipGroup1.IsRequired = false;
            beepMultiChipGroup1.IsRounded = true;
            beepMultiChipGroup1.IsRoundedAffectedByTheme = true;
            beepMultiChipGroup1.IsSelected = false;
            beepMultiChipGroup1.IsSelectedOptionOn = false;
            beepMultiChipGroup1.IsShadowAffectedByTheme = true;
            beepMultiChipGroup1.IsVisible = false;
            beepMultiChipGroup1.Items = (List<object>)resources.GetObject("beepMultiChipGroup1.Items");
            beepMultiChipGroup1.LabelText = "";
            beepMultiChipGroup1.LeftoffsetForDrawingRect = 0;
            beepMultiChipGroup1.LinkedProperty = null;
            beepMultiChipGroup1.Location = new Point(75, 284);
            beepMultiChipGroup1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepMultiChipGroup1.ModernGradientType = ModernGradientType.Subtle;
            beepMultiChipGroup1.Name = "beepMultiChipGroup1";
            beepMultiChipGroup1.OverrideFontSize = TypeStyleFontSize.None;
            beepMultiChipGroup1.Padding = new Padding(5);
            beepMultiChipGroup1.ParentBackColor = Color.Empty;
            beepMultiChipGroup1.ParentControl = null;
            beepMultiChipGroup1.PressedBackColor = Color.White;
            beepMultiChipGroup1.PressedBorderColor = Color.Gray;
            beepMultiChipGroup1.PressedForeColor = Color.Gray;
            beepMultiChipGroup1.RadialCenter = (PointF)resources.GetObject("beepMultiChipGroup1.RadialCenter");
            beepMultiChipGroup1.RightoffsetForDrawingRect = 0;
            beepMultiChipGroup1.SavedGuidID = null;
            beepMultiChipGroup1.SavedID = null;
            beepMultiChipGroup1.SelectedBackColor = Color.White;
            beepMultiChipGroup1.SelectedBorderColor = Color.Empty;
            beepMultiChipGroup1.SelectedForeColor = Color.Black;
            beepMultiChipGroup1.SelectedIndex = -1;
            beepMultiChipGroup1.SelectedItem = null;
            beepMultiChipGroup1.SelectedValue = null;
            beepMultiChipGroup1.ShadowColor = Color.Black;
            beepMultiChipGroup1.ShadowOffset = 3;
            beepMultiChipGroup1.ShadowOpacity = 0.5F;
            beepMultiChipGroup1.ShowAllBorders = false;
            beepMultiChipGroup1.ShowBottomBorder = false;
            beepMultiChipGroup1.ShowFocusIndicator = false;
            beepMultiChipGroup1.ShowLeftBorder = false;
            beepMultiChipGroup1.ShowRightBorder = false;
            beepMultiChipGroup1.ShowShadow = true;
            beepMultiChipGroup1.ShowTopBorder = false;
            beepMultiChipGroup1.Size = new Size(325, 87);
            beepMultiChipGroup1.SlideFrom = SlideDirection.Left;
            beepMultiChipGroup1.StaticNotMoving = false;
            beepMultiChipGroup1.TabIndex = 1;
            beepMultiChipGroup1.Tag = MainTemplatePanel;
            beepMultiChipGroup1.TempBackColor = Color.Empty;
            beepMultiChipGroup1.Text = "beepMultiChipGroup1";
            beepMultiChipGroup1.Theme = null;
            beepMultiChipGroup1.TitleAlignment = ContentAlignment.TopLeft;
            beepMultiChipGroup1.TitleColor = Color.Black;
            beepMultiChipGroup1.TitleFont = new Font("Segoe UI", 12F, FontStyle.Bold);
            beepMultiChipGroup1.TitleText = "Multi-Select Chip Group";
            beepMultiChipGroup1.ToolTipText = "";
            beepMultiChipGroup1.TopoffsetForDrawingRect = 0;
            beepMultiChipGroup1.UIAnimation = ReactUIAnimation.None;
            beepMultiChipGroup1.UIColor = ReactUIColor.Primary;
            beepMultiChipGroup1.UICustomElevation = 0;
            beepMultiChipGroup1.UIDensity = ReactUIDensity.Standard;
            beepMultiChipGroup1.UIDisabled = false;
            beepMultiChipGroup1.UIElevation = ReactUIElevation.None;
            beepMultiChipGroup1.UIFullWidth = false;
            beepMultiChipGroup1.UIShape = ReactUIShape.Rounded;
            beepMultiChipGroup1.UISize = ReactUISize.Medium;
            beepMultiChipGroup1.UIVariant = ReactUIVariant.Default;
            beepMultiChipGroup1.UseGlassmorphism = false;
            beepMultiChipGroup1.UseGradientBackground = true;
            beepMultiChipGroup1.UseThemeFont = true;
            // 
            // beepTextBox1
            // 
            beepTextBox1.AcceptsReturn = false;
            beepTextBox1.AcceptsTab = false;
            beepTextBox1.AnimationDuration = 500;
            beepTextBox1.AnimationType = DisplayAnimationType.None;
            beepTextBox1.ApplyThemeOnImage = false;
            beepTextBox1.ApplyThemeToChilds = false;
            beepTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            beepTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            beepTextBox1.BackColor = Color.White;
            beepTextBox1.BadgeBackColor = Color.Red;
            beepTextBox1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepTextBox1.BadgeForeColor = Color.White;
            beepTextBox1.BadgeShape = BadgeShape.Circle;
            beepTextBox1.BadgeText = "";
            beepTextBox1.BlockID = null;
            beepTextBox1.BorderColor = Color.FromArgb(200, 200, 200);
            beepTextBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepTextBox1.BorderRadius = 3;
            beepTextBox1.BorderStyle = BorderStyle.FixedSingle;
            beepTextBox1.BorderThickness = 1;
            beepTextBox1.BottomoffsetForDrawingRect = 0;
            beepTextBox1.BoundProperty = "Text";
            beepTextBox1.CanBeFocused = true;
            beepTextBox1.CanBeHovered = false;
            beepTextBox1.CanBePressed = true;
            beepTextBox1.Category = Utilities.DbFieldCategory.String;
            beepTextBox1.ComponentName = "BeepControl";
            beepTextBox1.CustomMask = "";
            beepTextBox1.DataSourceProperty = null;
            beepTextBox1.DateFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DisabledBackColor = Color.FromArgb(200, 200, 200);
            beepTextBox1.DisabledBorderColor = Color.Empty;
            beepTextBox1.DisabledForeColor = Color.Gray;
            beepTextBox1.DrawingRect = new Rectangle(4, 4, 194, 24);
            beepTextBox1.Easing = EasingType.Linear;
            beepTextBox1.EnableRippleEffect = false;
            beepTextBox1.ExternalDrawingLayer = BeepControl.DrawingLayer.AfterAll;
            beepTextBox1.FieldID = null;
            beepTextBox1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepTextBox1.FloatingLabel = true;
            beepTextBox1.FocusBackColor = Color.White;
            beepTextBox1.FocusBorderColor = Color.RoyalBlue;
            beepTextBox1.FocusForeColor = Color.Black;
            beepTextBox1.FocusIndicatorColor = Color.Blue;
            beepTextBox1.ForeColor = Color.Black;
            beepTextBox1.Form = null;
            beepTextBox1.GlassmorphismBlur = 10F;
            beepTextBox1.GlassmorphismOpacity = 0.1F;
            beepTextBox1.GradientAngle = 0F;
            beepTextBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepTextBox1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepTextBox1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepTextBox1.GridMode = false;
            beepTextBox1.GuidID = "90b4acd6-7d6e-494a-8407-29e26513ddb7";
            beepTextBox1.HelperText = "";
            beepTextBox1.HideSelection = true;
            beepTextBox1.HitAreaEventOn = false;
            beepTextBox1.HitTestControl = null;
            beepTextBox1.HoverBackColor = Color.WhiteSmoke;
            beepTextBox1.HoverBorderColor = Color.Gray;
            beepTextBox1.HoveredBackcolor = Color.Wheat;
            beepTextBox1.HoverForeColor = Color.Black;
            beepTextBox1.Id = -1;
            beepTextBox1.ImageAlign = ContentAlignment.MiddleLeft;
            beepTextBox1.ImagePath = null;
            beepTextBox1.InactiveBorderColor = Color.Gray;
            beepTextBox1.IsAcceptButton = false;
            beepTextBox1.IsBorderAffectedByTheme = false;
            beepTextBox1.IsCancelButton = false;
            beepTextBox1.IsChild = false;
            beepTextBox1.IsCustomeBorder = false;
            beepTextBox1.IsDefault = false;
            beepTextBox1.IsDeleted = false;
            beepTextBox1.IsDirty = false;
            beepTextBox1.IsEditable = false;
            beepTextBox1.IsFocused = false;
            beepTextBox1.IsFrameless = false;
            beepTextBox1.IsHovered = false;
            beepTextBox1.IsNew = false;
            beepTextBox1.IsPressed = false;
            beepTextBox1.IsReadOnly = false;
            beepTextBox1.IsRequired = false;
            beepTextBox1.IsRounded = true;
            beepTextBox1.IsRoundedAffectedByTheme = true;
            beepTextBox1.IsSelected = false;
            beepTextBox1.IsSelectedOptionOn = false;
            beepTextBox1.IsShadowAffectedByTheme = false;
            beepTextBox1.IsVisible = false;
            beepTextBox1.Items = (List<object>)resources.GetObject("beepTextBox1.Items");
            beepTextBox1.LabelText = "";
            beepTextBox1.LeftoffsetForDrawingRect = 0;
            beepTextBox1.LinkedProperty = null;
            beepTextBox1.Location = new Point(52, 129);
            beepTextBox1.MaskFormat = TextBoxMaskFormat.None;
            beepTextBox1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepTextBox1.MaxImageSize = new Size(16, 16);
            beepTextBox1.MinimumSize = new Size(30, 22);
            beepTextBox1.ModernGradientType = ModernGradientType.Subtle;
            beepTextBox1.Modified = false;
            beepTextBox1.Multiline = false;
            beepTextBox1.Name = "beepTextBox1";
            beepTextBox1.OnlyCharacters = false;
            beepTextBox1.OnlyDigits = false;
            beepTextBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepTextBox1.Padding = new Padding(3);
            beepTextBox1.ParentBackColor = Color.Empty;
            beepTextBox1.ParentControl = null;
            beepTextBox1.PasswordChar = '\0';
            beepTextBox1.PlaceholderText = "";
            beepTextBox1.PressedBackColor = Color.White;
            beepTextBox1.PressedBorderColor = Color.Gray;
            beepTextBox1.PressedForeColor = Color.Gray;
            beepTextBox1.RadialCenter = (PointF)resources.GetObject("beepTextBox1.RadialCenter");
            beepTextBox1.ReadOnly = false;
            beepTextBox1.RightoffsetForDrawingRect = 0;
            beepTextBox1.SavedGuidID = null;
            beepTextBox1.SavedID = null;
            beepTextBox1.ScrollBars = ScrollBars.None;
            beepTextBox1.SelectedBackColor = Color.White;
            beepTextBox1.SelectedBorderColor = Color.Empty;
            beepTextBox1.SelectedForeColor = Color.Black;
            beepTextBox1.SelectedValue = null;
            beepTextBox1.SelectionStart = 0;
            beepTextBox1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepTextBox1.ShadowOffset = 0;
            beepTextBox1.ShadowOpacity = 0.5F;
            beepTextBox1.ShowAllBorders = true;
            beepTextBox1.ShowBottomBorder = true;
            beepTextBox1.ShowFocusIndicator = false;
            beepTextBox1.ShowLeftBorder = true;
            beepTextBox1.ShowRightBorder = true;
            beepTextBox1.ShowScrollbars = false;
            beepTextBox1.ShowShadow = false;
            beepTextBox1.ShowTopBorder = true;
            beepTextBox1.ShowVerticalScrollBar = false;
            beepTextBox1.Size = new Size(202, 32);
            beepTextBox1.SlideFrom = SlideDirection.Left;
            beepTextBox1.StaticNotMoving = false;
            beepTextBox1.TabIndex = 2;
            beepTextBox1.Tag = MainTemplatePanel;
            beepTextBox1.TempBackColor = Color.Empty;
            beepTextBox1.Text = "beepTextBox1";
            beepTextBox1.TextAlignment = HorizontalAlignment.Left;
            beepTextBox1.TextFont = new Font("Arial", 16F);
            beepTextBox1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepTextBox1.Theme = null;
            beepTextBox1.TimeFormat = "HH:mm:ss";
            beepTextBox1.ToolTipText = "";
            beepTextBox1.TopoffsetForDrawingRect = 0;
            beepTextBox1.UIAnimation = ReactUIAnimation.None;
            beepTextBox1.UIColor = ReactUIColor.Primary;
            beepTextBox1.UICustomElevation = 0;
            beepTextBox1.UIDensity = ReactUIDensity.Standard;
            beepTextBox1.UIDisabled = false;
            beepTextBox1.UIElevation = ReactUIElevation.None;
            beepTextBox1.UIFullWidth = false;
            beepTextBox1.UIShape = ReactUIShape.Rounded;
            beepTextBox1.UISize = ReactUISize.Medium;
            beepTextBox1.UIVariant = ReactUIVariant.Default;
            beepTextBox1.UseGlassmorphism = false;
            beepTextBox1.UseGradientBackground = true;
            beepTextBox1.UseSystemPasswordChar = false;
            beepTextBox1.UseThemeFont = true;
            beepTextBox1.WordWrap = true;
            // 
            // uc_diagraming
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Margin = new Padding(6);
            Name = "uc_diagraming";
            Size = new Size(1005, 654);
            Load += uc_diagraming_Load;
            MainTemplatePanel.ResumeLayout(false);
            MainTemplatePanel.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private BeepTextBox beepTextBox1;
        private BeepMultiChipGroup beepMultiChipGroup1;
        private BeepSimpleTextBox beepSimpleTextBox1;
    }
}
