namespace TheTechIdea.Beep.Winform.Default.Views.Configuration
{
    partial class uc_diagraming
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_diagraming));
            beepCircularButton1 = new TheTechIdea.Beep.Winform.Controls.BeepCircularButton();
            beepSteppperBar1 = new TheTechIdea.Beep.Winform.Controls.BeepSteppperBar();
            beepChevronButton1 = new TheTechIdea.Beep.Winform.Controls.BeepChevronButton();
            beepStepperBreadCrumb1 = new TheTechIdea.Beep.Winform.Controls.BeepStepperBreadCrumb();
            SuspendLayout();
            // 
            // beepCircularButton1
            // 
            beepCircularButton1.AnimationDuration = 500;
            beepCircularButton1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepCircularButton1.ApplyThemeOnImage = false;
            beepCircularButton1.ApplyThemeToChilds = false;
            beepCircularButton1.BadgeBackColor = Color.Red;
            beepCircularButton1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepCircularButton1.BadgeForeColor = Color.White;
            beepCircularButton1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepCircularButton1.BadgeText = "";
            beepCircularButton1.BlockID = null;
            beepCircularButton1.BorderColor = Color.Black;
            beepCircularButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCircularButton1.BorderRadius = 8;
            beepCircularButton1.BorderStyle = BorderStyle.FixedSingle;
            beepCircularButton1.BorderThickness = 1;
            beepCircularButton1.BottomoffsetForDrawingRect = 0;
            beepCircularButton1.BoundProperty = null;
            beepCircularButton1.CanBeFocused = true;
            beepCircularButton1.CanBeHovered = false;
            beepCircularButton1.CanBePressed = true;
            beepCircularButton1.Category = Utilities.DbFieldCategory.String;
            beepCircularButton1.CircleSize = new Size(50, 50);
            beepCircularButton1.ComponentName = "beepCircularButton1";
            beepCircularButton1.DataSourceProperty = null;
            beepCircularButton1.DisabledBackColor = Color.FromArgb(233, 236, 239);
            beepCircularButton1.DisabledForeColor = Color.FromArgb(173, 181, 189);
            beepCircularButton1.DrawingRect = new Rectangle(0, 0, 73, 120);
            beepCircularButton1.Easing = Vis.Modules.EasingType.Linear;
            beepCircularButton1.FieldID = null;
            beepCircularButton1.FocusBackColor = Color.FromArgb(0, 120, 215);
            beepCircularButton1.FocusBorderColor = Color.Gray;
            beepCircularButton1.FocusForeColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.FocusIndicatorColor = Color.Blue;
            beepCircularButton1.Font = new Font("Arial", 8F);
            beepCircularButton1.ForeColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.Form = null;
            beepCircularButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCircularButton1.GradientEndColor = Color.Gray;
            beepCircularButton1.GradientStartColor = Color.Gray;
            beepCircularButton1.GuidID = "92258ee1-7f91-4399-a4b4-2a24f2aff930";
            beepCircularButton1.HideText = false;
            beepCircularButton1.HitAreaEventOn = false;
            beepCircularButton1.HitTestControl = null;
            beepCircularButton1.HoverBackColor = Color.FromArgb(30, 140, 235);
            beepCircularButton1.HoverBorderColor = Color.Gray;
            beepCircularButton1.HoveredBackcolor = Color.Wheat;
            beepCircularButton1.HoverForeColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.Id = -1;
            beepCircularButton1.ImagePath = null;
            beepCircularButton1.InactiveBorderColor = Color.Gray;
            beepCircularButton1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepCircularButton1.Info");
            beepCircularButton1.IsAcceptButton = false;
            beepCircularButton1.IsBorderAffectedByTheme = true;
            beepCircularButton1.IsCancelButton = false;
            beepCircularButton1.IsChild = true;
            beepCircularButton1.IsCustomeBorder = true;
            beepCircularButton1.IsDefault = false;
            beepCircularButton1.IsDeleted = false;
            beepCircularButton1.IsDirty = false;
            beepCircularButton1.IsEditable = false;
            beepCircularButton1.IsFocused = false;
            beepCircularButton1.IsForColorSet = false;
            beepCircularButton1.IsFrameless = false;
            beepCircularButton1.IsHovered = false;
            beepCircularButton1.IsNew = false;
            beepCircularButton1.IsPressed = false;
            beepCircularButton1.IsReadOnly = false;
            beepCircularButton1.IsRequired = false;
            beepCircularButton1.IsRounded = true;
            beepCircularButton1.IsRoundedAffectedByTheme = false;
            beepCircularButton1.IsSelected = false;
            beepCircularButton1.IsSelectedOptionOn = false;
            beepCircularButton1.IsShadowAffectedByTheme = false;
            beepCircularButton1.IsVisible = false;
            beepCircularButton1.Items = (List<object>)resources.GetObject("beepCircularButton1.Items");
            beepCircularButton1.LeftoffsetForDrawingRect = 0;
            beepCircularButton1.LinkedProperty = null;
            beepCircularButton1.Location = new Point(268, 369);
            beepCircularButton1.Name = "beepCircularButton1";
            beepCircularButton1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepCircularButton1.ParentBackColor = Color.Empty;
            beepCircularButton1.ParentControl = null;
            beepCircularButton1.PressedBackColor = Color.FromArgb(0, 100, 195);
            beepCircularButton1.PressedBorderColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.PressedForeColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.RightoffsetForDrawingRect = 0;
            beepCircularButton1.SavedGuidID = null;
            beepCircularButton1.SavedID = null;
            beepCircularButton1.SelectedBackColor = Color.White;
            beepCircularButton1.SelectedForeColor = Color.Black;
            beepCircularButton1.SelectedValue = null;
            beepCircularButton1.ShadowColor = Color.Black;
            beepCircularButton1.ShadowOffset = 0;
            beepCircularButton1.ShadowOpacity = 0.5F;
            beepCircularButton1.ShowAllBorders = false;
            beepCircularButton1.ShowBorder = true;
            beepCircularButton1.ShowBottomBorder = false;
            beepCircularButton1.ShowFocusIndicator = false;
            beepCircularButton1.ShowLeftBorder = false;
            beepCircularButton1.ShowRightBorder = false;
            beepCircularButton1.ShowShadow = false;
            beepCircularButton1.ShowTopBorder = false;
            beepCircularButton1.Size = new Size(73, 120);
            beepCircularButton1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepCircularButton1.StaticNotMoving = false;
            beepCircularButton1.TabIndex = 1;
            beepCircularButton1.TempBackColor = Color.Empty;
            beepCircularButton1.Text = "beep Circular Button1";
            beepCircularButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepCircularButton1.TextFont = new Font("Arial", 8F);
            beepCircularButton1.TextLocation = Winform.Controls.TextLocation.Below;
            beepCircularButton1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepCircularButton1.ToolTipText = "";
            beepCircularButton1.TopoffsetForDrawingRect = 0;
            beepCircularButton1.UseGradientBackground = false;
            beepCircularButton1.UseThemeFont = false;
            // 
            // beepSteppperBar1
            // 
            beepSteppperBar1.AnimationDuration = 500;
            beepSteppperBar1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepSteppperBar1.ApplyThemeToChilds = false;
            beepSteppperBar1.BackColor = Color.FromArgb(245, 245, 220);
            beepSteppperBar1.BadgeBackColor = Color.Red;
            beepSteppperBar1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepSteppperBar1.BadgeForeColor = Color.White;
            beepSteppperBar1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepSteppperBar1.BadgeText = "";
            beepSteppperBar1.BlockID = null;
            beepSteppperBar1.BorderColor = Color.FromArgb(184, 134, 11);
            beepSteppperBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSteppperBar1.BorderRadius = 8;
            beepSteppperBar1.BorderStyle = BorderStyle.FixedSingle;
            beepSteppperBar1.BorderThickness = 1;
            beepSteppperBar1.BottomoffsetForDrawingRect = 0;
            beepSteppperBar1.BoundProperty = null;
            beepSteppperBar1.ButtonSize = new Size(70, 70);
            beepSteppperBar1.CanBeFocused = true;
            beepSteppperBar1.CanBeHovered = false;
            beepSteppperBar1.CanBePressed = true;
            beepSteppperBar1.Category = Utilities.DbFieldCategory.String;
            beepSteppperBar1.CheckImage = "check.svg";
            beepSteppperBar1.ComponentName = "beepSteppperBar1";
            beepSteppperBar1.DataSourceProperty = null;
            beepSteppperBar1.DisabledBackColor = Color.White;
            beepSteppperBar1.DisabledForeColor = Color.Black;
            beepSteppperBar1.DrawingRect = new Rectangle(0, 0, 678, 122);
            beepSteppperBar1.Easing = Vis.Modules.EasingType.Linear;
            beepSteppperBar1.FieldID = null;
            beepSteppperBar1.FocusBackColor = Color.White;
            beepSteppperBar1.FocusBorderColor = Color.Gray;
            beepSteppperBar1.FocusForeColor = Color.Black;
            beepSteppperBar1.FocusIndicatorColor = Color.Blue;
            beepSteppperBar1.Form = null;
            beepSteppperBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSteppperBar1.GradientEndColor = Color.FromArgb(230, 230, 250);
            beepSteppperBar1.GradientStartColor = Color.FromArgb(245, 245, 220);
            beepSteppperBar1.GuidID = "cb723731-6666-45d2-b9a4-535c6ffacbb6";
            beepSteppperBar1.HitAreaEventOn = false;
            beepSteppperBar1.HitTestControl = null;
            beepSteppperBar1.HoverBackColor = Color.White;
            beepSteppperBar1.HoverBorderColor = Color.Gray;
            beepSteppperBar1.HoveredBackcolor = Color.Wheat;
            beepSteppperBar1.HoverForeColor = Color.Black;
            beepSteppperBar1.Id = -1;
            beepSteppperBar1.InactiveBorderColor = Color.Gray;
            beepSteppperBar1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepSteppperBar1.Info");
            beepSteppperBar1.IsAcceptButton = false;
            beepSteppperBar1.IsBorderAffectedByTheme = true;
            beepSteppperBar1.IsCancelButton = false;
            beepSteppperBar1.IsChild = false;
            beepSteppperBar1.IsCustomeBorder = false;
            beepSteppperBar1.IsDefault = false;
            beepSteppperBar1.IsDeleted = false;
            beepSteppperBar1.IsDirty = false;
            beepSteppperBar1.IsEditable = false;
            beepSteppperBar1.IsFocused = false;
            beepSteppperBar1.IsFrameless = false;
            beepSteppperBar1.IsHovered = false;
            beepSteppperBar1.IsNew = false;
            beepSteppperBar1.IsPressed = false;
            beepSteppperBar1.IsReadOnly = false;
            beepSteppperBar1.IsRequired = false;
            beepSteppperBar1.IsRounded = true;
            beepSteppperBar1.IsRoundedAffectedByTheme = true;
            beepSteppperBar1.IsSelected = false;
            beepSteppperBar1.IsSelectedOptionOn = true;
            beepSteppperBar1.IsShadowAffectedByTheme = true;
            beepSteppperBar1.IsVisible = false;
            beepSteppperBar1.Items = (List<object>)resources.GetObject("beepSteppperBar1.Items");
            beepSteppperBar1.LeftoffsetForDrawingRect = 0;
            beepSteppperBar1.LinkedProperty = null;
            beepSteppperBar1.ListItems = (System.ComponentModel.BindingList<Controls.Models.SimpleItem>)resources.GetObject("beepSteppperBar1.ListItems");
            beepSteppperBar1.Location = new Point(103, 33);
            beepSteppperBar1.MinConnectorLength = 20;
            beepSteppperBar1.Name = "beepSteppperBar1";
            beepSteppperBar1.Orientation = Orientation.Horizontal;
            beepSteppperBar1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepSteppperBar1.ParentBackColor = Color.Empty;
            beepSteppperBar1.ParentControl = null;
            beepSteppperBar1.PressedBackColor = Color.White;
            beepSteppperBar1.PressedBorderColor = Color.Gray;
            beepSteppperBar1.PressedForeColor = Color.Gray;
            beepSteppperBar1.RightoffsetForDrawingRect = 0;
            beepSteppperBar1.SavedGuidID = null;
            beepSteppperBar1.SavedID = null;
            beepSteppperBar1.SelectedBackColor = Color.White;
            beepSteppperBar1.SelectedForeColor = Color.Black;
            beepSteppperBar1.SelectedValue = null;
            beepSteppperBar1.ShadowColor = Color.FromArgb(184, 134, 11);
            beepSteppperBar1.ShadowOffset = 0;
            beepSteppperBar1.ShadowOpacity = 0.5F;
            beepSteppperBar1.ShowAllBorders = false;
            beepSteppperBar1.ShowBottomBorder = false;
            beepSteppperBar1.ShowFocusIndicator = false;
            beepSteppperBar1.ShowLeftBorder = false;
            beepSteppperBar1.ShowRightBorder = false;
            beepSteppperBar1.ShowShadow = false;
            beepSteppperBar1.ShowTopBorder = false;
            beepSteppperBar1.Size = new Size(678, 122);
            beepSteppperBar1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepSteppperBar1.StaticNotMoving = false;
            beepSteppperBar1.TabIndex = 2;
            beepSteppperBar1.TempBackColor = Color.Empty;
            beepSteppperBar1.Text = "beepSteppperBar1";
            beepSteppperBar1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepSteppperBar1.ToolTipText = "";
            beepSteppperBar1.TopoffsetForDrawingRect = 0;
            beepSteppperBar1.UseGradientBackground = false;
            beepSteppperBar1.UseThemeFont = true;
            // 
            // beepChevronButton1
            // 
            beepChevronButton1.AnimationDuration = 500;
            beepChevronButton1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepChevronButton1.ApplyThemeToChilds = false;
            beepChevronButton1.BadgeBackColor = Color.Red;
            beepChevronButton1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepChevronButton1.BadgeForeColor = Color.White;
            beepChevronButton1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepChevronButton1.BadgeText = "";
            beepChevronButton1.BlockID = null;
            beepChevronButton1.BorderColor = Color.FromArgb(173, 181, 189);
            beepChevronButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepChevronButton1.BorderRadius = 8;
            beepChevronButton1.BorderStyle = BorderStyle.FixedSingle;
            beepChevronButton1.BorderThickness = 1;
            beepChevronButton1.BottomoffsetForDrawingRect = 0;
            beepChevronButton1.BoundProperty = null;
            beepChevronButton1.CanBeFocused = true;
            beepChevronButton1.CanBeHovered = false;
            beepChevronButton1.CanBePressed = true;
            beepChevronButton1.Category = Utilities.DbFieldCategory.String;
            beepChevronButton1.ComponentName = "beepChevronButton1";
            beepChevronButton1.DataSourceProperty = null;
            beepChevronButton1.DisabledBackColor = Color.FromArgb(233, 236, 239);
            beepChevronButton1.DisabledForeColor = Color.FromArgb(173, 181, 189);
            beepChevronButton1.DrawingRect = new Rectangle(0, 0, 179, 50);
            beepChevronButton1.Easing = Vis.Modules.EasingType.Linear;
            beepChevronButton1.FieldID = null;
            beepChevronButton1.FocusBackColor = Color.FromArgb(0, 120, 215);
            beepChevronButton1.FocusBorderColor = Color.Gray;
            beepChevronButton1.FocusForeColor = Color.FromArgb(255, 255, 255);
            beepChevronButton1.FocusIndicatorColor = Color.Blue;
            beepChevronButton1.Font = new Font("Arial", 11F);
            beepChevronButton1.ForeColor = Color.FromArgb(255, 255, 255);
            beepChevronButton1.Form = null;
            beepChevronButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepChevronButton1.GradientEndColor = Color.FromArgb(255, 255, 255);
            beepChevronButton1.GradientStartColor = Color.FromArgb(245, 245, 245);
            beepChevronButton1.GuidID = "73cce18f-afde-45d4-ba78-b86c0704359c";
            beepChevronButton1.HitAreaEventOn = false;
            beepChevronButton1.HitTestControl = null;
            beepChevronButton1.HoverBackColor = Color.FromArgb(30, 140, 235);
            beepChevronButton1.HoverBorderColor = Color.Gray;
            beepChevronButton1.HoveredBackcolor = Color.Wheat;
            beepChevronButton1.HoverForeColor = Color.FromArgb(255, 255, 255);
            beepChevronButton1.Id = -1;
            beepChevronButton1.ImagePath = null;
            beepChevronButton1.InactiveBorderColor = Color.Gray;
            beepChevronButton1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepChevronButton1.Info");
            beepChevronButton1.IsAcceptButton = false;
            beepChevronButton1.IsBorderAffectedByTheme = true;
            beepChevronButton1.IsCancelButton = false;
            beepChevronButton1.IsChild = true;
            beepChevronButton1.IsCustomeBorder = true;
            beepChevronButton1.IsDefault = false;
            beepChevronButton1.IsDeleted = false;
            beepChevronButton1.IsDirty = false;
            beepChevronButton1.IsEditable = false;
            beepChevronButton1.IsFocused = false;
            beepChevronButton1.IsFrameless = false;
            beepChevronButton1.IsHovered = false;
            beepChevronButton1.IsNew = false;
            beepChevronButton1.IsPressed = false;
            beepChevronButton1.IsReadOnly = false;
            beepChevronButton1.IsRequired = false;
            beepChevronButton1.IsRounded = true;
            beepChevronButton1.IsRoundedAffectedByTheme = false;
            beepChevronButton1.IsSelected = false;
            beepChevronButton1.IsSelectedOptionOn = true;
            beepChevronButton1.IsShadowAffectedByTheme = false;
            beepChevronButton1.IsVisible = false;
            beepChevronButton1.Items = (List<object>)resources.GetObject("beepChevronButton1.Items");
            beepChevronButton1.LeftoffsetForDrawingRect = 0;
            beepChevronButton1.LinkedProperty = null;
            beepChevronButton1.Location = new Point(131, 282);
            beepChevronButton1.Name = "beepChevronButton1";
            beepChevronButton1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepChevronButton1.ParentBackColor = Color.Empty;
            beepChevronButton1.ParentControl = null;
            beepChevronButton1.PressedBackColor = Color.FromArgb(0, 100, 195);
            beepChevronButton1.PressedBorderColor = Color.FromArgb(255, 255, 255);
            beepChevronButton1.PressedForeColor = Color.FromArgb(255, 255, 255);
            beepChevronButton1.RightoffsetForDrawingRect = 0;
            beepChevronButton1.SavedGuidID = null;
            beepChevronButton1.SavedID = null;
            beepChevronButton1.SelectedBackColor = Color.White;
            beepChevronButton1.SelectedForeColor = Color.Black;
            beepChevronButton1.SelectedValue = null;
            beepChevronButton1.ShadowColor = Color.FromArgb(173, 181, 189);
            beepChevronButton1.ShadowOffset = 0;
            beepChevronButton1.ShadowOpacity = 0.5F;
            beepChevronButton1.ShowAllBorders = false;
            beepChevronButton1.ShowBottomBorder = false;
            beepChevronButton1.ShowFocusIndicator = false;
            beepChevronButton1.ShowLeftBorder = false;
            beepChevronButton1.ShowRightBorder = false;
            beepChevronButton1.ShowShadow = false;
            beepChevronButton1.ShowTopBorder = false;
            beepChevronButton1.Size = new Size(179, 50);
            beepChevronButton1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepChevronButton1.StaticNotMoving = false;
            beepChevronButton1.TabIndex = 3;
            beepChevronButton1.TempBackColor = Color.Empty;
            beepChevronButton1.Text = "beepChevronButton1";
            beepChevronButton1.TextFont = new Font("Arial", 11F);
            beepChevronButton1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepChevronButton1.ToolTipText = "";
            beepChevronButton1.TopoffsetForDrawingRect = 0;
            beepChevronButton1.UseGradientBackground = false;
            beepChevronButton1.UseThemeFont = true;
            // 
            // beepStepperBreadCrumb1
            // 
            beepStepperBreadCrumb1.AnimationDuration = 500;
            beepStepperBreadCrumb1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepStepperBreadCrumb1.ApplyThemeToChilds = false;
            beepStepperBreadCrumb1.BackColor = Color.FromArgb(245, 245, 245);
            beepStepperBreadCrumb1.BadgeBackColor = Color.Red;
            beepStepperBreadCrumb1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepStepperBreadCrumb1.BadgeForeColor = Color.White;
            beepStepperBreadCrumb1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepStepperBreadCrumb1.BadgeText = "";
            beepStepperBreadCrumb1.BlockID = null;
            beepStepperBreadCrumb1.BorderColor = Color.FromArgb(173, 181, 189);
            beepStepperBreadCrumb1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepStepperBreadCrumb1.BorderRadius = 8;
            beepStepperBreadCrumb1.BorderStyle = BorderStyle.FixedSingle;
            beepStepperBreadCrumb1.BorderThickness = 1;
            beepStepperBreadCrumb1.BottomoffsetForDrawingRect = 0;
            beepStepperBreadCrumb1.BoundProperty = null;
            beepStepperBreadCrumb1.CanBeFocused = true;
            beepStepperBreadCrumb1.CanBeHovered = false;
            beepStepperBreadCrumb1.CanBePressed = true;
            beepStepperBreadCrumb1.Category = Utilities.DbFieldCategory.String;
            beepStepperBreadCrumb1.CheckImage = "check.svg";
            beepStepperBreadCrumb1.ComponentName = "beepStepperBreadCrumb1";
            beepStepperBreadCrumb1.DataSourceProperty = null;
            beepStepperBreadCrumb1.Direction = Winform.Controls.ChevronDirection.Forward;
            beepStepperBreadCrumb1.DisabledBackColor = Color.White;
            beepStepperBreadCrumb1.DisabledForeColor = Color.Black;
            beepStepperBreadCrumb1.DrawingRect = new Rectangle(5, 5, 698, 44);
            beepStepperBreadCrumb1.Easing = Vis.Modules.EasingType.Linear;
            beepStepperBreadCrumb1.FieldID = null;
            beepStepperBreadCrumb1.FocusBackColor = Color.White;
            beepStepperBreadCrumb1.FocusBorderColor = Color.Gray;
            beepStepperBreadCrumb1.FocusForeColor = Color.Black;
            beepStepperBreadCrumb1.FocusIndicatorColor = Color.Blue;
            beepStepperBreadCrumb1.Form = null;
            beepStepperBreadCrumb1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepStepperBreadCrumb1.GradientEndColor = Color.FromArgb(255, 255, 255);
            beepStepperBreadCrumb1.GradientStartColor = Color.FromArgb(245, 245, 245);
            beepStepperBreadCrumb1.GuidID = "7b4bf993-f80f-4a4a-b648-071e136a5f4f";
            beepStepperBreadCrumb1.HitAreaEventOn = false;
            beepStepperBreadCrumb1.HitTestControl = null;
            beepStepperBreadCrumb1.HoverBackColor = Color.White;
            beepStepperBreadCrumb1.HoverBorderColor = Color.Gray;
            beepStepperBreadCrumb1.HoveredBackcolor = Color.Wheat;
            beepStepperBreadCrumb1.HoverForeColor = Color.Black;
            beepStepperBreadCrumb1.Id = -1;
            beepStepperBreadCrumb1.InactiveBorderColor = Color.Gray;
            beepStepperBreadCrumb1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepStepperBreadCrumb1.Info");
            beepStepperBreadCrumb1.IsAcceptButton = false;
            beepStepperBreadCrumb1.IsBorderAffectedByTheme = true;
            beepStepperBreadCrumb1.IsCancelButton = false;
            beepStepperBreadCrumb1.IsChild = false;
            beepStepperBreadCrumb1.IsCustomeBorder = false;
            beepStepperBreadCrumb1.IsDefault = false;
            beepStepperBreadCrumb1.IsDeleted = false;
            beepStepperBreadCrumb1.IsDirty = false;
            beepStepperBreadCrumb1.IsEditable = false;
            beepStepperBreadCrumb1.IsFocused = false;
            beepStepperBreadCrumb1.IsFrameless = false;
            beepStepperBreadCrumb1.IsHovered = false;
            beepStepperBreadCrumb1.IsNew = false;
            beepStepperBreadCrumb1.IsPressed = false;
            beepStepperBreadCrumb1.IsReadOnly = false;
            beepStepperBreadCrumb1.IsRequired = false;
            beepStepperBreadCrumb1.IsRounded = true;
            beepStepperBreadCrumb1.IsRoundedAffectedByTheme = true;
            beepStepperBreadCrumb1.IsSelected = false;
            beepStepperBreadCrumb1.IsSelectedOptionOn = true;
            beepStepperBreadCrumb1.IsShadowAffectedByTheme = true;
            beepStepperBreadCrumb1.IsVisible = false;
            beepStepperBreadCrumb1.Items = (List<object>)resources.GetObject("beepStepperBreadCrumb1.Items");
            beepStepperBreadCrumb1.LeftoffsetForDrawingRect = 0;
            beepStepperBreadCrumb1.LinkedProperty = null;
            beepStepperBreadCrumb1.ListItems = (System.ComponentModel.BindingList<Controls.Models.SimpleItem>)resources.GetObject("beepStepperBreadCrumb1.ListItems");
            beepStepperBreadCrumb1.Location = new Point(131, 203);
            beepStepperBreadCrumb1.Name = "beepStepperBreadCrumb1";
            beepStepperBreadCrumb1.Orientation = Orientation.Horizontal;
            beepStepperBreadCrumb1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepStepperBreadCrumb1.Padding = new Padding(5);
            beepStepperBreadCrumb1.ParentBackColor = Color.Empty;
            beepStepperBreadCrumb1.ParentControl = null;
            beepStepperBreadCrumb1.PressedBackColor = Color.White;
            beepStepperBreadCrumb1.PressedBorderColor = Color.Gray;
            beepStepperBreadCrumb1.PressedForeColor = Color.Gray;
            beepStepperBreadCrumb1.RightoffsetForDrawingRect = 0;
            beepStepperBreadCrumb1.SavedGuidID = null;
            beepStepperBreadCrumb1.SavedID = null;
            beepStepperBreadCrumb1.SelectedBackColor = Color.White;
            beepStepperBreadCrumb1.SelectedForeColor = Color.Black;
            beepStepperBreadCrumb1.SelectedValue = null;
            beepStepperBreadCrumb1.ShadowColor = Color.FromArgb(173, 181, 189);
            beepStepperBreadCrumb1.ShadowOffset = 0;
            beepStepperBreadCrumb1.ShadowOpacity = 0.5F;
            beepStepperBreadCrumb1.ShowAllBorders = false;
            beepStepperBreadCrumb1.ShowBottomBorder = false;
            beepStepperBreadCrumb1.ShowFocusIndicator = false;
            beepStepperBreadCrumb1.ShowLeftBorder = false;
            beepStepperBreadCrumb1.ShowRightBorder = false;
            beepStepperBreadCrumb1.ShowShadow = false;
            beepStepperBreadCrumb1.ShowTopBorder = false;
            beepStepperBreadCrumb1.Size = new Size(708, 54);
            beepStepperBreadCrumb1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepStepperBreadCrumb1.StaticNotMoving = false;
            beepStepperBreadCrumb1.TabIndex = 4;
            beepStepperBreadCrumb1.TempBackColor = Color.Empty;
            beepStepperBreadCrumb1.Text = "beepStepperBreadCrumb1";
            beepStepperBreadCrumb1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepStepperBreadCrumb1.ToolTipText = "";
            beepStepperBreadCrumb1.TopoffsetForDrawingRect = 0;
            beepStepperBreadCrumb1.UseGradientBackground = false;
            beepStepperBreadCrumb1.UseThemeFont = true;
            // 
            // uc_diagraming
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Controls.Add(beepStepperBreadCrumb1);
            Controls.Add(beepChevronButton1);
            Controls.Add(beepSteppperBar1);
            Controls.Add(beepCircularButton1);
            Name = "uc_diagraming";
            Size = new Size(948, 583);
            ResumeLayout(false);
        }

        #endregion

        private Controls.BeepCircularButton beepCircularButton1;
        private Controls.BeepSteppperBar beepSteppperBar1;
        private Controls.BeepChevronButton beepChevronButton1;
        private Controls.BeepStepperBreadCrumb beepStepperBreadCrumb1;
    }
}
