

using TheTechIdea.Beep.Vis.Modules;
using TheTechIdea.Beep.Winform.Controls;

namespace TheTechIdea.Beep.Winform.Default.Views.Configuration
{
    partial class uc_FilterForm
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_FilterForm));
            beepCard1 = new BeepCard();
            beepStatCard1 = new BeepStatCard();
            beepChart1 = new BeepChart();
            beepFeatureCard1 = new BeepFeatureCard();
            beepDatePicker1 = new BeepDatePicker();
            beepScrollList1 = new BeepScrollList();
            beepButton1 = new BeepButton();
            beepCalendarView1 = new BeepCalendarView();
            beepTextBox1 = new BeepTextBox();
            beepListBox1 = new BeepListBox();
            beepTextBox2 = new BeepTextBox();
            SuspendLayout();
            // 
            // beepCard1
            // 
            beepCard1.AnimationDuration = 500;
            beepCard1.AnimationType = DisplayAnimationType.None;
            beepCard1.ApplyThemeToChilds = false;
            beepCard1.BackColor = Color.FromArgb(245, 245, 245);
            beepCard1.BadgeBackColor = Color.Red;
            beepCard1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepCard1.BadgeForeColor = Color.White;
            beepCard1.BadgeShape = BadgeShape.Circle;
            beepCard1.BadgeText = "";
            beepCard1.BlockID = null;
            beepCard1.BorderColor = Color.Black;
            beepCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCard1.BorderRadius = 8;
            beepCard1.BorderStyle = BorderStyle.FixedSingle;
            beepCard1.BorderThickness = 1;
            beepCard1.BottomoffsetForDrawingRect = 0;
            beepCard1.BoundProperty = "ParagraphText";
            beepCard1.ButtonText = "Action";
            beepCard1.CanBeFocused = true;
            beepCard1.CanBeHovered = false;
            beepCard1.CanBePressed = true;
            beepCard1.Category = Utilities.DbFieldCategory.String;
            beepCard1.ComponentName = "beepCard1";
            beepCard1.DataContext = null;
            beepCard1.DataSourceProperty = null;
            beepCard1.DisabledBackColor = Color.Gray;
            beepCard1.DisabledForeColor = Color.Empty;
            beepCard1.DrawingRect = new Rectangle(4, 4, 321, 191);
            beepCard1.Easing = EasingType.Linear;
            beepCard1.FieldID = null;
            beepCard1.FocusBackColor = Color.Gray;
            beepCard1.FocusBorderColor = Color.Gray;
            beepCard1.FocusForeColor = Color.Black;
            beepCard1.FocusIndicatorColor = Color.Blue;
            beepCard1.Form = null;
            beepCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCard1.GradientEndColor = Color.Gray;
            beepCard1.GradientStartColor = Color.Gray;
            beepCard1.GuidID = "182deead-7099-48e0-bbbd-e6d504a20912";
            beepCard1.HeaderAlignment = ContentAlignment.TopLeft;
            beepCard1.HeaderText = "Card Title";
            beepCard1.HitAreaEventOn = false;
            beepCard1.HitTestControl = null;
            beepCard1.HoverBackColor = Color.Gray;
            beepCard1.HoverBorderColor = Color.Gray;
            beepCard1.HoveredBackcolor = Color.Wheat;
            beepCard1.HoverForeColor = Color.Black;
            beepCard1.Id = -1;
            beepCard1.ImageAlignment = ContentAlignment.TopRight;
            beepCard1.ImagePath = "H:\\dev\\iconPacks\\4205888-web-design-and-development\\4205888-web-design-and-development\\svg\\020-add.svg";
            beepCard1.InactiveBorderColor = Color.Gray;
            beepCard1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepCard1.Info");
            beepCard1.IsAcceptButton = false;
            beepCard1.IsBorderAffectedByTheme = true;
            beepCard1.IsCancelButton = false;
            beepCard1.IsChild = false;
            beepCard1.IsCustomeBorder = false;
            beepCard1.IsDefault = false;
            beepCard1.IsDeleted = false;
            beepCard1.IsDirty = false;
            beepCard1.IsEditable = false;
            beepCard1.IsFocused = false;
            beepCard1.IsFrameless = false;
            beepCard1.IsHovered = false;
            beepCard1.IsNew = false;
            beepCard1.IsPressed = false;
            beepCard1.IsReadOnly = false;
            beepCard1.IsRequired = false;
            beepCard1.IsRounded = true;
            beepCard1.IsRoundedAffectedByTheme = true;
            beepCard1.IsSelected = false;
            beepCard1.IsShadowAffectedByTheme = true;
            beepCard1.IsVisible = false;
            beepCard1.Items = (List<object>)resources.GetObject("beepCard1.Items");
            beepCard1.LeftoffsetForDrawingRect = 0;
            beepCard1.LinkedProperty = null;
            beepCard1.Location = new Point(673, 521);
            beepCard1.MaxImageSize = 64;
            beepCard1.Name = "beepCard1";
            beepCard1.OverrideFontSize = TypeStyleFontSize.None;
            beepCard1.Padding = new Padding(3);
            beepCard1.ParagraphText = "Card Description";
            beepCard1.ParentBackColor = Color.Empty;
            beepCard1.ParentControl = null;
            beepCard1.PressedBackColor = Color.Gray;
            beepCard1.PressedBorderColor = Color.Black;
            beepCard1.PressedForeColor = Color.Black;
            beepCard1.RightoffsetForDrawingRect = 0;
            beepCard1.SavedGuidID = null;
            beepCard1.SavedID = null;
            beepCard1.SelectedBackColor = Color.White;
            beepCard1.SelectedForeColor = Color.Black;
            beepCard1.ShadowColor = Color.Black;
            beepCard1.ShadowOffset = 0;
            beepCard1.ShadowOpacity = 0.5F;
            beepCard1.ShowAllBorders = true;
            beepCard1.ShowBottomBorder = true;
            beepCard1.ShowButton = true;
            beepCard1.ShowFocusIndicator = false;
            beepCard1.ShowLeftBorder = true;
            beepCard1.ShowRightBorder = true;
            beepCard1.ShowShadow = false;
            beepCard1.ShowTopBorder = true;
            beepCard1.Size = new Size(329, 199);
            beepCard1.SlideFrom = SlideDirection.Left;
            beepCard1.StaticNotMoving = false;
            beepCard1.TabIndex = 7;
            beepCard1.TempBackColor = Color.Empty;
            beepCard1.TextAlignment = ContentAlignment.TopLeft;
            beepCard1.Theme = EnumBeepThemes.WinterTheme;
            beepCard1.ToolTipText = "";
            beepCard1.TopoffsetForDrawingRect = 0;
            beepCard1.UseGradientBackground = false;
            beepCard1.UseThemeFont = true;
            beepCard1.ViewMode = CardViewMode.ImageLeft;
            // 
            // beepStatCard1
            // 
            beepStatCard1.AnimationDuration = 500;
            beepStatCard1.AnimationType = DisplayAnimationType.None;
            beepStatCard1.ApplyThemeToChilds = false;
            beepStatCard1.BackColor = Color.FromArgb(245, 245, 245);
            beepStatCard1.BadgeBackColor = Color.Red;
            beepStatCard1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepStatCard1.BadgeForeColor = Color.White;
            beepStatCard1.BadgeShape = BadgeShape.Circle;
            beepStatCard1.BadgeText = "";
            beepStatCard1.BlockID = null;
            beepStatCard1.BorderColor = Color.Black;
            beepStatCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepStatCard1.BorderRadius = 8;
            beepStatCard1.BorderStyle = BorderStyle.FixedSingle;
            beepStatCard1.BorderThickness = 1;
            beepStatCard1.BottomoffsetForDrawingRect = 0;
            beepStatCard1.BoundProperty = "ValueText";
            beepStatCard1.CanBeFocused = true;
            beepStatCard1.CanBeHovered = false;
            beepStatCard1.CanBePressed = true;
            beepStatCard1.Category = Utilities.DbFieldCategory.String;
            beepStatCard1.ComponentName = "beepStatCard1";
            beepStatCard1.DataContext = null;
            beepStatCard1.DataSourceProperty = null;
            beepStatCard1.DisabledBackColor = Color.Gray;
            beepStatCard1.DisabledForeColor = Color.Empty;
            beepStatCard1.DrawingRect = new Rectangle(11, 11, 305, 175);
            beepStatCard1.Easing = EasingType.Linear;
            beepStatCard1.FieldID = null;
            beepStatCard1.FocusBackColor = Color.Gray;
            beepStatCard1.FocusBorderColor = Color.Gray;
            beepStatCard1.FocusForeColor = Color.Black;
            beepStatCard1.FocusIndicatorColor = Color.Blue;
            beepStatCard1.Form = null;
            beepStatCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepStatCard1.GradientEndColor = Color.Gray;
            beepStatCard1.GradientStartColor = Color.Gray;
            beepStatCard1.GuidID = "432b9d1a-2075-4062-b0a7-c702ae86d126";
            beepStatCard1.HeaderText = "Total Revenue";
            beepStatCard1.HitAreaEventOn = false;
            beepStatCard1.HitTestControl = null;
            beepStatCard1.HoverBackColor = Color.Gray;
            beepStatCard1.HoverBorderColor = Color.Gray;
            beepStatCard1.HoveredBackcolor = Color.Wheat;
            beepStatCard1.HoverForeColor = Color.Black;
            beepStatCard1.Icon = "simpleinfoapps.svg";
            beepStatCard1.Id = -1;
            beepStatCard1.InactiveBorderColor = Color.Gray;
            beepStatCard1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepStatCard1.Info");
            beepStatCard1.InfoText = "Visitors for the last 6 months";
            beepStatCard1.IsAcceptButton = false;
            beepStatCard1.IsBorderAffectedByTheme = true;
            beepStatCard1.IsCancelButton = false;
            beepStatCard1.IsChild = false;
            beepStatCard1.IsCustomeBorder = false;
            beepStatCard1.IsDefault = false;
            beepStatCard1.IsDeleted = false;
            beepStatCard1.IsDirty = false;
            beepStatCard1.IsEditable = false;
            beepStatCard1.IsFocused = false;
            beepStatCard1.IsFrameless = false;
            beepStatCard1.IsHovered = false;
            beepStatCard1.IsNew = false;
            beepStatCard1.IsPressed = false;
            beepStatCard1.IsReadOnly = false;
            beepStatCard1.IsRequired = false;
            beepStatCard1.IsRounded = true;
            beepStatCard1.IsRoundedAffectedByTheme = true;
            beepStatCard1.IsSelected = false;
            beepStatCard1.IsShadowAffectedByTheme = true;
            beepStatCard1.IsTrendingUp = true;
            beepStatCard1.IsVisible = false;
            beepStatCard1.Items = (List<object>)resources.GetObject("beepStatCard1.Items");
            beepStatCard1.LeftoffsetForDrawingRect = 0;
            beepStatCard1.LinkedProperty = null;
            beepStatCard1.Location = new Point(673, 309);
            beepStatCard1.Name = "beepStatCard1";
            beepStatCard1.OverrideFontSize = TypeStyleFontSize.None;
            beepStatCard1.Padding = new Padding(10);
            beepStatCard1.ParentBackColor = Color.FromArgb(245, 245, 245);
            beepStatCard1.ParentControl = null;
            beepStatCard1.PercentageText = "+12.5%";
            beepStatCard1.PressedBackColor = Color.Gray;
            beepStatCard1.PressedBorderColor = Color.Black;
            beepStatCard1.PressedForeColor = Color.Black;
            beepStatCard1.RightoffsetForDrawingRect = 0;
            beepStatCard1.SavedGuidID = null;
            beepStatCard1.SavedID = null;
            beepStatCard1.SelectedBackColor = Color.White;
            beepStatCard1.SelectedForeColor = Color.Black;
            beepStatCard1.ShadowColor = Color.Black;
            beepStatCard1.ShadowOffset = 0;
            beepStatCard1.ShadowOpacity = 0.5F;
            beepStatCard1.ShowAllBorders = true;
            beepStatCard1.ShowBottomBorder = true;
            beepStatCard1.ShowFocusIndicator = false;
            beepStatCard1.ShowLeftBorder = true;
            beepStatCard1.ShowRightBorder = true;
            beepStatCard1.ShowShadow = false;
            beepStatCard1.ShowTopBorder = true;
            beepStatCard1.Size = new Size(327, 197);
            beepStatCard1.SlideFrom = SlideDirection.Left;
            beepStatCard1.StaticNotMoving = false;
            beepStatCard1.TabIndex = 8;
            beepStatCard1.TempBackColor = Color.Empty;
            beepStatCard1.Theme = EnumBeepThemes.WinterTheme;
            beepStatCard1.ToolTipText = "";
            beepStatCard1.TopoffsetForDrawingRect = 0;
            beepStatCard1.TrendDownSvgPath = "trenddown.svg";
            beepStatCard1.TrendText = "Trending up this month";
            beepStatCard1.TrendUpSvgPath = "trendup.svg";
            beepStatCard1.UseGradientBackground = false;
            beepStatCard1.UseThemeFont = true;
            beepStatCard1.ValueText = "$1,250.00";
            // 
            // beepChart1
            // 
            beepChart1.AnimationDuration = 500;
            beepChart1.AnimationType = DisplayAnimationType.None;
            beepChart1.ApplyThemeToChilds = false;
            beepChart1.BackColor = Color.FromArgb(240, 248, 255);
            beepChart1.BadgeBackColor = Color.Red;
            beepChart1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepChart1.BadgeForeColor = Color.White;
            beepChart1.BadgeShape = BadgeShape.Circle;
            beepChart1.BadgeText = "";
            beepChart1.BlockID = null;
            beepChart1.BorderColor = Color.FromArgb(176, 196, 222);
            beepChart1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepChart1.BorderRadius = 8;
            beepChart1.BorderStyle = BorderStyle.FixedSingle;
            beepChart1.BorderThickness = 1;
            beepChart1.BottomAxisType = AxisType.Numeric;
            beepChart1.BottomoffsetForDrawingRect = 0;
            beepChart1.BoundProperty = null;
            beepChart1.CanBeFocused = true;
            beepChart1.CanBeHovered = false;
            beepChart1.CanBePressed = true;
            beepChart1.Category = Utilities.DbFieldCategory.String;
            beepChart1.ChartAxisColor = Color.FromArgb(70, 130, 180);
            beepChart1.ChartBackColor = Color.FromArgb(245, 245, 245);
            beepChart1.ChartFillColor = Color.FromArgb(176, 196, 222);
            beepChart1.ChartGridLineColor = Color.FromArgb(176, 196, 222);
            beepChart1.ChartLegendBackColor = Color.FromArgb(240, 248, 255);
            beepChart1.ChartLegendShapeColor = Color.FromArgb(70, 130, 180);
            beepChart1.ChartLegendTextColor = Color.FromArgb(25, 25, 112);
            beepChart1.ChartLineColor = Color.FromArgb(25, 25, 112);
            beepChart1.ChartSubtitle = "Subtitle or Description";
            beepChart1.ChartSubtitleFont = new Font("Microsoft Sans Serif", 14F);
            beepChart1.ChartTextColor = Color.FromArgb(47, 79, 79);
            beepChart1.ChartTitle = "Chart Title";
            beepChart1.ChartTitleColor = Color.FromArgb(70, 130, 180);
            beepChart1.ChartTitleFont = new Font("Segoe UI", 24F);
            beepChart1.ChartTitleForeColor = Color.Black;
            beepChart1.ChartType = ChartType.Line;
            beepChart1.ChartValue = "$12,000,000";
            beepChart1.ChartValueFont = new Font("Microsoft Sans Serif", 24F, FontStyle.Bold);
            beepChart1.ComponentName = "beepChart1";
            beepChart1.CustomDraw = false;
            beepChart1.DataContext = null;
            beepChart1.DataSourceProperty = null;
            beepChart1.DisabledBackColor = Color.Gray;
            beepChart1.DisabledForeColor = Color.Empty;
            beepChart1.DrawingRect = new Rectangle(1, 1, 251, 289);
            beepChart1.Easing = EasingType.Linear;
            beepChart1.FieldID = null;
            beepChart1.FocusBackColor = Color.White;
            beepChart1.FocusBorderColor = Color.Gray;
            beepChart1.FocusForeColor = Color.Black;
            beepChart1.FocusIndicatorColor = Color.Blue;
            beepChart1.Form = null;
            beepChart1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepChart1.GradientEndColor = Color.FromArgb(173, 216, 230);
            beepChart1.GradientStartColor = Color.FromArgb(240, 248, 255);
            beepChart1.GuidID = "a3ce32e6-ef63-4ff5-a3cb-c56ebde5fba4";
            beepChart1.HitAreaEventOn = false;
            beepChart1.HitTestControl = null;
            beepChart1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepChart1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepChart1.HoveredBackcolor = Color.Wheat;
            beepChart1.HoverForeColor = Color.Black;
            beepChart1.Id = -1;
            beepChart1.InactiveBorderColor = Color.Gray;
            beepChart1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepChart1.Info");
            beepChart1.IsAcceptButton = false;
            beepChart1.IsBorderAffectedByTheme = true;
            beepChart1.IsCancelButton = false;
            beepChart1.IsChild = false;
            beepChart1.IsCustomeBorder = false;
            beepChart1.IsDefault = false;
            beepChart1.IsDeleted = false;
            beepChart1.IsDirty = false;
            beepChart1.IsEditable = false;
            beepChart1.IsFocused = false;
            beepChart1.IsFrameless = false;
            beepChart1.IsHovered = false;
            beepChart1.IsNew = false;
            beepChart1.IsPressed = false;
            beepChart1.IsReadOnly = false;
            beepChart1.IsRequired = false;
            beepChart1.IsRounded = true;
            beepChart1.IsRoundedAffectedByTheme = true;
            beepChart1.IsSelected = false;
            beepChart1.IsShadowAffectedByTheme = true;
            beepChart1.IsVisible = false;
            beepChart1.Items = (List<object>)resources.GetObject("beepChart1.Items");
            beepChart1.LeftAxisType = AxisType.Numeric;
            beepChart1.LeftoffsetForDrawingRect = 0;
            beepChart1.LinkedProperty = null;
            beepChart1.Location = new Point(389, 17);
            beepChart1.Name = "beepChart1";
            beepChart1.OverrideFontSize = TypeStyleFontSize.None;
            beepChart1.ParentBackColor = Color.Empty;
            beepChart1.ParentControl = null;
            beepChart1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepChart1.PressedBorderColor = Color.Black;
            beepChart1.PressedForeColor = Color.Black;
            beepChart1.RightoffsetForDrawingRect = 0;
            beepChart1.SavedGuidID = null;
            beepChart1.SavedID = null;
            beepChart1.SelectedBackColor = Color.White;
            beepChart1.SelectedForeColor = Color.Black;
            beepChart1.ShadowColor = Color.FromArgb(176, 196, 222);
            beepChart1.ShadowOffset = 0;
            beepChart1.ShadowOpacity = 0.5F;
            beepChart1.ShowAllBorders = true;
            beepChart1.ShowBottomBorder = true;
            beepChart1.ShowFocusIndicator = false;
            beepChart1.ShowLeftBorder = true;
            beepChart1.ShowLegend = true;
            beepChart1.ShowRightBorder = true;
            beepChart1.ShowShadow = false;
            beepChart1.ShowTitle = true;
            beepChart1.ShowTopBorder = true;
            beepChart1.Size = new Size(253, 291);
            beepChart1.SlideFrom = SlideDirection.Left;
            beepChart1.StaticNotMoving = false;
            beepChart1.TabIndex = 10;
            beepChart1.TempBackColor = Color.Empty;
            beepChart1.Theme = EnumBeepThemes.WinterTheme;
            beepChart1.ToolTipText = "";
            beepChart1.TopoffsetForDrawingRect = 0;
            beepChart1.UseGradientBackground = false;
            beepChart1.UseThemeFont = true;
            beepChart1.ViewportXMax = 0F;
            beepChart1.ViewportXMin = 0F;
            beepChart1.ViewportYMax = 0F;
            beepChart1.ViewportYMin = 0F;
            beepChart1.XAxisTitle = "X Title";
            beepChart1.YAxisTitle = "Y Title";
            // 
            // beepFeatureCard1
            // 
            beepFeatureCard1.ActionIcon1Path = "action1.svg";
            beepFeatureCard1.ActionIcon2Path = "action2.svg";
            beepFeatureCard1.AnimationDuration = 500;
            beepFeatureCard1.AnimationType = DisplayAnimationType.None;
            beepFeatureCard1.ApplyThemeToChilds = false;
            beepFeatureCard1.BackColor = Color.FromArgb(245, 245, 245);
            beepFeatureCard1.BadgeBackColor = Color.Red;
            beepFeatureCard1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepFeatureCard1.BadgeForeColor = Color.White;
            beepFeatureCard1.BadgeShape = BadgeShape.Circle;
            beepFeatureCard1.BadgeText = "";
            beepFeatureCard1.BlockID = null;
            beepFeatureCard1.BorderColor = Color.Black;
            beepFeatureCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepFeatureCard1.BorderRadius = 8;
            beepFeatureCard1.BorderStyle = BorderStyle.FixedSingle;
            beepFeatureCard1.BorderThickness = 1;
            beepFeatureCard1.BottomoffsetForDrawingRect = 0;
            beepFeatureCard1.BoundProperty = "TitleText";
            beepFeatureCard1.BulletIconPath = "bullet.svg";
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints1"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints2"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints3"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints4"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints5"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints6"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints7"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints8"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints9"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints10"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints11"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints12"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints13"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints14"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints15"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints16"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints17"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints18"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints19"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints20"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints21"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints22"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints23"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints24"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints25"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints26"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints27"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints28"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints29"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints30"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints31"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints32"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints33"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints34"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints35"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints36"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints37"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints38"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints39"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints40"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints41"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints42"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints43"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints44"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints45"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints46"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints47"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints48"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints49"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints50"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints51"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints52"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints53"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints54"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints55"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints56"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints57"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints58"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints59"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints60"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints61"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints62"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints63"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints64"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints65"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints66"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints67"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints68"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints69"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints70"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints71"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints72"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints73"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints74"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints75"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints76"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints77"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints78"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints79"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints80"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints81"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints82"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints83"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints84"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints85"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints86"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints87"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints88"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints89"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints90"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints91"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints92"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints93"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints94"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints95"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints96"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints97"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints98"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints99"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints100"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints101"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints102"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints103"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints104"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints105"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints106"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints107"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints108"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints109"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints110"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints111"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints112"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints113"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints114"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints115"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints116"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints117"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints118"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints119"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints120"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints121"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints122"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints123"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints124"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints125"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints126"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints127"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints128"));
            beepFeatureCard1.BulletPoints.Add((Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.BulletPoints129"));
            beepFeatureCard1.CanBeFocused = true;
            beepFeatureCard1.CanBeHovered = false;
            beepFeatureCard1.CanBePressed = true;
            beepFeatureCard1.CardIconPath = "simpleinfoapps.svg";
            beepFeatureCard1.Category = Utilities.DbFieldCategory.String;
            beepFeatureCard1.ComponentName = "beepFeatureCard1";
            beepFeatureCard1.DataContext = null;
            beepFeatureCard1.DataSourceProperty = null;
            beepFeatureCard1.DisabledBackColor = Color.Gray;
            beepFeatureCard1.DisabledForeColor = Color.Empty;
            beepFeatureCard1.DrawingRect = new Rectangle(16, 16, 308, 239);
            beepFeatureCard1.Easing = EasingType.Linear;
            beepFeatureCard1.FieldID = null;
            beepFeatureCard1.FocusBackColor = Color.Gray;
            beepFeatureCard1.FocusBorderColor = Color.Gray;
            beepFeatureCard1.FocusForeColor = Color.Black;
            beepFeatureCard1.FocusIndicatorColor = Color.Blue;
            beepFeatureCard1.Form = null;
            beepFeatureCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepFeatureCard1.GradientEndColor = Color.Gray;
            beepFeatureCard1.GradientStartColor = Color.Gray;
            beepFeatureCard1.GuidID = "949d4134-f4f9-44fd-91cf-003fcf2b867f";
            beepFeatureCard1.HitAreaEventOn = false;
            beepFeatureCard1.HitTestControl = null;
            beepFeatureCard1.HoverBackColor = Color.Gray;
            beepFeatureCard1.HoverBorderColor = Color.Gray;
            beepFeatureCard1.HoveredBackcolor = Color.Wheat;
            beepFeatureCard1.HoverForeColor = Color.Black;
            beepFeatureCard1.Id = -1;
            beepFeatureCard1.InactiveBorderColor = Color.Gray;
            beepFeatureCard1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepFeatureCard1.Info");
            beepFeatureCard1.IsAcceptButton = false;
            beepFeatureCard1.IsBorderAffectedByTheme = true;
            beepFeatureCard1.IsCancelButton = false;
            beepFeatureCard1.IsChild = false;
            beepFeatureCard1.IsCustomeBorder = false;
            beepFeatureCard1.IsDefault = false;
            beepFeatureCard1.IsDeleted = false;
            beepFeatureCard1.IsDirty = false;
            beepFeatureCard1.IsEditable = false;
            beepFeatureCard1.IsFocused = false;
            beepFeatureCard1.IsFrameless = false;
            beepFeatureCard1.IsHovered = false;
            beepFeatureCard1.IsNew = false;
            beepFeatureCard1.IsPressed = false;
            beepFeatureCard1.IsReadOnly = false;
            beepFeatureCard1.IsRequired = false;
            beepFeatureCard1.IsRounded = true;
            beepFeatureCard1.IsRoundedAffectedByTheme = true;
            beepFeatureCard1.IsSelected = false;
            beepFeatureCard1.IsShadowAffectedByTheme = true;
            beepFeatureCard1.IsVisible = false;
            beepFeatureCard1.Items = (List<object>)resources.GetObject("beepFeatureCard1.Items");
            beepFeatureCard1.LeftoffsetForDrawingRect = 0;
            beepFeatureCard1.LinkedProperty = null;
            beepFeatureCard1.Location = new Point(660, 17);
            beepFeatureCard1.LogoPath = "";
            beepFeatureCard1.Name = "beepFeatureCard1";
            beepFeatureCard1.OverrideFontSize = TypeStyleFontSize.None;
            beepFeatureCard1.Padding = new Padding(15);
            beepFeatureCard1.ParentBackColor = Color.FromArgb(245, 245, 245);
            beepFeatureCard1.ParentControl = null;
            beepFeatureCard1.PressedBackColor = Color.Gray;
            beepFeatureCard1.PressedBorderColor = Color.Black;
            beepFeatureCard1.PressedForeColor = Color.Black;
            beepFeatureCard1.RightoffsetForDrawingRect = 0;
            beepFeatureCard1.SavedGuidID = null;
            beepFeatureCard1.SavedID = null;
            beepFeatureCard1.SelectedBackColor = Color.White;
            beepFeatureCard1.SelectedForeColor = Color.Black;
            beepFeatureCard1.ShadowColor = Color.Black;
            beepFeatureCard1.ShadowOffset = 0;
            beepFeatureCard1.ShadowOpacity = 0.5F;
            beepFeatureCard1.ShowAllBorders = true;
            beepFeatureCard1.ShowBottomBorder = true;
            beepFeatureCard1.ShowFocusIndicator = false;
            beepFeatureCard1.ShowLeftBorder = true;
            beepFeatureCard1.ShowRightBorder = true;
            beepFeatureCard1.ShowShadow = false;
            beepFeatureCard1.ShowTopBorder = true;
            beepFeatureCard1.Size = new Size(340, 271);
            beepFeatureCard1.SlideFrom = SlideDirection.Left;
            beepFeatureCard1.StaticNotMoving = false;
            beepFeatureCard1.SubtitleText = "Charts version";
            beepFeatureCard1.TabIndex = 11;
            beepFeatureCard1.TempBackColor = Color.Empty;
            beepFeatureCard1.Theme = EnumBeepThemes.WinterTheme;
            beepFeatureCard1.TitleText = "Sphere UI";
            beepFeatureCard1.ToolTipText = "";
            beepFeatureCard1.TopoffsetForDrawingRect = 0;
            beepFeatureCard1.UseGradientBackground = false;
            beepFeatureCard1.UseThemeFont = true;
            // 
            // beepDatePicker1
            // 
            beepDatePicker1.AnimationDuration = 500;
            beepDatePicker1.AnimationType = DisplayAnimationType.None;
            beepDatePicker1.ApplyThemeToChilds = false;
            beepDatePicker1.BackColor = Color.FromArgb(245, 245, 245);
            beepDatePicker1.BadgeBackColor = Color.Red;
            beepDatePicker1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepDatePicker1.BadgeForeColor = Color.White;
            beepDatePicker1.BadgeShape = BadgeShape.Circle;
            beepDatePicker1.BadgeText = "";
            beepDatePicker1.BlockID = null;
            beepDatePicker1.BorderColor = Color.FromArgb(173, 181, 189);
            beepDatePicker1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepDatePicker1.BorderRadius = 8;
            beepDatePicker1.BorderStyle = BorderStyle.FixedSingle;
            beepDatePicker1.BorderThickness = 1;
            beepDatePicker1.BottomoffsetForDrawingRect = 0;
            beepDatePicker1.BoundProperty = "SelectedDate";
            beepDatePicker1.CanBeFocused = true;
            beepDatePicker1.CanBeHovered = false;
            beepDatePicker1.CanBePressed = true;
            beepDatePicker1.Category = Utilities.DbFieldCategory.String;
            beepDatePicker1.ComponentName = "beepDatePicker1";
            beepDatePicker1.Culture = new System.Globalization.CultureInfo("en-AE");
            beepDatePicker1.DataContext = null;
            beepDatePicker1.DataSourceProperty = null;
            beepDatePicker1.DateFormat = "dd/MM/yyyy HH:mm";
            beepDatePicker1.DisabledBackColor = Color.Gray;
            beepDatePicker1.DisabledForeColor = Color.Empty;
            beepDatePicker1.DrawingRect = new Rectangle(1, 1, 160, 20);
            beepDatePicker1.Easing = EasingType.Linear;
            beepDatePicker1.FieldID = null;
            beepDatePicker1.FocusBackColor = Color.White;
            beepDatePicker1.FocusBorderColor = Color.Gray;
            beepDatePicker1.FocusForeColor = Color.Black;
            beepDatePicker1.FocusIndicatorColor = Color.Blue;
            beepDatePicker1.Form = null;
            beepDatePicker1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepDatePicker1.GradientEndColor = Color.FromArgb(255, 255, 255);
            beepDatePicker1.GradientStartColor = Color.FromArgb(245, 245, 245);
            beepDatePicker1.GuidID = "ff4e3c08-96cd-4db6-82ec-55e8ad402329";
            beepDatePicker1.HitAreaEventOn = false;
            beepDatePicker1.HitTestControl = null;
            beepDatePicker1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepDatePicker1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepDatePicker1.HoveredBackcolor = Color.Wheat;
            beepDatePicker1.HoverForeColor = Color.Black;
            beepDatePicker1.Id = -1;
            beepDatePicker1.InactiveBorderColor = Color.Gray;
            beepDatePicker1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepDatePicker1.Info");
            beepDatePicker1.IsAcceptButton = false;
            beepDatePicker1.IsBorderAffectedByTheme = true;
            beepDatePicker1.IsCancelButton = false;
            beepDatePicker1.IsChild = false;
            beepDatePicker1.IsCustomeBorder = false;
            beepDatePicker1.IsDefault = false;
            beepDatePicker1.IsDeleted = false;
            beepDatePicker1.IsDirty = false;
            beepDatePicker1.IsEditable = false;
            beepDatePicker1.IsFocused = false;
            beepDatePicker1.IsFrameless = false;
            beepDatePicker1.IsHovered = false;
            beepDatePicker1.IsNew = false;
            beepDatePicker1.IsPressed = false;
            beepDatePicker1.IsReadOnly = false;
            beepDatePicker1.IsRequired = false;
            beepDatePicker1.IsRounded = true;
            beepDatePicker1.IsRoundedAffectedByTheme = true;
            beepDatePicker1.IsSelected = false;
            beepDatePicker1.IsShadowAffectedByTheme = true;
            beepDatePicker1.IsVisible = false;
            beepDatePicker1.Items = (List<object>)resources.GetObject("beepDatePicker1.Items");
            beepDatePicker1.LeftoffsetForDrawingRect = 0;
            beepDatePicker1.LinkedProperty = null;
            beepDatePicker1.Location = new Point(403, 314);
            beepDatePicker1.Name = "beepDatePicker1";
            beepDatePicker1.OverrideFontSize = TypeStyleFontSize.None;
            beepDatePicker1.ParentBackColor = Color.Empty;
            beepDatePicker1.ParentControl = null;
            beepDatePicker1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepDatePicker1.PressedBorderColor = Color.Black;
            beepDatePicker1.PressedForeColor = Color.Black;
            beepDatePicker1.RightoffsetForDrawingRect = 0;
            beepDatePicker1.SavedGuidID = null;
            beepDatePicker1.SavedID = null;
            beepDatePicker1.SelectedBackColor = Color.White;
            beepDatePicker1.SelectedDate = "07/04/2025 00:00";
            beepDatePicker1.SelectedDateTime = new DateTime(2025, 4, 7, 0, 0, 0, 0);
            beepDatePicker1.SelectedForeColor = Color.Black;
            beepDatePicker1.ShadowColor = Color.FromArgb(173, 181, 189);
            beepDatePicker1.ShadowOffset = 0;
            beepDatePicker1.ShadowOpacity = 0.5F;
            beepDatePicker1.ShowAllBorders = true;
            beepDatePicker1.ShowBottomBorder = true;
            beepDatePicker1.ShowFocusIndicator = false;
            beepDatePicker1.ShowLeftBorder = true;
            beepDatePicker1.ShowRightBorder = true;
            beepDatePicker1.ShowShadow = false;
            beepDatePicker1.ShowTopBorder = true;
            beepDatePicker1.Size = new Size(162, 22);
            beepDatePicker1.SlideFrom = SlideDirection.Left;
            beepDatePicker1.StaticNotMoving = false;
            beepDatePicker1.TabIndex = 12;
            beepDatePicker1.TempBackColor = Color.Empty;
            beepDatePicker1.Text = "beepDatePicker1";
            beepDatePicker1.Theme = EnumBeepThemes.DefaultTheme;
            beepDatePicker1.ToolTipText = "";
            beepDatePicker1.TopoffsetForDrawingRect = 0;
            beepDatePicker1.UseGradientBackground = false;
            beepDatePicker1.UseThemeFont = true;
            // 
            // beepScrollList1
            // 
            beepScrollList1.AnimationDuration = 500;
            beepScrollList1.AnimationType = DisplayAnimationType.None;
            beepScrollList1.ApplyThemeToChilds = false;
            beepScrollList1.BackColor = Color.FromArgb(255, 255, 255);
            beepScrollList1.BadgeBackColor = Color.Red;
            beepScrollList1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepScrollList1.BadgeForeColor = Color.White;
            beepScrollList1.BadgeShape = BadgeShape.Circle;
            beepScrollList1.BadgeText = "";
            beepScrollList1.BlockID = null;
            beepScrollList1.BorderColor = Color.FromArgb(173, 181, 189);
            beepScrollList1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepScrollList1.BorderRadius = 8;
            beepScrollList1.BorderStyle = BorderStyle.FixedSingle;
            beepScrollList1.BorderThickness = 1;
            beepScrollList1.BottomoffsetForDrawingRect = 0;
            beepScrollList1.BoundProperty = null;
            beepScrollList1.CanBeFocused = true;
            beepScrollList1.CanBeHovered = false;
            beepScrollList1.CanBePressed = true;
            beepScrollList1.Category = Utilities.DbFieldCategory.String;
            beepScrollList1.ComponentName = "beepScrollList1";
            beepScrollList1.DataContext = null;
            beepScrollList1.DataSourceProperty = null;
            beepScrollList1.DisabledBackColor = Color.Gray;
            beepScrollList1.DisabledForeColor = Color.Empty;
            beepScrollList1.DrawingRect = new Rectangle(3, 3, 201, 67);
            beepScrollList1.Easing = EasingType.Linear;
            beepScrollList1.FieldID = null;
            beepScrollList1.FocusBackColor = Color.White;
            beepScrollList1.FocusBorderColor = Color.Gray;
            beepScrollList1.FocusForeColor = Color.Black;
            beepScrollList1.FocusIndicatorColor = Color.Blue;
            beepScrollList1.Font = new Font("Arial", 10F);
            beepScrollList1.Form = null;
            beepScrollList1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepScrollList1.GradientEndColor = Color.FromArgb(255, 255, 255);
            beepScrollList1.GradientStartColor = Color.FromArgb(245, 245, 245);
            beepScrollList1.GuidID = "75d31b7b-a835-4790-90eb-8b5efffc78b3";
            beepScrollList1.HitAreaEventOn = false;
            beepScrollList1.HitTestControl = null;
            beepScrollList1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepScrollList1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepScrollList1.HoveredBackcolor = Color.Wheat;
            beepScrollList1.HoverForeColor = Color.Black;
            beepScrollList1.Id = -1;
            beepScrollList1.InactiveBorderColor = Color.Gray;
            beepScrollList1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepScrollList1.Info");
            beepScrollList1.IsAcceptButton = false;
            beepScrollList1.IsBorderAffectedByTheme = true;
            beepScrollList1.IsCancelButton = false;
            beepScrollList1.IsChild = false;
            beepScrollList1.IsCustomeBorder = false;
            beepScrollList1.IsDefault = false;
            beepScrollList1.IsDeleted = false;
            beepScrollList1.IsDirty = false;
            beepScrollList1.IsEditable = false;
            beepScrollList1.IsFocused = false;
            beepScrollList1.IsFrameless = false;
            beepScrollList1.IsHovered = false;
            beepScrollList1.IsNew = false;
            beepScrollList1.IsPressed = false;
            beepScrollList1.IsReadOnly = false;
            beepScrollList1.IsRequired = false;
            beepScrollList1.IsRounded = true;
            beepScrollList1.IsRoundedAffectedByTheme = true;
            beepScrollList1.IsSelected = false;
            beepScrollList1.IsShadowAffectedByTheme = true;
            beepScrollList1.IsVisible = false;
            beepScrollList1.Items = (List<object>)resources.GetObject("beepScrollList1.Items");
            beepScrollList1.LeftoffsetForDrawingRect = 0;
            beepScrollList1.LinkedProperty = null;
            beepScrollList1.ListItems.Add((Controls.Models.SimpleItem)resources.GetObject("beepScrollList1.ListItems"));
            beepScrollList1.ListItems.Add((Controls.Models.SimpleItem)resources.GetObject("beepScrollList1.ListItems1"));
            beepScrollList1.Location = new Point(437, 624);
            beepScrollList1.Name = "beepScrollList1";
            beepScrollList1.Orientation = ScrollOrientation.HorizontalScroll;
            beepScrollList1.OverrideFontSize = TypeStyleFontSize.None;
            beepScrollList1.Padding = new Padding(2);
            beepScrollList1.ParentBackColor = Color.FromArgb(108, 117, 125);
            beepScrollList1.ParentControl = null;
            beepScrollList1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepScrollList1.PressedBorderColor = Color.Black;
            beepScrollList1.PressedForeColor = Color.Black;
            beepScrollList1.RightoffsetForDrawingRect = 0;
            beepScrollList1.SavedGuidID = null;
            beepScrollList1.SavedID = null;
            beepScrollList1.SelectedBackColor = Color.White;
            beepScrollList1.SelectedForeColor = Color.Black;
            beepScrollList1.SelectedIndex = -1;
            beepScrollList1.SelectedItem = null;
            beepScrollList1.ShadowColor = Color.FromArgb(173, 181, 189);
            beepScrollList1.ShadowOffset = 0;
            beepScrollList1.ShadowOpacity = 0.5F;
            beepScrollList1.ShowAllBorders = true;
            beepScrollList1.ShowBottomBorder = true;
            beepScrollList1.ShowFocusIndicator = false;
            beepScrollList1.ShowLeftBorder = true;
            beepScrollList1.ShowRightBorder = true;
            beepScrollList1.ShowShadow = false;
            beepScrollList1.ShowTopBorder = true;
            beepScrollList1.Size = new Size(207, 73);
            beepScrollList1.SlideFrom = SlideDirection.Left;
            beepScrollList1.StaticNotMoving = false;
            beepScrollList1.TabIndex = 13;
            beepScrollList1.TempBackColor = Color.Empty;
            beepScrollList1.Text = "beepScrollList1";
            beepScrollList1.TextFont = new Font("Arial", 10F);
            beepScrollList1.Theme = EnumBeepThemes.DefaultTheme;
            beepScrollList1.ToolTipText = "";
            beepScrollList1.TopoffsetForDrawingRect = 0;
            beepScrollList1.UseGradientBackground = false;
            beepScrollList1.UseThemeFont = true;
            // 
            // beepButton1
            // 
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.ApplyThemeToChilds = false;
            beepButton1.BackColor = Color.FromArgb(105, 105, 105);
            beepButton1.BadgeBackColor = Color.Red;
            beepButton1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepButton1.BadgeForeColor = Color.White;
            beepButton1.BadgeShape = BadgeShape.Circle;
            beepButton1.BadgeText = "";
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.FromArgb(169, 169, 169);
            beepButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton1.BorderRadius = 8;
            beepButton1.BorderSize = 1;
            beepButton1.BorderStyle = BorderStyle.FixedSingle;
            beepButton1.BorderThickness = 1;
            beepButton1.BottomoffsetForDrawingRect = 0;
            beepButton1.BoundProperty = null;
            beepButton1.CanBeFocused = true;
            beepButton1.CanBeHovered = true;
            beepButton1.CanBePressed = true;
            beepButton1.Category = Utilities.DbFieldCategory.Boolean;
            beepButton1.ComponentName = "beepButton1";
            beepButton1.DataContext = null;
            beepButton1.DataSourceProperty = null;
            beepButton1.DisabledBackColor = Color.FromArgb(70, 70, 70);
            beepButton1.DisabledForeColor = Color.FromArgb(120, 120, 120);
            beepButton1.DrawingRect = new Rectangle(0, 0, 179, 43);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.FieldID = null;
            beepButton1.FocusBackColor = Color.FromArgb(25, 25, 112);
            beepButton1.FocusBorderColor = Color.Gray;
            beepButton1.FocusForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.FocusIndicatorColor = Color.Blue;
            beepButton1.Font = new Font("Segoe UI", 9F);
            beepButton1.ForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.Form = null;
            beepButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.FromArgb(35, 35, 50);
            beepButton1.GradientStartColor = Color.FromArgb(18, 18, 18);
            beepButton1.GuidID = "010408c2-0998-4449-9980-77394786ecce";
            beepButton1.HideText = false;
            beepButton1.HitAreaEventOn = false;
            beepButton1.HitTestControl = null;
            beepButton1.HoverBackColor = Color.FromArgb(45, 45, 132);
            beepButton1.HoverBorderColor = Color.Gray;
            beepButton1.HoveredBackcolor = Color.Wheat;
            beepButton1.HoverForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton1.ImageClicked = null;
            beepButton1.ImageEmbededin = ImageEmbededin.Button;
            beepButton1.ImagePath = null;
            beepButton1.InactiveBorderColor = Color.Gray;
            beepButton1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepButton1.Info");
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = false;
            beepButton1.IsCustomeBorder = false;
            beepButton1.IsDefault = false;
            beepButton1.IsDeleted = false;
            beepButton1.IsDirty = false;
            beepButton1.IsEditable = false;
            beepButton1.IsFocused = false;
            beepButton1.IsFrameless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsNew = false;
            beepButton1.IsPopupOpen = false;
            beepButton1.IsPressed = false;
            beepButton1.IsReadOnly = false;
            beepButton1.IsRequired = false;
            beepButton1.IsRounded = true;
            beepButton1.IsRoundedAffectedByTheme = true;
            beepButton1.IsSelected = false;
            beepButton1.IsSelectedAuto = false;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.IsVisible = false;
            beepButton1.Items = (List<object>)resources.GetObject("beepButton1.Items");
            beepButton1.LeftoffsetForDrawingRect = 0;
            beepButton1.LinkedProperty = null;
            beepButton1.Location = new Point(403, 339);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaxImageSize = new Size(32, 32);
            beepButton1.Name = "beepButton1";
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.ParentBackColor = Color.Empty;
            beepButton1.ParentControl = null;
            beepButton1.PopPosition = BeepPopupFormPosition.Bottom;
            beepButton1.PopupListForm = null;
            beepButton1.PopupMode = false;
            beepButton1.PressedBackColor = Color.FromArgb(15, 15, 92);
            beepButton1.PressedBorderColor = Color.FromArgb(255, 255, 255);
            beepButton1.PressedForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.RightoffsetForDrawingRect = 0;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.SelectedBackColor = Color.White;
            beepButton1.SelectedForeColor = Color.Black;
            beepButton1.SelectedIndex = -1;
            beepButton1.SelectedItem = null;
            beepButton1.ShadowColor = Color.FromArgb(25, 25, 112);
            beepButton1.ShadowOffset = 0;
            beepButton1.ShadowOpacity = 0.5F;
            beepButton1.ShowAllBorders = false;
            beepButton1.ShowBottomBorder = false;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowLeftBorder = false;
            beepButton1.ShowRightBorder = false;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = false;
            beepButton1.Size = new Size(179, 43);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 15;
            beepButton1.TempBackColor = Color.Empty;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepButton1.TextFont = new Font("Segoe UI", 9F);
            beepButton1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton1.Theme = EnumBeepThemes.MidnightTheme;
            beepButton1.ToolTipText = "";
            beepButton1.TopoffsetForDrawingRect = 0;
            beepButton1.UseGradientBackground = false;
            beepButton1.UseScaledFont = false;
            beepButton1.UseThemeFont = true;
            // 
            // beepCalendarView1
            // 
            beepCalendarView1.AnimationDuration = 500;
            beepCalendarView1.AnimationType = DisplayAnimationType.None;
            beepCalendarView1.ApplyThemeToChilds = false;
            beepCalendarView1.BackColor = Color.FromArgb(255, 255, 255);
            beepCalendarView1.BadgeBackColor = Color.Red;
            beepCalendarView1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepCalendarView1.BadgeForeColor = Color.White;
            beepCalendarView1.BadgeShape = BadgeShape.Circle;
            beepCalendarView1.BadgeText = "";
            beepCalendarView1.BlockID = null;
            beepCalendarView1.BorderColor = Color.FromArgb(173, 181, 189);
            beepCalendarView1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCalendarView1.BorderRadius = 8;
            beepCalendarView1.BorderStyle = BorderStyle.FixedSingle;
            beepCalendarView1.BorderThickness = 1;
            beepCalendarView1.BottomoffsetForDrawingRect = 0;
            beepCalendarView1.BoundProperty = null;
            beepCalendarView1.CanBeFocused = true;
            beepCalendarView1.CanBeHovered = false;
            beepCalendarView1.CanBePressed = true;
            beepCalendarView1.Category = Utilities.DbFieldCategory.String;
            beepCalendarView1.ComponentName = "beepCalendarView1";
            beepCalendarView1.DataContext = null;
            beepCalendarView1.DataSourceProperty = null;
            beepCalendarView1.DisabledBackColor = Color.White;
            beepCalendarView1.DisabledForeColor = Color.Black;
            beepCalendarView1.DrawingRect = new Rectangle(1, 1, 298, 328);
            beepCalendarView1.Easing = EasingType.Linear;
            beepCalendarView1.FieldID = null;
            beepCalendarView1.FocusBackColor = Color.White;
            beepCalendarView1.FocusBorderColor = Color.Gray;
            beepCalendarView1.FocusForeColor = Color.Black;
            beepCalendarView1.FocusIndicatorColor = Color.Blue;
            beepCalendarView1.Form = null;
            beepCalendarView1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCalendarView1.GradientEndColor = Color.FromArgb(255, 255, 255);
            beepCalendarView1.GradientStartColor = Color.FromArgb(245, 245, 245);
            beepCalendarView1.GuidID = "9086e7ff-1426-437b-a4e9-95ff5ca6bf0a";
            beepCalendarView1.HitAreaEventOn = false;
            beepCalendarView1.HitTestControl = null;
            beepCalendarView1.HoverBackColor = Color.White;
            beepCalendarView1.HoverBorderColor = Color.Gray;
            beepCalendarView1.HoveredBackcolor = Color.Wheat;
            beepCalendarView1.HoverForeColor = Color.Black;
            beepCalendarView1.Id = -1;
            beepCalendarView1.InactiveBorderColor = Color.Gray;
            beepCalendarView1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepCalendarView1.Info");
            beepCalendarView1.IsAcceptButton = false;
            beepCalendarView1.IsBorderAffectedByTheme = true;
            beepCalendarView1.IsCancelButton = false;
            beepCalendarView1.IsChild = false;
            beepCalendarView1.IsCustomeBorder = false;
            beepCalendarView1.IsDefault = false;
            beepCalendarView1.IsDeleted = false;
            beepCalendarView1.IsDirty = false;
            beepCalendarView1.IsEditable = false;
            beepCalendarView1.IsFocused = false;
            beepCalendarView1.IsFrameless = false;
            beepCalendarView1.IsHovered = false;
            beepCalendarView1.IsNew = false;
            beepCalendarView1.IsPressed = false;
            beepCalendarView1.IsReadOnly = false;
            beepCalendarView1.IsRequired = false;
            beepCalendarView1.IsRounded = true;
            beepCalendarView1.IsRoundedAffectedByTheme = true;
            beepCalendarView1.IsSelected = false;
            beepCalendarView1.IsShadowAffectedByTheme = true;
            beepCalendarView1.IsVisible = false;
            beepCalendarView1.Items = (List<object>)resources.GetObject("beepCalendarView1.Items");
            beepCalendarView1.LeftoffsetForDrawingRect = 0;
            beepCalendarView1.LinkedProperty = null;
            beepCalendarView1.Location = new Point(36, 32);
            beepCalendarView1.Name = "beepCalendarView1";
            beepCalendarView1.OverrideFontSize = TypeStyleFontSize.None;
            beepCalendarView1.ParentBackColor = Color.Empty;
            beepCalendarView1.ParentControl = null;
            beepCalendarView1.PressedBackColor = Color.White;
            beepCalendarView1.PressedBorderColor = Color.Gray;
            beepCalendarView1.PressedForeColor = Color.Gray;
            beepCalendarView1.RightoffsetForDrawingRect = 0;
            beepCalendarView1.SavedGuidID = null;
            beepCalendarView1.SavedID = null;
            beepCalendarView1.SelectedBackColor = Color.White;
            beepCalendarView1.SelectedDateTime = null;
            beepCalendarView1.SelectedForeColor = Color.Black;
            beepCalendarView1.ShadowColor = Color.FromArgb(173, 181, 189);
            beepCalendarView1.ShadowOffset = 0;
            beepCalendarView1.ShadowOpacity = 0.5F;
            beepCalendarView1.ShowAllBorders = true;
            beepCalendarView1.ShowBottomBorder = true;
            beepCalendarView1.ShowFocusIndicator = false;
            beepCalendarView1.ShowLeftBorder = true;
            beepCalendarView1.ShowRightBorder = true;
            beepCalendarView1.ShowShadow = false;
            beepCalendarView1.ShowTopBorder = true;
            beepCalendarView1.Size = new Size(300, 330);
            beepCalendarView1.SlideFrom = SlideDirection.Left;
            beepCalendarView1.StaticNotMoving = false;
            beepCalendarView1.TabIndex = 16;
            beepCalendarView1.TempBackColor = Color.Empty;
            beepCalendarView1.Text = "beepCalendarView1";
            beepCalendarView1.Theme = EnumBeepThemes.DefaultTheme;
            beepCalendarView1.ToolTipText = "";
            beepCalendarView1.TopoffsetForDrawingRect = 0;
            beepCalendarView1.UseGradientBackground = false;
            beepCalendarView1.UseThemeFont = true;
            // 
            // beepTextBox1
            // 
            beepTextBox1.AcceptsReturn = false;
            beepTextBox1.AcceptsTab = false;
            beepTextBox1.AnimationDuration = 500;
            beepTextBox1.AnimationType = DisplayAnimationType.None;
            beepTextBox1.ApplyThemeOnImage = false;
            beepTextBox1.ApplyThemeToChilds = false;
            beepTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            beepTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            beepTextBox1.BackColor = Color.FromArgb(245, 245, 220);
            beepTextBox1.BadgeBackColor = Color.Red;
            beepTextBox1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepTextBox1.BadgeForeColor = Color.White;
            beepTextBox1.BadgeShape = BadgeShape.Circle;
            beepTextBox1.BadgeText = "";
            beepTextBox1.BlockID = null;
            beepTextBox1.BorderColor = Color.FromArgb(255, 192, 203);
            beepTextBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepTextBox1.BorderRadius = 3;
            beepTextBox1.BorderStyle = BorderStyle.FixedSingle;
            beepTextBox1.BorderThickness = 1;
            beepTextBox1.BottomoffsetForDrawingRect = 0;
            beepTextBox1.BoundProperty = "Text";
            beepTextBox1.CanBeFocused = true;
            beepTextBox1.CanBeHovered = false;
            beepTextBox1.CanBePressed = true;
            beepTextBox1.Category = Utilities.DbFieldCategory.String;
            beepTextBox1.ComponentName = "beepTextBox1";
            beepTextBox1.CustomMask = "";
            beepTextBox1.DataContext = null;
            beepTextBox1.DataSourceProperty = null;
            beepTextBox1.DateFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DisabledBackColor = Color.FromArgb(200, 200, 200);
            beepTextBox1.DisabledForeColor = Color.FromArgb(150, 150, 150);
            beepTextBox1.DrawingRect = new Rectangle(1, 1, 183, 51);
            beepTextBox1.Easing = EasingType.Linear;
            beepTextBox1.FieldID = null;
            beepTextBox1.FocusBackColor = Color.White;
            beepTextBox1.FocusBorderColor = Color.Gray;
            beepTextBox1.FocusForeColor = Color.Black;
            beepTextBox1.FocusIndicatorColor = Color.Blue;
            beepTextBox1.Font = new Font("Segoe UI", 11F);
            beepTextBox1.ForeColor = Color.FromArgb(75, 0, 130);
            beepTextBox1.Form = null;
            beepTextBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepTextBox1.GradientEndColor = Color.FromArgb(173, 216, 230);
            beepTextBox1.GradientStartColor = Color.FromArgb(255, 245, 247);
            beepTextBox1.GuidID = "8b3a173d-a63b-4717-a250-1c7e85ffb0d5";
            beepTextBox1.HideSelection = true;
            beepTextBox1.HitAreaEventOn = false;
            beepTextBox1.HitTestControl = null;
            beepTextBox1.HoverBackColor = Color.FromArgb(255, 235, 240);
            beepTextBox1.HoverBorderColor = Color.Gray;
            beepTextBox1.HoveredBackcolor = Color.Wheat;
            beepTextBox1.HoverForeColor = Color.FromArgb(75, 0, 130);
            beepTextBox1.Id = -1;
            beepTextBox1.ImageAlign = ContentAlignment.MiddleLeft;
            beepTextBox1.ImagePath = "TheTechIdea.Beep.Winform.Controls.GFX.SVG.search.svg";
            beepTextBox1.InactiveBorderColor = Color.Gray;
            beepTextBox1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepTextBox1.Info");
            beepTextBox1.IsAcceptButton = false;
            beepTextBox1.IsBorderAffectedByTheme = false;
            beepTextBox1.IsCancelButton = false;
            beepTextBox1.IsChild = false;
            beepTextBox1.IsCustomeBorder = false;
            beepTextBox1.IsDefault = false;
            beepTextBox1.IsDeleted = false;
            beepTextBox1.IsDirty = false;
            beepTextBox1.IsEditable = false;
            beepTextBox1.IsFocused = false;
            beepTextBox1.IsFrameless = false;
            beepTextBox1.IsHovered = false;
            beepTextBox1.IsNew = false;
            beepTextBox1.IsPressed = false;
            beepTextBox1.IsReadOnly = false;
            beepTextBox1.IsRequired = false;
            beepTextBox1.IsRounded = true;
            beepTextBox1.IsRoundedAffectedByTheme = true;
            beepTextBox1.IsSelected = false;
            beepTextBox1.IsShadowAffectedByTheme = false;
            beepTextBox1.IsVisible = false;
            beepTextBox1.Items = (List<object>)resources.GetObject("beepTextBox1.Items");
            beepTextBox1.LeftoffsetForDrawingRect = 0;
            beepTextBox1.LinkedProperty = null;
            beepTextBox1.Location = new Point(403, 385);
            beepTextBox1.MaskFormat = TextBoxMaskFormat.None;
            beepTextBox1.MaxImageSize = new Size(16, 16);
            beepTextBox1.Modified = false;
            beepTextBox1.Multiline = false;
            beepTextBox1.Name = "beepTextBox1";
            beepTextBox1.OnlyCharacters = false;
            beepTextBox1.OnlyDigits = false;
            beepTextBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepTextBox1.ParentBackColor = Color.Empty;
            beepTextBox1.ParentControl = null;
            beepTextBox1.PasswordChar = '\0';
            beepTextBox1.PlaceholderText = "";
            beepTextBox1.PressedBackColor = Color.White;
            beepTextBox1.PressedBorderColor = Color.Gray;
            beepTextBox1.PressedForeColor = Color.Gray;
            beepTextBox1.ReadOnly = false;
            beepTextBox1.RightoffsetForDrawingRect = 0;
            beepTextBox1.SavedGuidID = null;
            beepTextBox1.SavedID = null;
            beepTextBox1.ScrollBars = ScrollBars.None;
            beepTextBox1.SelectedBackColor = Color.FromArgb(245, 245, 220);
            beepTextBox1.SelectedForeColor = Color.FromArgb(75, 0, 130);
            beepTextBox1.SelectionStart = 0;
            beepTextBox1.ShadowColor = Color.FromArgb(255, 192, 203);
            beepTextBox1.ShadowOffset = 0;
            beepTextBox1.ShadowOpacity = 0.5F;
            beepTextBox1.ShowAllBorders = true;
            beepTextBox1.ShowBottomBorder = true;
            beepTextBox1.ShowFocusIndicator = false;
            beepTextBox1.ShowLeftBorder = true;
            beepTextBox1.ShowRightBorder = true;
            beepTextBox1.ShowScrollbars = false;
            beepTextBox1.ShowShadow = false;
            beepTextBox1.ShowTopBorder = true;
            beepTextBox1.ShowVerticalScrollBar = false;
            beepTextBox1.Size = new Size(185, 53);
            beepTextBox1.SlideFrom = SlideDirection.Left;
            beepTextBox1.StaticNotMoving = false;
            beepTextBox1.TabIndex = 17;
            beepTextBox1.TempBackColor = Color.Empty;
            beepTextBox1.Text = "beepTextBox1";
            beepTextBox1.TextAlignment = HorizontalAlignment.Left;
            beepTextBox1.TextFont = new Font("Segoe UI", 11F);
            beepTextBox1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepTextBox1.Theme = EnumBeepThemes.CandyTheme;
            beepTextBox1.TimeFormat = "HH:mm:ss";
            beepTextBox1.ToolTipText = "";
            beepTextBox1.TopoffsetForDrawingRect = 0;
            beepTextBox1.UseGradientBackground = false;
            beepTextBox1.UseSystemPasswordChar = false;
            beepTextBox1.UseThemeFont = true;
            beepTextBox1.WordWrap = true;
            // 
            // beepListBox1
            // 
            beepListBox1.AnimationDuration = 500;
            beepListBox1.AnimationType = DisplayAnimationType.None;
            beepListBox1.ApplyThemeToChilds = false;
            beepListBox1.BackColor = Color.FromArgb(255, 255, 255);
            beepListBox1.BadgeBackColor = Color.Red;
            beepListBox1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepListBox1.BadgeForeColor = Color.White;
            beepListBox1.BadgeShape = BadgeShape.Circle;
            beepListBox1.BadgeText = "";
            beepListBox1.BlockID = null;
            beepListBox1.BorderColor = Color.Black;
            beepListBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepListBox1.BorderRadius = 3;
            beepListBox1.BorderStyle = BorderStyle.FixedSingle;
            beepListBox1.BorderThickness = 1;
            beepListBox1.BottomoffsetForDrawingRect = 0;
            beepListBox1.BoundProperty = "SelectedMenuItem";
            beepListBox1.CanBeFocused = true;
            beepListBox1.CanBeHovered = false;
            beepListBox1.CanBePressed = true;
            beepListBox1.Category = Utilities.DbFieldCategory.String;
            beepListBox1.Collapsed = false;
            beepListBox1.ComponentName = "beepListBox1";
            beepListBox1.DataContext = null;
            beepListBox1.DataSourceProperty = null;
            beepListBox1.DisabledBackColor = Color.White;
            beepListBox1.DisabledForeColor = Color.Black;
            beepListBox1.DrawingRect = new Rectangle(0, 0, 304, 323);
            beepListBox1.Easing = EasingType.Linear;
            beepListBox1.FieldID = null;
            beepListBox1.FocusBackColor = Color.White;
            beepListBox1.FocusBorderColor = Color.Gray;
            beepListBox1.FocusForeColor = Color.Black;
            beepListBox1.FocusIndicatorColor = Color.Blue;
            beepListBox1.Font = new Font("Arial", 10F);
            beepListBox1.ForeColor = Color.FromArgb(33, 37, 41);
            beepListBox1.Form = null;
            beepListBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepListBox1.GradientEndColor = Color.Gray;
            beepListBox1.GradientStartColor = Color.Gray;
            beepListBox1.GuidID = "2646de57-63fc-4370-923a-13ab484c0a50";
            beepListBox1.HitAreaEventOn = false;
            beepListBox1.HitTestControl = null;
            beepListBox1.HoverBackColor = Color.White;
            beepListBox1.HoverBorderColor = Color.Gray;
            beepListBox1.HoveredBackcolor = Color.Wheat;
            beepListBox1.HoverForeColor = Color.Black;
            beepListBox1.Id = -1;
            beepListBox1.ImageSize = 18;
            beepListBox1.InactiveBorderColor = Color.Gray;
            beepListBox1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepListBox1.Info");
            beepListBox1.IsAcceptButton = false;
            beepListBox1.IsBorderAffectedByTheme = true;
            beepListBox1.IsCancelButton = false;
            beepListBox1.IsChild = false;
            beepListBox1.IsCustomeBorder = false;
            beepListBox1.IsDefault = false;
            beepListBox1.IsDeleted = false;
            beepListBox1.IsDirty = false;
            beepListBox1.IsEditable = false;
            beepListBox1.IsFocused = false;
            beepListBox1.IsFrameless = false;
            beepListBox1.IsHovered = false;
            beepListBox1.IsItemChilds = true;
            beepListBox1.IsNew = false;
            beepListBox1.IsPressed = false;
            beepListBox1.IsReadOnly = false;
            beepListBox1.IsRequired = false;
            beepListBox1.IsRounded = true;
            beepListBox1.IsRoundedAffectedByTheme = true;
            beepListBox1.IsSelected = false;
            beepListBox1.IsShadowAffectedByTheme = true;
            beepListBox1.IsVisible = false;
            beepListBox1.Items = (List<object>)resources.GetObject("beepListBox1.Items");
            beepListBox1.LeftoffsetForDrawingRect = 0;
            beepListBox1.LinkedProperty = null;
            beepListBox1.ListItems.Add((Controls.Models.SimpleItem)resources.GetObject("beepListBox1.ListItems"));
            beepListBox1.ListItems.Add((Controls.Models.SimpleItem)resources.GetObject("beepListBox1.ListItems1"));
            beepListBox1.ListItems.Add((Controls.Models.SimpleItem)resources.GetObject("beepListBox1.ListItems2"));
            beepListBox1.ListItems.Add((Controls.Models.SimpleItem)resources.GetObject("beepListBox1.ListItems3"));
            beepListBox1.Location = new Point(32, 387);
            beepListBox1.MenuItemHeight = 20;
            beepListBox1.Name = "beepListBox1";
            beepListBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepListBox1.ParentBackColor = Color.Empty;
            beepListBox1.ParentControl = null;
            beepListBox1.PressedBackColor = Color.FromArgb(0, 100, 195);
            beepListBox1.PressedBorderColor = Color.FromArgb(255, 255, 255);
            beepListBox1.PressedForeColor = Color.FromArgb(255, 255, 255);
            beepListBox1.RightoffsetForDrawingRect = 0;
            beepListBox1.SavedGuidID = null;
            beepListBox1.SavedID = null;
            beepListBox1.SelectedBackColor = Color.White;
            beepListBox1.SelectedForeColor = Color.Black;
            beepListBox1.SelectedIndex = -1;
            beepListBox1.SelectedItem = null;
            beepListBox1.ShadowColor = Color.Black;
            beepListBox1.ShadowOffset = 0;
            beepListBox1.ShadowOpacity = 0.5F;
            beepListBox1.ShowAllBorders = false;
            beepListBox1.ShowBottomBorder = false;
            beepListBox1.ShowCheckBox = false;
            beepListBox1.ShowFocusIndicator = false;
            beepListBox1.ShowHilightBox = true;
            beepListBox1.ShowImage = false;
            beepListBox1.ShowLeftBorder = false;
            beepListBox1.ShowRightBorder = false;
            beepListBox1.ShowShadow = false;
            beepListBox1.ShowTitle = true;
            beepListBox1.ShowTitleLine = true;
            beepListBox1.ShowTitleLineinFullWidth = true;
            beepListBox1.ShowTopBorder = false;
            beepListBox1.Size = new Size(304, 323);
            beepListBox1.SlideFrom = SlideDirection.Left;
            beepListBox1.StaticNotMoving = false;
            beepListBox1.TabIndex = 18;
            beepListBox1.TempBackColor = Color.Empty;
            beepListBox1.Text = "beepListBox1";
            beepListBox1.TextFont = new Font("Arial", 10F);
            beepListBox1.Theme = EnumBeepThemes.DefaultTheme;
            beepListBox1.TitleAlignment = ContentAlignment.TopLeft;
            beepListBox1.TitleBottomY = 24;
            beepListBox1.TitleLineColor = Color.Gray;
            beepListBox1.TitleLineThickness = 2;
            beepListBox1.TitleText = "List Box";
            beepListBox1.ToolTipText = "";
            beepListBox1.TopoffsetForDrawingRect = 0;
            beepListBox1.UseGradientBackground = false;
            beepListBox1.UseThemeFont = false;
            // 
            // beepTextBox2
            // 
            beepTextBox2.AcceptsReturn = false;
            beepTextBox2.AcceptsTab = false;
            beepTextBox2.AnimationDuration = 500;
            beepTextBox2.AnimationType = DisplayAnimationType.None;
            beepTextBox2.ApplyThemeOnImage = false;
            beepTextBox2.ApplyThemeToChilds = false;
            beepTextBox2.AutoCompleteMode = AutoCompleteMode.None;
            beepTextBox2.AutoCompleteSource = AutoCompleteSource.None;
            beepTextBox2.BadgeBackColor = Color.Red;
            beepTextBox2.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepTextBox2.BadgeForeColor = Color.White;
            beepTextBox2.BadgeShape = BadgeShape.Circle;
            beepTextBox2.BadgeText = "";
            beepTextBox2.BlockID = null;
            beepTextBox2.BorderColor = Color.Black;
            beepTextBox2.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepTextBox2.BorderRadius = 3;
            beepTextBox2.BorderStyle = BorderStyle.FixedSingle;
            beepTextBox2.BorderThickness = 1;
            beepTextBox2.BottomoffsetForDrawingRect = 0;
            beepTextBox2.BoundProperty = "Text";
            beepTextBox2.CanBeFocused = true;
            beepTextBox2.CanBeHovered = false;
            beepTextBox2.CanBePressed = true;
            beepTextBox2.Category = Utilities.DbFieldCategory.String;
            beepTextBox2.ComponentName = "beepTextBox2";
            beepTextBox2.CustomMask = "";
            beepTextBox2.DataContext = null;
            beepTextBox2.DataSourceProperty = null;
            beepTextBox2.DateFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox2.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox2.DisabledBackColor = Color.White;
            beepTextBox2.DisabledForeColor = Color.Black;
            beepTextBox2.DrawingRect = new Rectangle(1, 1, 198, 21);
            beepTextBox2.Easing = EasingType.Linear;
            beepTextBox2.FieldID = null;
            beepTextBox2.FocusBackColor = Color.White;
            beepTextBox2.FocusBorderColor = Color.Gray;
            beepTextBox2.FocusForeColor = Color.Black;
            beepTextBox2.FocusIndicatorColor = Color.Blue;
            beepTextBox2.Form = null;
            beepTextBox2.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepTextBox2.GradientEndColor = Color.Gray;
            beepTextBox2.GradientStartColor = Color.Gray;
            beepTextBox2.GuidID = "01983524-bcee-4452-a9bb-5eae7c701df1";
            beepTextBox2.HideSelection = true;
            beepTextBox2.HitAreaEventOn = false;
            beepTextBox2.HitTestControl = null;
            beepTextBox2.HoverBackColor = Color.White;
            beepTextBox2.HoverBorderColor = Color.Gray;
            beepTextBox2.HoveredBackcolor = Color.Wheat;
            beepTextBox2.HoverForeColor = Color.Black;
            beepTextBox2.Id = -1;
            beepTextBox2.ImageAlign = ContentAlignment.MiddleLeft;
            beepTextBox2.ImagePath = null;
            beepTextBox2.InactiveBorderColor = Color.Gray;
            beepTextBox2.Info = (Controls.Models.SimpleItem)resources.GetObject("beepTextBox2.Info");
            beepTextBox2.IsAcceptButton = false;
            beepTextBox2.IsBorderAffectedByTheme = false;
            beepTextBox2.IsCancelButton = false;
            beepTextBox2.IsChild = false;
            beepTextBox2.IsCustomeBorder = false;
            beepTextBox2.IsDefault = false;
            beepTextBox2.IsDeleted = false;
            beepTextBox2.IsDirty = false;
            beepTextBox2.IsEditable = false;
            beepTextBox2.IsFocused = false;
            beepTextBox2.IsFrameless = false;
            beepTextBox2.IsHovered = false;
            beepTextBox2.IsNew = false;
            beepTextBox2.IsPressed = false;
            beepTextBox2.IsReadOnly = false;
            beepTextBox2.IsRequired = false;
            beepTextBox2.IsRounded = true;
            beepTextBox2.IsRoundedAffectedByTheme = true;
            beepTextBox2.IsSelected = false;
            beepTextBox2.IsShadowAffectedByTheme = false;
            beepTextBox2.IsVisible = false;
            beepTextBox2.Items = (List<object>)resources.GetObject("beepTextBox2.Items");
            beepTextBox2.LeftoffsetForDrawingRect = 0;
            beepTextBox2.LinkedProperty = null;
            beepTextBox2.Location = new Point(403, 514);
            beepTextBox2.MaskFormat = TextBoxMaskFormat.None;
            beepTextBox2.MaxImageSize = new Size(16, 16);
            beepTextBox2.Modified = false;
            beepTextBox2.Multiline = false;
            beepTextBox2.Name = "beepTextBox2";
            beepTextBox2.OnlyCharacters = false;
            beepTextBox2.OnlyDigits = false;
            beepTextBox2.OverrideFontSize = TypeStyleFontSize.None;
            beepTextBox2.ParentBackColor = Color.Empty;
            beepTextBox2.ParentControl = null;
            beepTextBox2.PasswordChar = '\0';
            beepTextBox2.PlaceholderText = "";
            beepTextBox2.PressedBackColor = Color.White;
            beepTextBox2.PressedBorderColor = Color.Gray;
            beepTextBox2.PressedForeColor = Color.Gray;
            beepTextBox2.ReadOnly = false;
            beepTextBox2.RightoffsetForDrawingRect = 0;
            beepTextBox2.SavedGuidID = null;
            beepTextBox2.SavedID = null;
            beepTextBox2.ScrollBars = ScrollBars.None;
            beepTextBox2.SelectedBackColor = Color.White;
            beepTextBox2.SelectedForeColor = Color.Black;
            beepTextBox2.SelectionStart = 0;
            beepTextBox2.ShadowColor = Color.Black;
            beepTextBox2.ShadowOffset = 0;
            beepTextBox2.ShadowOpacity = 0.5F;
            beepTextBox2.ShowAllBorders = true;
            beepTextBox2.ShowBottomBorder = true;
            beepTextBox2.ShowFocusIndicator = false;
            beepTextBox2.ShowLeftBorder = true;
            beepTextBox2.ShowRightBorder = true;
            beepTextBox2.ShowScrollbars = false;
            beepTextBox2.ShowShadow = false;
            beepTextBox2.ShowTopBorder = true;
            beepTextBox2.ShowVerticalScrollBar = false;
            beepTextBox2.Size = new Size(200, 23);
            beepTextBox2.SlideFrom = SlideDirection.Left;
            beepTextBox2.StaticNotMoving = false;
            beepTextBox2.TabIndex = 19;
            beepTextBox2.TempBackColor = Color.Empty;
            beepTextBox2.Text = "beepTextBox2";
            beepTextBox2.TextAlignment = HorizontalAlignment.Left;
            beepTextBox2.TextFont = new Font("Arial", 10F);
            beepTextBox2.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepTextBox2.Theme = EnumBeepThemes.DefaultTheme;
            beepTextBox2.TimeFormat = "HH:mm:ss";
            beepTextBox2.ToolTipText = "";
            beepTextBox2.TopoffsetForDrawingRect = 0;
            beepTextBox2.UseGradientBackground = false;
            beepTextBox2.UseSystemPasswordChar = false;
            beepTextBox2.UseThemeFont = true;
            beepTextBox2.WordWrap = true;
            // 
            // uc_FilterForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Controls.Add(beepTextBox2);
            Controls.Add(beepListBox1);
            Controls.Add(beepTextBox1);
            Controls.Add(beepCalendarView1);
            Controls.Add(beepButton1);
            Controls.Add(beepScrollList1);
            Controls.Add(beepDatePicker1);
            Controls.Add(beepFeatureCard1);
            Controls.Add(beepChart1);
            Controls.Add(beepStatCard1);
            Controls.Add(beepCard1);
            Name = "uc_FilterForm";
            Size = new Size(1044, 738);
            ResumeLayout(false);
        }

        #endregion
        private Controls.BeepCard beepCard1;
        private Controls.BeepStatCard beepStatCard1;
        private Controls.BeepChart beepChart1;
        private Controls.BeepFeatureCard beepFeatureCard1;
        private BeepDatePicker beepDatePicker1;
        private BeepScrollList beepScrollList1;
        private BeepButton beepButton1;
        private BeepCalendarView beepCalendarView1;
        private BeepTextBox beepTextBox1;
        private BeepListBox beepListBox1;
        private BeepTextBox beepTextBox2;
    }
}
