

namespace TheTechIdea.Beep.Winform.Default.Views.Configuration
{
    partial class uc_FilterForm
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_FilterForm));
            beepRadioButton1 = new TheTechIdea.Beep.Winform.Controls.BeepRadioButton();
            beepSwitch1 = new TheTechIdea.Beep.Winform.Controls.BeepSwitch();
            beepToolStrip1 = new TheTechIdea.Beep.Winform.Controls.BeepToolStrip();
            beepNumericUpDown1 = new TheTechIdea.Beep.Winform.Controls.BeepNumericUpDown();
            beepDatePicker1 = new TheTechIdea.Beep.Winform.Controls.BeepDatePicker();
            monthCalendar1 = new MonthCalendar();
            beepCard1 = new TheTechIdea.Beep.Winform.Controls.BeepCard();
            SuspendLayout();
            // 
            // beepRadioButton1
            // 
            beepRadioButton1.ActiveBackColor = Color.FromArgb(0, 120, 215);
            beepRadioButton1.AnimationDuration = 500;
            beepRadioButton1.AnimationType = Winform.Controls.DisplayAnimationType.None;
            beepRadioButton1.ApplyThemeToChilds = false;
            beepRadioButton1.BackColor = Color.FromArgb(245, 245, 245);
            beepRadioButton1.BadgeBackColor = Color.Red;
            beepRadioButton1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepRadioButton1.BadgeForeColor = Color.White;
            beepRadioButton1.BadgeShape = Winform.Controls.BadgeShape.Circle;
            beepRadioButton1.BadgeText = "";
            beepRadioButton1.BlockID = null;
            beepRadioButton1.BorderColor = Color.FromArgb(200, 200, 200);
            beepRadioButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepRadioButton1.BorderRadius = 3;
            beepRadioButton1.BorderStyle = BorderStyle.FixedSingle;
            beepRadioButton1.BorderThickness = 1;
            beepRadioButton1.BottomoffsetForDrawingRect = 0;
            beepRadioButton1.BoundProperty = null;
            beepRadioButton1.CanBeFocused = true;
            beepRadioButton1.CanBeHovered = false;
            beepRadioButton1.CanBePressed = true;
            beepRadioButton1.Category = Utilities.DbFieldCategory.String;
            beepRadioButton1.ComponentName = "beepRadioButton1";
            beepRadioButton1.DataContext = null;
            beepRadioButton1.DataSourceProperty = null;
            beepRadioButton1.DisabledBackColor = Color.Gray;
            beepRadioButton1.DisabledForeColor = Color.Empty;
            beepRadioButton1.DrawingRect = new Rectangle(1, 1, 100, 49);
            beepRadioButton1.Easing = Winform.Controls.EasingType.Linear;
            beepRadioButton1.FieldID = null;
            beepRadioButton1.FocusBackColor = Color.White;
            beepRadioButton1.FocusBorderColor = Color.Gray;
            beepRadioButton1.FocusForeColor = Color.Black;
            beepRadioButton1.FocusIndicatorColor = Color.Blue;
            beepRadioButton1.Font = new Font("Segoe UI", 9F);
            beepRadioButton1.ForeColor = Color.FromArgb(0, 0, 0);
            beepRadioButton1.Form = null;
            beepRadioButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepRadioButton1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepRadioButton1.GradientStartColor = Color.White;
            beepRadioButton1.GuidID = "0c6da190-2156-4126-9ff7-72aa145e1030";
            beepRadioButton1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepRadioButton1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepRadioButton1.HoveredBackcolor = Color.Wheat;
            beepRadioButton1.HoverForeColor = Color.Black;
            beepRadioButton1.Id = -1;
            beepRadioButton1.InactiveBackColor = Color.Gray;
            beepRadioButton1.InactiveBorderColor = Color.Gray;
            beepRadioButton1.InactiveForeColor = Color.Black;
            beepRadioButton1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepRadioButton1.Info");
            beepRadioButton1.IsAcceptButton = false;
            beepRadioButton1.IsBorderAffectedByTheme = true;
            beepRadioButton1.IsCancelButton = false;
            beepRadioButton1.IsChild = false;
            beepRadioButton1.IsCustomeBorder = false;
            beepRadioButton1.IsDefault = false;
            beepRadioButton1.IsDeleted = false;
            beepRadioButton1.IsDirty = false;
            beepRadioButton1.IsEditable = false;
            beepRadioButton1.IsFocused = false;
            beepRadioButton1.IsFrameless = false;
            beepRadioButton1.IsHovered = false;
            beepRadioButton1.IsNew = false;
            beepRadioButton1.IsPressed = false;
            beepRadioButton1.IsReadOnly = false;
            beepRadioButton1.IsRequired = false;
            beepRadioButton1.IsRounded = true;
            beepRadioButton1.IsRoundedAffectedByTheme = true;
            beepRadioButton1.IsSelected = false;
            beepRadioButton1.IsShadowAffectedByTheme = true;
            beepRadioButton1.IsVisible = false;
            beepRadioButton1.Items = (List<object>)resources.GetObject("beepRadioButton1.Items");
            beepRadioButton1.LeftoffsetForDrawingRect = 0;
            beepRadioButton1.LinkedProperty = null;
            beepRadioButton1.Location = new Point(189, 318);
            beepRadioButton1.Name = "beepRadioButton1";
            beepRadioButton1.OverrideFontSize = Winform.Controls.TypeStyleFontSize.None;
            beepRadioButton1.ParentBackColor = Color.Empty;
            beepRadioButton1.ParentControl = null;
            beepRadioButton1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepRadioButton1.PressedBorderColor = Color.Gray;
            beepRadioButton1.PressedForeColor = Color.Black;
            beepRadioButton1.RightoffsetForDrawingRect = 0;
            beepRadioButton1.SavedGuidID = null;
            beepRadioButton1.SavedID = null;
            beepRadioButton1.SelectedValue = "";
            beepRadioButton1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepRadioButton1.ShadowOffset = 0;
            beepRadioButton1.ShadowOpacity = 0.5F;
            beepRadioButton1.ShowAllBorders = true;
            beepRadioButton1.ShowBottomBorder = true;
            beepRadioButton1.ShowFocusIndicator = false;
            beepRadioButton1.ShowLeftBorder = true;
            beepRadioButton1.ShowRightBorder = true;
            beepRadioButton1.ShowShadow = false;
            beepRadioButton1.ShowTopBorder = true;
            beepRadioButton1.Size = new Size(102, 51);
            beepRadioButton1.SlideFrom = Winform.Controls.SlideDirection.Left;
            beepRadioButton1.StaticNotMoving = false;
            beepRadioButton1.TabIndex = 0;
            beepRadioButton1.TempBackColor = Color.Empty;
            beepRadioButton1.Text = "beepRadioButton1";
            beepRadioButton1.TextFont = new Font("Segoe UI", 9F);
            beepRadioButton1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepRadioButton1.ToolTipText = "";
            beepRadioButton1.TopoffsetForDrawingRect = 0;
            beepRadioButton1.UseGradientBackground = false;
            beepRadioButton1.UseThemeFont = true;
            // 
            // beepSwitch1
            // 
            beepSwitch1.ActiveBackColor = Color.FromArgb(0, 120, 215);
            beepSwitch1.AnimationDuration = 500;
            beepSwitch1.AnimationType = Winform.Controls.DisplayAnimationType.None;
            beepSwitch1.ApplyThemeToChilds = false;
            beepSwitch1.BackColor = Color.White;
            beepSwitch1.BadgeBackColor = Color.Red;
            beepSwitch1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepSwitch1.BadgeForeColor = Color.White;
            beepSwitch1.BadgeShape = Winform.Controls.BadgeShape.Circle;
            beepSwitch1.BadgeText = "";
            beepSwitch1.BlockID = null;
            beepSwitch1.BorderColor = Color.FromArgb(200, 200, 200);
            beepSwitch1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSwitch1.BorderRadius = 3;
            beepSwitch1.BorderStyle = BorderStyle.FixedSingle;
            beepSwitch1.BorderThickness = 1;
            beepSwitch1.BottomoffsetForDrawingRect = 0;
            beepSwitch1.BoundProperty = "Checked";
            beepSwitch1.CanBeFocused = true;
            beepSwitch1.CanBeHovered = false;
            beepSwitch1.CanBePressed = true;
            beepSwitch1.Category = Utilities.DbFieldCategory.String;
            beepSwitch1.Checked = false;
            beepSwitch1.ComponentName = "beepSwitch1";
            beepSwitch1.DataContext = null;
            beepSwitch1.DataSourceProperty = null;
            beepSwitch1.DisabledBackColor = Color.Gray;
            beepSwitch1.DisabledForeColor = Color.Empty;
            beepSwitch1.DrawingRect = new Rectangle(1, 1, 118, 48);
            beepSwitch1.Easing = Winform.Controls.EasingType.Linear;
            beepSwitch1.FieldID = null;
            beepSwitch1.FocusBackColor = Color.White;
            beepSwitch1.FocusBorderColor = Color.Gray;
            beepSwitch1.FocusForeColor = Color.Black;
            beepSwitch1.FocusIndicatorColor = Color.Blue;
            beepSwitch1.ForeColor = Color.FromArgb(0, 0, 0);
            beepSwitch1.Form = null;
            beepSwitch1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSwitch1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepSwitch1.GradientStartColor = Color.White;
            beepSwitch1.GuidID = "68e34f90-2779-45bf-abb9-5751e4145061";
            beepSwitch1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepSwitch1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepSwitch1.HoveredBackcolor = Color.Wheat;
            beepSwitch1.HoverForeColor = Color.Black;
            beepSwitch1.Id = -1;
            beepSwitch1.InactiveBackColor = Color.Gray;
            beepSwitch1.InactiveBorderColor = Color.Gray;
            beepSwitch1.InactiveForeColor = Color.Black;
            beepSwitch1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepSwitch1.Info");
            beepSwitch1.IsAcceptButton = false;
            beepSwitch1.IsBorderAffectedByTheme = true;
            beepSwitch1.IsCancelButton = false;
            beepSwitch1.IsChild = false;
            beepSwitch1.IsCustomeBorder = false;
            beepSwitch1.IsDefault = false;
            beepSwitch1.IsDeleted = false;
            beepSwitch1.IsDirty = false;
            beepSwitch1.IsEditable = false;
            beepSwitch1.IsFocused = false;
            beepSwitch1.IsFrameless = false;
            beepSwitch1.IsHovered = false;
            beepSwitch1.IsNew = false;
            beepSwitch1.IsPressed = false;
            beepSwitch1.IsReadOnly = false;
            beepSwitch1.IsRequired = false;
            beepSwitch1.IsRounded = true;
            beepSwitch1.IsRoundedAffectedByTheme = true;
            beepSwitch1.IsSelected = false;
            beepSwitch1.IsShadowAffectedByTheme = true;
            beepSwitch1.IsVisible = false;
            beepSwitch1.Items = (List<object>)resources.GetObject("beepSwitch1.Items");
            beepSwitch1.LeftoffsetForDrawingRect = 0;
            beepSwitch1.LinkedProperty = null;
            beepSwitch1.Location = new Point(195, 418);
            beepSwitch1.Name = "beepSwitch1";
            beepSwitch1.OffImagePath = null;
            beepSwitch1.OffLabel = "Off";
            beepSwitch1.OnImagePath = null;
            beepSwitch1.OnLabel = "On";
            beepSwitch1.OverrideFontSize = Winform.Controls.TypeStyleFontSize.None;
            beepSwitch1.ParentBackColor = Color.Empty;
            beepSwitch1.ParentControl = null;
            beepSwitch1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepSwitch1.PressedBorderColor = Color.Gray;
            beepSwitch1.PressedForeColor = Color.Black;
            beepSwitch1.RightoffsetForDrawingRect = 0;
            beepSwitch1.SavedGuidID = null;
            beepSwitch1.SavedID = null;
            beepSwitch1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepSwitch1.ShadowOffset = 0;
            beepSwitch1.ShadowOpacity = 0.5F;
            beepSwitch1.ShowAllBorders = true;
            beepSwitch1.ShowBottomBorder = true;
            beepSwitch1.ShowFocusIndicator = false;
            beepSwitch1.ShowLeftBorder = true;
            beepSwitch1.ShowRightBorder = true;
            beepSwitch1.ShowShadow = false;
            beepSwitch1.ShowTopBorder = true;
            beepSwitch1.Size = new Size(120, 50);
            beepSwitch1.SlideFrom = Winform.Controls.SlideDirection.Left;
            beepSwitch1.StaticNotMoving = false;
            beepSwitch1.TabIndex = 1;
            beepSwitch1.TempBackColor = Color.Empty;
            beepSwitch1.Text = "beepSwitch1";
            beepSwitch1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepSwitch1.ToolTipText = "";
            beepSwitch1.TopoffsetForDrawingRect = 0;
            beepSwitch1.UseGradientBackground = false;
            beepSwitch1.UseThemeFont = true;
            // 
            // beepToolStrip1
            // 
            beepToolStrip1.ActiveBackColor = Color.FromArgb(0, 120, 215);
            beepToolStrip1.AnimationDuration = 500;
            beepToolStrip1.AnimationType = Winform.Controls.DisplayAnimationType.None;
            beepToolStrip1.ApplyThemeToChilds = false;
            beepToolStrip1.BackColor = Color.FromArgb(245, 245, 245);
            beepToolStrip1.BadgeBackColor = Color.Red;
            beepToolStrip1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepToolStrip1.BadgeForeColor = Color.White;
            beepToolStrip1.BadgeShape = Winform.Controls.BadgeShape.Circle;
            beepToolStrip1.BadgeText = "";
            beepToolStrip1.BlockID = null;
            beepToolStrip1.BorderColor = Color.FromArgb(200, 200, 200);
            beepToolStrip1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepToolStrip1.BorderRadius = 3;
            beepToolStrip1.BorderStyle = BorderStyle.FixedSingle;
            beepToolStrip1.BorderThickness = 1;
            beepToolStrip1.BottomoffsetForDrawingRect = 0;
            beepToolStrip1.BoundProperty = null;
            beepToolStrip1.CanBeFocused = true;
            beepToolStrip1.CanBeHovered = false;
            beepToolStrip1.CanBePressed = true;
            beepToolStrip1.Category = Utilities.DbFieldCategory.String;
            beepToolStrip1.ComponentName = "beepToolStrip1";
            beepToolStrip1.DataContext = null;
            beepToolStrip1.DataSourceProperty = null;
            beepToolStrip1.DisabledBackColor = Color.Gray;
            beepToolStrip1.DisabledForeColor = Color.Empty;
            beepToolStrip1.DrawingRect = new Rectangle(1, 1, 347, 21);
            beepToolStrip1.Easing = Winform.Controls.EasingType.Linear;
            beepToolStrip1.FieldID = null;
            beepToolStrip1.FocusBackColor = Color.White;
            beepToolStrip1.FocusBorderColor = Color.Gray;
            beepToolStrip1.FocusForeColor = Color.Black;
            beepToolStrip1.FocusIndicatorColor = Color.Blue;
            beepToolStrip1.Form = null;
            beepToolStrip1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepToolStrip1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepToolStrip1.GradientStartColor = Color.White;
            beepToolStrip1.GuidID = "86e5fc6f-0c3e-47df-8a17-7e4ed87871ee";
            beepToolStrip1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepToolStrip1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepToolStrip1.HoveredBackcolor = Color.Wheat;
            beepToolStrip1.HoverForeColor = Color.Black;
            beepToolStrip1.Id = -1;
            beepToolStrip1.InactiveBackColor = Color.Gray;
            beepToolStrip1.InactiveBorderColor = Color.Gray;
            beepToolStrip1.InactiveForeColor = Color.Black;
            beepToolStrip1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepToolStrip1.Info");
            beepToolStrip1.IsAcceptButton = false;
            beepToolStrip1.IsBorderAffectedByTheme = true;
            beepToolStrip1.IsCancelButton = false;
            beepToolStrip1.IsChild = false;
            beepToolStrip1.IsCustomeBorder = false;
            beepToolStrip1.IsDefault = false;
            beepToolStrip1.IsDeleted = false;
            beepToolStrip1.IsDirty = false;
            beepToolStrip1.IsEditable = false;
            beepToolStrip1.IsFocused = false;
            beepToolStrip1.IsFrameless = false;
            beepToolStrip1.IsHovered = false;
            beepToolStrip1.IsNew = false;
            beepToolStrip1.IsPressed = false;
            beepToolStrip1.IsReadOnly = false;
            beepToolStrip1.IsRequired = false;
            beepToolStrip1.IsRounded = true;
            beepToolStrip1.IsRoundedAffectedByTheme = true;
            beepToolStrip1.IsSelected = false;
            beepToolStrip1.IsShadowAffectedByTheme = true;
            beepToolStrip1.IsVisible = false;
            beepToolStrip1.Items = (List<object>)resources.GetObject("beepToolStrip1.Items");
            beepToolStrip1.LeftoffsetForDrawingRect = 0;
            beepToolStrip1.LinkedProperty = null;
            beepToolStrip1.Location = new Point(160, 32);
            beepToolStrip1.Name = "beepToolStrip1";
            beepToolStrip1.Orientation = Winform.Controls.ToolStripOrientation.Horizontal;
            beepToolStrip1.OverrideFontSize = Winform.Controls.TypeStyleFontSize.None;
            beepToolStrip1.ParentBackColor = Color.Empty;
            beepToolStrip1.ParentControl = null;
            beepToolStrip1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepToolStrip1.PressedBorderColor = Color.Gray;
            beepToolStrip1.PressedForeColor = Color.Black;
            beepToolStrip1.RightoffsetForDrawingRect = 0;
            beepToolStrip1.SavedGuidID = null;
            beepToolStrip1.SavedID = null;
            beepToolStrip1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepToolStrip1.ShadowOffset = 0;
            beepToolStrip1.ShadowOpacity = 0.5F;
            beepToolStrip1.ShowAllBorders = true;
            beepToolStrip1.ShowBottomBorder = true;
            beepToolStrip1.ShowFocusIndicator = false;
            beepToolStrip1.ShowLeftBorder = true;
            beepToolStrip1.ShowRightBorder = true;
            beepToolStrip1.ShowShadow = false;
            beepToolStrip1.ShowTopBorder = true;
            beepToolStrip1.Size = new Size(349, 23);
            beepToolStrip1.SlideFrom = Winform.Controls.SlideDirection.Left;
            beepToolStrip1.StaticNotMoving = false;
            beepToolStrip1.TabIndex = 3;
            beepToolStrip1.TempBackColor = Color.Empty;
            beepToolStrip1.Text = "beepToolStrip1";
            beepToolStrip1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepToolStrip1.ToolTipText = "";
            beepToolStrip1.TopoffsetForDrawingRect = 0;
            beepToolStrip1.UseGradientBackground = false;
            beepToolStrip1.UseThemeFont = true;
            // 
            // beepNumericUpDown1
            // 
            beepNumericUpDown1.ActiveBackColor = Color.FromArgb(0, 120, 215);
            beepNumericUpDown1.AnimationDuration = 500;
            beepNumericUpDown1.AnimationType = Winform.Controls.DisplayAnimationType.None;
            beepNumericUpDown1.ApplyThemeToChilds = false;
            beepNumericUpDown1.BackColor = Color.White;
            beepNumericUpDown1.BadgeBackColor = Color.Red;
            beepNumericUpDown1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepNumericUpDown1.BadgeForeColor = Color.White;
            beepNumericUpDown1.BadgeShape = Winform.Controls.BadgeShape.Circle;
            beepNumericUpDown1.BadgeText = "";
            beepNumericUpDown1.BlockID = null;
            beepNumericUpDown1.BorderColor = Color.FromArgb(200, 200, 200);
            beepNumericUpDown1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepNumericUpDown1.BorderRadius = 3;
            beepNumericUpDown1.BorderStyle = BorderStyle.FixedSingle;
            beepNumericUpDown1.BorderThickness = 1;
            beepNumericUpDown1.BottomoffsetForDrawingRect = 0;
            beepNumericUpDown1.BoundProperty = null;
            beepNumericUpDown1.CanBeFocused = true;
            beepNumericUpDown1.CanBeHovered = false;
            beepNumericUpDown1.CanBePressed = true;
            beepNumericUpDown1.Category = Utilities.DbFieldCategory.String;
            beepNumericUpDown1.ComponentName = "beepNumericUpDown1";
            beepNumericUpDown1.DataContext = null;
            beepNumericUpDown1.DataSourceProperty = null;
            beepNumericUpDown1.DisabledBackColor = Color.Gray;
            beepNumericUpDown1.DisabledForeColor = Color.Empty;
            beepNumericUpDown1.DrawingRect = new Rectangle(1, 1, 98, 22);
            beepNumericUpDown1.Easing = Winform.Controls.EasingType.Linear;
            beepNumericUpDown1.FieldID = null;
            beepNumericUpDown1.FocusBackColor = Color.White;
            beepNumericUpDown1.FocusBorderColor = Color.Gray;
            beepNumericUpDown1.FocusForeColor = Color.Black;
            beepNumericUpDown1.FocusIndicatorColor = Color.Blue;
            beepNumericUpDown1.Form = null;
            beepNumericUpDown1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepNumericUpDown1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepNumericUpDown1.GradientStartColor = Color.White;
            beepNumericUpDown1.GuidID = "28f2280e-4790-42bf-ab40-34387dbd53fb";
            beepNumericUpDown1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepNumericUpDown1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepNumericUpDown1.HoveredBackcolor = Color.Wheat;
            beepNumericUpDown1.HoverForeColor = Color.Black;
            beepNumericUpDown1.Id = -1;
            beepNumericUpDown1.InactiveBackColor = Color.Gray;
            beepNumericUpDown1.InactiveBorderColor = Color.Gray;
            beepNumericUpDown1.InactiveForeColor = Color.Black;
            beepNumericUpDown1.IncrementValue = new decimal(new int[] { 1, 0, 0, 0 });
            beepNumericUpDown1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepNumericUpDown1.Info");
            beepNumericUpDown1.IsAcceptButton = false;
            beepNumericUpDown1.IsBorderAffectedByTheme = true;
            beepNumericUpDown1.IsCancelButton = false;
            beepNumericUpDown1.IsChild = false;
            beepNumericUpDown1.IsCustomeBorder = false;
            beepNumericUpDown1.IsDefault = false;
            beepNumericUpDown1.IsDeleted = false;
            beepNumericUpDown1.IsDirty = false;
            beepNumericUpDown1.IsEditable = false;
            beepNumericUpDown1.IsFocused = false;
            beepNumericUpDown1.IsFrameless = false;
            beepNumericUpDown1.IsHovered = false;
            beepNumericUpDown1.IsNew = false;
            beepNumericUpDown1.IsPressed = false;
            beepNumericUpDown1.IsReadOnly = false;
            beepNumericUpDown1.IsRequired = false;
            beepNumericUpDown1.IsRounded = true;
            beepNumericUpDown1.IsRoundedAffectedByTheme = true;
            beepNumericUpDown1.IsSelected = false;
            beepNumericUpDown1.IsShadowAffectedByTheme = true;
            beepNumericUpDown1.IsVisible = false;
            beepNumericUpDown1.Items = (List<object>)resources.GetObject("beepNumericUpDown1.Items");
            beepNumericUpDown1.LeftoffsetForDrawingRect = 0;
            beepNumericUpDown1.LinkedProperty = null;
            beepNumericUpDown1.Location = new Point(236, 514);
            beepNumericUpDown1.Margin = new Padding(0);
            beepNumericUpDown1.MaximumValue = new decimal(new int[] { 1000, 0, 0, 0 });
            beepNumericUpDown1.MinimumValue = new decimal(new int[] { 0, 0, 0, 0 });
            beepNumericUpDown1.Name = "beepNumericUpDown1";
            beepNumericUpDown1.OverrideFontSize = Winform.Controls.TypeStyleFontSize.None;
            beepNumericUpDown1.ParentBackColor = Color.Empty;
            beepNumericUpDown1.ParentControl = null;
            beepNumericUpDown1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepNumericUpDown1.PressedBorderColor = Color.Gray;
            beepNumericUpDown1.PressedForeColor = Color.Black;
            beepNumericUpDown1.RightoffsetForDrawingRect = 0;
            beepNumericUpDown1.SavedGuidID = null;
            beepNumericUpDown1.SavedID = null;
            beepNumericUpDown1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepNumericUpDown1.ShadowOffset = 0;
            beepNumericUpDown1.ShadowOpacity = 0.5F;
            beepNumericUpDown1.ShowAllBorders = true;
            beepNumericUpDown1.ShowBottomBorder = true;
            beepNumericUpDown1.ShowFocusIndicator = false;
            beepNumericUpDown1.ShowLeftBorder = true;
            beepNumericUpDown1.ShowRightBorder = true;
            beepNumericUpDown1.ShowShadow = false;
            beepNumericUpDown1.ShowTopBorder = true;
            beepNumericUpDown1.Size = new Size(100, 24);
            beepNumericUpDown1.SlideFrom = Winform.Controls.SlideDirection.Left;
            beepNumericUpDown1.StaticNotMoving = false;
            beepNumericUpDown1.TabIndex = 4;
            beepNumericUpDown1.TempBackColor = Color.Empty;
            beepNumericUpDown1.Text = "beepNumericUpDown1";
            beepNumericUpDown1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepNumericUpDown1.ToolTipText = "";
            beepNumericUpDown1.TopoffsetForDrawingRect = 0;
            beepNumericUpDown1.UseGradientBackground = false;
            beepNumericUpDown1.UseThemeFont = true;
            beepNumericUpDown1.Value = new decimal(new int[] { 0, 0, 0, 0 });
            // 
            // beepDatePicker1
            // 
            beepDatePicker1.ActiveBackColor = Color.FromArgb(0, 120, 215);
            beepDatePicker1.AnimationDuration = 500;
            beepDatePicker1.AnimationType = Winform.Controls.DisplayAnimationType.None;
            beepDatePicker1.ApplyThemeToChilds = false;
            beepDatePicker1.BackColor = Color.White;
            beepDatePicker1.BadgeBackColor = Color.Red;
            beepDatePicker1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepDatePicker1.BadgeForeColor = Color.White;
            beepDatePicker1.BadgeShape = Winform.Controls.BadgeShape.Circle;
            beepDatePicker1.BadgeText = "";
            beepDatePicker1.BlockID = null;
            beepDatePicker1.BorderColor = Color.FromArgb(200, 200, 200);
            beepDatePicker1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepDatePicker1.BorderRadius = 3;
            beepDatePicker1.BorderStyle = BorderStyle.FixedSingle;
            beepDatePicker1.BorderThickness = 1;
            beepDatePicker1.BottomoffsetForDrawingRect = 0;
            beepDatePicker1.BoundProperty = "SelectedDate";
            beepDatePicker1.CanBeFocused = true;
            beepDatePicker1.CanBeHovered = false;
            beepDatePicker1.CanBePressed = true;
            beepDatePicker1.Category = Utilities.DbFieldCategory.String;
            beepDatePicker1.ComponentName = "beepDatePicker1";
            beepDatePicker1.Culture = new System.Globalization.CultureInfo("en-AE");
            beepDatePicker1.DataContext = null;
            beepDatePicker1.DataSourceProperty = null;
            beepDatePicker1.DateFormat = "dd/MM/yyyy";
            beepDatePicker1.DisabledBackColor = Color.Gray;
            beepDatePicker1.DisabledForeColor = Color.Empty;
            beepDatePicker1.DrawingRect = new Rectangle(1, 1, 115, 20);
            beepDatePicker1.Easing = Winform.Controls.EasingType.Linear;
            beepDatePicker1.FieldID = null;
            beepDatePicker1.FocusBackColor = Color.White;
            beepDatePicker1.FocusBorderColor = Color.Gray;
            beepDatePicker1.FocusForeColor = Color.Black;
            beepDatePicker1.FocusIndicatorColor = Color.Blue;
            beepDatePicker1.Form = null;
            beepDatePicker1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepDatePicker1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepDatePicker1.GradientStartColor = Color.White;
            beepDatePicker1.GuidID = "8b541c51-51d6-4156-a2c3-0ecb39654cba";
            beepDatePicker1.HoverBackColor = Color.FromArgb(230, 230, 230);
            beepDatePicker1.HoverBorderColor = Color.FromArgb(0, 120, 215);
            beepDatePicker1.HoveredBackcolor = Color.Wheat;
            beepDatePicker1.HoverForeColor = Color.Black;
            beepDatePicker1.Id = -1;
            beepDatePicker1.InactiveBackColor = Color.Gray;
            beepDatePicker1.InactiveBorderColor = Color.Gray;
            beepDatePicker1.InactiveForeColor = Color.Black;
            beepDatePicker1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepDatePicker1.Info");
            beepDatePicker1.IsAcceptButton = false;
            beepDatePicker1.IsBorderAffectedByTheme = true;
            beepDatePicker1.IsCancelButton = false;
            beepDatePicker1.IsChild = false;
            beepDatePicker1.IsCustomeBorder = false;
            beepDatePicker1.IsDefault = false;
            beepDatePicker1.IsDeleted = false;
            beepDatePicker1.IsDirty = false;
            beepDatePicker1.IsEditable = false;
            beepDatePicker1.IsFocused = false;
            beepDatePicker1.IsFrameless = false;
            beepDatePicker1.IsHovered = false;
            beepDatePicker1.IsNew = false;
            beepDatePicker1.IsPressed = false;
            beepDatePicker1.IsReadOnly = false;
            beepDatePicker1.IsRequired = false;
            beepDatePicker1.IsRounded = true;
            beepDatePicker1.IsRoundedAffectedByTheme = true;
            beepDatePicker1.IsSelected = false;
            beepDatePicker1.IsShadowAffectedByTheme = true;
            beepDatePicker1.IsVisible = false;
            beepDatePicker1.Items = (List<object>)resources.GetObject("beepDatePicker1.Items");
            beepDatePicker1.LeftoffsetForDrawingRect = 0;
            beepDatePicker1.LinkedProperty = null;
            beepDatePicker1.Location = new Point(151, 73);
            beepDatePicker1.Name = "beepDatePicker1";
            beepDatePicker1.OverrideFontSize = Winform.Controls.TypeStyleFontSize.None;
            beepDatePicker1.ParentBackColor = Color.Empty;
            beepDatePicker1.ParentControl = null;
            beepDatePicker1.PressedBackColor = Color.FromArgb(0, 120, 215);
            beepDatePicker1.PressedBorderColor = Color.Gray;
            beepDatePicker1.PressedForeColor = Color.Black;
            beepDatePicker1.RightoffsetForDrawingRect = 0;
            beepDatePicker1.SavedGuidID = null;
            beepDatePicker1.SavedID = null;
            beepDatePicker1.SelectedDate = "22/03/2025";
            beepDatePicker1.SelectedDateTime = new DateTime(2025, 3, 22, 0, 0, 0, 0);
            beepDatePicker1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepDatePicker1.ShadowOffset = 0;
            beepDatePicker1.ShadowOpacity = 0.5F;
            beepDatePicker1.ShowAllBorders = true;
            beepDatePicker1.ShowBottomBorder = true;
            beepDatePicker1.ShowFocusIndicator = false;
            beepDatePicker1.ShowLeftBorder = true;
            beepDatePicker1.ShowRightBorder = true;
            beepDatePicker1.ShowShadow = false;
            beepDatePicker1.ShowTopBorder = true;
            beepDatePicker1.Size = new Size(117, 22);
            beepDatePicker1.SlideFrom = Winform.Controls.SlideDirection.Left;
            beepDatePicker1.StaticNotMoving = false;
            beepDatePicker1.TabIndex = 5;
            beepDatePicker1.TempBackColor = Color.Empty;
            beepDatePicker1.Text = "beepDatePicker1";
            beepDatePicker1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepDatePicker1.ToolTipText = "";
            beepDatePicker1.TopoffsetForDrawingRect = 0;
            beepDatePicker1.UseGradientBackground = false;
            beepDatePicker1.UseThemeFont = true;
            // 
            // monthCalendar1
            // 
            monthCalendar1.Location = new Point(118, 205);
            monthCalendar1.Name = "monthCalendar1";
            monthCalendar1.TabIndex = 6;
            // 
            // beepCard1
            // 
            beepCard1.ActiveBackColor = Color.Gray;
            beepCard1.AnimationDuration = 500;
            beepCard1.AnimationType = Winform.Controls.DisplayAnimationType.None;
            beepCard1.ApplyThemeToChilds = false;
            beepCard1.BackColor = Color.FromArgb(210, 180, 140);
            beepCard1.BadgeBackColor = Color.Red;
            beepCard1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepCard1.BadgeForeColor = Color.White;
            beepCard1.BadgeShape = Winform.Controls.BadgeShape.Circle;
            beepCard1.BadgeText = "";
            beepCard1.BlockID = null;
            beepCard1.BorderColor = Color.Black;
            beepCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCard1.BorderRadius = 3;
            beepCard1.BorderStyle = BorderStyle.FixedSingle;
            beepCard1.BorderThickness = 1;
            beepCard1.BottomoffsetForDrawingRect = 0;
            beepCard1.BoundProperty = "ParagraphText";
            beepCard1.ButtonText = "Action";
            beepCard1.CanBeFocused = true;
            beepCard1.CanBeHovered = false;
            beepCard1.CanBePressed = true;
            beepCard1.Category = Utilities.DbFieldCategory.String;
            beepCard1.ComponentName = "beepCard1";
            beepCard1.DataContext = null;
            beepCard1.DataSourceProperty = null;
            beepCard1.DisabledBackColor = Color.Gray;
            beepCard1.DisabledForeColor = Color.Empty;
            beepCard1.DrawingRect = new Rectangle(11, 11, 378, 278);
            beepCard1.Easing = Winform.Controls.EasingType.Linear;
            beepCard1.FieldID = null;
            beepCard1.FocusBackColor = Color.Gray;
            beepCard1.FocusBorderColor = Color.Gray;
            beepCard1.FocusForeColor = Color.Black;
            beepCard1.FocusIndicatorColor = Color.Blue;
            beepCard1.Form = null;
            beepCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCard1.GradientEndColor = Color.Gray;
            beepCard1.GradientStartColor = Color.Gray;
            beepCard1.GuidID = "182deead-7099-48e0-bbbd-e6d504a20912";
            beepCard1.HeaderAlignment = ContentAlignment.TopLeft;
            beepCard1.HeaderText = "Card Title";
            beepCard1.HoverBackColor = Color.Gray;
            beepCard1.HoverBorderColor = Color.Gray;
            beepCard1.HoveredBackcolor = Color.Wheat;
            beepCard1.HoverForeColor = Color.Black;
            beepCard1.Id = -1;
            beepCard1.ImageAlignment = ContentAlignment.TopRight;
            beepCard1.ImagePath = "H:\\dev\\iconPacks\\4205888-web-design-and-development\\4205888-web-design-and-development\\svg\\020-add.svg";
            beepCard1.InactiveBackColor = Color.Gray;
            beepCard1.InactiveBorderColor = Color.Gray;
            beepCard1.InactiveForeColor = Color.Black;
            beepCard1.Info = (Controls.Models.SimpleItem)resources.GetObject("beepCard1.Info");
            beepCard1.IsAcceptButton = false;
            beepCard1.IsBorderAffectedByTheme = true;
            beepCard1.IsCancelButton = false;
            beepCard1.IsChild = false;
            beepCard1.IsCustomeBorder = false;
            beepCard1.IsDefault = false;
            beepCard1.IsDeleted = false;
            beepCard1.IsDirty = false;
            beepCard1.IsEditable = false;
            beepCard1.IsFocused = false;
            beepCard1.IsFrameless = false;
            beepCard1.IsHovered = false;
            beepCard1.IsNew = false;
            beepCard1.IsPressed = false;
            beepCard1.IsReadOnly = false;
            beepCard1.IsRequired = false;
            beepCard1.IsRounded = true;
            beepCard1.IsRoundedAffectedByTheme = true;
            beepCard1.IsSelected = false;
            beepCard1.IsShadowAffectedByTheme = true;
            beepCard1.IsVisible = false;
            beepCard1.Items = (List<object>)resources.GetObject("beepCard1.Items");
            beepCard1.LeftoffsetForDrawingRect = 0;
            beepCard1.LinkedProperty = null;
            beepCard1.Location = new Point(429, 275);
            beepCard1.MaxImageSize = 64;
            beepCard1.Name = "beepCard1";
            beepCard1.OverrideFontSize = Winform.Controls.TypeStyleFontSize.None;
            beepCard1.Padding = new Padding(10);
            beepCard1.ParagraphText = "Card Description";
            beepCard1.ParentBackColor = Color.Empty;
            beepCard1.ParentControl = null;
            beepCard1.PressedBackColor = Color.Gray;
            beepCard1.PressedBorderColor = Color.Gray;
            beepCard1.PressedForeColor = Color.Black;
            beepCard1.RightoffsetForDrawingRect = 0;
            beepCard1.SavedGuidID = null;
            beepCard1.SavedID = null;
            beepCard1.ShadowColor = Color.Black;
            beepCard1.ShadowOffset = 0;
            beepCard1.ShadowOpacity = 0.5F;
            beepCard1.ShowAllBorders = true;
            beepCard1.ShowBottomBorder = true;
            beepCard1.ShowButton = true;
            beepCard1.ShowFocusIndicator = false;
            beepCard1.ShowLeftBorder = true;
            beepCard1.ShowRightBorder = true;
            beepCard1.ShowShadow = false;
            beepCard1.ShowTopBorder = true;
            beepCard1.Size = new Size(400, 300);
            beepCard1.SlideFrom = Winform.Controls.SlideDirection.Left;
            beepCard1.StaticNotMoving = false;
            beepCard1.TabIndex = 7;
            beepCard1.TempBackColor = Color.Empty;
            beepCard1.Text = "beepCard1";
            beepCard1.TextAlignment = ContentAlignment.TopLeft;
            beepCard1.Theme = Vis.Modules.EnumBeepThemes.RusticTheme;
            beepCard1.ToolTipText = "";
            beepCard1.TopoffsetForDrawingRect = 0;
            beepCard1.UseGradientBackground = false;
            beepCard1.UseThemeFont = true;
            beepCard1.ViewMode = Winform.Controls.CardViewMode.ImageLeft;
            // 
            // uc_FilterForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Controls.Add(beepCard1);
            Controls.Add(monthCalendar1);
            Controls.Add(beepDatePicker1);
            Controls.Add(beepNumericUpDown1);
            Controls.Add(beepToolStrip1);
            Controls.Add(beepSwitch1);
            Controls.Add(beepRadioButton1);
            Name = "uc_FilterForm";
            Size = new Size(1044, 738);
            ResumeLayout(false);
        }

        #endregion

        private Controls.BeepRadioButton beepRadioButton1;
        private Controls.BeepSwitch beepSwitch1;
        private Controls.BeepToolStrip beepToolStrip1;
        private Controls.BeepNumericUpDown beepNumericUpDown1;
        private Controls.BeepDatePicker beepDatePicker1;
        private MonthCalendar monthCalendar1;
        private Controls.BeepCard beepCard1;
    }
}
