namespace TheTechIdea.Beep.Winform.Default.Views
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            GraphicsPath graphicsPath1 = new GraphicsPath();
            GraphicsPath graphicsPath2 = new GraphicsPath();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            GraphicsPath graphicsPath3 = new GraphicsPath();
            GraphicsPath graphicsPath4 = new GraphicsPath();
            GraphicsPath graphicsPath5 = new GraphicsPath();
            GraphicsPath graphicsPath6 = new GraphicsPath();
            beepTextBox1 = new BeepTextBox();
            beepButton1 = new BeepButton();
            SuspendLayout();
            // 
            // beepTextBox1
            // 
            beepTextBox1.AcceptsReturn = false;
            beepTextBox1.AcceptsTab = false;
            beepTextBox1.AnimationDuration = 500;
            beepTextBox1.AnimationType = DisplayAnimationType.None;
            beepTextBox1.ApplyThemeOnImage = false;
            beepTextBox1.ApplyThemeToChilds = true;
            beepTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            beepTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            beepTextBox1.AutoDrawHitListComponents = true;
            beepTextBox1.BackColor = Color.FromArgb(0, 0, 0);
            beepTextBox1.BadgeBackColor = Color.FromArgb(14, 14, 14);
            beepTextBox1.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            beepTextBox1.BadgeForeColor = Color.FromArgb(0, 230, 153);
            beepTextBox1.BadgeShape = BadgeShape.Circle;
            beepTextBox1.BadgeText = "";
            beepTextBox1.BlockID = null;
            beepTextBox1.BorderColor = Color.FromArgb(0, 255, 0);
            beepTextBox1.BorderDashStyle = DashStyle.Solid;
            beepTextBox1.BorderPainter = BeepControlStyle.Terminal;
            graphicsPath1.FillMode = FillMode.Alternate;
            beepTextBox1.BorderPath = graphicsPath1;
            beepTextBox1.BorderRadius = 0;
            beepTextBox1.BorderRect = new Rectangle(0, 0, 180, 45);
            beepTextBox1.BorderStyle = BorderStyle.FixedSingle;
            beepTextBox1.BorderThickness = 2;
            beepTextBox1.BottomoffsetForDrawingRect = 0;
            beepTextBox1.BoundProperty = "Text";
            beepTextBox1.CanBeFocused = false;
            beepTextBox1.CanBeHovered = true;
            beepTextBox1.CanBePressed = true;
            beepTextBox1.CanBeSelected = true;
            beepTextBox1.Category = DbFieldCategory.String;
            beepTextBox1.ComponentName = "BaseControl";
            beepTextBox1.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath2.FillMode = FillMode.Alternate;
            beepTextBox1.ContentShape = graphicsPath2;
            beepTextBox1.ControlStyle = BeepControlStyle.Terminal;
            beepTextBox1.CustomMask = "";
            beepTextBox1.CustomPadding = new Padding(0);
            beepTextBox1.DataContext = null;
            beepTextBox1.DataSourceProperty = null;
            beepTextBox1.DateFormat = "MM/dd/yyyy";
            beepTextBox1.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DisabledBackColor = Color.FromArgb(12, 12, 12);
            beepTextBox1.DisabledBorderColor = Color.FromArgb(0, 255, 0);
            beepTextBox1.DisabledForeColor = Color.FromArgb(19, 27, 19);
            beepTextBox1.DrawingRect = new Rectangle(3, 3, 174, 39);
            beepTextBox1.Easing = EasingType.Linear;
            beepTextBox1.EnableHighQualityRendering = true;
            beepTextBox1.EnableMaterialStyle = false;
            beepTextBox1.EnableRippleEffect = false;
            beepTextBox1.EnableSplashEffect = false;
            beepTextBox1.ErrorColor = Color.Empty;
            beepTextBox1.ErrorText = "";
            beepTextBox1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepTextBox1.FieldID = null;
            beepTextBox1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepTextBox1.FloatingLabel = true;
            beepTextBox1.FocusBackColor = Color.LightYellow;
            beepTextBox1.FocusBorderColor = Color.FromArgb(0, 255, 0);
            beepTextBox1.FocusForeColor = Color.Black;
            beepTextBox1.FocusIndicatorColor = Color.RoyalBlue;
            beepTextBox1.ForeColor = Color.FromArgb(0, 230, 153);
            beepTextBox1.Form = null;
            beepTextBox1.GlassmorphismBlur = 10F;
            beepTextBox1.GlassmorphismOpacity = 0.1F;
            beepTextBox1.GlowIntensity = 0.2F;
            beepTextBox1.GradientAngle = 0F;
            beepTextBox1.GradientDirection = LinearGradientMode.Horizontal;
            beepTextBox1.GradientEndColor = Color.FromArgb(14, 14, 14);
            beepTextBox1.GradientStartColor = Color.FromArgb(10, 10, 10);
            beepTextBox1.GridMode = false;
            beepTextBox1.GuidID = "499eff1b-d830-4125-86e2-7c377d20ab1a";
            beepTextBox1.HasError = false;
            beepTextBox1.HelperText = "";
            beepTextBox1.HelperTextOn = false;
            beepTextBox1.HideSelection = true;
            beepTextBox1.HitAreaEventOn = false;
            beepTextBox1.HitTestControl = null;
            beepTextBox1.HoverBackColor = Color.FromArgb(10, 10, 10);
            beepTextBox1.HoverBorderColor = Color.Blue;
            beepTextBox1.HoveredBackcolor = Color.FromArgb(10, 10, 10);
            beepTextBox1.HoverForeColor = Color.FromArgb(0, 255, 153);
            beepTextBox1.IconKey = "";
            beepTextBox1.IconSize = 20;
            beepTextBox1.Id = -1;
            beepTextBox1.ImageAlign = ContentAlignment.MiddleLeft;
            beepTextBox1.ImageMargin = new Padding(2);
            beepTextBox1.ImagePath = "";
            beepTextBox1.ImageVisible = false;
            beepTextBox1.InactiveBorderColor = Color.Gray;
            graphicsPath3.FillMode = FillMode.Alternate;
            beepTextBox1.InnerShape = graphicsPath3;
            beepTextBox1.IsAcceptButton = false;
            beepTextBox1.IsBorderAffectedByTheme = true;
            beepTextBox1.IsCancelButton = false;
            beepTextBox1.IsChild = true;
            beepTextBox1.IsCustomeBorder = false;
            beepTextBox1.IsDefault = false;
            beepTextBox1.IsDeleted = false;
            beepTextBox1.IsDirty = false;
            beepTextBox1.IsEditable = true;
            beepTextBox1.IsFocused = false;
            beepTextBox1.IsFrameless = false;
            beepTextBox1.IsHovered = false;
            beepTextBox1.IsNew = false;
            beepTextBox1.IsPressed = false;
            beepTextBox1.IsReadOnly = false;
            beepTextBox1.IsRequired = false;
            beepTextBox1.IsRounded = true;
            beepTextBox1.IsRoundedAffectedByTheme = true;
            beepTextBox1.IsSelected = false;
            beepTextBox1.IsSelectedOptionOn = false;
            beepTextBox1.IsShadowAffectedByTheme = true;
            beepTextBox1.IsTransparentBackground = false;
            beepTextBox1.IsValid = true;
            beepTextBox1.IsVisible = true;
            beepTextBox1.Items = (List<object>)resources.GetObject("beepTextBox1.Items");
            beepTextBox1.LabelPosition = LabelPosition.Left;
            beepTextBox1.LabelText = "";
            beepTextBox1.LabelTextOn = false;
            beepTextBox1.LeadingIconPath = "";
            beepTextBox1.LeadingImagePath = "";
            beepTextBox1.LeftoffsetForDrawingRect = 0;
            beepTextBox1.LineNumberBackColor = Color.FromArgb(248, 248, 248);
            beepTextBox1.LineNumberFont = new Font("Consolas", 8F);
            beepTextBox1.LineNumberForeColor = Color.Gray;
            beepTextBox1.LinkedProperty = null;
            beepTextBox1.Location = new Point(208, 163);
            beepTextBox1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepTextBox1.MaxHitListDrawPerFrame = 0;
            beepTextBox1.MaxImageSize = new Size(20, 20);
            beepTextBox1.MinimumSize = new Size(0, 21);
            beepTextBox1.ModernGradientType = ModernGradientType.None;
            beepTextBox1.Modified = true;
            beepTextBox1.Multiline = false;
            beepTextBox1.Name = "beepTextBox1";
            beepTextBox1.OnlyCharacters = false;
            beepTextBox1.OnlyDigits = false;
            beepTextBox1.OuterShape = null;
            beepTextBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepTextBox1.PainterKind = BaseControlPainterKind.Classic;
            beepTextBox1.ParentBackColor = Color.FromArgb(0, 0, 0);
            beepTextBox1.ParentControl = null;
            beepTextBox1.PasswordChar = '\0';
            beepTextBox1.PlaceholderText = "";
            beepTextBox1.PlaceholderTextColor = Color.FromArgb(21, 32, 24);
            beepTextBox1.PressedBackColor = Color.Gray;
            beepTextBox1.PressedBorderColor = Color.DarkGray;
            beepTextBox1.PressedForeColor = Color.White;
            beepTextBox1.RadialCenter = (PointF)resources.GetObject("beepTextBox1.RadialCenter");
            beepTextBox1.ReadOnly = false;
            beepTextBox1.RightoffsetForDrawingRect = 0;
            beepTextBox1.SavedGuidID = null;
            beepTextBox1.SavedID = null;
            beepTextBox1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepTextBox1.ScrollBars = ScrollBars.Both;
            beepTextBox1.SearchCurrentMatchColor = Color.FromArgb(255, 165, 0);
            beepTextBox1.SearchMatchHighlightColor = Color.FromArgb(255, 255, 0);
            beepTextBox1.SelectedBackColor = Color.FromArgb(10, 10, 10);
            beepTextBox1.SelectedBorderColor = Color.Green;
            beepTextBox1.SelectedForeColor = Color.FromArgb(0, 230, 153);
            beepTextBox1.SelectedValue = null;
            beepTextBox1.SelectionBackColor = SystemColors.Highlight;
            beepTextBox1.SelectionLength = 0;
            beepTextBox1.SelectionStart = 0;
            beepTextBox1.ShadowColor = Color.FromArgb(0, 0, 0);
            beepTextBox1.ShadowOffset = 3;
            beepTextBox1.ShadowOpacity = 0.25F;
            beepTextBox1.ShowAllBorders = true;
            beepTextBox1.ShowBottomBorder = false;
            beepTextBox1.ShowFocusIndicator = false;
            beepTextBox1.ShowLabelAboveBorder = false;
            beepTextBox1.ShowLeftBorder = false;
            beepTextBox1.ShowRightBorder = false;
            beepTextBox1.ShowScrollbars = true;
            beepTextBox1.ShowShadow = false;
            beepTextBox1.ShowTopBorder = false;
            beepTextBox1.Size = new Size(180, 45);
            beepTextBox1.SlideFrom = SlideDirection.Left;
            beepTextBox1.StaticNotMoving = false;
            beepTextBox1.TabIndex = 0;
            beepTextBox1.Tag = this;
            beepTextBox1.TempBackColor = Color.LightGray;
            beepTextBox1.Text = "beepTextBox1";
            beepTextBox1.TextAlignment = HorizontalAlignment.Left;
            beepTextBox1.TextFont = new Font("Consolas", 8F);
            beepTextBox1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepTextBox1.Theme = "TerminalTheme";
            beepTextBox1.TimeFormat = "HH:mm:ss";
            beepTextBox1.TooltipFont = null;
            beepTextBox1.TooltipMaxSize = null;
            beepTextBox1.ToolTipText = null;
            beepTextBox1.TopoffsetForDrawingRect = 0;
            beepTextBox1.TrailingIconPath = "";
            beepTextBox1.TrailingImagePath = "";
            beepTextBox1.UseExternalBufferedGraphics = true;
            beepTextBox1.UseFormStylePaint = true;
            beepTextBox1.UseGlassmorphism = false;
            beepTextBox1.UseGradientBackground = false;
            beepTextBox1.UseRichToolTip = true;
            beepTextBox1.UseSystemPasswordChar = false;
            beepTextBox1.UseThemeFont = true;
            beepTextBox1.WordWrap = false;
            // 
            // beepButton1
            // 
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.ApplyThemeToChilds = true;
            beepButton1.AutoDrawHitListComponents = true;
            beepButton1.AutoSizeContent = false;
            beepButton1.BackColor = Color.FromArgb(18, 42, 24);
            beepButton1.BadgeBackColor = Color.Red;
            beepButton1.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            beepButton1.BadgeForeColor = Color.White;
            beepButton1.BadgeShape = BadgeShape.Circle;
            beepButton1.BadgeText = "";
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.FromArgb(0, 255, 0);
            beepButton1.BorderDashStyle = DashStyle.Solid;
            beepButton1.BorderPainter = BeepControlStyle.Terminal;
            graphicsPath4.FillMode = FillMode.Alternate;
            beepButton1.BorderPath = graphicsPath4;
            beepButton1.BorderRadius = 0;
            beepButton1.BorderRect = new Rectangle(0, 0, 124, 47);
         
            beepButton1.ButtonMinSize = new Size(32, 32);
            beepButton1.ButtonType = ButtonType.Normal;
            beepButton1.CanBeFocused = true;
            beepButton1.CanBeHovered = true;
            beepButton1.CanBePressed = true;
            beepButton1.CanBeSelected = true;
            beepButton1.Category = DbFieldCategory.Boolean;
            beepButton1.ComponentName = "BaseControl";
            beepButton1.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath5.FillMode = FillMode.Alternate;
            beepButton1.ContentShape = graphicsPath5;
            beepButton1.ControlStyle = BeepControlStyle.Terminal;
            beepButton1.CustomPadding = new Padding(0);
            beepButton1.DataContext = null;
            beepButton1.DataSourceProperty = null;
            beepButton1.DisabledBackColor = Color.FromArgb(12, 12, 12);
            beepButton1.DisabledBorderColor = Color.Gray;
            beepButton1.DisabledForeColor = Color.FromArgb(19, 27, 19);
            beepButton1.DrawingRect = new Rectangle(3, 3, 118, 41);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.EnableHighQualityRendering = true;
            beepButton1.EnableMaterialStyle = false;
            beepButton1.EnableRippleEffect = false;
            beepButton1.EnableSplashEffect = false;
            beepButton1.ErrorColor = Color.Empty;
            beepButton1.ErrorText = "";
            beepButton1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepButton1.FieldID = null;
            beepButton1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepButton1.FloatingLabel = true;
            beepButton1.FocusBackColor = Color.FromArgb(24, 56, 32);
            beepButton1.FocusBorderColor = Color.RoyalBlue;
            beepButton1.FocusForeColor = Color.FromArgb(0, 255, 153);
            beepButton1.FocusIndicatorColor = Color.RoyalBlue;
            beepButton1.ForeColor = Color.FromArgb(0, 230, 153);
            beepButton1.Form = null;
            beepButton1.GlassmorphismBlur = 10F;
            beepButton1.GlassmorphismOpacity = 0.1F;
            beepButton1.GradientAngle = 0F;
            beepButton1.GradientDirection = LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.Gray;
            beepButton1.GradientStartColor = Color.LightGray;
            beepButton1.GridMode = false;
            beepButton1.GuidID = "c8e01844-44ff-4027-9b5c-ba7bebd5bc36";
            beepButton1.HasError = false;
            beepButton1.HelperText = "";
            beepButton1.HelperTextOn = false;
            beepButton1.HideText = false;
            beepButton1.HitAreaEventOn = false;
            beepButton1.HitTestControl = null;
            beepButton1.HoverBackColor = Color.FromArgb(22, 52, 30);
            beepButton1.HoverBorderColor = Color.Blue;
            beepButton1.HoveredBackcolor = Color.FromArgb(22, 52, 30);
            beepButton1.HoverForeColor = Color.FromArgb(0, 255, 153);
            beepButton1.IconKey = "";
            beepButton1.IconSize = 20;
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton1.ImageClicked = null;
            beepButton1.ImageEmbededin = ImageEmbededin.Button;
            beepButton1.ImagePath = "";
            beepButton1.InactiveBorderColor = Color.Gray;
            graphicsPath6.FillMode = FillMode.Alternate;
            beepButton1.InnerShape = graphicsPath6;
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = false;
            beepButton1.IsColorFromTheme = true;
            beepButton1.IsCustomeBorder = false;
            beepButton1.IsDefault = false;
            beepButton1.IsDeleted = false;
            beepButton1.IsDirty = false;
            beepButton1.IsEditable = true;
            beepButton1.IsFocused = false;
            beepButton1.IsFrameless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsNew = false;
            beepButton1.IsPopupOpen = false;
            beepButton1.IsPressed = false;
            beepButton1.IsReadOnly = false;
            beepButton1.IsRequired = false;
            beepButton1.IsRounded = true;
            beepButton1.IsRoundedAffectedByTheme = true;
            beepButton1.IsSelected = false;
            beepButton1.IsSelectedOptionOn = false;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.IsTransparentBackground = false;
            beepButton1.IsValid = true;
            beepButton1.IsVisible = true;
            beepButton1.Items = (List<object>)resources.GetObject("beepButton1.Items");
            beepButton1.LabelPosition = LabelPosition.Left;
            beepButton1.LabelText = "";
            beepButton1.LabelTextOn = false;
            beepButton1.LeadingIconPath = "";
            beepButton1.LeadingImagePath = "";
            beepButton1.LeftoffsetForDrawingRect = 0;
            beepButton1.LinkedProperty = null;
            beepButton1.Location = new Point(208, 295);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepButton1.MaxHitListDrawPerFrame = 0;
            beepButton1.MaxImageSize = new Size(32, 32);
            beepButton1.ModernGradientType = ModernGradientType.None;
            beepButton1.Name = "beepButton1";
            beepButton1.OuterShape = null;
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.PainterKind = BaseControlPainterKind.Classic;
            beepButton1.ParentBackColor = Color.Empty;
            beepButton1.ParentControl = null;
            beepButton1.PopPosition = BeepPopupFormPosition.Bottom;
            beepButton1.PopupListForm = null;
            beepButton1.PopupMode = false;
            beepButton1.PressedBackColor = Color.FromArgb(14, 34, 20);
            beepButton1.PressedBorderColor = Color.DarkGray;
            beepButton1.PressedForeColor = Color.FromArgb(0, 255, 153);
            beepButton1.RadialCenter = (PointF)resources.GetObject("beepButton1.RadialCenter");
            beepButton1.RightoffsetForDrawingRect = 0;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepButton1.SelectedBackColor = Color.FromArgb(24, 56, 32);
            beepButton1.SelectedBorderColor = Color.Green;
            beepButton1.SelectedForeColor = Color.FromArgb(0, 255, 153);
            beepButton1.SelectedIndex = 0;
            beepButton1.SelectedItem = null;
            beepButton1.SelectedValue = null;
            beepButton1.ShadowColor = Color.Black;
            beepButton1.ShadowOffset = 3;
            beepButton1.ShadowOpacity = 0.25F;
            beepButton1.ShowAllBorders = false;
            beepButton1.ShowBottomBorder = false;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowLabelAboveBorder = false;
            beepButton1.ShowLeftBorder = false;
            beepButton1.ShowRightBorder = false;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = false;
            beepButton1.Size = new Size(124, 47);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.SplashColor = Color.Gray;
            beepButton1.StandardImages = (List<SimpleItem>)resources.GetObject("beepButton1.StandardImages");
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 1;
            beepButton1.Tag = this;
            beepButton1.TempBackColor = Color.LightGray;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepButton1.TextFont = new Font("Consolas", 8F, FontStyle.Bold);
            beepButton1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton1.Theme = "TerminalTheme";
            beepButton1.TooltipFont = null;
            beepButton1.TooltipMaxSize = null;
            beepButton1.ToolTipText = null;
            beepButton1.TopoffsetForDrawingRect = 0;
            beepButton1.TrailingIconPath = "";
            beepButton1.TrailingImagePath = "";
            beepButton1.UseExternalBufferedGraphics = true;
            beepButton1.UseFormStylePaint = true;
            beepButton1.UseGlassmorphism = false;
            beepButton1.UseGradientBackground = false;
            beepButton1.UseRichToolTip = true;
            beepButton1.UseScaledFont = false;
            beepButton1.UseThemeFont = true;
            // 
            // Form2
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(808, 401);
            Controls.Add(beepButton1);
            Controls.Add(beepTextBox1);
            FormStyle = FormStyle.Terminal;
            Location = new Point(0, 0);
            Name = "Form2";
            Text = "Form2";
            ResumeLayout(false);
        }

        #endregion

        private BeepTextBox beepTextBox1;
        private BeepButton beepButton1;
    }
}