using TheTechIdea.Beep.Vis.Modules;
using TheTechIdea.Beep.Winform.Controls;
using TheTechIdea.Beep.Winform.Controls.AppBars;
using TheTechIdea.Beep.Winform.Controls.DisplayContainers;
using TheTechIdea.Beep.Winform.Controls.Managers;
using TheTechIdea.Beep.Winform.Controls.Models;

namespace TheTechIdea.Beep.Winform.Default.Views
{
    partial class MainFrm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainFrm));
            beepMenuAppBar1 = new TheTechIdea.Beep.Winform.Controls.MenuBar.BeepMenuAppBar();
            beepAppTree1 = new TheTechIdea.Beep.Winform.Controls.ITrees.BeepTreeView.BeepAppTree();
            beepDisplayContainer1 = new BeepDisplayContainer();
            SuspendLayout();
            // 
            // beepFormuiManager1
            // 
            beepFormuiManager1.BeepMenuBar = beepMenuAppBar1;
            beepFormuiManager1.ShowBorder = false;
            beepFormuiManager1.Theme = "DefaultTheme";
            beepFormuiManager1.Title = "Beep";
            // 
            // beepMenuAppBar1
            // 
            beepMenuAppBar1.ActiveMenuButton = null;
            beepMenuAppBar1.AnimationDuration = 500;
            beepMenuAppBar1.AnimationType = DisplayAnimationType.None;
            beepMenuAppBar1.ApplyThemeToChilds = true;
            beepMenuAppBar1.AutoDrawHitListComponents = true;
            beepMenuAppBar1.BackColor = Color.White;
            beepMenuAppBar1.BadgeBackColor = Color.FromArgb(33, 150, 243);
            beepMenuAppBar1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepMenuAppBar1.BadgeForeColor = Color.White;
            beepMenuAppBar1.BadgeShape = BadgeShape.Circle;
            beepMenuAppBar1.BadgeText = "";
            beepMenuAppBar1.beepServices = null;
            beepMenuAppBar1.BlockID = null;
            beepMenuAppBar1.BorderColor = Color.LightGray;
            beepMenuAppBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepMenuAppBar1.BorderPainter = Winform.Controls.Common.BeepControlStyle.None;
            beepMenuAppBar1.BorderRadius = 8;
            beepMenuAppBar1.BorderStyle = BorderStyle.FixedSingle;
            beepMenuAppBar1.BorderThickness = 1;
            beepMenuAppBar1.BottomoffsetForDrawingRect = 0;
            beepMenuAppBar1.BoundProperty = "SelectedMenuItem";
            beepMenuAppBar1.CanBeFocused = false;
            beepMenuAppBar1.CanBeHovered = true;
            beepMenuAppBar1.CanBePressed = true;
            beepMenuAppBar1.CanBeSelected = false;
            beepMenuAppBar1.Category = Utilities.DbFieldCategory.String;
            beepMenuAppBar1.ComponentName = "BaseControl";
            beepMenuAppBar1.DataContext = null;
            beepMenuAppBar1.DataSourceProperty = null;
            beepMenuAppBar1.DisabledBackColor = Color.FromArgb(200, 200, 200);
            beepMenuAppBar1.DisabledBorderColor = Color.LightGray;
            beepMenuAppBar1.DisabledForeColor = Color.Gray;
            //beepMenuAppBar1.DisableDpiAndScaling = false;
            beepMenuAppBar1.Dock = DockStyle.Top;
            beepMenuAppBar1.DrawingRect = new Rectangle(1, 1, 1434, 67);
            beepMenuAppBar1.Easing = EasingType.Linear;
            beepMenuAppBar1.EnableHighQualityRendering = true;
            beepMenuAppBar1.EnableMaterialStyle = false;
            beepMenuAppBar1.EnableRippleEffect = false;
            beepMenuAppBar1.EnableSplashEffect = false;
            beepMenuAppBar1.ErrorColor = Color.FromArgb(176, 0, 32);
            beepMenuAppBar1.ErrorText = "";
            beepMenuAppBar1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepMenuAppBar1.FieldID = null;
            beepMenuAppBar1.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            beepMenuAppBar1.FloatingLabel = true;
            beepMenuAppBar1.FocusBackColor = Color.LightYellow;
            beepMenuAppBar1.FocusBorderColor = Color.RoyalBlue;
            beepMenuAppBar1.FocusForeColor = Color.Black;
            beepMenuAppBar1.FocusIndicatorColor = Color.RoyalBlue;
            beepMenuAppBar1.ForeColor = Color.Black;
            beepMenuAppBar1.Form = null;
            beepMenuAppBar1.GlassmorphismBlur = 10F;
            beepMenuAppBar1.GlassmorphismOpacity = 0.1F;
            beepMenuAppBar1.GradientAngle = 0F;
            beepMenuAppBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepMenuAppBar1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepMenuAppBar1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepMenuAppBar1.GridMode = false;
            beepMenuAppBar1.GuidID = "4e186fd4-9fb9-4194-b393-b5fdc2cdf3a0";
            beepMenuAppBar1.HasError = false;
            beepMenuAppBar1.HelperText = "";
            beepMenuAppBar1.HitAreaEventOn = false;
            beepMenuAppBar1.HitTestControl = null;
            beepMenuAppBar1.HoverBackColor = Color.LightBlue;
            beepMenuAppBar1.HoverBorderColor = Color.Blue;
            beepMenuAppBar1.HoveredBackcolor = Color.LightBlue;
            beepMenuAppBar1.HoverForeColor = Color.Black;
            beepMenuAppBar1.IconSize = 20;
            beepMenuAppBar1.Id = -1;
            beepMenuAppBar1.ImageSize = 18;
            beepMenuAppBar1.InactiveBorderColor = Color.Gray;
            beepMenuAppBar1.InnerShape = null;
            beepMenuAppBar1.IsAcceptButton = false;
            beepMenuAppBar1.IsBorderAffectedByTheme = false;
            beepMenuAppBar1.IsCancelButton = false;
            beepMenuAppBar1.IsChild = false;
            beepMenuAppBar1.IsCustomeBorder = false;
            beepMenuAppBar1.IsDefault = false;
            beepMenuAppBar1.IsDeleted = false;
            beepMenuAppBar1.IsDirty = false;
            beepMenuAppBar1.IsEditable = true;
            beepMenuAppBar1.IsFocused = false;
            beepMenuAppBar1.IsFrameless = true;
            beepMenuAppBar1.IsHovered = false;
            beepMenuAppBar1.IsNew = false;
            beepMenuAppBar1.IsPressed = false;
            beepMenuAppBar1.IsReadOnly = false;
            beepMenuAppBar1.IsRequired = false;
            beepMenuAppBar1.IsRounded = false;
            beepMenuAppBar1.IsRoundedAffectedByTheme = false;
            beepMenuAppBar1.IsSelected = false;
            beepMenuAppBar1.IsSelectedOptionOn = false;
            beepMenuAppBar1.IsShadowAffectedByTheme = false;
            beepMenuAppBar1.IsValid = true;
            beepMenuAppBar1.IsVisible = true;
            beepMenuAppBar1.Items = (List<object>)resources.GetObject("beepMenuAppBar1.Items");
            beepMenuAppBar1.LabelText = "";
            beepMenuAppBar1.LeadingIconPath = "";
            beepMenuAppBar1.LeadingImagePath = "";
            beepMenuAppBar1.LeftoffsetForDrawingRect = 0;
            beepMenuAppBar1.LinkedProperty = null;
            beepMenuAppBar1.Location = new Point(10, 54);
            beepMenuAppBar1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepMenuAppBar1.MaterialCustomPadding = new Padding(0);
            beepMenuAppBar1.MaterialFillColor = Color.FromArgb(245, 245, 245);
            beepMenuAppBar1.MaterialIconPadding = 8;
            beepMenuAppBar1.MaterialIconSize = 20;
            beepMenuAppBar1.MaterialOutlineColor = Color.FromArgb(140, 140, 140);
            beepMenuAppBar1.MaterialPrimaryColor = Color.FromArgb(25, 118, 210);
            beepMenuAppBar1.MaterialVariant = MaterialTextFieldVariant.Standard;
            beepMenuAppBar1.MaxHitListDrawPerFrame = 0;
      
            beepMenuAppBar1.MenuItemHeight = 20;
            beepMenuAppBar1.MenuItemWidth = 60;
            beepMenuAppBar1.MenuStyle = Winform.Controls.Forms.ModernForm.FormStyle.Modern;
            beepMenuAppBar1.ModernGradientType = ModernGradientType.None;
            beepMenuAppBar1.Name = "beepMenuAppBar1";
            beepMenuAppBar1.OverrideFontSize = TypeStyleFontSize.None;
            beepMenuAppBar1.Padding = new Padding(1);
            beepMenuAppBar1.PainterKind = BaseControlPainterKind.Classic;
            beepMenuAppBar1.ParentBackColor = Color.Empty;
            beepMenuAppBar1.ParentControl = null;
            beepMenuAppBar1.PressedBackColor = Color.Gray;
            beepMenuAppBar1.PressedBorderColor = Color.DarkGray;
            beepMenuAppBar1.PressedForeColor = Color.White;
            beepMenuAppBar1.RadialCenter = (PointF)resources.GetObject("beepMenuAppBar1.RadialCenter");
            beepMenuAppBar1.RightoffsetForDrawingRect = 0;
            beepMenuAppBar1.SavedGuidID = null;
            beepMenuAppBar1.SavedID = null;
            beepMenuAppBar1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepMenuAppBar1.SelectedBackColor = Color.LightGreen;
            beepMenuAppBar1.SelectedBorderColor = Color.Green;
            beepMenuAppBar1.SelectedForeColor = Color.Black;
            beepMenuAppBar1.SelectedIndex = -1;
            beepMenuAppBar1.SelectedValue = null;
            beepMenuAppBar1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepMenuAppBar1.ShadowOffset = 3;
            beepMenuAppBar1.ShadowOpacity = 0.25F;
            beepMenuAppBar1.ShowAllBorders = false;
            beepMenuAppBar1.ShowBottomBorder = false;
            beepMenuAppBar1.ShowFocusIndicator = false;
            beepMenuAppBar1.ShowLeftBorder = false;
            beepMenuAppBar1.ShowRightBorder = false;
            beepMenuAppBar1.ShowShadow = false;
            beepMenuAppBar1.ShowTopBorder = false;
            beepMenuAppBar1.Size = new Size(1436, 69);
            beepMenuAppBar1.SlideFrom = SlideDirection.Left;
            beepMenuAppBar1.StaticNotMoving = false;
            beepMenuAppBar1.TabIndex = 0;
            beepMenuAppBar1.Tag = this;
            beepMenuAppBar1.TempBackColor = Color.LightGray;
            beepMenuAppBar1.Text = "beepMenuAppBar1";
            beepMenuAppBar1.TextFont = new Font("Arial", 12F);
            beepMenuAppBar1.Theme = "DefaultTheme";
            beepMenuAppBar1.ToolTipText = null;
            beepMenuAppBar1.TopoffsetForDrawingRect = 0;
            beepMenuAppBar1.TrailingIconPath = "";
            beepMenuAppBar1.TrailingImagePath = "";
            beepMenuAppBar1.UseExternalBufferedGraphics = false;
            beepMenuAppBar1.UseGlassmorphism = false;
            beepMenuAppBar1.UseGradientBackground = false;
            beepMenuAppBar1.UseRichToolTip = true;
            beepMenuAppBar1.UseThemeFont = true;
            // 
            // beepAppTree1
            // 
            beepAppTree1.AllowMultiSelect = false;
            beepAppTree1.AnimationDuration = 500;
            beepAppTree1.AnimationType = DisplayAnimationType.None;
            beepAppTree1.ApplyThemeToChilds = true;
            beepAppTree1.args = null;
            beepAppTree1.AutoDrawHitListComponents = false;
            beepAppTree1.BackColor = Color.FromArgb(255, 255, 255);
            beepAppTree1.BadgeBackColor = Color.FromArgb(33, 150, 243);
            beepAppTree1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepAppTree1.BadgeForeColor = Color.White;
            beepAppTree1.BadgeShape = BadgeShape.Circle;
            beepAppTree1.BadgeText = "";
            beepAppTree1.BeepService = null;
            beepAppTree1.BlockID = null;
            beepAppTree1.BorderColor = Color.FromArgb(200, 200, 200);
            beepAppTree1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepAppTree1.BorderPainter = Winform.Controls.Common.BeepControlStyle.None;
            beepAppTree1.BorderRadius = 8;
            beepAppTree1.BorderStyle = BorderStyle.FixedSingle;
            beepAppTree1.BorderThickness = 1;
            beepAppTree1.BottomoffsetForDrawingRect = 0;
            beepAppTree1.BoundProperty = null;
            beepAppTree1.Branches = (List<IBranch>)resources.GetObject("beepAppTree1.Branches");
            beepAppTree1.CanBeFocused = false;
            beepAppTree1.CanBeHovered = true;
            beepAppTree1.CanBePressed = true;
            beepAppTree1.CanBeSelected = true;
            beepAppTree1.Category = Utilities.DbFieldCategory.String;
            beepAppTree1.CategoryIcon = "Category.svg";
            beepAppTree1.ComponentName = "BaseControl";
            beepAppTree1.CurrentBranch = null;
            beepAppTree1.CurrentMenutems = null;
            beepAppTree1.DataContext = null;
            beepAppTree1.DataSourceProperty = null;
            beepAppTree1.DisabledBackColor = Color.FromArgb(200, 200, 200);
            beepAppTree1.DisabledBorderColor = Color.LightGray;
            beepAppTree1.DisabledForeColor = Color.Gray;
            //beepAppTree1.DisableDpiAndScaling = false;
            beepAppTree1.DMEEditor = null;
            beepAppTree1.Dock = DockStyle.Left;
            beepAppTree1.DrawingRect = new Rectangle(0, 0, 400, 931);
            beepAppTree1.DropHandler = null;
            beepAppTree1.Easing = EasingType.Linear;
            beepAppTree1.EnableHighQualityRendering = true;
            beepAppTree1.EnableMaterialStyle = false;
            beepAppTree1.EnableRippleEffect = false;
            beepAppTree1.EnableSplashEffect = false;
            beepAppTree1.ErrorColor = Color.FromArgb(176, 0, 32);
            beepAppTree1.ErrorText = "";
            beepAppTree1.ExtensionsHelpers = null;
            beepAppTree1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepAppTree1.FieldID = null;
            beepAppTree1.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            beepAppTree1.Filterstring = null;
            beepAppTree1.FloatingLabel = true;
            beepAppTree1.FocusBackColor = Color.LightYellow;
            beepAppTree1.FocusBorderColor = Color.RoyalBlue;
            beepAppTree1.FocusForeColor = Color.Black;
            beepAppTree1.FocusIndicatorColor = Color.RoyalBlue;
            beepAppTree1.ForeColor = Color.Black;
            beepAppTree1.Form = null;
            beepAppTree1.GlassmorphismBlur = 10F;
            beepAppTree1.GlassmorphismOpacity = 0.1F;
            beepAppTree1.GradientAngle = 0F;
            beepAppTree1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepAppTree1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepAppTree1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepAppTree1.GridMode = false;
            beepAppTree1.GuidID = "87325237-adfe-4acf-b9d3-093ea074d6ff";
            beepAppTree1.HasError = false;
            beepAppTree1.HelperText = "";
            beepAppTree1.HitAreaEventOn = false;
            beepAppTree1.HitTestControl = null;
            beepAppTree1.HoverBackColor = Color.LightBlue;
            beepAppTree1.HoverBorderColor = Color.Blue;
            beepAppTree1.HoveredBackcolor = Color.LightBlue;
            beepAppTree1.HoverForeColor = Color.Black;
            beepAppTree1.IconSize = 20;
            beepAppTree1.Id = -1;
            beepAppTree1.InactiveBorderColor = Color.Gray;
            beepAppTree1.InnerShape = null;
            beepAppTree1.IsAcceptButton = false;
            beepAppTree1.IsBorderAffectedByTheme = true;
            beepAppTree1.IsCancelButton = false;
            beepAppTree1.IsCheckBoxon = false;
            beepAppTree1.IsChild = true;
            beepAppTree1.IsCustomeBorder = false;
            beepAppTree1.IsDefault = false;
            beepAppTree1.IsDeleted = false;
            beepAppTree1.IsDirty = false;
            beepAppTree1.IsEditable = true;
            beepAppTree1.IsFocused = false;
            beepAppTree1.IsFrameless = true;
            beepAppTree1.IsHovered = false;
            beepAppTree1.IsNew = false;
            beepAppTree1.IsPressed = false;
            beepAppTree1.IsReadOnly = false;
            beepAppTree1.IsRequired = false;
            beepAppTree1.IsRounded = false;
            beepAppTree1.IsRoundedAffectedByTheme = true;
            beepAppTree1.IsSelected = false;
            beepAppTree1.IsSelectedOptionOn = false;
            beepAppTree1.IsShadowAffectedByTheme = true;
            beepAppTree1.IsValid = true;
            beepAppTree1.IsVisible = true;
            beepAppTree1.Items = (List<object>)resources.GetObject("beepAppTree1.Items");
            beepAppTree1.LabelText = "";
            beepAppTree1.LeadingIconPath = "";
            beepAppTree1.LeadingImagePath = "";
            beepAppTree1.LeftoffsetForDrawingRect = 0;
            beepAppTree1.LinkedProperty = null;
            beepAppTree1.Location = new Point(10, 123);
            beepAppTree1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepAppTree1.MaterialCustomPadding = new Padding(0);
            beepAppTree1.MaterialFillColor = Color.FromArgb(245, 245, 245);
            beepAppTree1.MaterialIconPadding = 8;
            beepAppTree1.MaterialIconSize = 20;
            beepAppTree1.MaterialOutlineColor = Color.FromArgb(140, 140, 140);
            beepAppTree1.MaterialPrimaryColor = Color.FromArgb(25, 118, 210);
            beepAppTree1.MaxHitListDrawPerFrame = 0;
            beepAppTree1.MenuStyle = Winform.Controls.Forms.ModernForm.FormStyle.Modern;
            beepAppTree1.ModernGradientType = ModernGradientType.None;
            beepAppTree1.Name = "beepAppTree1";
            beepAppTree1.ObjectType = "Beep";
            beepAppTree1.OverrideFontSize = TypeStyleFontSize.None;
            beepAppTree1.Padding = new Padding(1);
            beepAppTree1.PainterKind = BaseControlPainterKind.None;
            beepAppTree1.ParentBackColor = Color.FromArgb(255, 255, 255);
            beepAppTree1.ParentControl = null;
            beepAppTree1.PressedBackColor = Color.Gray;
            beepAppTree1.PressedBorderColor = Color.DarkGray;
            beepAppTree1.PressedForeColor = Color.White;
            beepAppTree1.RadialCenter = (PointF)resources.GetObject("beepAppTree1.RadialCenter");
            beepAppTree1.RightoffsetForDrawingRect = 0;
            beepAppTree1.SavedGuidID = null;
            beepAppTree1.SavedID = null;
            beepAppTree1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepAppTree1.SelectedBackColor = Color.LightGreen;
            beepAppTree1.SelectedBorderColor = Color.Green;
            beepAppTree1.SelectedBranch = null;
            beepAppTree1.SelectedBranchID = 0;
            beepAppTree1.SelectedBranchs = (List<int>)resources.GetObject("beepAppTree1.SelectedBranchs");
            beepAppTree1.SelectedForeColor = Color.Black;
            beepAppTree1.SelectedValue = null;
            beepAppTree1.SelectIcon = "Select.svg";
            beepAppTree1.SeqID = 3;
            beepAppTree1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepAppTree1.ShadowOffset = 3;
            beepAppTree1.ShadowOpacity = 0.25F;
            beepAppTree1.ShowAllBorders = false;
            beepAppTree1.ShowBottomBorder = false;
            beepAppTree1.ShowCheckBox = true;
            beepAppTree1.ShowFocusIndicator = false;
            beepAppTree1.ShowHorizontalScrollBar = true;
            beepAppTree1.ShowLeftBorder = false;
            beepAppTree1.ShowRightBorder = false;
            beepAppTree1.ShowShadow = false;
            beepAppTree1.ShowTopBorder = false;
            beepAppTree1.ShowVerticalScrollBar = true;
            beepAppTree1.Size = new Size(400, 931);
            beepAppTree1.SlideFrom = SlideDirection.Left;
            beepAppTree1.StaticNotMoving = false;
            beepAppTree1.TabIndex = 10;
            beepAppTree1.Tag = this;
            beepAppTree1.TempBackColor = Color.LightGray;
            beepAppTree1.Text = "beepAppTree1";
            beepAppTree1.TextAlignment = TextAlignment.Left;
            beepAppTree1.TextFont = new Font("Arial", 10F);
            beepAppTree1.Theme = "DefaultTheme";
            beepAppTree1.ToolTipText = null;
            beepAppTree1.TopoffsetForDrawingRect = 0;
            beepAppTree1.TrailingIconPath = "";
            beepAppTree1.TrailingImagePath = "";
            beepAppTree1.Treebranchhandler = null;
            beepAppTree1.TreeStyle = Winform.Controls.Trees.Models.TreeStyle.Standard;
            beepAppTree1.TreeType = "Beep";
            beepAppTree1.UseExternalBufferedGraphics = false;
            beepAppTree1.UseGlassmorphism = false;
            beepAppTree1.UseGradientBackground = false;
            beepAppTree1.UseRichToolTip = true;
            beepAppTree1.UseScaledFont = false;
            beepAppTree1.UseThemeFont = false;
            beepAppTree1.VirtualizationBufferRows = 100;
            beepAppTree1.VirtualizeLayout = true;
            beepAppTree1.VisManager = null;
            // 
            // beepDisplayContainer1
            // 
            beepDisplayContainer1.AnimationDuration = 500;
            beepDisplayContainer1.AnimationType = DisplayAnimationType.None;
            beepDisplayContainer1.ApplyThemeToChilds = true;
            beepDisplayContainer1.AutoDrawHitListComponents = false;
            beepDisplayContainer1.BackColor = Color.FromArgb(255, 255, 255);
            beepDisplayContainer1.BadgeBackColor = Color.Red;
            beepDisplayContainer1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepDisplayContainer1.BadgeForeColor = Color.White;
            beepDisplayContainer1.BadgeShape = BadgeShape.Circle;
            beepDisplayContainer1.BadgeText = "";
            beepDisplayContainer1.BlockID = null;
            beepDisplayContainer1.BorderColor = Color.BurlyWood;
            beepDisplayContainer1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepDisplayContainer1.BorderPainter = Winform.Controls.Common.BeepControlStyle.None;
            beepDisplayContainer1.BorderRadius = 8;
            beepDisplayContainer1.BorderStyle = BorderStyle.None;
            beepDisplayContainer1.BorderThickness = 0;
            beepDisplayContainer1.BottomoffsetForDrawingRect = 0;
            beepDisplayContainer1.BoundProperty = null;
            beepDisplayContainer1.CanBeFocused = false;
            beepDisplayContainer1.CanBeHovered = true;
            beepDisplayContainer1.CanBePressed = true;
            beepDisplayContainer1.CanBeSelected = true;
            beepDisplayContainer1.Category = Utilities.DbFieldCategory.String;
            beepDisplayContainer1.ComponentName = "BeepDisplayContainer";
            beepDisplayContainer1.ContainerType = ContainerTypeEnum.TabbedPanel;
           
            beepDisplayContainer1.DataContext = null;
            beepDisplayContainer1.DataSourceProperty = null;
            beepDisplayContainer1.DisabledBackColor = Color.LightGray;
            beepDisplayContainer1.DisabledBorderColor = Color.Gray;
            beepDisplayContainer1.DisabledForeColor = Color.DarkGray;
            //beepDisplayContainer1.DisableDpiAndScaling = false;
            beepDisplayContainer1.Dock = DockStyle.Fill;
            beepDisplayContainer1.DrawingRect = new Rectangle(0, 0, 1036, 931);
            beepDisplayContainer1.Easing = EasingType.Linear;
            beepDisplayContainer1.EnableHighQualityRendering = true;
            beepDisplayContainer1.EnableMaterialStyle = false;
            beepDisplayContainer1.EnableRippleEffect = false;
            beepDisplayContainer1.EnableSplashEffect = false;
            beepDisplayContainer1.ErrorColor = Color.FromArgb(176, 0, 32);
            beepDisplayContainer1.ErrorText = "";
            beepDisplayContainer1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepDisplayContainer1.FieldID = null;
            beepDisplayContainer1.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            beepDisplayContainer1.FloatingLabel = true;
            beepDisplayContainer1.FocusBackColor = Color.LightYellow;
            beepDisplayContainer1.FocusBorderColor = Color.RoyalBlue;
            beepDisplayContainer1.FocusForeColor = Color.Blue;
            beepDisplayContainer1.FocusIndicatorColor = Color.RoyalBlue;
            beepDisplayContainer1.ForeColor = Color.BlanchedAlmond;
            beepDisplayContainer1.Form = null;
            beepDisplayContainer1.GlassmorphismBlur = 10F;
            beepDisplayContainer1.GlassmorphismOpacity = 0.1F;
            beepDisplayContainer1.GradientAngle = 0F;
            beepDisplayContainer1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepDisplayContainer1.GradientEndColor = Color.Gray;
            beepDisplayContainer1.GradientStartColor = Color.LightGray;
            beepDisplayContainer1.GridMode = false;
            beepDisplayContainer1.GuidID = "f5f07e88-411b-4af7-81b6-a62b568b1c6b";
            beepDisplayContainer1.HasError = false;
            beepDisplayContainer1.HelperText = "";
            beepDisplayContainer1.HitAreaEventOn = false;
            beepDisplayContainer1.HitTestControl = null;
            beepDisplayContainer1.HoverBackColor = Color.LightBlue;
            beepDisplayContainer1.HoverBorderColor = Color.Blue;
            beepDisplayContainer1.HoveredBackcolor = Color.LightBlue;
            beepDisplayContainer1.HoverForeColor = Color.Blue;
            beepDisplayContainer1.IconSize = 20;
            beepDisplayContainer1.Id = -1;
            beepDisplayContainer1.InactiveBorderColor = Color.Gray;
            beepDisplayContainer1.InnerShape = null;
            beepDisplayContainer1.IsAcceptButton = false;
            beepDisplayContainer1.IsBorderAffectedByTheme = true;
            beepDisplayContainer1.IsCancelButton = false;
            beepDisplayContainer1.IsChild = true;
            beepDisplayContainer1.IsCustomeBorder = false;
            beepDisplayContainer1.IsDefault = false;
            beepDisplayContainer1.IsDeleted = false;
            beepDisplayContainer1.IsDirty = false;
            beepDisplayContainer1.IsEditable = true;
            beepDisplayContainer1.IsFocused = false;
            beepDisplayContainer1.IsFrameless = true;
            beepDisplayContainer1.IsHovered = false;
            beepDisplayContainer1.IsNew = false;
            beepDisplayContainer1.IsPressed = false;
            beepDisplayContainer1.IsReadOnly = false;
            beepDisplayContainer1.IsRequired = false;
            beepDisplayContainer1.IsRounded = false;
            beepDisplayContainer1.IsRoundedAffectedByTheme = true;
            beepDisplayContainer1.IsSelected = false;
            beepDisplayContainer1.IsSelectedOptionOn = false;
            beepDisplayContainer1.IsShadowAffectedByTheme = true;
            beepDisplayContainer1.IsValid = true;
            beepDisplayContainer1.IsVisible = true;
            beepDisplayContainer1.Items = (List<object>)resources.GetObject("beepDisplayContainer1.Items");
            beepDisplayContainer1.LabelText = "";
            beepDisplayContainer1.LeadingIconPath = "";
            beepDisplayContainer1.LeadingImagePath = "";
            beepDisplayContainer1.LeftoffsetForDrawingRect = 0;
            beepDisplayContainer1.LinkedProperty = null;
            beepDisplayContainer1.Location = new Point(410, 123);
            beepDisplayContainer1.MaterialBorderVariant = MaterialTextFieldVariant.Standard;
            beepDisplayContainer1.MaterialCustomPadding = new Padding(0);
            beepDisplayContainer1.MaterialFillColor = Color.FromArgb(245, 245, 245);
            beepDisplayContainer1.MaterialIconPadding = 8;
            beepDisplayContainer1.MaterialIconSize = 20;
            beepDisplayContainer1.MaterialOutlineColor = Color.FromArgb(140, 140, 140);
            beepDisplayContainer1.MaterialPreserveContentArea = true;
            beepDisplayContainer1.MaterialPrimaryColor = Color.FromArgb(25, 118, 210);
            beepDisplayContainer1.MaterialVariant = MaterialTextFieldVariant.Standard;
            beepDisplayContainer1.MaxHitListDrawPerFrame = 0;
            beepDisplayContainer1.MenuStyle = Winform.Controls.Forms.ModernForm.FormStyle.Modern;
            beepDisplayContainer1.ModernGradientType = ModernGradientType.None;
            beepDisplayContainer1.Name = "beepDisplayContainer1";
            beepDisplayContainer1.OverrideFontSize = TypeStyleFontSize.None;
            beepDisplayContainer1.Padding = new Padding(2);
            beepDisplayContainer1.PainterKind = BaseControlPainterKind.None;
            beepDisplayContainer1.ParentBackColor = Color.FromArgb(255, 255, 255);
            beepDisplayContainer1.ParentControl = null;
            beepDisplayContainer1.PressedBackColor = Color.Gray;
            beepDisplayContainer1.PressedBorderColor = Color.DarkGray;
            beepDisplayContainer1.PressedForeColor = Color.White;
            beepDisplayContainer1.RadialCenter = (PointF)resources.GetObject("beepDisplayContainer1.RadialCenter");
            beepDisplayContainer1.RightoffsetForDrawingRect = 0;
            beepDisplayContainer1.SavedGuidID = null;
            beepDisplayContainer1.SavedID = null;
            beepDisplayContainer1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepDisplayContainer1.SelectedBackColor = Color.LightGreen;
            beepDisplayContainer1.SelectedBorderColor = Color.Green;
            beepDisplayContainer1.SelectedForeColor = Color.Blue;
            beepDisplayContainer1.SelectedValue = null;
            beepDisplayContainer1.ShadowColor = Color.BlueViolet;
            beepDisplayContainer1.ShadowOffset = 3;
            beepDisplayContainer1.ShadowOpacity = 0.25F;
            beepDisplayContainer1.ShowAllBorders = false;
            beepDisplayContainer1.ShowBottomBorder = false;
            beepDisplayContainer1.ShowFocusIndicator = false;
            beepDisplayContainer1.ShowLeftBorder = false;
            beepDisplayContainer1.ShowRightBorder = false;
            beepDisplayContainer1.ShowShadow = false;
            beepDisplayContainer1.ShowTopBorder = false;
            beepDisplayContainer1.Size = new Size(1036, 931);
            beepDisplayContainer1.SlideFrom = SlideDirection.Left;
            beepDisplayContainer1.StaticNotMoving = false;
            beepDisplayContainer1.TabIndex = 11;
            beepDisplayContainer1.Tag = this;
            beepDisplayContainer1.TempBackColor = Color.LightGray;
            beepDisplayContainer1.Text = "beepDisplayContainer1";
            beepDisplayContainer1.Theme = null;
            beepDisplayContainer1.ToolTipText = null;
            beepDisplayContainer1.TopoffsetForDrawingRect = 0;
            beepDisplayContainer1.TrailingIconPath = "";
            beepDisplayContainer1.TrailingImagePath = "";
            beepDisplayContainer1.UseExternalBufferedGraphics = true;
            beepDisplayContainer1.UseGlassmorphism = false;
            beepDisplayContainer1.UseGradientBackground = false;
            beepDisplayContainer1.UseRichToolTip = true;
            beepDisplayContainer1.UseThemeFont = true;
            // 
            // MainFrm
            // 
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Backdrop = BackdropType.Mica;
            ClientSize = new Size(1456, 1064);
            Controls.Add(beepDisplayContainer1);
            Controls.Add(beepAppTree1);
            Controls.Add(beepMenuAppBar1);
            Name = "MainFrm";
            Padding = new Padding(10);
            ShowStyleButton = true;
            ShowThemeButton = true;
            Text = "Beep";
            Theme = "DefaultTheme";
            ResumeLayout(false);
        }

        #endregion

        private Controls.MenuBar.BeepMenuAppBar beepMenuAppBar1;
        private Controls.ITrees.BeepTreeView.BeepAppTree beepAppTree1;
        private BeepDisplayContainer beepDisplayContainer1;
    }
}