using TheTechIdea.Beep.Vis.Modules;
using TheTechIdea.Beep.Winform.Controls.Models;

namespace TheTechIdea.Beep.Winform.Default.Views
{
    partial class MainFrm_SideBar
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainFrm_SideBar));
            beepAppBar1 = new TheTechIdea.Beep.Winform.Controls.BeepAppBar();
            beepSideMenu1 = new TheTechIdea.Beep.Winform.Controls.BeepSideMenu();
            beepDisplayContainer1 = new TheTechIdea.Beep.Winform.Controls.BeepDisplayContainer();
            beepMenuBar1 = new TheTechIdea.Beep.Winform.Controls.BeepMenuBar();
            SuspendLayout();
            // 
            // beepuiManager1
            // 
            beepuiManager1.BeepAppBar = beepAppBar1;
            beepuiManager1.BeepiForm = this;
            beepuiManager1.BeepMenuBar = beepMenuBar1;
            beepuiManager1.BeepSideMenu = beepSideMenu1;
            beepuiManager1.DisplayContainer = beepDisplayContainer1;
            beepuiManager1.IsRounded = false;
            beepuiManager1.ShowBorder = false;
            // 
            // beepAppBar1
            // 
            beepAppBar1.AnimationDuration = 500;
            beepAppBar1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepAppBar1.ApplyThemeButtons = true;
            beepAppBar1.ApplyThemeToChilds = false;
            beepAppBar1.AutoCompleteMode = AutoCompleteMode.None;
            beepAppBar1.AutoCompleteSource = AutoCompleteSource.None;
            beepAppBar1.BackColor = Color.FromArgb(33, 150, 243);
            beepAppBar1.BadgeBackColor = Color.Red;
            beepAppBar1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepAppBar1.BadgeForeColor = Color.White;
            beepAppBar1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepAppBar1.BadgeText = "";
            beepAppBar1.BlockID = null;
            beepAppBar1.BorderColor = Color.Black;
            beepAppBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepAppBar1.BorderRadius = 8;
            beepAppBar1.BorderStyle = BorderStyle.FixedSingle;
            beepAppBar1.BorderThickness = 1;
            beepAppBar1.BottomoffsetForDrawingRect = 0;
            beepAppBar1.BoundProperty = null;
            beepAppBar1.CanBeFocused = true;
            beepAppBar1.CanBeHovered = false;
            beepAppBar1.CanBePressed = true;
            beepAppBar1.Category = Utilities.DbFieldCategory.String;
            beepAppBar1.ComponentName = "BeepControl";
          //  beepAppBar1.CurrentMenutems = (System.ComponentModel.BindingList<SimpleItem>)resources.GetObject("beepAppBar1.CurrentMenutems");
            beepAppBar1.DataSourceProperty = null;
            beepAppBar1.DisabledBackColor = Color.White;
            beepAppBar1.DisabledBorderColor = Color.Empty;
            beepAppBar1.DisabledForeColor = Color.Black;
            beepAppBar1.Dock = DockStyle.Top;
          
            beepAppBar1.Easing = Vis.Modules.EasingType.Linear;
            beepAppBar1.EnableRippleEffect = true;
            beepAppBar1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepAppBar1.FieldID = null;
            beepAppBar1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepAppBar1.FloatingLabel = true;
            beepAppBar1.FocusBackColor = Color.White;
            beepAppBar1.FocusBorderColor = Color.RoyalBlue;
            beepAppBar1.FocusForeColor = Color.Black;
            beepAppBar1.FocusIndicatorColor = Color.Blue;
            beepAppBar1.Font = new Font("Arial", 18F);
            beepAppBar1.ForeColor = Color.White;
            beepAppBar1.Form = null;
            beepAppBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            beepAppBar1.GradientEndColor = Color.FromArgb(25, 118, 210);
            beepAppBar1.GradientStartColor = Color.FromArgb(33, 150, 243);
            beepAppBar1.GuidID = "2cfa0ec4-5de6-4771-8f7a-a0f5be8aa1b6";
            beepAppBar1.HelperText = "";
            
            beepAppBar1.HoverBackColor = Color.White;
            beepAppBar1.HoverBorderColor = Color.Gray;
            beepAppBar1.HoveredBackcolor = Color.Wheat;
            beepAppBar1.HoverForeColor = Color.Black;
            beepAppBar1.Id = -1;
            beepAppBar1.InactiveBorderColor = Color.Gray;
        //    beepAppBar1.Info = (SimpleItem)resources.GetObject("beepAppBar1.Info");
            beepAppBar1.IsAcceptButton = false;
            beepAppBar1.IsBorderAffectedByTheme = false;
            beepAppBar1.IsCancelButton = false;
            beepAppBar1.IsChild = false;
            beepAppBar1.IsCustomeBorder = false;
            beepAppBar1.IsDefault = false;
            beepAppBar1.IsDeleted = false;
            beepAppBar1.IsDirty = false;
            beepAppBar1.IsEditable = false;
            beepAppBar1.IsFocused = false;
            beepAppBar1.IsFrameless = false;
            beepAppBar1.IsHovered = false;
            beepAppBar1.IsNew = false;
            beepAppBar1.IsPressed = false;
            beepAppBar1.IsReadOnly = false;
            beepAppBar1.IsRequired = false;
            beepAppBar1.IsRounded = false;
            beepAppBar1.IsRoundedAffectedByTheme = false;
            beepAppBar1.IsSelected = false;
            beepAppBar1.IsSelectedOptionOn = false;
            beepAppBar1.IsShadowAffectedByTheme = false;
            beepAppBar1.IsVisible = false;
            beepAppBar1.Items = (List<object>)resources.GetObject("beepAppBar1.Items");
            beepAppBar1.LabelText = "";
            beepAppBar1.LeftoffsetForDrawingRect = 0;
            beepAppBar1.LinkedProperty = null;
            beepAppBar1.Location = new Point(108, 1);
            beepAppBar1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepAppBar1.Name = "beepAppBar1";
            beepAppBar1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepAppBar1.ParentBackColor = Color.Empty;
            beepAppBar1.ParentControl = null;
            beepAppBar1.PopupListForm = null;
            beepAppBar1.PressedBackColor = Color.White;
            beepAppBar1.PressedBorderColor = Color.Gray;
            beepAppBar1.PressedForeColor = Color.Gray;
            beepAppBar1.RightoffsetForDrawingRect = 0;
            beepAppBar1.SavedGuidID = null;
            beepAppBar1.SavedID = null;
            beepAppBar1.SearchBoxPlaceholder = " Search...";
            beepAppBar1.SearchBoxText = "";
            beepAppBar1.SelectedBackColor = Color.White;
            beepAppBar1.SelectedBorderColor = Color.Empty;
            beepAppBar1.SelectedForeColor = Color.Black;
            beepAppBar1.SelectedValue = null;
            beepAppBar1.ShadowColor = Color.Black;
            beepAppBar1.ShadowOffset = 0;
            beepAppBar1.ShadowOpacity = 0.5F;
            beepAppBar1.ShowAllBorders = false;
            beepAppBar1.ShowBottomBorder = false;
            beepAppBar1.ShowCloseIcon = true;
            beepAppBar1.ShowFocusIndicator = false;
            beepAppBar1.ShowLeftBorder = false;
            beepAppBar1.ShowLogo = false;
            beepAppBar1.ShowMaximizeIcon = true;
            beepAppBar1.ShowMinimizeIcon = true;
            beepAppBar1.ShowNotificationIcon = true;
            beepAppBar1.ShowProfileIcon = true;
            beepAppBar1.ShowRightBorder = false;
            beepAppBar1.ShowSearchBox = true;
            beepAppBar1.ShowShadow = false;
            beepAppBar1.ShowThemeIcon = true;
            beepAppBar1.ShowTitle = false;
            beepAppBar1.ShowTopBorder = false;
            beepAppBar1.Size = new Size(691, 40);
            beepAppBar1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepAppBar1.StaticNotMoving = false;
            beepAppBar1.TabIndex = 0;
            beepAppBar1.Tag = this;
            beepAppBar1.TempBackColor = Color.Empty;
            beepAppBar1.Text = "beepAppBar1";
            beepAppBar1.TextFont = new Font("Arial", 18F);
            beepAppBar1.Theme = "DefaultTheme";
            beepAppBar1.ToolTipText = "";
            beepAppBar1.TopoffsetForDrawingRect = 0;
            beepAppBar1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepAppBar1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepAppBar1.UICustomElevation = 0;
            beepAppBar1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepAppBar1.UIDisabled = false;
            beepAppBar1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepAppBar1.UIFullWidth = false;
            beepAppBar1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepAppBar1.UISize = Vis.Modules.ReactUISize.Medium;
            beepAppBar1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepAppBar1.UseGradientBackground = false;
            beepAppBar1.UseThemeFont = true;
            // 
            // beepSideMenu1
            // 
            beepSideMenu1.AnimationDuration = 500;
            beepSideMenu1.AnimationStep = 2;
            beepSideMenu1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepSideMenu1.ApplyThemeOnImages = false;
            beepSideMenu1.ApplyThemeToChilds = false;
            beepSideMenu1.BackColor = Color.White;
            beepSideMenu1.BadgeBackColor = Color.Red;
            beepSideMenu1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepSideMenu1.BadgeForeColor = Color.White;
            beepSideMenu1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepSideMenu1.BadgeText = "";
            beepSideMenu1.BeepAppBar = null;
            beepSideMenu1.BeepForm = this;
            beepSideMenu1.BlockID = null;
            beepSideMenu1.BorderColor = Color.Black;
            beepSideMenu1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSideMenu1.BorderRadius = 8;
            beepSideMenu1.BorderStyle = BorderStyle.FixedSingle;
            beepSideMenu1.BorderThickness = 1;
            beepSideMenu1.BottomoffsetForDrawingRect = 0;
            beepSideMenu1.BoundProperty = null;
            beepSideMenu1.ButtonSize = new Size(190, 40);
            beepSideMenu1.CanBeFocused = true;
            beepSideMenu1.CanBeHovered = false;
            beepSideMenu1.CanBePressed = true;
            beepSideMenu1.Category = Utilities.DbFieldCategory.String;
            beepSideMenu1.CollapsedWidth = 64;
            beepSideMenu1.ComponentName = "BeepControl";
            beepSideMenu1.DataSourceProperty = null;
            beepSideMenu1.DescriptionSize = new Size(100, 20);
            beepSideMenu1.DisabledBackColor = Color.White;
            beepSideMenu1.DisabledBorderColor = Color.Empty;
            beepSideMenu1.DisabledForeColor = Color.Black;
            beepSideMenu1.Dock = DockStyle.Left;
            beepSideMenu1.DrawingRect = new Rectangle(5, 5, 97, 438);
            beepSideMenu1.Easing = Vis.Modules.EasingType.Linear;
            beepSideMenu1.EnableRippleEffect = true;
            beepSideMenu1.ExpandedWidth = 200;
            beepSideMenu1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepSideMenu1.FieldID = null;
            beepSideMenu1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepSideMenu1.FloatingLabel = true;
            beepSideMenu1.FocusBackColor = Color.White;
            beepSideMenu1.FocusBorderColor = Color.RoyalBlue;
            beepSideMenu1.FocusForeColor = Color.Black;
            beepSideMenu1.FocusIndicatorColor = Color.Blue;
            beepSideMenu1.Font = new Font("Segoe UI", 9F);
            beepSideMenu1.ForeColor = Color.White;
            beepSideMenu1.Form = null;
            beepSideMenu1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSideMenu1.GradientEndColor = Color.Gray;
            beepSideMenu1.GradientStartColor = Color.Gray;
            beepSideMenu1.GuidID = "766debb9-c948-435c-a4e3-7b9b335ac926";
            beepSideMenu1.HelperText = "";
            beepSideMenu1.HilightPanelSize = 5;
            beepSideMenu1.HitAreaEventOn = false;
            beepSideMenu1.HitTestControl = null;
            beepSideMenu1.HoverBackColor = Color.White;
            beepSideMenu1.HoverBorderColor = Color.Gray;
            beepSideMenu1.HoveredBackcolor = Color.Wheat;
            beepSideMenu1.HoverForeColor = Color.Black;
            beepSideMenu1.Id = -1;
            beepSideMenu1.InactiveBorderColor = Color.Gray;
       //     beepSideMenu1.Info = (SimpleItem)resources.GetObject("beepSideMenu1.Info");
            beepSideMenu1.IsAcceptButton = false;
            beepSideMenu1.IsBorderAffectedByTheme = false;
            beepSideMenu1.IsCancelButton = false;
            beepSideMenu1.IsChild = false;
            beepSideMenu1.IsCustomeBorder = false;
            beepSideMenu1.IsDefault = false;
            beepSideMenu1.IsDeleted = false;
            beepSideMenu1.IsDirty = false;
            beepSideMenu1.IsEditable = false;
            beepSideMenu1.IsFocused = false;
            beepSideMenu1.IsFrameless = true;
            beepSideMenu1.IsHovered = false;
            beepSideMenu1.IsNew = false;
            beepSideMenu1.IsPressed = false;
            beepSideMenu1.IsReadOnly = false;
            beepSideMenu1.IsRequired = false;
            beepSideMenu1.IsRounded = false;
            beepSideMenu1.IsRoundedAffectedByTheme = false;
            beepSideMenu1.IsSelected = false;
            beepSideMenu1.IsSelectedOptionOn = false;
            beepSideMenu1.IsShadowAffectedByTheme = false;
            beepSideMenu1.IsVisible = false;
            beepSideMenu1.LabelText = "";
            beepSideMenu1.LeftoffsetForDrawingRect = 0;
            beepSideMenu1.LinkedProperty = null;
            beepSideMenu1.ListButtonFont = new Font("Arial", 10F);
            beepSideMenu1.ListImageSize = new Size(20, 20);
            beepSideMenu1.Location = new Point(1, 1);
            beepSideMenu1.LogoImage = "";
            beepSideMenu1.LogoSize = new Size(100, 100);
            beepSideMenu1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepSideMenu1.Name = "beepSideMenu1";
            beepSideMenu1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepSideMenu1.Padding = new Padding(5);
            beepSideMenu1.ParentBackColor = Color.Empty;
            beepSideMenu1.ParentControl = null;
            beepSideMenu1.PressedBackColor = Color.White;
            beepSideMenu1.PressedBorderColor = Color.Gray;
            beepSideMenu1.PressedForeColor = Color.Gray;
            beepSideMenu1.RightoffsetForDrawingRect = 0;
            beepSideMenu1.SavedGuidID = null;
            beepSideMenu1.SavedID = null;
            beepSideMenu1.SelectedBackColor = Color.White;
            beepSideMenu1.SelectedBorderColor = Color.Empty;
            beepSideMenu1.SelectedForeColor = Color.Black;
            beepSideMenu1.SelectedValue = null;
            beepSideMenu1.ShadowColor = Color.Black;
            beepSideMenu1.ShadowOffset = 0;
            beepSideMenu1.ShadowOpacity = 0.5F;
            beepSideMenu1.ShowAllBorders = false;
            beepSideMenu1.ShowBottomBorder = false;
            beepSideMenu1.ShowFocusIndicator = false;
            beepSideMenu1.ShowLeftBorder = false;
            beepSideMenu1.ShowRightBorder = false;
            beepSideMenu1.ShowShadow = false;
            beepSideMenu1.ShowTopBorder = false;
            beepSideMenu1.Size = new Size(107, 448);
            beepSideMenu1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepSideMenu1.StaticNotMoving = false;
            beepSideMenu1.TabIndex = 1;
            beepSideMenu1.Tag = this;
            beepSideMenu1.TempBackColor = Color.Empty;
            beepSideMenu1.Text = "beepSideMenu1";
            beepSideMenu1.Theme = "DefaultTheme";
            beepSideMenu1.Title = "Beep Form";
            beepSideMenu1.TitleSize = new Size(87, 74);
            beepSideMenu1.ToolTipText = "";
            beepSideMenu1.TopoffsetForDrawingRect = 0;
            beepSideMenu1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepSideMenu1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepSideMenu1.UICustomElevation = 0;
            beepSideMenu1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepSideMenu1.UIDisabled = false;
            beepSideMenu1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepSideMenu1.UIFullWidth = false;
            beepSideMenu1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepSideMenu1.UISize = Vis.Modules.ReactUISize.Medium;
            beepSideMenu1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepSideMenu1.UseGradientBackground = false;
            beepSideMenu1.UseThemeFont = true;
            // 
            // beepDisplayContainer1
            // 
            beepDisplayContainer1.AnimationDuration = 500;
            beepDisplayContainer1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepDisplayContainer1.ApplyThemeToChilds = false;
            beepDisplayContainer1.BackColor = Color.White;
            beepDisplayContainer1.BadgeBackColor = Color.Red;
            beepDisplayContainer1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepDisplayContainer1.BadgeForeColor = Color.White;
            beepDisplayContainer1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepDisplayContainer1.BadgeText = "";
            beepDisplayContainer1.BlockID = null;
            beepDisplayContainer1.BorderColor = Color.Black;
            beepDisplayContainer1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepDisplayContainer1.BorderRadius = 8;
            beepDisplayContainer1.BorderStyle = BorderStyle.FixedSingle;
            beepDisplayContainer1.BorderThickness = 1;
            beepDisplayContainer1.BottomoffsetForDrawingRect = 0;
            beepDisplayContainer1.BoundProperty = null;
            beepDisplayContainer1.CanBeFocused = true;
            beepDisplayContainer1.CanBeHovered = false;
            beepDisplayContainer1.CanBePressed = true;
            beepDisplayContainer1.Category = Utilities.DbFieldCategory.String;
            beepDisplayContainer1.ComponentName = "BeepDisplayContainer";
            beepDisplayContainer1.ContainerType = Vis.Modules.ContainerTypeEnum.TabbedPanel;
            beepDisplayContainer1.DataSourceProperty = null;
            beepDisplayContainer1.DisabledBackColor = Color.White;
            beepDisplayContainer1.DisabledBorderColor = Color.Empty;
            beepDisplayContainer1.DisabledForeColor = Color.Black;
            beepDisplayContainer1.Dock = DockStyle.Fill;
            beepDisplayContainer1.DrawingRect = new Rectangle(2, 2, 687, 369);
            beepDisplayContainer1.Easing = Vis.Modules.EasingType.Linear;
            beepDisplayContainer1.EnableRippleEffect = true;
            beepDisplayContainer1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepDisplayContainer1.FieldID = null;
            beepDisplayContainer1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepDisplayContainer1.FloatingLabel = true;
            beepDisplayContainer1.FocusBackColor = Color.White;
            beepDisplayContainer1.FocusBorderColor = Color.RoyalBlue;
            beepDisplayContainer1.FocusForeColor = Color.Black;
            beepDisplayContainer1.FocusIndicatorColor = Color.Blue;
            beepDisplayContainer1.Form = null;
            beepDisplayContainer1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepDisplayContainer1.GradientEndColor = Color.Gray;
            beepDisplayContainer1.GradientStartColor = Color.Gray;
            beepDisplayContainer1.GuidID = "19bcd2cb-ed98-4f05-af5c-c537a78e2c46";
            beepDisplayContainer1.HelperText = "";
            beepDisplayContainer1.HitAreaEventOn = false;
            beepDisplayContainer1.HitTestControl = null;
            beepDisplayContainer1.HoverBackColor = Color.White;
            beepDisplayContainer1.HoverBorderColor = Color.Gray;
            beepDisplayContainer1.HoveredBackcolor = Color.Wheat;
            beepDisplayContainer1.HoverForeColor = Color.Black;
            beepDisplayContainer1.Id = -1;
            beepDisplayContainer1.InactiveBorderColor = Color.Gray;
          //  beepDisplayContainer1.Info = (SimpleItem)resources.GetObject("beepDisplayContainer1.Info");
            beepDisplayContainer1.IsAcceptButton = false;
            beepDisplayContainer1.IsBorderAffectedByTheme = true;
            beepDisplayContainer1.IsCancelButton = false;
            beepDisplayContainer1.IsChild = false;
            beepDisplayContainer1.IsCustomeBorder = false;
            beepDisplayContainer1.IsDefault = false;
            beepDisplayContainer1.IsDeleted = false;
            beepDisplayContainer1.IsDirty = false;
            beepDisplayContainer1.IsEditable = false;
            beepDisplayContainer1.IsFocused = false;
            beepDisplayContainer1.IsFrameless = false;
            beepDisplayContainer1.IsHovered = false;
            beepDisplayContainer1.IsNew = false;
            beepDisplayContainer1.IsPressed = false;
            beepDisplayContainer1.IsReadOnly = false;
            beepDisplayContainer1.IsRequired = false;
            beepDisplayContainer1.IsRounded = false;
            beepDisplayContainer1.IsRoundedAffectedByTheme = true;
            beepDisplayContainer1.IsSelected = false;
            beepDisplayContainer1.IsSelectedOptionOn = false;
            beepDisplayContainer1.IsShadowAffectedByTheme = true;
            beepDisplayContainer1.IsVisible = false;
            beepDisplayContainer1.Items = (List<object>)resources.GetObject("beepDisplayContainer1.Items");
            beepDisplayContainer1.LabelText = "";
            beepDisplayContainer1.LeftoffsetForDrawingRect = 0;
            beepDisplayContainer1.LinkedProperty = null;
            beepDisplayContainer1.Location = new Point(108, 76);
            beepDisplayContainer1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepDisplayContainer1.Name = "beepDisplayContainer1";
            beepDisplayContainer1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepDisplayContainer1.Padding = new Padding(2);
            beepDisplayContainer1.ParentBackColor = Color.Empty;
            beepDisplayContainer1.ParentControl = null;
            beepDisplayContainer1.PressedBackColor = Color.White;
            beepDisplayContainer1.PressedBorderColor = Color.Gray;
            beepDisplayContainer1.PressedForeColor = Color.Gray;
            beepDisplayContainer1.RightoffsetForDrawingRect = 0;
            beepDisplayContainer1.SavedGuidID = null;
            beepDisplayContainer1.SavedID = null;
            beepDisplayContainer1.SelectedBackColor = Color.White;
            beepDisplayContainer1.SelectedBorderColor = Color.Empty;
            beepDisplayContainer1.SelectedForeColor = Color.Black;
            beepDisplayContainer1.SelectedValue = null;
            beepDisplayContainer1.ShadowColor = Color.Black;
            beepDisplayContainer1.ShadowOffset = 0;
            beepDisplayContainer1.ShadowOpacity = 0.5F;
            beepDisplayContainer1.ShowAllBorders = false;
            beepDisplayContainer1.ShowBottomBorder = false;
            beepDisplayContainer1.ShowFocusIndicator = false;
            beepDisplayContainer1.ShowLeftBorder = false;
            beepDisplayContainer1.ShowRightBorder = false;
            beepDisplayContainer1.ShowShadow = false;
            beepDisplayContainer1.ShowTopBorder = false;
            beepDisplayContainer1.Size = new Size(691, 373);
            beepDisplayContainer1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepDisplayContainer1.StaticNotMoving = false;
            beepDisplayContainer1.TabIndex = 2;
            beepDisplayContainer1.Tag = this;
            beepDisplayContainer1.TempBackColor = Color.Empty;
            beepDisplayContainer1.Text = "beepDisplayContainer1";
            beepDisplayContainer1.Theme = "DefaultTheme";
            beepDisplayContainer1.ToolTipText = "";
            beepDisplayContainer1.TopoffsetForDrawingRect = 0;
            beepDisplayContainer1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepDisplayContainer1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepDisplayContainer1.UICustomElevation = 0;
            beepDisplayContainer1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepDisplayContainer1.UIDisabled = false;
            beepDisplayContainer1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepDisplayContainer1.UIFullWidth = false;
            beepDisplayContainer1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepDisplayContainer1.UISize = Vis.Modules.ReactUISize.Medium;
            beepDisplayContainer1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepDisplayContainer1.UseGradientBackground = false;
            beepDisplayContainer1.UseThemeFont = true;
            // 
            // beepMenuBar1
            // 
            beepMenuBar1.ActiveMenuButton = null;
            beepMenuBar1.AnimationDuration = 500;
            beepMenuBar1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepMenuBar1.ApplyThemeToChilds = true;
            beepMenuBar1.BackColor = Color.White;
            beepMenuBar1.BadgeBackColor = Color.Red;
            beepMenuBar1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepMenuBar1.BadgeForeColor = Color.White;
            beepMenuBar1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepMenuBar1.BadgeText = "";
            beepMenuBar1.BlockID = null;
            beepMenuBar1.BorderColor = Color.LightGray;
            beepMenuBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepMenuBar1.BorderRadius = 8;
            beepMenuBar1.BorderStyle = BorderStyle.FixedSingle;
            beepMenuBar1.BorderThickness = 1;
            beepMenuBar1.BottomoffsetForDrawingRect = 0;
            beepMenuBar1.BoundProperty = "SelectedMenuItem";
            beepMenuBar1.CanBeFocused = true;
            beepMenuBar1.CanBeHovered = false;
            beepMenuBar1.CanBePressed = true;
            beepMenuBar1.Category = Utilities.DbFieldCategory.String;
            beepMenuBar1.ComponentName = "BeepControl";
            beepMenuBar1.DataSourceProperty = null;
            beepMenuBar1.DisabledBackColor = Color.White;
            beepMenuBar1.DisabledBorderColor = Color.Empty;
            beepMenuBar1.DisabledForeColor = Color.Black;
            beepMenuBar1.Dock = DockStyle.Top;
            beepMenuBar1.DrawingRect = new Rectangle(0, 0, 691, 35);
            beepMenuBar1.Easing = Vis.Modules.EasingType.Linear;
            beepMenuBar1.EnableRippleEffect = true;
            beepMenuBar1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepMenuBar1.FieldID = null;
            beepMenuBar1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepMenuBar1.FloatingLabel = true;
            beepMenuBar1.FocusBackColor = Color.White;
            beepMenuBar1.FocusBorderColor = Color.RoyalBlue;
            beepMenuBar1.FocusForeColor = Color.Black;
            beepMenuBar1.FocusIndicatorColor = Color.Blue;
            beepMenuBar1.Font = new Font("Arial", 14F, FontStyle.Bold);
            beepMenuBar1.ForeColor = Color.Black;
            beepMenuBar1.Form = null;
            beepMenuBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepMenuBar1.GradientEndColor = Color.Gray;
            beepMenuBar1.GradientStartColor = Color.Gray;
            beepMenuBar1.GuidID = "b94263d6-2cab-4ca6-8f38-3986eaed9b40";
            beepMenuBar1.HelperText = "";
            beepMenuBar1.HitAreaEventOn = false;
            beepMenuBar1.HitTestControl = null;
            beepMenuBar1.HoverBackColor = Color.White;
            beepMenuBar1.HoverBorderColor = Color.Gray;
            beepMenuBar1.HoveredBackcolor = Color.Wheat;
            beepMenuBar1.HoverForeColor = Color.Black;
            beepMenuBar1.Id = -1;
            beepMenuBar1.ImageSize = 20;
            beepMenuBar1.InactiveBorderColor = Color.Gray;
         //   beepMenuBar1.Info = (SimpleItem)resources.GetObject("beepMenuBar1.Info");
            beepMenuBar1.IsAcceptButton = false;
            beepMenuBar1.IsBorderAffectedByTheme = false;
            beepMenuBar1.IsCancelButton = false;
            beepMenuBar1.IsChild = false;
            beepMenuBar1.IsCustomeBorder = false;
            beepMenuBar1.IsDefault = false;
            beepMenuBar1.IsDeleted = false;
            beepMenuBar1.IsDirty = false;
            beepMenuBar1.IsEditable = false;
            beepMenuBar1.IsFocused = false;
            beepMenuBar1.IsFrameless = true;
            beepMenuBar1.IsHovered = false;
            beepMenuBar1.IsNew = false;
            beepMenuBar1.IsPressed = false;
            beepMenuBar1.IsReadOnly = false;
            beepMenuBar1.IsRequired = false;
            beepMenuBar1.IsRounded = false;
            beepMenuBar1.IsRoundedAffectedByTheme = false;
            beepMenuBar1.IsSelected = false;
            beepMenuBar1.IsSelectedOptionOn = false;
            beepMenuBar1.IsShadowAffectedByTheme = false;
            beepMenuBar1.IsVisible = false;
            beepMenuBar1.Items = (List<object>)resources.GetObject("beepMenuBar1.Items");
            beepMenuBar1.LabelText = "";
            beepMenuBar1.LeftoffsetForDrawingRect = 0;
            beepMenuBar1.LinkedProperty = null;
            beepMenuBar1.Location = new Point(108, 41);
            beepMenuBar1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepMenuBar1.MenuItemHeight = 35;
            beepMenuBar1.MenuItemWidth = 60;
            beepMenuBar1.Name = "beepMenuBar1";
            beepMenuBar1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepMenuBar1.ParentBackColor = Color.Empty;
            beepMenuBar1.ParentControl = null;
            beepMenuBar1.PressedBackColor = Color.White;
            beepMenuBar1.PressedBorderColor = Color.Gray;
            beepMenuBar1.PressedForeColor = Color.Gray;
            beepMenuBar1.RightoffsetForDrawingRect = 0;
            beepMenuBar1.SavedGuidID = null;
            beepMenuBar1.SavedID = null;
            beepMenuBar1.SelectedBackColor = Color.White;
            beepMenuBar1.SelectedBorderColor = Color.Empty;
            beepMenuBar1.SelectedForeColor = Color.Black;
            beepMenuBar1.SelectedIndex = -1;
            beepMenuBar1.SelectedValue = null;
            beepMenuBar1.ShadowColor = Color.Black;
            beepMenuBar1.ShadowOffset = 0;
            beepMenuBar1.ShadowOpacity = 0.5F;
            beepMenuBar1.ShowAllBorders = false;
            beepMenuBar1.ShowBottomBorder = false;
            beepMenuBar1.ShowFocusIndicator = false;
            beepMenuBar1.ShowLeftBorder = false;
            beepMenuBar1.ShowRightBorder = false;
            beepMenuBar1.ShowShadow = false;
            beepMenuBar1.ShowTopBorder = false;
            beepMenuBar1.Size = new Size(691, 35);
            beepMenuBar1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepMenuBar1.StaticNotMoving = false;
            beepMenuBar1.TabIndex = 3;
            beepMenuBar1.Tag = this;
            beepMenuBar1.TempBackColor = Color.Empty;
            beepMenuBar1.Text = "beepMenuBar1";
            beepMenuBar1.TextFont = new Font("Arial", 14F, FontStyle.Bold);
            beepMenuBar1.Theme = "DefaultTheme";
            beepMenuBar1.ToolTipText = "";
            beepMenuBar1.TopoffsetForDrawingRect = 0;
            beepMenuBar1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepMenuBar1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepMenuBar1.UICustomElevation = 0;
            beepMenuBar1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepMenuBar1.UIDisabled = false;
            beepMenuBar1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepMenuBar1.UIFullWidth = false;
            beepMenuBar1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepMenuBar1.UISize = Vis.Modules.ReactUISize.Medium;
            beepMenuBar1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepMenuBar1.UseGradientBackground = false;
            beepMenuBar1.UseThemeFont = true;
            // 
            // MainFrm_SideBar
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BorderColor = Color.FromArgb(200, 200, 200);
            ClientSize = new Size(800, 450);
            Controls.Add(beepDisplayContainer1);
            Controls.Add(beepMenuBar1);
            Controls.Add(beepAppBar1);
            Controls.Add(beepSideMenu1);
            Name = "MainFrm_SideBar";
            Text = "MainFrm_SideBar";
            Theme = "DefaultTheme";
            ResumeLayout(false);
        }

        #endregion

        private Controls.BeepAppBar beepAppBar1;
        private Controls.BeepDisplayContainer beepDisplayContainer1;
        private Controls.BeepSideMenu beepSideMenu1;
        private Controls.BeepMenuBar beepMenuBar1;
    }
}