//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_POTENTIAL
    {
        
public System.String ITEM_TYPE  { get; set; }
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? OIL_VOL  { get; set; }
public System.String OIL_VOL_UOM  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_POTENTIAL()
        {
        }
    }
}
