//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_PATTERN_READ
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? PRESSURE  { get; set; }
public System.String PRESSURE_UOM  { get; set; }
public System.Decimal? STEAM_QUALITY  { get; set; }
public System.String STEAM_QUALITY_UOM  { get; set; }
public System.Decimal? TEMP  { get; set; }
public System.String TEMP_UOM  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_PATTERN_READ()
        {
        }
    }
}
