//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DHUB_LOGIN_HIST
    {
        
public System.Decimal? ID  { get; set; }
public System.String USERKOCID  { get; set; }
public System.DateTime? LOGINDATETIME  { get; set; }
public System.String MODULENAME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DHUB_LOGIN_HIST()
        {
        }
    }
}
