//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DOWNHOLE_FACILITY_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.String FACILITY_TYPE  { get; set; }
public System.String SUPER_TYPE  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.Decimal? TOP_DEPTH  { get; set; }
public System.Decimal? BOTTOM_DEPTH  { get; set; }
public System.String FACILITY_NAME  { get; set; }
public System.Decimal? WEIGHT  { get; set; }
public System.String GRADE  { get; set; }
public System.String COUPLING_TYPE  { get; set; }
public System.Decimal? OUTER_DIAMETER  { get; set; }
public System.Decimal? INNER_DIAMETER  { get; set; }
public System.Decimal? CONNECTION  { get; set; }
public System.String COMPANY  { get; set; }
public System.String USAGE  { get; set; }
public System.String DATA_SOURCE  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.String ACTIVITY_TYPE  { get; set; }
public System.DateTime? ACTIVITY_START_TIME  { get; set; }
public System.DateTime? ACTIVITY_END_TIME  { get; set; }
public System.String OPERATOR_SUPERVISOR  { get; set; }
public System.String BUSINESS_ASSOC_ID  { get; set; }
public System.Decimal? TOTAL_COST  { get; set; }
public System.String CONTRACTOR_PERF  { get; set; }
public System.String SOURCE  { get; set; }
public System.String ACTIVITY_REMARKS  { get; set; }
public System.String STAGES  { get; set; }
public System.Decimal? HORSEPOWER  { get; set; }
public System.Decimal? AMPERAGE  { get; set; }
public System.Decimal? FREQUENCY  { get; set; }
public System.Decimal? VOLTAGE  { get; set; }
public System.String ICD_NOZZLES  { get; set; }
public System.Decimal? ICD_FLOW_COEFFICIENT  { get; set; }
public System.Decimal? ICD_PACKER_TOP_DEPTH  { get; set; }
public System.Decimal? DOWNHOLE_FACILITY_S  { get; set; }
public System.String FACILITY_TBL  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERTED_BY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.String UPDATED_BY  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DOWNHOLE_FACILITY_VW()
        {
        }
    }
}
