//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class ENG_PLT_DET
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? ENG_PLT_HDR_ID  { get; set; }
public System.String ZONEFTDD  { get; set; }
public System.Decimal? CONTRIBUTION  { get; set; }
public System.Decimal? QOIL  { get; set; }
public System.Decimal? QWATER  { get; set; }
public System.String INSERTBY  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ENG_PLT_DET()
        {
        }
    }
}
