//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class ESP_DAILY_READINGS_VW
    {
        
public System.String UBHI  { get; set; }
public System.String ASSET  { get; set; }
public System.String GC  { get; set; }
public System.DateTime? INSTALLATION_DATE  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.DateTime? READING_DATE_TIME  { get; set; }
public System.DateTime? RECORD_ENTRY_DATE_TIME  { get; set; }
public System.String PI  { get; set; }
public System.String PD  { get; set; }
public System.String WHP  { get; set; }
public System.String TI  { get; set; }
public System.String TM  { get; set; }
public System.String FLP  { get; set; }
public System.String CURRENT_A  { get; set; }
public System.String CURRENT_B  { get; set; }
public System.String CURRENT_C  { get; set; }
public System.String VOLTAGE_AB  { get; set; }
public System.String VOLTAGE_BC  { get; set; }
public System.String VOLTAGE_CA  { get; set; }
public System.String FREQUENCY  { get; set; }
public System.String VIBRATION  { get; set; }
public System.String TANK_LEVEL  { get; set; }
public System.String REMARKS  { get; set; }
public System.String RECORD_STATUS  { get; set; }
public System.String SCADADATA  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ESP_DAILY_READINGS_VW()
        {
        }
    }
}
