//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class FLUID_LIFT_SYS_PTY_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String FACILITY_TYPE  { get; set; }
public System.String TEST_TYPE  { get; set; }
public System.String TEST_NAME  { get; set; }
public System.Decimal? WELL_COMPLETION_ID  { get; set; }
public System.DateTime? START_DATE  { get; set; }
public System.DateTime? END_DATE  { get; set; }
public System.Decimal? GAS_LIFT_PRESSURE  { get; set; }
public System.Decimal? GAS_LIFT_RATE  { get; set; }
public System.Decimal? GAS_LIFT_TEMP  { get; set; }
public System.Decimal? GAS_LIFT_CHOKE  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Decimal? WELL_ID  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.Decimal? WELL_TEST_ID  { get; set; }
public System.Decimal? WELL_TEST_STAGE_ID  { get; set; }
public System.DateTime? SYNC_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public FLUID_LIFT_SYS_PTY_VW()
        {
        }
    }
}
