//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class FLUID_ANALYSIS_VW
    {
        
public System.String ANALYSIS_METHOD  { get; set; }
public System.Decimal? SAMPLE_POINT_ID  { get; set; }
public System.DateTime? ACQUISITION_START_DATE  { get; set; }
public System.String ACTIVITY_ID  { get; set; }
public System.String ACQUISITION_NAME  { get; set; }
public System.DateTime? START_DATE  { get; set; }
public System.DateTime? END_DATE  { get; set; }
public System.String ANALYSIS_TYPE  { get; set; }
public System.String ANALYSIS_CODE  { get; set; }
public System.Decimal? ACQUISITION_PRESSURE  { get; set; }
public System.Decimal? ACQUISITION_TEMPERATURE  { get; set; }
public System.Decimal? ANALYSIS_PRESSURE  { get; set; }
public System.Decimal? ANALYSIS_TEMPERATURE  { get; set; }
public System.Decimal? ID  { get; set; }
public System.String COMPONENT_MATERIAL_TYPE  { get; set; }
public System.Decimal? CONCENTRATION  { get; set; }
public System.Decimal? EQUILIBRIUM_RATIO  { get; set; }
public System.String MATERIAL_TYPE  { get; set; }
public System.String MATERIAL_PHASE_CODE  { get; set; }
public System.Decimal? MASS_FRACTION  { get; set; }
public System.Decimal? MOLE_FRACTION  { get; set; }
public System.Decimal? VOLUME_FRACTION  { get; set; }
public System.String MATERIAL_COMP_VERSION  { get; set; }
public System.String MATERIAL_COMP_REMARKS  { get; set; }
public System.DateTime? ACQUISITION_END_DATE  { get; set; }
public System.String ACQUISITION_TYPE  { get; set; }
public System.String ACQUISITION_CODE  { get; set; }
public System.Decimal? SAMPLE_MD  { get; set; }
public System.String ACQUISITION_PURPOSE  { get; set; }
public System.String ORIGINAL_SOURCE  { get; set; }
public System.String ACQUISITION_SOURCE  { get; set; }
public System.String ACQUISITION_REMARKS  { get; set; }
public System.String SAMPLING_METHOD  { get; set; }
public System.Decimal? ACQUIRED_FROM_FACILITY_ID  { get; set; }
public System.String ACQUIRED_FROM_FACILITY_TBL  { get; set; }
public System.String SAMPLE_NAME  { get; set; }
public System.String SAMPLE_ORIGINAL_SOURCE  { get; set; }
public System.String SAMPLE_REMARKS  { get; set; }
public System.String SAMPLE_MATERIAL_PHASE  { get; set; }
public System.String SAMPLE_MATERIAL_TYPE  { get; set; }
public System.String SAMPLE_NUMBER  { get; set; }
public System.String SAMPLE_TYPE  { get; set; }
public System.Decimal? WELL_TEST_STAGE_ID  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.Decimal? MEASURED_FACILITY_ID  { get; set; }
public System.String MEASURED_FACILITY_TBL  { get; set; }
public System.Decimal? MEASUREMENT_POINT_ID  { get; set; }
public System.String MEASUREMENT_POINT_TYPE  { get; set; }
public System.String ANALYSIS_VERSION  { get; set; }
public System.String ANALYSIS_NAME  { get; set; }
public System.String ANALYSIS_ORIGINAL_SOURCE  { get; set; }
public System.String ANALYSIS_REMARKS  { get; set; }
public System.String ANALYSIS_SOURCE  { get; set; }
public System.String ACTIVITY_STATE  { get; set; }
public System.String ANALYSIS_PURPOSE  { get; set; }
public System.String REPORT_NUMBER  { get; set; }
public System.Decimal? ACQUISITION_ID  { get; set; }
public System.Decimal? SAMPLE_ID  { get; set; }
public System.Decimal? ANALYSIS_ID  { get; set; }
public System.DateTime? ANALYSIS_INSERT_DATE  { get; set; }
public System.String ANALYSIS_INSERT_USER  { get; set; }
public System.DateTime? ANALYSIS_UPDATE_DATE  { get; set; }
public System.String ANALYSIS_UPDATE_USER  { get; set; }
public System.DateTime? ANALYSIS_SYNC_DATE  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.DateTime? SYNC_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public FLUID_ANALYSIS_VW()
        {
        }
    }
}
