//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class LOSS_CODES
    {
        
public System.Int64 ID  { get; set; }
public System.Int64 PARENTID  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.String LEVELID  { get; set; }
public System.String GROUPID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public LOSS_CODES()
        {
        }
    }
}
