//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_APPROVALS
    {
        
public System.Decimal? ID  { get; set; }
public System.String TITLE  { get; set; }
public System.String PERSONNAME  { get; set; }
public System.Decimal? TELEXT  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.String PDDP_TYPE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_APPROVALS()
        {
        }
    }
}
