//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_WELLTESTOBJECTIVES
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Decimal? EPERF_PT_FROMDD  { get; set; }
public System.Decimal? EPERF_PT_TODD  { get; set; }
public System.Decimal? EPERF_PT_RUNTYPE_FROMDD  { get; set; }
public System.Decimal? EPERF_PT_RUNTYPE_TODD  { get; set; }
public System.Decimal? EPERF_PT_CHARGE_FROMDD  { get; set; }
public System.Decimal? EPERF_PT_CHARGE_TODD  { get; set; }
public System.Decimal? EPERF_PT_DENSITY  { get; set; }
public System.Decimal? EPERF_PT_PHASING  { get; set; }
public System.Decimal? EPERF_ST_FROMDD  { get; set; }
public System.Decimal? EPERF_ST_TODD  { get; set; }
public System.Decimal? EPERF_ST_RUNTYPE_FROMDD  { get; set; }
public System.Decimal? EPERF_ST_RUNTYPE_TODD  { get; set; }
public System.Decimal? EPERF_ST_CHARGE_FROMDD  { get; set; }
public System.Decimal? EPERF_ST_CHARGE_TODD  { get; set; }
public System.Decimal? EPERF_ST_DENSITY  { get; set; }
public System.Decimal? EPERF_ST_PHASING  { get; set; }
public System.String REMARKS  { get; set; }
public System.String CORINGPROGYN  { get; set; }
public System.String SIDEWALLCOREYN  { get; set; }
public System.String ADDITIONALSERVICESYN  { get; set; }
public System.String CHECKSHOTVSPYN  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_WELLTESTOBJECTIVES()
        {
        }
    }
}
