//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_HDR
    {
        
public System.Decimal? ID  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.String TEAM_CODE  { get; set; }
public System.String GROUP_CODE  { get; set; }
public System.String STAGE  { get; set; }
public System.String UWI  { get; set; }
public System.String OPENCASEDHOLE_COMMENTS  { get; set; }
public System.String FORMATIONTOPS_COMMENTS  { get; set; }
public System.String CASINGPROGRAM_COMMENTS  { get; set; }
public System.String COMMENTS  { get; set; }
public System.String BUDGETYEAR  { get; set; }
public System.DateTime? SITEVISIT  { get; set; }
public System.DateTime? ESTIMATEDSPUDDATE  { get; set; }
public System.DateTime? INITIATED_DATE  { get; set; }
public System.DateTime? MEETING  { get; set; }
public System.DateTime? TODRILLING  { get; set; }
public System.DateTime? PROGRAMMTG  { get; set; }
public System.DateTime? PRESPUDMTG  { get; set; }
public System.DateTime? SPUDDATE  { get; set; }
public System.String RFTPRESSURE  { get; set; }
public System.String MDTFLUIDSAMPLE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_HDR()
        {
        }
    }
}
