//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PERFORATION_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String PERFORATION_TYPE  { get; set; }
public System.String ZONE_ID  { get; set; }
public System.DateTime? PERF_START_TIME  { get; set; }
public System.DateTime? PERF_END_TIME  { get; set; }
public System.Decimal? TOP_DEPTH  { get; set; }
public System.Decimal? BOTTOM_DEPTH  { get; set; }
public System.String PERFORATION_OBJECTIVE  { get; set; }
public System.String CURRENT_STATUS  { get; set; }
public System.String REMARKS  { get; set; }
public System.String GUN_TYPE  { get; set; }
public System.Decimal? SHOT_PER_UOM  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.String EXISTENCE_TYPE  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.Decimal? PERFORATION_UNIQUE_ID  { get; set; }
public System.Decimal? ZONE_S  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERTED_BY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.String UPDATED_BY  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Decimal? PERFORATION_ACTIVITY_ID  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.String WC_NAME  { get; set; }
public System.Decimal? TOP_INTERVAL_MD  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PERFORATION_VW()
        {
        }
    }
}
