//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class VIEWLOGTRACKER
    {
        
public System.Decimal? ID  { get; set; }
public System.String VIEWNAME  { get; set; }
public System.String FIELDNAME  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public VIEWLOGTRACKER()
        {
        }
    }
}
