//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WCS_AREA
    {
        
public System.String PPDM_WCS_UWI  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.String RESERVOIR_NAME  { get; set; }
public System.String LAYER_NAME  { get; set; }
public System.String AREA  { get; set; }
public System.Decimal? H2S  { get; set; }
public System.Decimal? OIL_API  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.String UWI  { get; set; }
public System.String RESERVOIR_ID  { get; set; }
public System.String WELL_OWNERSHIP  { get; set; }
public System.DateTime? WELL_OWNERSHIP_DATE  { get; set; }
public System.Decimal? WHT  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.Decimal? SHRINKAGE_FACTOR  { get; set; }
public System.Decimal? GAS_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? WATER_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? BSW  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S_IN_OIL  { get; set; }
public System.Decimal? H2S_IN_GAS  { get; set; }
public System.Decimal? CHLORIDE  { get; set; }
public System.Decimal? SEABED_WCS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WCS_AREA()
        {
        }
    }
}
