//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WELL_TEST_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String ACTIVITY_TYPE  { get; set; }
public System.String ACTIVITY_NAME  { get; set; }
public System.String ACTIVITY_ID  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.Decimal? DURATION  { get; set; }
public System.Decimal? LEFT_CHOKE_SIZE  { get; set; }
public System.Decimal? RIGHT_CHOKE_SIZE  { get; set; }
public System.Decimal? LIQUID_RATE  { get; set; }
public System.String PREFFERED_FLAG  { get; set; }
public System.Decimal? WHP  { get; set; }
public System.Decimal? FLP  { get; set; }
public System.String PRESSURE_FLAG  { get; set; }
public System.Decimal? WC  { get; set; }
public System.String WC_FLAG  { get; set; }
public System.Decimal? TOTAL_GOR  { get; set; }
public System.String GOR_FLAG  { get; set; }
public System.Decimal? WHT  { get; set; }
public System.Decimal? H2S  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.Decimal? API  { get; set; }
public System.Decimal? GAS_RATE  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.Decimal? WELL_TEST_ID  { get; set; }
public System.DateTime? VALIDATE_DATE  { get; set; }
public System.String VALIDATED_BY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_TEST_VW()
        {
        }
    }
}
