//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WELL_TREE
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PARENTID  { get; set; }
public System.String UWI  { get; set; }
public System.String FACILITY_TYPE  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.String ACTIVE  { get; set; }
public System.Decimal? INSERTBY  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.Decimal? UPDATEBY  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String FACILITY_KEY  { get; set; }
public System.String FACILITY_NAME  { get; set; }
public System.String DEFINITION  { get; set; }
public System.Decimal? TOP  { get; set; }
public System.Decimal? BOTTOM  { get; set; }
public System.String GRADE  { get; set; }
public System.Decimal? WEIGHT  { get; set; }
public System.Decimal? INNER_DIAMETER  { get; set; }
public System.Decimal? OUTER_DIAMETER  { get; set; }
public System.String STATUS  { get; set; }
public System.DateTime? WO_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_TREE()
        {
        }
    }
}
