//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class BUSINESSWORKFLOW_DTL_MEMBERS
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? BW_DTL_ID  { get; set; }
public System.Decimal? BW_HDR_ID  { get; set; }
public System.Decimal? BU_MEMBER_ID  { get; set; }
public System.DateTime? CREATEDATE  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String CREATEBY  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.Decimal? PARENTID  { get; set; }
public System.Decimal? ROLEID  { get; set; }
public System.Decimal? PSTATUS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public BUSINESSWORKFLOW_DTL_MEMBERS()
        {
        }
    }
}
