//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEV_VT_INVENTORY
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? FW_LVL  { get; set; }
public System.String FW_LVL_UOM  { get; set; }
public System.Int64 FW_LVL_FT  { get; set; }
public System.String FW_LVL_FT_UOM  { get; set; }
public System.Int64 LEVEL_FT  { get; set; }
public System.String LEVEL_FT_UOM  { get; set; }
public System.Int64 LEVEL_IN  { get; set; }
public System.String LEVEL_IN_UOM  { get; set; }
public System.Decimal? LEVEL_PCT  { get; set; }
public System.String LEVEL_PCT_UOM  { get; set; }
public System.Decimal? LIQ_VOL  { get; set; }
public System.String LIQ_VOL_UOM  { get; set; }
public System.Decimal? OIL_VOL  { get; set; }
public System.String OIL_VOL_UOM  { get; set; }
public System.Decimal? WET_OIL_VOL  { get; set; }
public System.String WET_OIL_VOL_UOM  { get; set; }
public System.Decimal? WAT_IN_OIL_VOL  { get; set; }
public System.String WAT_IN_OIL_VOL_UOM  { get; set; }
public System.Decimal? WATER_VOL  { get; set; }
public System.String WATER_VOL_UOM  { get; set; }
public System.Decimal? FREE_WAT_VOL  { get; set; }
public System.String FREE_WAT_VOL_UOM  { get; set; }
public System.String COMMENT_1  { get; set; }
public System.Decimal? LIQ_VOL_DIFF  { get; set; }
public System.String LIQ_VOL_DIFF_UOM  { get; set; }
public System.Decimal? OIL_VOL_DIFF  { get; set; }
public System.String OIL_VOL_DIFF_UOM  { get; set; }
public System.Decimal? WAT_VOL_DIFF  { get; set; }
public System.String WAT_VOL_DIFF_UOM  { get; set; }
public System.Decimal? BELOW_PLATE  { get; set; }
public System.String BELOW_PLATE_UOM  { get; set; }
public System.DateTime? PROD_DAY  { get; set; }
public System.String COMMENT  { get; set; }
public System.DateTime? END_DATETIME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_INVENTORY()
        {
        }
    }
}
