//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class ENG_PVT
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? INSERTBY  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.String RESERVOIRID  { get; set; }
public System.Decimal? BUBBLEPOINTPRESSURE  { get; set; }
public System.Decimal? ASPHALTENEONSETPRESSURE  { get; set; }
public System.Decimal? WCS  { get; set; }
public System.String UWI  { get; set; }
public System.DateTime? TEST_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ENG_PVT()
        {
        }
    }
}
