//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class KOC_TREE
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PARENT_ID  { get; set; }
public System.String TITLE  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.String LEVELTYPE  { get; set; }
public System.String CODE  { get; set; }
public System.Decimal? TL_ID  { get; set; }
public System.Decimal? MGR_ID  { get; set; }
public System.Decimal? DCEO_ID  { get; set; }
public System.Decimal? AG_TL_ID  { get; set; }
public System.Decimal? AG_MGR_ID  { get; set; }
public System.Decimal? AG_DCEO_ID  { get; set; }
public System.String KOC_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public KOC_TREE()
        {
        }
    }
}
