//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class LOOKMANSCRIPTS
    {
        
public System.Int32 QUERY_ID  { get; set; }
public System.String Q_STRING  { get; set; }
public System.Int16 DB_ID  { get; set; }
public System.Int16 P_TYPE  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.String LONG_D  { get; set; }
public System.String CREATED  { get; set; }
public System.String MODIFIED  { get; set; }
public System.DateTime? MODIFY_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public LOOKMANSCRIPTS()
        {
        }
    }
}
