//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PDDP_RESTARGETS_SEC
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String OFFSETREFERENCEWELLS  { get; set; }
public System.String REM1  { get; set; }
public System.Decimal? EXPECTEDINITIALRESERVOIRPRESS  { get; set; }
public System.String REM2  { get; set; }
public System.Decimal? PRESSUREDATUM  { get; set; }
public System.String REM3  { get; set; }
public System.DateTime? DATEOFPRESSUREESTIMATE  { get; set; }
public System.String REM4  { get; set; }
public System.Decimal? EXPECTEDWELLPOTENTIAL  { get; set; }
public System.String REM5  { get; set; }
public System.Decimal? EXPECTEDFLUIDCONTACTS  { get; set; }
public System.String REM6  { get; set; }
public System.Decimal? EXPECTEDPAYTHICKNESS  { get; set; }
public System.String REM7  { get; set; }
public System.String COMMENTS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_RESTARGETS_SEC()
        {
        }
    }
}
