//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PL_BALANCESCORECARD_CALC
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? Q1  { get; set; }
public System.Decimal? Q2  { get; set; }
public System.Decimal? Q3  { get; set; }
public System.Decimal? Q4  { get; set; }
public System.DateTime? CREATE_DATE  { get; set; }
public System.String CREATE_BY  { get; set; }
public System.String UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Decimal? PL_BAL_ID  { get; set; }
public System.String Q1TYPE  { get; set; }
public System.String Q2TYPE  { get; set; }
public System.String Q3TYPE  { get; set; }
public System.String Q4TYPE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PL_BALANCESCORECARD_CALC()
        {
        }
    }
}
