//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace KOC.DHUB3.Models
{
    
    
    public class WELL_TREE
    {
        public int ID { get; set; }
        public int PARENTID { get; set; }
        public string UWI { get; set; }
        public string FACILITY_TYPE { get; set; }
        public DateTime? START_TIME { get; set; }
        public DateTime? END_TIME { get; set; }
        public string ACTIVE { get; set; }
        public int INSERTBY { get; set; }
        public DateTime? INSERTDATE { get; set; }
        public int UPDATEBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public int FACILITY_KEY { get; set; }
        public string FACILITY_NAME { get; set; }
        public string DEFINITION { get; set; }
        public int TOP { get; set; }
        public int BOTTOM { get; set; }
        public string GRADE { get; set; }
        public int WEIGHT { get; set; }
        public int INNER_DIAMETER { get; set; }
        public int OUTER_DIAMETER { get; set; }
        public string STATUS { get; set; }
        public DateTime? WO_DATE { get; set; }
        public System.Int64 RN  { get; set; }
        
        public WELL_TREE()
        {
        }
    }
}
