//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class WELL_NAME_MAP_VW
    {
        
public System.String KOC_WELL_NAME  { get; set; }
public System.String BLOCK_NO  { get; set; }
public System.String PATTERN  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_NAME_MAP_VW()
        {
        }
    }
}
