//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class WELL_HISTORY
    {
        
public System.Decimal? ID  { get; set; }
public System.String UWI  { get; set; }
public System.Decimal? ENTRED_BY  { get; set; }
public System.DateTime? ENTRY_DATE  { get; set; }
public System.DateTime? EVENT_DATE  { get; set; }
public System.String EVENT  { get; set; }
public System.String EVENT_TYPE  { get; set; }
public System.String EVENT_STATUS  { get; set; }
public System.Decimal? PRINTABLE  { get; set; }
public System.String DISPLAYDOMAINNAME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_HISTORY()
        {
        }
    }
}
