//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class WORKOVER_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String ASSET  { get; set; }
public System.String ACTIVITY_TYPE  { get; set; }
public System.String ACTIVITY_ID  { get; set; }
public System.String OPERATION_PURPOSE  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.Decimal? TOTAL_COST  { get; set; }
public System.Decimal? DURATION  { get; set; }
public System.String RIG_NAME  { get; set; }
public System.String ENGINEER  { get; set; }
public System.String DEPTH_TYPE  { get; set; }
public System.Decimal? BASE_DEPTH  { get; set; }
public System.String WELL_HEAD_TYPE  { get; set; }
public System.String FLUID_TYPE  { get; set; }
public System.String FLUID_AMOUNT  { get; set; }
public System.String DRILLING_TEAM  { get; set; }
public System.String OBJECTIVE  { get; set; }
public System.String LOP_PAGE1  { get; set; }
public System.String LOP_PAGE2  { get; set; }
public System.String LOP_PAGE3  { get; set; }
public System.String LOP_PAGE4  { get; set; }
public System.String LOP_PAGE5  { get; set; }
public System.String LOP_PAGE6  { get; set; }
public System.String LOP_PAGE7  { get; set; }
public System.String LOP_PAGE8  { get; set; }
public System.String LOP_PAGE9  { get; set; }
public System.String LOP_PAGE10  { get; set; }
public System.String LOP_PAGE11  { get; set; }
public System.String LOP_PAGE12  { get; set; }
public System.String LOP_PAGE13  { get; set; }
public System.String LOP_PAGE14  { get; set; }
public System.String LOP_PAGE15  { get; set; }
public System.String QC_FLAG  { get; set; }
public System.Decimal? ID  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.DateTime? SYNC_DATE  { get; set; }
public System.Decimal? WELL_ID  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WORKOVER_VW()
        {
        }
    }
}
