using System;
using System.Drawing;
using System.Collections.Generic;
using System.Drawing.Drawing2D;
using TheTechIdea.Beep.Vis.Modules;

namespace TheTechIdea.Beep.Winform.Controls.Themes
{
    public sealed partial class NeonTheme
    {
        private void ApplyTypography()
        {
            this.BadgeFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ButtonHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ButtonSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CardTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CardSubTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CardHeaderStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CardparagraphStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CardSubTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CalendarTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DaysHeaderFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SelectedDateFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CalendarSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CalendarUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.HeaderFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.MonthFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.YearFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DaysFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DaysSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DateFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.FooterFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ChartTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ChartSubTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CheckBoxFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CheckBoxCheckedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ComboBoxItemFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ComboBoxListFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DashboardTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DashboardSubTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DashboardTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DashboardSubTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogYesButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogNoButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogOkButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogCancelButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogWarningButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogErrorButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogInformationButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogQuestionButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogHelpButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogCloseButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogYesButtonHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogNoButtonHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DialogOkButtonHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.FontName = "Montserrat";
            this.FontSize = 8f;
            this.TitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 20f, FontWeight = FontWeight.Bold, FontStyle = FontStyle.Regular, TextColor = ForeColor, LetterSpacing = 0.02f, LineHeight = 1.2f };
            this.SubtitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.SemiBold, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.2f };
            this.BodyStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.6f };
            this.CaptionStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Italic, TextColor = InactiveBorderColor, LineHeight = 1.1f };
            this.ButtonStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Bold, FontStyle = FontStyle.Regular, TextColor = OnPrimaryColor, LetterSpacing = 0.08f, LineHeight = 1.0f };
            this.LinkStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.SemiBold, FontStyle = FontStyle.Underline, IsUnderlined = true, TextColor = SecondaryColor, LineHeight = 1.0f };
            this.OverlineStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Medium, FontStyle = FontStyle.Regular, TextColor = InactiveBorderColor, LetterSpacing = 0.22f, LineHeight = 1.0f };
            this.GridHeaderFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.GridRowFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.GridCellFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.GridCellSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.GridCellHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.GridCellErrorFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.GridColumnFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LabelFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SubLabelFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ListTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Bold, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.26f };
            this.ListSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.SemiBold, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.26f };
            this.ListUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = InactiveBorderColor, LineHeight = 1.26f };
            this.LoginTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LoginSubtitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LoginDescriptionFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LoginLinkFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LoginButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.MenuTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.MenuItemSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.MenuItemUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.FontFamily = string.Empty;
            this.FontSizeBlockHeader = 14f;
            this.FontSizeBlockText = 8f;
            this.FontSizeQuestion = 12f;
            this.FontSizeAnswer = 10f;
            this.FontSizeCaption = 8f;
            this.FontSizeButton = 8f;
            this.FontStyleRegular = System.Drawing.FontStyle.Regular;
            this.FontStyleBold = System.Drawing.FontStyle.Regular;
            this.FontStyleItalic = System.Drawing.FontStyle.Regular;
            this.NavigationTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.NavigationSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.NavigationUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ProgressBarFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.RadioButtonFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.RadioButtonCheckedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ScrollListTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ScrollListSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ScrollListUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ScrollListIItemFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.ScrollListItemSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SideMenuTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SideMenuSubTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SideMenuTextFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SideMenuTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SideMenuSubTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StarTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StarSubTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StarSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StarUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsCardTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsCardSubStyleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsCardValueStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsCardInfoStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StatsCardTrendStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StepperTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StepperSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StepperUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StepperItemFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StepperSubTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SwitchTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SwitchSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SwitchUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TabFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TabHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TabSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardTitleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardSubStyleStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardMetricTextStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TaskCardProgressValueStyle = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TestimoniaTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TestimoniaSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TestimoniaUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TextBoxFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TextBoxHoverFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TextBoxSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TreeTitleFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TreeNodeSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TreeNodeUnSelectedFont = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Heading1 = new TypographyStyle { FontFamily = "Montserrat", FontSize = 22f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Heading2 = new TypographyStyle { FontFamily = "Montserrat", FontSize = 20f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Heading3 = new TypographyStyle { FontFamily = "Montserrat", FontSize = 18f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Heading4 = new TypographyStyle { FontFamily = "Montserrat", FontSize = 16f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Heading5 = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Heading6 = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Paragraph = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Blockquote = new TypographyStyle { FontFamily = "Montserrat", FontSize = 10f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.InlineCode = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.CodeBlock = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.UnorderedList = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.OrderedList = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.Link = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.SmallText = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.StrongText = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.EmphasisText = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DisplayLarge = new TypographyStyle { FontFamily = "Montserrat", FontSize = 44f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DisplayMedium = new TypographyStyle { FontFamily = "Montserrat", FontSize = 34f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.DisplaySmall = new TypographyStyle { FontFamily = "Montserrat", FontSize = 26f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.HeadlineLarge = new TypographyStyle { FontFamily = "Montserrat", FontSize = 22f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.HeadlineMedium = new TypographyStyle { FontFamily = "Montserrat", FontSize = 20f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.HeadlineSmall = new TypographyStyle { FontFamily = "Montserrat", FontSize = 18f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TitleLarge = new TypographyStyle { FontFamily = "Montserrat", FontSize = 16f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TitleMedium = new TypographyStyle { FontFamily = "Montserrat", FontSize = 14f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.TitleSmall = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.BodyLarge = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.BodyMedium = new TypographyStyle { FontFamily = "Montserrat", FontSize = 10f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.BodySmall = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LabelLarge = new TypographyStyle { FontFamily = "Montserrat", FontSize = 12f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LabelMedium = new TypographyStyle { FontFamily = "Montserrat", FontSize = 10f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
            this.LabelSmall = new TypographyStyle { FontFamily = "Montserrat", FontSize = 8f, FontWeight = FontWeight.Normal, FontStyle = FontStyle.Regular, TextColor = ForeColor, LineHeight = 1.5f };
        }
    }
}
