using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace TheTechIdea.Beep.Vis.Modules.ThemeTypes.ModernDarkTheme
{
    public partial class ModernDarkTheme : BeepTheme
    {
        public ModernDarkTheme()
        {
            ThemeGuid = Guid.NewGuid().ToString();
            FontFamily = "Segoe UI";
            FontSize = 12f;
            IsDarkTheme = true;
            FontName = "Segoe UI";
            PrimaryColor = Color.FromArgb(33, 150, 243);
            SecondaryColor = Color.FromArgb(66, 66, 66);
            AccentColor = Color.FromArgb(255, 87, 34);
            BackgroundColor = Color.FromArgb(30, 30, 30);
            SurfaceColor = Color.FromArgb(43, 43, 43);
            ErrorColor = Color.FromArgb(211, 47, 47);
            WarningColor = Color.FromArgb(255, 167, 38);
            SuccessColor = Color.FromArgb(76, 175, 80);
            OnPrimaryColor = Color.White;
            OnBackgroundColor = Color.FromArgb(245, 245, 245);
            BorderColor = Color.FromArgb(66, 66, 66);
            DisabledForeColor = Color.FromArgb(120, 120, 120);
            DisabledBackColor = Color.FromArgb(66, 66, 66);
            BackColor = Color.FromArgb(30, 30, 30);
            PanelBackColor = Color.FromArgb(43, 43, 43);
            DisabledBorderColor = Color.FromArgb(80, 80, 80);
            ActiveBorderColor = Color.FromArgb(33, 150, 243);
            InactiveBorderColor = Color.FromArgb(66, 66, 66);
            GradientStartColor = Color.FromArgb(50, 50, 50);
            GradientEndColor = Color.FromArgb(30, 30, 30);
            GradientDirection = LinearGradientMode.Vertical;
            AppBarBackColor = Color.FromArgb(38, 38, 38);
            AppBarForeColor = Color.White;
            AppBarButtonForeColor = Color.White;
            AppBarButtonBackColor = Color.FromArgb(50, 50, 50);
            AppBarTextBoxBackColor = Color.FromArgb(60, 60, 60);
            AppBarTextBoxForeColor = Color.White;
            AppBarLabelForeColor = Color.FromArgb(200, 200, 200);
            AppBarLabelBackColor = Color.FromArgb(38, 38, 38);
            AppBarTitleForeColor = Color.White;
            AppBarTitleBackColor = Color.FromArgb(38, 38, 38);
            AppBarSubTitleForeColor = Color.FromArgb(180, 180, 180);
            AppBarSubTitleBackColor = Color.FromArgb(38, 38, 38);
            AppBarCloseButtonColor = Color.FromArgb(211, 47, 47);
            AppBarMaxButtonColor = Color.FromArgb(76, 175, 80);
            AppBarMinButtonColor = Color.FromArgb(255, 167, 38);
            AppBarTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            AppBarSubTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            AppBarTextStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(200, 200, 200), LineHeight = 1.2f };
            TitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 24f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            SubtitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            BodyStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            CaptionStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(120, 120, 120), LineHeight = 1.2f };
            ButtonStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Medium, TextColor = Color.White, LineHeight = 1.2f };
            LinkStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(33, 150, 243), IsUnderlined = true, LineHeight = 1.2f };
            OverlineStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            ButtonBackColor = Color.FromArgb(43, 43, 43);
            ButtonForeColor = Color.White;
            ButtonBorderColor = Color.FromArgb(66, 66, 66);
            ButtonHoverBackColor = Color.FromArgb(50, 50, 50);
            ButtonHoverForeColor = Color.White;
            ButtonHoverBorderColor = Color.FromArgb(80, 80, 80);
            ButtonSelectedBorderColor = Color.FromArgb(33, 150, 243);
            ButtonSelectedBackColor = Color.FromArgb(50, 50, 50);
            ButtonSelectedForeColor = Color.White;
            ButtonSelectedHoverBackColor = Color.FromArgb(70, 70, 70);
            ButtonSelectedHoverForeColor = Color.White;
            ButtonSelectedHoverBorderColor = Color.FromArgb(33, 150, 243);
            ButtonErrorBackColor = Color.FromArgb(211, 47, 47);
            ButtonErrorForeColor = Color.White;
            ButtonErrorBorderColor = Color.FromArgb(244, 67, 54);
            ButtonPressedBackColor = Color.FromArgb(33, 33, 33);
            ButtonPressedForeColor = Color.White;
            ButtonPressedBorderColor = Color.FromArgb(66, 66, 66);
            TextBoxBackColor = Color.FromArgb(50, 50, 50);
            TextBoxForeColor = Color.White;
            TextBoxBorderColor = Color.FromArgb(66, 66, 66);
            TextBoxHoverBorderColor = Color.FromArgb(80, 80, 80);
            TextBoxHoverBackColor = Color.FromArgb(60, 60, 60);
            TextBoxHoverForeColor = Color.White;
            TextBoxSelectedBorderColor = Color.FromArgb(33, 150, 243);
            TextBoxSelectedBackColor = Color.FromArgb(50, 50, 50);
            TextBoxSelectedForeColor = Color.White;
            TextBoxPlaceholderColor = Color.FromArgb(120, 120, 120);
            TextBoxErrorBorderColor = Color.FromArgb(211, 47, 47);
            TextBoxErrorBackColor = Color.FromArgb(50, 50, 50);
            TextBoxErrorForeColor = Color.White;
            TextBoxErrorTextColor = Color.FromArgb(211, 47, 47);
            LabelBackColor = Color.FromArgb(43, 43, 43);
            LabelForeColor = Color.FromArgb(245, 245, 245);
            LabelBorderColor = Color.FromArgb(66, 66, 66);
            LabelHoverBorderColor = Color.FromArgb(80, 80, 80);
            LabelHoverBackColor = Color.FromArgb(50, 50, 50);
            LabelHoverForeColor = Color.White;
            LabelSelectedBorderColor = Color.FromArgb(33, 150, 243);
            LabelSelectedBackColor = Color.FromArgb(50, 50, 50);
            LabelSelectedForeColor = Color.White;
            LabelDisabledBackColor = Color.FromArgb(66, 66, 66);
            LabelDisabledForeColor = Color.FromArgb(120, 120, 120);
            LabelDisabledBorderColor = Color.FromArgb(80, 80, 80);
            ComboBoxBackColor = Color.FromArgb(50, 50, 50);
            ComboBoxForeColor = Color.White;
            ComboBoxBorderColor = Color.FromArgb(66, 66, 66);
            CheckBoxBackColor = Color.FromArgb(43, 43, 43);
            CheckBoxForeColor = Color.FromArgb(245, 245, 245);
            CheckBoxBorderColor = Color.FromArgb(66, 66, 66);
            CheckBoxSelectedForeColor = Color.White;
            CheckBoxSelectedBackColor = Color.FromArgb(33, 150, 243);
            CheckBoxHoverBackColor = Color.FromArgb(50, 50, 50);
            CheckBoxHoverForeColor = Color.White;
            CheckBoxHoverBorderColor = Color.FromArgb(80, 80, 80);
            RadioButtonBackColor = Color.FromArgb(43, 43, 43);
            RadioButtonForeColor = Color.FromArgb(245, 245, 245);
            RadioButtonBorderColor = Color.FromArgb(66, 66, 66);
            RadioButtonSelectedForeColor = Color.White;
            RadioButtonSelectedBackColor = Color.FromArgb(33, 150, 243);
            RadioButtonHoverBackColor = Color.FromArgb(50, 50, 50);
            RadioButtonHoverForeColor = Color.White;
            RadioButtonHoverBorderColor = Color.FromArgb(80, 80, 80);
            ProgressBarBackColor = Color.FromArgb(66, 66, 66);
            ProgressBarForeColor = Color.FromArgb(33, 150, 243);
            ProgressBarBorderColor = Color.FromArgb(80, 80, 80);
            ProgressBarInsideTextColor = Color.White;
            ProgressBarHoverBackColor = Color.FromArgb(70, 70, 70);
            ProgressBarHoverForeColor = Color.FromArgb(33, 150, 243);
            ProgressBarHoverBorderColor = Color.FromArgb(90, 90, 90);
            ProgressBarHoverInsideTextColor = Color.White;
            ScrollBarBackColor = Color.FromArgb(43, 43, 43);
            ScrollBarThumbColor = Color.FromArgb(80, 80, 80);
            ScrollBarTrackColor = Color.FromArgb(50, 50, 50);
            ScrollBarHoverThumbColor = Color.FromArgb(100, 100, 100);
            ScrollBarHoverTrackColor = Color.FromArgb(60, 60, 60);
            ScrollBarActiveThumbColor = Color.FromArgb(33, 150, 243);
            StatusBarBackColor = Color.FromArgb(38, 38, 38);
            StatusBarForeColor = Color.FromArgb(200, 200, 200);
            StatusBarBorderColor = Color.FromArgb(66, 66, 66);
            StatusBarHoverBackColor = Color.FromArgb(50, 50, 50);
            StatusBarHoverForeColor = Color.White;
            StatusBarHoverBorderColor = Color.FromArgb(80, 80, 80);
            LinkColor = Color.FromArgb(33, 150, 243);
            VisitedLinkColor = Color.FromArgb(156, 39, 176);
            HoverLinkColor = Color.FromArgb(66, 165, 245);
            ToolTipBackColor = Color.FromArgb(50, 50, 50);
            ToolTipForeColor = Color.White;
            ToolTipBorderColor = Color.FromArgb(80, 80, 80);
            ToolTipShadowColor = Color.FromArgb(20, 20, 20);
            ToolTipShadowOpacity = Color.FromArgb(255, 20, 20, 20);
            ToolTipTextColor = Color.FromArgb(245, 245, 245);
            ToolTipLinkColor = Color.FromArgb(33, 150, 243);
            ToolTipLinkHoverColor = Color.FromArgb(66, 165, 245);
            ToolTipLinkVisitedColor = Color.FromArgb(156, 39, 176);
            TabBackColor = Color.FromArgb(43, 43, 43);
            TabForeColor = Color.FromArgb(200, 200, 200);
            ActiveTabBackColor = Color.FromArgb(50, 50, 50);
            ActiveTabForeColor = Color.White;
            InactiveTabBackColor = Color.FromArgb(38, 38, 38);
            InactiveTabForeColor = Color.FromArgb(180, 180, 180);
            TabBorderColor = Color.FromArgb(66, 66, 66);
            TabHoverBackColor = Color.FromArgb(60, 60, 60);
            TabHoverForeColor = Color.White;
            TabSelectedBackColor = Color.FromArgb(33, 150, 243);
            TabSelectedForeColor = Color.White;
            TabSelectedBorderColor = Color.FromArgb(33, 150, 243);
            TabHoverBorderColor = Color.FromArgb(80, 80, 80);
            DialogBackColor = Color.FromArgb(50, 50, 50);
            DialogForeColor = Color.White;
            DialogYesButtonBackColor = Color.FromArgb(76, 175, 80);
            DialogYesButtonForeColor = Color.White;
            DialogYesButtonHoverBackColor = Color.FromArgb(96, 195, 100);
            DialogYesButtonHoverForeColor = Color.White;
            DialogYesButtonHoverBorderColor = Color.FromArgb(76, 175, 80);
            DialogCancelButtonBackColor = Color.FromArgb(66, 66, 66);
            DialogCancelButtonForeColor = Color.White;
            DialogCancelButtonHoverBackColor = Color.FromArgb(80, 80, 80);
            DialogCancelButtonHoverForeColor = Color.White;
            DialogCancelButtonHoverBorderColor = Color.FromArgb(66, 66, 66);
            DialogCloseButtonBackColor = Color.FromArgb(211, 47, 47);
            DialogCloseButtonForeColor = Color.White;
            DialogCloseButtonHoverBackColor = Color.FromArgb(231, 67, 67);
            DialogCloseButtonHoverForeColor = Color.White;
            DialogCloseButtonHoverBorderColor = Color.FromArgb(211, 47, 47);
            DialogHelpButtonBackColor = Color.FromArgb(33, 150, 243);
            DialogNoButtonBackColor = Color.FromArgb(66, 66, 66);
            DialogNoButtonForeColor = Color.White;
            DialogNoButtonHoverBackColor = Color.FromArgb(80, 80, 80);
            DialogNoButtonHoverForeColor = Color.White;
            DialogNoButtonHoverBorderColor = Color.FromArgb(66, 66, 66);
            DialogOkButtonBackColor = Color.FromArgb(33, 150, 243);
            DialogOkButtonForeColor = Color.White;
            DialogOkButtonHoverBackColor = Color.FromArgb(66, 165, 245);
            DialogOkButtonHoverForeColor = Color.White;
            DialogOkButtonHoverBorderColor = Color.FromArgb(33, 150, 243);
            DialogWarningButtonBackColor = Color.FromArgb(255, 167, 38);
            DialogWarningButtonForeColor = Color.White;
            DialogWarningButtonHoverBackColor = Color.FromArgb(255, 187, 58);
            DialogWarningButtonHoverForeColor = Color.White;
            DialogWarningButtonHoverBorderColor = Color.FromArgb(255, 167, 38);
            DialogErrorButtonBackColor = Color.FromArgb(211, 47, 47);
            DialogErrorButtonForeColor = Color.White;
            DialogErrorButtonHoverBackColor = Color.FromArgb(231, 67, 67);
            DialogErrorButtonHoverForeColor = Color.White;
            DialogErrorButtonHoverBorderColor = Color.FromArgb(211, 47, 47);
            DialogInformationButtonBackColor = Color.FromArgb(33, 150, 243);
            DialogInformationButtonForeColor = Color.White;
            DialogInformationButtonHoverBackColor = Color.FromArgb(66, 165, 245);
            DialogInformationButtonHoverForeColor = Color.White;
            DialogInformationButtonHoverBorderColor = Color.FromArgb(33, 150, 243);
            DialogQuestionButtonBackColor = Color.FromArgb(33, 150, 243);
            DialogQuestionButtonForeColor = Color.White;
            DialogQuestionButtonHoverBackColor = Color.FromArgb(66, 165, 245);
            DialogQuestionButtonHoverForeColor = Color.White;
            DialogQuestionButtonHoverBorderColor = Color.FromArgb(33, 150, 243);
            GridBackColor = Color.FromArgb(33, 33, 33);
            GridForeColor = Color.FromArgb(232, 234, 237);
            GridHeaderBackColor = Color.FromArgb(48, 48, 48);
            GridHeaderForeColor = Color.FromArgb(232, 234, 237);
            GridHeaderBorderColor = Color.FromArgb(48, 48, 48);
            GridHeaderHoverBackColor = Color.FromArgb(66, 66, 66);
            GridHeaderHoverForeColor = Color.FromArgb(232, 234, 237);
            GridHeaderSelectedBackColor = Color.FromArgb(103, 80, 164);
            GridHeaderSelectedForeColor = Color.FromArgb(232, 234, 237);
            GridHeaderHoverBorderColor = Color.FromArgb(66, 66, 66);
            GridHeaderSelectedBorderColor = Color.FromArgb(103, 80, 164);
            GridRowHoverBackColor = Color.FromArgb(48, 48, 48);
            GridRowHoverForeColor = Color.FromArgb(232, 234, 237);
            GridRowSelectedBackColor = Color.FromArgb(103, 80, 164);
            GridRowSelectedForeColor = Color.FromArgb(232, 234, 237);
            GridRowHoverBorderColor = Color.FromArgb(66, 66, 66);
            GridRowSelectedBorderColor = Color.FromArgb(103, 80, 164);
            GridLineColor = Color.FromArgb(48, 48, 48);
            RowBackColor = Color.FromArgb(33, 33, 33);
            RowForeColor = Color.FromArgb(232, 234, 237);
            AltRowBackColor = Color.FromArgb(30, 30, 30);
            SelectedRowBackColor = Color.FromArgb(103, 80, 164);
            SelectedRowForeColor = Color.FromArgb(232, 234, 237);
            CardTextForeColor = Color.FromArgb(245, 245, 245);
            CardBackColor = Color.FromArgb(50, 50, 50);
            CardTitleForeColor = Color.White;
            CardSubTitleForeColor = Color.FromArgb(180, 180, 180);
            CardHeaderStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            CardparagraphStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            CardSubTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            SideMenuBackColor = Color.FromArgb(38, 38, 38);
            SideMenuHoverBackColor = Color.FromArgb(50, 50, 50);
            SideMenuSelectedBackColor = Color.FromArgb(33, 150, 243);
            SideMenuForeColor = Color.FromArgb(200, 200, 200);
            SideMenuSelectedForeColor = Color.White;
            SideMenuHoverForeColor = Color.White;
            SideMenuBorderColor = Color.FromArgb(66, 66, 66);
            SideMenuTitleTextColor = Color.White;
            SideMenuTitleBackColor = Color.FromArgb(38, 38, 38);
            SideMenuTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 16f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            SideMenuSubTitleTextColor = Color.FromArgb(180, 180, 180);
            SideMenuSubTitleBackColor = Color.FromArgb(38, 38, 38);
            SideMenuSubTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            DashboardBackColor = Color.FromArgb(30, 30, 30);
            DashboardCardBackColor = Color.FromArgb(50, 50, 50);
            DashboardCardHoverBackColor = Color.FromArgb(60, 60, 60);
            DashboardTitleForeColor = Color.White;
            DashboardTitleBackColor = Color.FromArgb(30, 30, 30);
            DashboardTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 24f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            DashboardSubTitleForeColor = Color.FromArgb(180, 180, 180);
            DashboardSubTitleBackColor = Color.FromArgb(30, 30, 30);
            DashboardSubTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 16f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            ChartBackColor = Color.FromArgb(43, 43, 43);
            ChartLineColor = Color.FromArgb(33, 150, 243);
            ChartFillColor = Color.FromArgb(33, 150, 243);
            ChartAxisColor = Color.FromArgb(80, 80, 80);
            ChartTitleColor = Color.White;
            ChartTextColor = Color.FromArgb(245, 245, 245);
            ChartLegendBackColor = Color.FromArgb(50, 50, 50);
            ChartLegendTextColor = Color.FromArgb(200, 200, 200);
            ChartLegendShapeColor = Color.FromArgb(33, 150, 243);
            ChartGridLineColor = Color.FromArgb(66, 66, 66);
            ChartDefaultSeriesColors = new List<Color> { Color.FromArgb(33, 150, 243), Color.FromArgb(255, 87, 34), Color.FromArgb(76, 175, 80), Color.FromArgb(255, 167, 38) };
            NavigationBackColor = Color.FromArgb(38, 38, 38);
            NavigationForeColor = Color.FromArgb(200, 200, 200);
            NavigationHoverBackColor = Color.FromArgb(50, 50, 50);
            NavigationHoverForeColor = Color.White;
            BadgeBackColor = Color.FromArgb(33, 150, 243);
            BadgeForeColor = Color.White;
            HighlightBackColor = Color.FromArgb(255, 87, 34);
            MenuBackColor = Color.FromArgb(38, 38, 38);
            MenuForeColor = Color.FromArgb(200, 200, 200);
            MenuBorderColor = Color.FromArgb(66, 66, 66);
            MenuMainItemForeColor = Color.FromArgb(245, 245, 245);
            MenuMainItemHoverForeColor = Color.White;
            MenuMainItemHoverBackColor = Color.FromArgb(50, 50, 50);
            MenuMainItemSelectedForeColor = Color.White;
            MenuMainItemSelectedBackColor = Color.FromArgb(33, 150, 243);
            MenuItemForeColor = Color.FromArgb(200, 200, 200);
            MenuItemHoverForeColor = Color.White;
            MenuItemHoverBackColor = Color.FromArgb(50, 50, 50);
            MenuItemSelectedForeColor = Color.White;
            MenuItemSelectedBackColor = Color.FromArgb(33, 150, 243);
            TreeBackColor = Color.FromArgb(43, 43, 43);
            TreeForeColor = Color.FromArgb(245, 245, 245);
            TreeBorderColor = Color.FromArgb(66, 66, 66);
            TreeNodeForeColor = Color.FromArgb(200, 200, 200);
            TreeNodeHoverForeColor = Color.White;
            TreeNodeHoverBackColor = Color.FromArgb(50, 50, 50);
            TreeNodeSelectedForeColor = Color.White;
            TreeNodeSelectedBackColor = Color.FromArgb(33, 150, 243);
            TreeNodeCheckedBoxForeColor = Color.White;
            TreeNodeCheckedBoxBackColor = Color.FromArgb(33, 150, 243);
            CalendarBackColor = Color.FromArgb(43, 43, 43);
            CalendarForeColor = Color.FromArgb(245, 245, 245);
            CalendarTodayForeColor = Color.FromArgb(255, 87, 34);
            ListBackColor = Color.FromArgb(43, 43, 43);
            ListForeColor = Color.FromArgb(245, 245, 245);
            ListBorderColor = Color.FromArgb(66, 66, 66);
            ListItemForeColor = Color.FromArgb(200, 200, 200);
            ListItemHoverForeColor = Color.White;
            ListItemHoverBackColor = Color.FromArgb(50, 50, 50);
            ListItemSelectedForeColor = Color.White;
            ListItemSelectedBackColor = Color.FromArgb(33, 150, 243);
            ListItemSelectedBorderColor = Color.FromArgb(33, 150, 243);
            ListItemBorderColor = Color.FromArgb(66, 66, 66);
            ListItemHoverBorderColor = Color.FromArgb(80, 80, 80);
            StarRatingForeColor = Color.FromArgb(245, 245, 245);
            StarRatingBackColor = Color.FromArgb(43, 43, 43);
            StarRatingBorderColor = Color.FromArgb(66, 66, 66);
            StarRatingFillColor = Color.FromArgb(255, 167, 38);
            StarRatingHoverForeColor = Color.White;
            StarRatingHoverBackColor = Color.FromArgb(50, 50, 50);
            StarRatingHoverBorderColor = Color.FromArgb(80, 80, 80);
            StarRatingSelectedForeColor = Color.White;
            StarRatingSelectedBackColor = Color.FromArgb(255, 167, 38);
            StarRatingSelectedBorderColor = Color.FromArgb(255, 167, 38);
            StatsCardBackColor = Color.FromArgb(50, 50, 50);
            StatsCardForeColor = Color.FromArgb(245, 245, 245);
            StatsCardBorderColor = Color.FromArgb(66, 66, 66);
            StatsCardTitleForeColor = Color.White;
            StatsCardTitleBackColor = Color.FromArgb(50, 50, 50);
            StatsCardTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            StatsCardSubTitleForeColor = Color.FromArgb(180, 180, 180);
            StatsCardSubTitleBackColor = Color.FromArgb(50, 50, 50);
            StatsCardSubStyleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            StatsCardValueForeColor = Color.FromArgb(33, 150, 243);
            StatsCardValueBackColor = Color.FromArgb(50, 50, 50);
            StatsCardValueBorderColor = Color.FromArgb(66, 66, 66);
            StatsCardValueHoverForeColor = Color.FromArgb(66, 165, 245);
            StatsCardValueHoverBackColor = Color.FromArgb(60, 60, 60);
            StatsCardValueHoverBorderColor = Color.FromArgb(80, 80, 80);
            StatsCardValueStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 24f, FontWeight = FontWeight.Bold, TextColor = Color.FromArgb(33, 150, 243), LineHeight = 1.2f };
            StatsCardInfoForeColor = Color.FromArgb(200, 200, 200);
            StatsCardInfoBackColor = Color.FromArgb(50, 50, 50);
            StatsCardInfoBorderColor = Color.FromArgb(66, 66, 66);
            StatsCardInfoStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(200, 200, 200), LineHeight = 1.2f };
            StatsCardTrendForeColor = Color.FromArgb(76, 175, 80);
            StatsCardTrendBackColor = Color.FromArgb(50, 50, 50);
            StatsCardTrendBorderColor = Color.FromArgb(66, 66, 66);
            StatsCardTrendStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(76, 175, 80), LineHeight = 1.2f };
            SwitchBackColor = Color.FromArgb(66, 66, 66);
            SwitchBorderColor = Color.FromArgb(80, 80, 80);
            SwitchForeColor = Color.FromArgb(245, 245, 245);
            SwitchSelectedBackColor = Color.FromArgb(33, 150, 243);
            SwitchSelectedBorderColor = Color.FromArgb(33, 150, 243);
            SwitchSelectedForeColor = Color.White;
            SwitchHoverBackColor = Color.FromArgb(80, 80, 80);
            SwitchHoverBorderColor = Color.FromArgb(90, 90, 90);
            SwitchHoverForeColor = Color.White;
            TaskCardBackColor = Color.FromArgb(50, 50, 50);
            TaskCardForeColor = Color.FromArgb(245, 245, 245);
            TaskCardBorderColor = Color.FromArgb(66, 66, 66);
            TaskCardTitleForeColor = Color.White;
            TaskCardTitleBackColor = Color.FromArgb(50, 50, 50);
            TaskCardTitleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            TaskCardSubTitleForeColor = Color.FromArgb(180, 180, 180);
            TaskCardSubTitleBackColor = Color.FromArgb(50, 50, 50);
            TaskCardSubStyleStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            TaskCardMetricTextForeColor = Color.FromArgb(33, 150, 243);
            TaskCardMetricTextBackColor = Color.FromArgb(50, 50, 50);
            TaskCardMetricTextBorderColor = Color.FromArgb(66, 66, 66);
            TaskCardMetricTextHoverForeColor = Color.FromArgb(66, 165, 245);
            TaskCardMetricTextHoverBackColor = Color.FromArgb(60, 60, 60);
            TaskCardMetricTextHoverBorderColor = Color.FromArgb(80, 80, 80);
            TaskCardMetricTextStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 16f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(33, 150, 243), LineHeight = 1.2f };
            TaskCardProgressValueForeColor = Color.FromArgb(76, 175, 80);
            TaskCardProgressValueBackColor = Color.FromArgb(50, 50, 50);
            TaskCardProgressValueBorderColor = Color.FromArgb(66, 66, 66);
            TaskCardProgressValueStyle = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(76, 175, 80), LineHeight = 1.2f };
            TestimonialBackColor = Color.FromArgb(50, 50, 50);
            TestimonialTextColor = Color.FromArgb(245, 245, 245);
            TestimonialNameColor = Color.FromArgb(33, 150, 243);
            TestimonialDetailsColor = Color.FromArgb(180, 180, 180);
            TestimonialDateColor = Color.FromArgb(120, 120, 120);
            TestimonialRatingColor = Color.FromArgb(255, 167, 38);
            TestimonialStatusColor = Color.FromArgb(76, 175, 80);
            CompanyPopoverBackgroundColor = Color.FromArgb(50, 50, 50);
            CompanyTitleColor = Color.White;
            CompanySubtitleColor = Color.FromArgb(33, 150, 243);
            CompanyDescriptionColor = Color.FromArgb(180, 180, 180);
            CompanyLinkColor = Color.FromArgb(33, 150, 243);
            CompanyButtonBackgroundColor = Color.FromArgb(33, 150, 243);
            CompanyButtonTextColor = Color.White;
            CompanyDropdownBackgroundColor = Color.FromArgb(50, 50, 50);
            CompanyDropdownTextColor = Color.FromArgb(245, 245, 245);
            CompanyLogoBackgroundColor = Color.FromArgb(43, 43, 43);
            LoginPopoverBackgroundColor = Color.FromArgb(50, 50, 50);
            LoginTitleColor = Color.White;
            LoginSubtitleColor = Color.FromArgb(33, 150, 243);
            LoginDescriptionColor = Color.FromArgb(180, 180, 180);
            LoginLinkColor = Color.FromArgb(33, 150, 243);
            LoginButtonBackgroundColor = Color.FromArgb(33, 150, 243);
            LoginButtonTextColor = Color.White;
            LoginDropdownBackgroundColor = Color.FromArgb(50, 50, 50);
            LoginDropdownTextColor = Color.FromArgb(245, 245, 245);
            LoginLogoBackgroundColor = Color.FromArgb(43, 43, 43);
            Heading1 = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 32f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            Heading2 = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 28f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            Heading3 = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 24f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            Heading4 = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 20f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            Heading5 = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            Heading6 = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 16f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            Paragraph = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            Blockquote = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.5f, FontStyle = FontStyle.Italic };
            BlockquoteBorderColor = Color.FromArgb(66, 66, 66);
            BlockquoteBorderWidth = 2f;
            BlockquotePadding = 10f;
            InlineCode = new TypographyStyle { FontFamily = "Consolas", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(255, 167, 38), LineHeight = 1.2f };
            InlineCodeBackgroundColor = Color.FromArgb(60, 60, 60);
            InlineCodePadding = 2f;
            CodeBlock = new TypographyStyle { FontFamily = "Consolas", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            CodeBlockBackgroundColor = Color.FromArgb(38, 38, 38);
            CodeBlockBorderColor = Color.FromArgb(66, 66, 66);
            CodeBlockBorderWidth = 1f;
            CodeBlockPadding = 10f;
            UnorderedList = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            OrderedList = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            ListItemSpacing = 5f;
            ListIndentation = 20f;
            Link = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(33, 150, 243), IsUnderlined = true, LineHeight = 1.2f };
            LinkHoverColor = Color.FromArgb(66, 165, 245);
            LinkIsUnderline = true;
            SmallText = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(180, 180, 180), LineHeight = 1.2f };
            StrongText = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Bold, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            EmphasisText = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), FontStyle = FontStyle.Italic, LineHeight = 1.5f };
            DisplayLarge = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 48f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.1f };
            DisplayMedium = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 36f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.1f };
            DisplaySmall = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 28f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.1f };
            HeadlineLarge = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 32f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            HeadlineMedium = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 28f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            HeadlineSmall = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 24f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            TitleLarge = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 22f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            TitleMedium = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 18f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            TitleSmall = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 16f, FontWeight = FontWeight.Bold, TextColor = Color.White, LineHeight = 1.2f };
            BodyLarge = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 16f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            BodyMedium = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            BodySmall = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Normal, TextColor = Color.FromArgb(245, 245, 245), LineHeight = 1.5f };
            LabelLarge = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 12f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(200, 200, 200), LineHeight = 1.2f };
            LabelMedium = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 10f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(200, 200, 200), LineHeight = 1.2f };
            LabelSmall = new TypographyStyle { FontFamily = "Segoe UI", FontSize = 11f, FontWeight = FontWeight.Medium, TextColor = Color.FromArgb(200, 200, 200), LineHeight = 1.2f };
            FontSizeBlockHeader = 24f;
            FontSizeBlockText = 14f;
            FontSizeQuestion = 16f;
            FontSizeAnswer = 14f;
            FontSizeCaption = 12f;
            FontSizeButton = 14f;
            FontStyleRegular = FontStyle.Regular;
            FontStyleBold = FontStyle.Bold;
            FontStyleItalic = FontStyle.Italic;
            PrimaryTextColor = Color.FromArgb(245, 245, 245);
            SecondaryTextColor = Color.FromArgb(180, 180, 180);
            AccentTextColor = Color.FromArgb(33, 150, 243);
            PaddingSmall = 4;
            PaddingMedium = 8;
            PaddingLarge = 16;
            BorderRadius = 4;
            BorderSize = 1;
            IconSet = "Material";
            ApplyThemeToIcons = true;
            ShadowColor = Color.FromArgb(20, 20, 20);
            ShadowOpacity = 0.2f;
            AnimationDurationShort = 0.2;
            AnimationDurationMedium = 0.4;
            AnimationDurationLong = 0.6;
            AnimationEasingFunction = "ease-in-out";
            HighContrastMode = false;
            FocusIndicatorColor = Color.FromArgb(33, 150, 243);
        }
    }
}