//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class BUSINESSUNITS_HDR
    {
        
public System.Decimal? ID  { get; set; }
public System.String BUSINESSUNITNAME  { get; set; }
public System.Decimal? PARENTID  { get; set; }
public System.String TL_KOCNO  { get; set; }
public System.String MGR_KOCNO  { get; set; }
public System.String DCEO_KOCNO  { get; set; }
public System.String TL_DISPLAYNAME  { get; set; }
public System.String MGR_DISPLAYNAME  { get; set; }
public System.String DCEO_DISPLAYNAME  { get; set; }
public System.String UNITHEAD_KOCNO  { get; set; }
public System.String UNITHEAD_DISPLAYNAME  { get; set; }
public System.String COORDINATOR_KOCNO  { get; set; }
public System.String COORDINATOR_DISPLAYNAME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public BUSINESSUNITS_HDR()
        {
        }
    }
}
