//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class CONCENTRATION_TESTS
    {
        
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.Decimal? OIL_FIELD_OPERATION_S  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.Decimal? MATERIAL_COMPOSITION_S  { get; set; }
public System.Decimal? STAGE_FLUID_ANALYSIS_S  { get; set; }
public System.String MATERIAL_TYPE  { get; set; }
public System.Decimal? PROJECT_FLUID_ANALYSIS_S  { get; set; }
public System.String COMPONENT_MATERIAL_TYPE  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.Decimal? CONCENTRATION  { get; set; }
public System.Decimal? DENSITY  { get; set; }
public System.Decimal? MASS  { get; set; }
public System.Decimal? MASS_FRACTION  { get; set; }
public System.Decimal? MOLECULAR_WEIGHT  { get; set; }
public System.Decimal? MOLE_FRACTION  { get; set; }
public System.Decimal? NUMBER_OF_COMPONENTS  { get; set; }
public System.Decimal? SOLUBILITY  { get; set; }
public System.Decimal? VOLUME_FRACTION  { get; set; }
public System.Decimal? EQUILIBRIUM_RATIO  { get; set; }
public System.Decimal? CRITICAL_TEMPRATURE  { get; set; }
public System.Decimal? Z_FACTOR  { get; set; }
public System.Decimal? CRITICAL_PRESSURE  { get; set; }
public System.Decimal? SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? API_GRAVITY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String UPDATED_BY  { get; set; }
public System.String INSERTED_BY  { get; set; }
public System.Int64 SDAT_LABEL  { get; set; }
public System.String FA_ACTIVITY_TYPE  { get; set; }
public System.String OFO_ACTIVITY_TYPE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public CONCENTRATION_TESTS()
        {
        }
    }
}
