//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DECLINE_FORCAST_PREC
    {
        
public System.Decimal? MONTHS  { get; set; }
public System.Decimal? RATE  { get; set; }
public System.Decimal? CUMULATIVE  { get; set; }
public System.Double PREC  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DECLINE_FORCAST_PREC()
        {
        }
    }
}
