//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEV_VT_HO60K_ANALYSIS
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? SP_GRAVITY_15C  { get; set; }
public System.Decimal? SAND_CUT  { get; set; }
public System.Decimal? WATER_CUT  { get; set; }
public System.Decimal? API  { get; set; }
public System.String API_UOM  { get; set; }
public System.Decimal? HARDNESS  { get; set; }
public System.Decimal? PH  { get; set; }
public System.Decimal? TDS  { get; set; }
public System.String TDS_UOM  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.String SALINITY_UOM  { get; set; }
public System.String COMMENT  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S  { get; set; }
public System.String H2S_UOM  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.Decimal? SG_WATER  { get; set; }
public System.String COMPANY  { get; set; }
public System.Decimal? SG_GAS  { get; set; }
public System.Decimal? TOT_GOR  { get; set; }
public System.String ITEM_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_HO60K_ANALYSIS()
        {
        }
    }
}
