//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEV_VT_OPERATION_PLAN
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.DateTime? STEAM_DATE  { get; set; }
public System.DateTime? SOAK_DATE  { get; set; }
public System.DateTime? PROD_DATE  { get; set; }
public System.DateTime? RPIH_DATE  { get; set; }
public System.Decimal? GROUP  { get; set; }
public System.String COMMENTS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_OPERATION_PLAN()
        {
        }
    }
}
