//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEV_VT_MTR_READ_DAY
    {
        
public System.String ITEM_TYPE  { get; set; }
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? PRESS  { get; set; }
public System.String PRESS_UOM  { get; set; }
public System.Decimal? TEMP  { get; set; }
public System.String TEMP_UOM  { get; set; }
public System.Decimal? LIQ_VOL  { get; set; }
public System.String LIQ_VOL_UOM  { get; set; }
public System.Decimal? BSW_VOL_FRAC  { get; set; }
public System.String BSW_VOL_FRAC_UOM  { get; set; }
public System.Decimal? GAS_VOL  { get; set; }
public System.String GAS_VOL_UOM  { get; set; }
public System.Decimal? OIL_VOL  { get; set; }
public System.String OIL_VOL_UOM  { get; set; }
public System.Decimal? WATER_VOL  { get; set; }
public System.String WATER_VOL_UOM  { get; set; }
public System.Decimal? LIQ_VOL_RATE  { get; set; }
public System.String LIQ_VOL_RATE_UOM  { get; set; }
public System.Decimal? WATER_VOL_RATE  { get; set; }
public System.String WATER_VOL_RATE_UOM  { get; set; }
public System.Decimal? TEMP_CORR_FACT  { get; set; }
public System.String COMMENT_1  { get; set; }
public System.String TR_STATUS  { get; set; }
public System.Decimal? CALC_OIL_VOL  { get; set; }
public System.String CALC_OIL_VOL_UOM  { get; set; }
public System.Decimal? CALC_WATER_VOL  { get; set; }
public System.String CALC_WATER_VOL_UOM  { get; set; }
public System.Decimal? CORR_FACTOR  { get; set; }
public System.Decimal? ONSPEC_HRS  { get; set; }
public System.Decimal? LIQ_VOL2  { get; set; }
public System.String LIQ_VOL2_UOM  { get; set; }
public System.Decimal? OFFSPEC_HRS  { get; set; }
public System.Decimal? SR  { get; set; }
public System.DateTime? END_DATETIME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_MTR_READ_DAY()
        {
        }
    }
}
