//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEV_VT_WELL_READ_INJ
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? FLOW_TIME  { get; set; }
public System.String FLOW_TIME_UOM  { get; set; }
public System.Decimal? CASING_TEMP  { get; set; }
public System.String CASING_TEMP_UOM  { get; set; }
public System.Decimal? CASING_PRESS1  { get; set; }
public System.String CASING_PRESS1_UOM  { get; set; }
public System.Decimal? FLOW_PRESS  { get; set; }
public System.String FLOW_PRESS_UOM  { get; set; }
public System.Decimal? FLOW_TEMP  { get; set; }
public System.String FLOW_TEMP_UOM  { get; set; }
public System.Decimal? WH_PRESS  { get; set; }
public System.String WH_PRESS_UOM  { get; set; }
public System.String COMMENT  { get; set; }
public System.Decimal? INJ_STEAM_VOL  { get; set; }
public System.String INJ_STEAM_VOL_UOM  { get; set; }
public System.Decimal? STEAM_CNTRL_V  { get; set; }
public System.String STEAM_CNTRL_V_UOM  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_WELL_READ_INJ()
        {
        }
    }
}
