//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEV_VT_PUMP_READ_DAY
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? RUN_TIME  { get; set; }
public System.String RUN_TIME_UOM  { get; set; }
public System.String PUMP_STATUS  { get; set; }
public System.DateTime? END_DATETIME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_PUMP_READ_DAY()
        {
        }
    }
}
