//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DEVIATION_SURVEY_VW
    {
        
public System.String FIELD_NAME  { get; set; }
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String BOREHOLE_NAME  { get; set; }
public System.String SOURCE  { get; set; }
public System.String SURVEY_MODE  { get; set; }
public System.DateTime? SURVEY_DATE  { get; set; }
public System.Decimal? MD  { get; set; }
public System.Decimal? INCLINATION  { get; set; }
public System.Decimal? AZIMUTH  { get; set; }
public System.String AZIMUTH_TYPE  { get; set; }
public System.String CRS_NAME  { get; set; }
public System.String REMARKS  { get; set; }
public System.Decimal? DX  { get; set; }
public System.Decimal? DY  { get; set; }
public System.Decimal? TVD  { get; set; }
public System.Decimal? DOG_LEG_SEVERITY  { get; set; }
public System.Decimal? VERTICAL_SECT  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.Decimal? WELL_ID  { get; set; }
public System.Decimal? FIELD_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEVIATION_SURVEY_VW()
        {
        }
    }
}
