//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DHUB_USERS
    {
        
public System.Decimal? ID  { get; set; }
public System.String KOCNO  { get; set; }
public System.String LOGINID  { get; set; }
public System.String USERNAME  { get; set; }
public System.String FAV1  { get; set; }
public System.String FAV2  { get; set; }
public System.String FAV3  { get; set; }
public System.String FAV4  { get; set; }
public System.String AREA  { get; set; }
public System.String FUNCTIONS  { get; set; }
public System.String TEAM  { get; set; }
public System.String GRP  { get; set; }
public System.String ROLE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DHUB_USERS()
        {
        }
    }
}
