//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DHUB_INTEGRATED
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? BU_ID  { get; set; }
public System.Decimal? BU_M_ID  { get; set; }
public System.Decimal? BW_ID  { get; set; }
public System.Decimal? BW_DTL_ID  { get; set; }
public System.Decimal? KPI_ID  { get; set; }
public System.Decimal? KPI_M_ID  { get; set; }
public System.Decimal? PROJECT_ID  { get; set; }
public System.Decimal? TASK_ID  { get; set; }
public System.Decimal? ACTION_STATUS  { get; set; }
public System.Decimal? ACTION_TYPE  { get; set; }
public System.String PARENTID  { get; set; }
public System.Decimal? SEQ  { get; set; }
public System.Decimal? ACTION_SUB_TYPE  { get; set; }
public System.String DOCID  { get; set; }
public System.String UWI  { get; set; }
public System.String TEAMID  { get; set; }
public System.String GROUPID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DHUB_INTEGRATED()
        {
        }
    }
}
