//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class DOWNHOLE_FACILITY_CAT_VW
    {
        
public System.String FACILITY_TYPE  { get; set; }
public System.String SUPER_TYPE  { get; set; }
public System.String API_GRADE  { get; set; }
public System.Decimal? INNER_DIAMETER  { get; set; }
public System.Decimal? OUTER_DIAMETER  { get; set; }
public System.Decimal? WEIGHT  { get; set; }
public System.String COMPANY  { get; set; }
public System.String MODEL_NUMBER  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.Decimal? ID  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DOWNHOLE_FACILITY_CAT_VW()
        {
        }
    }
}
