//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class ENG_ZONE_STATUS
    {
        
public System.Decimal? ID  { get; set; }
public System.String UWI  { get; set; }
public System.String INSERTBY  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String TESTSTATUS  { get; set; }
public System.String STRINGTYPE  { get; set; }
public System.String RESID  { get; set; }
public System.Decimal? LQ  { get; set; }
public System.Decimal? GOR  { get; set; }
public System.Decimal? WC  { get; set; }
public System.Decimal? OIL  { get; set; }
public System.Decimal? WATER  { get; set; }
public System.Decimal? GAS  { get; set; }
public System.Decimal? FWHP  { get; set; }
public System.String CHOKE  { get; set; }
public System.Decimal? FLP  { get; set; }
public System.DateTime? TESTDATE  { get; set; }
public System.Decimal? API  { get; set; }
public System.DateTime? SAMPLEDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ENG_ZONE_STATUS()
        {
        }
    }
}
