//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class ENG_PLT_HDR
    {
        
public System.Decimal? ID  { get; set; }
public System.String DONEBY  { get; set; }
public System.Decimal? ISSUE_BY  { get; set; }
public System.String ISSUE_DT  { get; set; }
public System.DateTime? SURVEYDATE  { get; set; }
public System.String UWI  { get; set; }
public System.Decimal? WCS  { get; set; }
public System.String INSERTBY  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ENG_PLT_HDR()
        {
        }
    }
}
