//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class ENG_PIPE_INFO
    {
        
public System.Decimal? ID  { get; set; }
public System.String PIPRTYPE  { get; set; }
public System.String OD  { get; set; }
public System.Decimal? WEIGHT  { get; set; }
public System.String CRADE  { get; set; }
public System.String COUPLINGTYPE  { get; set; }
public System.Decimal? TOP  { get; set; }
public System.Decimal? BOTTOM  { get; set; }
public System.String COMMENTS  { get; set; }
public System.String INSERTBY  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String UWI  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ENG_PIPE_INFO()
        {
        }
    }
}
