//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class ENG_TEST_DATA
    {
        
public System.String UWI  { get; set; }
public System.DateTime? SBHP_START_TIME  { get; set; }
public System.Decimal? SBHP_EXTRAPOLATED_PRESSURE  { get; set; }
public System.Decimal? SBHP_RESSURE_DATUM  { get; set; }
public System.Decimal? SBHP_GRADIENT  { get; set; }
public System.String SBHP_RESERVOIR_NAME  { get; set; }
public System.DateTime? FBHP_START_TIME  { get; set; }
public System.Decimal? FBHP_DATUM  { get; set; }
public System.Decimal? FBHP_PSI  { get; set; }
public System.Decimal? FBHP_GRADIENT  { get; set; }
public System.String FBHP_RESERVOIR_NAME  { get; set; }
public System.DateTime? PORTABLE_DATE  { get; set; }
public System.String PORTABLE_CHOKE  { get; set; }
public System.Decimal? PORTABLE_WHP  { get; set; }
public System.Decimal? PORTABLE_FLP  { get; set; }
public System.Decimal? PORTABLE_LIQRATE  { get; set; }
public System.Decimal? PORTABLE_OILRATE  { get; set; }
public System.Decimal? PORTABLE_WC  { get; set; }
public System.Decimal? PORTABLE_GOR  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Decimal? FPHP_PL  { get; set; }
public System.String PORTABLE_RES  { get; set; }
public System.Decimal? USERID  { get; set; }
public System.String DISPLAYNAME  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String INSERTBY  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ENG_TEST_DATA()
        {
        }
    }
}
