//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class ERRANDMESSEGELOG
    {
        
public System.Decimal? ID  { get; set; }
public System.String MODULE  { get; set; }
public System.String MESSEGE  { get; set; }
public System.DateTime? ISSUE_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ERRANDMESSEGELOG()
        {
        }
    }
}
