//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class HEAVYOILWELLS
    {
        
public System.Decimal? WCS  { get; set; }
public System.String UWI  { get; set; }
public System.String BLOCK  { get; set; }
public System.String PATTERN  { get; set; }
public System.String CURRENTSTATUS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public HEAVYOILWELLS()
        {
        }
    }
}
