//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class IMAGE_ARCHIVE
    {
        
public System.Decimal? ID  { get; set; }
public System.String PDESCRIPTION  { get; set; }
public System.String TEAMCODE  { get; set; }
public System.String UWI  { get; set; }
public System.Decimal? WCS  { get; set; }
public System.DateTime? INSERTDATE  { get; set; }
public System.String INSERTBY  { get; set; }
public System.String IMAGEPATH  { get; set; }
public System.String IMAGETYPE  { get; set; }
public System.Byte[] IMAGEBLOB  { get; set; }
public System.DateTime? DOCDATE  { get; set; }
public System.String RES_ID  { get; set; }
public System.String FIELD_CODE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public IMAGE_ARCHIVE()
        {
        }
    }
}
