//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class KPI_MEMBERS
    {
        
public System.Decimal? ID  { get; set; }
public System.String KOCNO  { get; set; }
public System.Decimal? TASKID  { get; set; }
public System.DateTime? CREATEDATE  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String CREATEBY  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.Decimal? KPI_HDR_ID  { get; set; }
public System.Decimal? PROJECT_ID  { get; set; }
public System.Decimal? PSTATUS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public KPI_MEMBERS()
        {
        }
    }
}
