//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class LATEST_WELL_OP_STATUS_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.String STATUS  { get; set; }
public System.String STATUS_REASON  { get; set; }
public System.String REMARKS  { get; set; }
public System.String OFO_REMARKS  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.Decimal? OIL_FIELD_OPERATION_S  { get; set; }
public System.Decimal? FACILITY_STATUS_S  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERTED_BY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.String UPDATED_BY  { get; set; }
public System.Int64 RN  { get; set; }
        
        public LATEST_WELL_OP_STATUS_VW()
        {
        }
    }
}
