//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class LOV
    {
        
public System.Decimal? ID  { get; set; }
public System.String LOV_NAME_ENG  { get; set; }
public System.String DESCRIPTION  { get; set; }
public System.String LOV_TYPE  { get; set; }
public System.Decimal? PARENTID  { get; set; }
public System.String LOV_NAME_ARA  { get; set; }
public System.String ACTIVE  { get; set; }
public System.String ROW_CREATED_BY  { get; set; }
public System.DateTime? ROW_CREATE_DATE  { get; set; }
public System.DateTime? ROW_UPDATE_DATE  { get; set; }
public System.String ROW_UPDATE_BY  { get; set; }
public System.String LOV_CODE  { get; set; }
public System.String TEAMCODE  { get; set; }
public System.String GRPCODE  { get; set; }
public System.String KOCNO  { get; set; }
public System.Int64 RN  { get; set; }
        
        public LOV()
        {
        }
    }
}
