//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PATTERNREVIEW_HDR
    {
        
public System.Decimal? ID  { get; set; }
public System.String PATTERN  { get; set; }
public System.String ROW_CHANGED_BY  { get; set; }
public System.DateTime? ROW_CHANGED_DATE  { get; set; }
public System.String ROW_CREATED_BY  { get; set; }
public System.DateTime? ROW_CREATED_DATE  { get; set; }
public System.DateTime? REVIEWDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PATTERNREVIEW_HDR()
        {
        }
    }
}
