//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PATTERNREVIEW_DET
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PATTERNREVIEW_ID  { get; set; }
public System.String COMMENTS  { get; set; }
public System.Decimal? PICTUREID  { get; set; }
public System.String COMMENTTYPE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PATTERNREVIEW_DET()
        {
        }
    }
}
