//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PDDP_OPENHOLELOGS
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.String HOLESIZEINCH  { get; set; }
public System.Decimal? FROMFTDD  { get; set; }
public System.Decimal? TOFTDD  { get; set; }
public System.String WIRELINE  { get; set; }
public System.String MWD  { get; set; }
public System.String OHLOGSTYPE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_OPENHOLELOGS()
        {
        }
    }
}
