//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PDDP_FORMATIONTOPS
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String FORMATION  { get; set; }
public System.Decimal? DEPTHFTSS  { get; set; }
public System.Decimal? DEPTHFTDD  { get; set; }
public System.String UNCERTAINTY  { get; set; }
public System.String ESTPOREPINPPG  { get; set; }
public System.String MUDWEIGHTPPG  { get; set; }
public System.String MUDTYPE  { get; set; }
public System.Decimal? MD  { get; set; }
public System.Decimal? THICK  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_FORMATIONTOPS()
        {
        }
    }
}
