//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PDDP_TDCRITERIA
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Decimal? OH_BOTTOMLOGGINGINTERVAL  { get; set; }
public System.Decimal? OH_LOGGINGSUMP  { get; set; }
public System.Decimal? OH_TD12  { get; set; }
public System.Decimal? OH_TDDEEPEROFAORB  { get; set; }
public System.Decimal? CH_BOTTOMPERFDEPTH  { get; set; }
public System.Decimal? CS_PRODUCTIONLOGSUMP  { get; set; }
public System.Decimal? CS_DRILLINGSUMP  { get; set; }
public System.Decimal? CS_TD123  { get; set; }
public System.String REMARKS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_TDCRITERIA()
        {
        }
    }
}
