//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PDDP_RESTEMPDATA
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Decimal? SURFACETEMP  { get; set; }
public System.Decimal? GEOTHERMALGRADIENT  { get; set; }
public System.Decimal? PRIMARYTARGETBHT  { get; set; }
public System.Decimal? SECONDARYTARGETBHT  { get; set; }
public System.Decimal? BHTTD  { get; set; }
public System.String COMMENTS  { get; set; }
public System.String REM1  { get; set; }
public System.String REM2  { get; set; }
public System.String REM3  { get; set; }
public System.String REM4  { get; set; }
public System.String REM5  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_RESTEMPDATA()
        {
        }
    }
}
