//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class PRODUCTION_HISTORY_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String FACILITY_TYPE  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.DateTime? PRODUCTION_DATE  { get; set; }
public System.Decimal? OIL_VOLUME  { get; set; }
public System.Decimal? CONDENSATE_VOLUME  { get; set; }
public System.Decimal? GAS_VOLUME  { get; set; }
public System.Decimal? WATER_VOLUME  { get; set; }
public System.Decimal? PRODUCTIVE_DAYS  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PRODUCTION_HISTORY_VW()
        {
        }
    }
}
