//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class STAT_ESP_FAILURES
    {
        
public System.Decimal? FAILURES  { get; set; }
public System.String AREA  { get; set; }
public System.String FIELD_CODE  { get; set; }
public System.String CURRENT_GC  { get; set; }
public System.String RESERVOIR_ID  { get; set; }
public System.String ZONES  { get; set; }
public System.String MONTHYEAR  { get; set; }
public System.String TYPENAME  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public STAT_ESP_FAILURES()
        {
        }
    }
}
