//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KOC.DHUB3.Models.Analysis;
using System.Collections.Generic;

namespace KOC.DHUB3.Models
{
    
    
    public class WELL_LATEST_DATA
    {
        
public System.String FACILITY_TYPE  { get; set; }
public System.String WCC_STATUS  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.String RESERVOIR_NAME  { get; set; }
public System.String LAYER_NAME  { get; set; }
public System.String FIELD_NAME  { get; set; }
public System.String AREA  { get; set; }
public System.String CR_STATUS  { get; set; }
public System.Decimal? KBE  { get; set; }
public System.DateTime? COMP_DATE  { get; set; }
public System.Decimal? DRILLERS_TD  { get; set; }
public System.String ZONES  { get; set; }
public System.Decimal? GROUND_ELEVATION  { get; set; }
public System.Decimal? PLUGBACK_TD  { get; set; }
public System.Decimal? PORTABLE_TEST_STAGE_S  { get; set; }
public System.Decimal? DCS_TEST_STAGE_S  { get; set; }
public System.Decimal? SBHP_TEST_STAGE_S  { get; set; }
public System.Decimal? FBHP_TEST_STAGE_S  { get; set; }
public System.String PORTABLE_GC  { get; set; }
public System.Decimal? PORTABLE_WHP  { get; set; }
public System.Decimal? PORTABLE_LIQUID_RATE  { get; set; }
public System.String PORTABLE_WH_CHOKE_SIZE  { get; set; }
public System.Decimal? PORTABLE_FLOWSTATION_PRESS  { get; set; }
public System.String PORTABLE_GOR_REMARKS  { get; set; }
public System.Decimal? PORTABLE_FLOW_LINE_PRESSURE  { get; set; }
public System.Decimal? PORTABLE_AVG_GAS_RATE  { get; set; }
public System.Decimal? PORTABLE  { get; set; }
public System.DateTime? PORTABLE_DATE  { get; set; }
public System.String DCS_GC  { get; set; }
public System.Decimal? DCS  { get; set; }
public System.DateTime? DCS_DATE  { get; set; }
public System.Decimal? DCS_WHP  { get; set; }
public System.Decimal? DCS_LIQUID_RATE  { get; set; }
public System.String DCS_WH_CHOKE_SIZE  { get; set; }
public System.Decimal? DCS_FLOWSTATION_PRESS  { get; set; }
public System.String DCS_GOR_REMARKS  { get; set; }
public System.Decimal? DCS_FLOW_LINE_PRESSURE  { get; set; }
public System.Decimal? DCS_AVG_GAS_RATE  { get; set; }
public System.Decimal? WATER_CUT  { get; set; }
public System.DateTime? WATER_CUT_DATE  { get; set; }
public System.Decimal? WATER_CUT_WHP  { get; set; }
public System.Decimal? WATER_CUT_FLP  { get; set; }
public System.String GC_CHK_GC  { get; set; }
public System.String GC_CHK  { get; set; }
public System.Decimal? GC_CHK_WHP  { get; set; }
public System.Decimal? GC_CHK_FLP  { get; set; }
public System.DateTime? GC_CHK_DATE  { get; set; }
public System.String GC_PRESS_GC  { get; set; }
public System.String GC_PRESS_CHK  { get; set; }
public System.Decimal? GC_PRESS_WHP  { get; set; }
public System.Decimal? GC_PRESS_FLP  { get; set; }
public System.DateTime? GC_PRESS_DATE  { get; set; }
public System.Decimal? H2S  { get; set; }
public System.Decimal? OIL_API  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.Decimal? ALLOWABLE  { get; set; }
public System.String SBHP_REMARKS  { get; set; }
public System.Decimal? SBHP_PRESSURE  { get; set; }
public System.Decimal? SBHP_PRESSURE_DATUM  { get; set; }
public System.DateTime? SBHP_DATE  { get; set; }
public System.Decimal? SBHP_GRADIANT  { get; set; }
public System.Decimal? FBHP_PRESSURE  { get; set; }
public System.DateTime? FBHP_DATE  { get; set; }
public System.Decimal? FBHP_PRESSURE_DATUM  { get; set; }
public System.String FBHP_DEPTH  { get; set; }
public System.String FBHP_REMARKS  { get; set; }
public System.Decimal? FBHP_GRADIANT  { get; set; }
public System.String UWI  { get; set; }
public System.String HEADER  { get; set; }
public System.String SLOT  { get; set; }
public System.String CURRENT_GC  { get; set; }
public System.Decimal? PORTABLE_WATER_CUT  { get; set; }
public System.Decimal? X  { get; set; }
public System.Decimal? Y  { get; set; }
public System.String FACILITY_NAME  { get; set; }
public System.String STATUS_TYPE  { get; set; }
public System.DateTime? STATUS_DATE  { get; set; }
public System.String STATUS_DESCRIPTION  { get; set; }
public System.String STATUS_REASON  { get; set; }
public System.String INJ  { get; set; }
public System.Decimal? DCS_GOR_BEFORE  { get; set; }
public System.Decimal? PORTABLE_GOR_BEFORE  { get; set; }
public System.Decimal? SBHP_PRESSURE_BEFORE  { get; set; }
public System.Decimal? FBHP_PRESSURE_BEFORE  { get; set; }
public System.Decimal? WATERCUT_BEFORE  { get; set; }
public System.String CHOKE_BEFORE  { get; set; }
public System.Decimal? LIQUID_RATE  { get; set; }
public System.DateTime? LIQUID_RATE_DATE  { get; set; }
public System.String CHOKE  { get; set; }
public System.DateTime? CHOKE_DATE  { get; set; }
public System.String ESP  { get; set; }
public System.Decimal? DCS_OILRATE  { get; set; }
public System.Decimal? PORTABLE_OILRATE  { get; set; }
public System.Decimal? WC_OILRATE  { get; set; }
public System.Decimal? PRESSURE_OILRATE  { get; set; }
public System.Decimal? CHOKECHANGE_OILRATE  { get; set; }
public System.Decimal? LATEST_GOR  { get; set; }
public System.DateTime? LATEST_GOR_DATE  { get; set; }
public System.DateTime? LATEST_WC_DATE  { get; set; }
public System.Decimal? LATEST_WC  { get; set; }
public System.Decimal? LATEST_OIL_RATE  { get; set; }
public System.Decimal? LATEST_WATER_RATE  { get; set; }
public System.Decimal? LATEST_HRS  { get; set; }
public System.Decimal? LATEST_PROD_RATE  { get; set; }
public System.Decimal? LATEST_GAS_RATE  { get; set; }
public System.DateTime? LAST_PROD_DATE  { get; set; }
public System.Decimal? BEFORE_LIQUID_RATE  { get; set; }
public System.Int64 PORTABLE_WC  { get; set; }
public System.Int64 DCS_WC  { get; set; }
public System.String DRYORNOT  { get; set; }
public System.Int64 LATEST_FLP  { get; set; }
public System.Int64 LATEST_WHP  { get; set; }
public System.String MFL  { get; set; }
public System.Double LATEST_SULFUR  { get; set; }
public System.DateTime? LATEST_SULFUR_DT  { get; set; }
public System.String FIELD_CODE  { get; set; }
public System.Decimal? LATEST_INJ_RATE  { get; set; }
public System.Decimal? F_AVG_BOPD  { get; set; }
public System.Decimal? F_AVG_BWIPD  { get; set; }
public System.Decimal? F_AVG_BWPD  { get; set; }
public System.Decimal? F_GET_CUM_OIL  { get; set; }
public System.Decimal? F_GET_CUM_WAT  { get; set; }
public System.Decimal? F_PAT_INJ  { get; set; }
public System.Decimal? F_PAT_PROD  { get; set; }
public System.String RESERVOIR_ID  { get; set; }
public System.String GASINJ  { get; set; }
public System.String LF  { get; set; }
public System.String LF_DESCR  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.String ORSTATUS  { get; set; }
public System.String PPDM_WCS_UWI  { get; set; }
public System.String SCADA  { get; set; }
public System.Decimal? NODE_X  { get; set; }
public System.Decimal? NODE_Y  { get; set; }
public System.Decimal? LONGITUDE  { get; set; }
public System.Decimal? LATITUDE  { get; set; }
public System.String ESP_STATUS  { get; set; }
public System.DateTime? ESP_STATUS_DATE  { get; set; }
public System.String ESP_STATUS_REASON  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.Decimal? INSERTDAY  { get; set; }
public System.Decimal? INSERTMONTH  { get; set; }
public System.Decimal? INSERTYEAR  { get; set; }
public System.String TRANS_TYPE  { get; set; }
public System.String WELL_OWNERSHIP  { get; set; }
public System.DateTime? WELL_OWNERSHIP_DATE  { get; set; }
public System.DateTime? LATEST_FLP_DATE  { get; set; }
public System.DateTime? SPUD_DATE  { get; set; }
public System.Double TVD  { get; set; }
public System.String MYSTATUS  { get; set; }
public System.Decimal? STRING_S  { get; set; }
public System.Decimal? WHP  { get; set; }
public System.Decimal? WHT  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.Decimal? SHRINKAGE_FACTOR  { get; set; }
public System.Decimal? GAS_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? WATER_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? BSW  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S_IN_OIL  { get; set; }
public System.Decimal? H2S_IN_GAS  { get; set; }
public System.Decimal? CHLORIDE  { get; set; }
public System.Decimal? CURRENT_ESP  { get; set; }
public System.Decimal? ESP_PI  { get; set; }
public System.Decimal? CURRENT_PCP  { get; set; }
public System.Decimal? FREQUENCY  { get; set; }
public System.Decimal? RPM  { get; set; }
public System.Decimal? PCP_DISCHARGE_PRESS  { get; set; }
public System.Decimal? PCP_INTAKE_TEMP  { get; set; }
public System.Decimal? PCP_MOTOR_TEMP  { get; set; }
public System.Decimal? PCP_TORQUE  { get; set; }
public System.Decimal? ESP_FREQUENCY  { get; set; }
public System.Decimal? ESP_DISCHARGE_PRESS  { get; set; }
public System.Decimal? ESP_INTAKE_TEMP  { get; set; }
public System.Decimal? ESP_MOTOR_TEMP  { get; set; }
public System.Decimal? ESP_TORQUE  { get; set; }
public System.Decimal? ESP_VOLTAGE  { get; set; }
public System.Decimal? ESP_SRP  { get; set; }
public System.Decimal? GAS_LIFT_PRESSURE  { get; set; }
public System.Decimal? GAS_LIFT_RATE  { get; set; }
public System.Decimal? GAS_LIFT_TEMP  { get; set; }
public System.Decimal? GAS_LIFT_CHOKE  { get; set; }
public System.String WELL_DEVIATION  { get; set; }
public System.DateTime? INTERVENTION_END  { get; set; }
public System.String INTERVENTION_FACILITY  { get; set; }
public System.String INTERVENTION_NO  { get; set; }
public System.String INTERVENTION_OBJECTIVE  { get; set; }
public System.String INTERVENTION_PURPOSE  { get; set; }
public System.DateTime? INTERVENTION_START  { get; set; }
public System.String BLOCK  { get; set; }
public System.String PATTERN  { get; set; }
public int BOPD { get; set; }
public int BWPD { get; set; }
        public System.Int64 RN  { get; set; }
        
        public WELL_LATEST_DATA()
        {
        }


        public List<StatusCls> StatusHistory { get; set; } = new List<StatusCls>();
        public List<StatusCls> ESPStatusHistory { get; set; } = new List<StatusCls>();
        public List<cls_file_lib> Files { get; set; }
        public List<WellAllowedcls> AllowedHistory { get; set; } = new List<WellAllowedcls>();
        public List<WellSlotCls> SlotHistory { get; set; } = new List<WellSlotCls>();
        public List<WellHeadercls> HeaderHistory { get; set; } = new List<WellHeadercls>();
        public List<PortableData> PortableDataList { get; set; } = new List<PortableData>();
        public List<PortableMultiRate> PortableMutliRateDataList { get; set; } = new List<PortableMultiRate>();
        public List<WaterCutData> WaterCutDataList { get; set; } = new List<WaterCutData>();
        public List<DCSData> DCSDataList { get; set; } = new List<DCSData>();
        public List<FluidAnalysisData> FluidAnalysisDataList { get; set; } = new List<FluidAnalysisData>();
        public List<TestStageData> TestStageDataList { get; set; } = new List<TestStageData>();
        public List<WellLiftMethodcls> LiftMethods { get; set; } = new List<WellLiftMethodcls>();
        public List<FBHPclassreport> FBHPList { get; set; } = new List<FBHPclassreport>();
        public List<FBHPclassreport> SBHPList { get; set; } = new List<FBHPclassreport>();
        public List<WellSCADAcls> SCADAHistory { get; set; } = new List<WellSCADAcls>();
        public List<Workoverclassreport> WorkoverList { get; set; } = new List<Workoverclassreport>();
        public List<cls_portable_vs_dcs_report> portable_vs_dcsHistory { get; set; } = new List<cls_portable_vs_dcs_report>();
        public List<cls_GC_ChokeChange_data> ChokeChangeDataList { get; set; } = new List<cls_GC_ChokeChange_data>();
        public List<cls_survillanceclassreport> rep_survillance_report { get; set; } = new List<cls_survillanceclassreport>();
        public List<cls_ots_dm_al_stopstart_events> rep_survillance_ALMS_StartStopreport { get; set; } = new List<cls_ots_dm_al_stopstart_events>();
        public List<cls_rigactivityreport> rep_RigAcivities_report { get; set; } = new List<cls_rigactivityreport>();
        public List<cls_ESP_DAILY_READING_report> rep_ESP_Reading_report { get; set; } = new List<cls_ESP_DAILY_READING_report>();
        public List<cls_prepostdata> rep_prepost_data_report { get; set; } = new List<cls_prepostdata>();
        public List<cls_image_arh> ListofImages { get; set; } = new List<cls_image_arh>();
        public List<cls_opc_unit_tag> OPC_DATA { get; set; } = new List<cls_opc_unit_tag>();
        public List<HistoryDailyData> Production_history { get; set; } = new List<HistoryDailyData>();
        public List<cls_Wide_workover> Wide_WorkOver_report { get; set; } = new List<cls_Wide_workover>();
        public List<IPRPoints> IPR { get; set; } = new List<IPRPoints>();
        public List<Decline_Case> DeclineCases { get; set; } = new List<Decline_Case>();
        public List<cls_ba> rep_ba { get; set; } = new List<cls_ba>();
    }
}
