//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class WELL_TESTS
    {
        
public System.Decimal? TEST_STAGE_S  { get; set; }
public System.Decimal? OIL_FIELD_OPERATION_S  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.String TEST_TYPE  { get; set; }
public System.Decimal? TEST_RATE  { get; set; }
public System.Decimal? WC  { get; set; }
public System.Decimal? GOR  { get; set; }
public System.Decimal? WHP  { get; set; }
public System.Decimal? FLP  { get; set; }
public System.String LEFT_CHOKE_SIZE  { get; set; }
public System.String RIGHT_CHOKE_SIZE  { get; set; }
public System.String CHOKE  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.Decimal? WHT  { get; set; }
public System.String UWI  { get; set; }
public System.String DOMAIN  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_TESTS()
        {
        }
    }
}
