//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOC.DHUB3.Models
{
    
    
    public class WIRELINE_ACTIVITY_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String ACTIVITY_NAME  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.String CONTRACTOR  { get; set; }
public System.String STATUS  { get; set; }
public System.String REMARKS  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WIRELINE_ACTIVITY_VW()
        {
        }
    }
}
