
using TheTechIdea.Beep.Winform.Controls;
using TheTechIdea.Beep.Winform.Controls.ComboBoxes;

namespace TheTechIdea.Beep.Winform.Default.Views.DataSource_Connection_Controls
{
    partial class uc_DataConnectionBase
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath7 = new System.Drawing.Drawing2D.GraphicsPath();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_DataConnectionBase));
            System.Drawing.Drawing2D.GraphicsPath graphicsPath1 = new System.Drawing.Drawing2D.GraphicsPath();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath2 = new System.Drawing.Drawing2D.GraphicsPath();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath3 = new System.Drawing.Drawing2D.GraphicsPath();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath4 = new System.Drawing.Drawing2D.GraphicsPath();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath5 = new System.Drawing.Drawing2D.GraphicsPath();
            System.Drawing.Drawing2D.GraphicsPath graphicsPath6 = new System.Drawing.Drawing2D.GraphicsPath();
            dataConnectionViewModelBindingSource = new BindingSource(components);
            beepPanel1 = new TheTechIdea.Beep.Winform.Controls.BeepPanel();
            beepTabs1 = new TheTechIdea.Beep.Winform.Controls.BeepTabs();
            tabPage1 = new TabPage();
            ConnectionNamebeepTextBox = new TheTechIdea.Beep.Winform.Controls.BeepTextBox();
            DriverbeepComboBox = new TheTechIdea.Beep.Winform.Controls.BeepComboBox();
            ConnectionStringbeepTextBox = new TheTechIdea.Beep.Winform.Controls.BeepTextBox();
            DriverVersionbeepComboBox = new TheTechIdea.Beep.Winform.Controls.BeepComboBox();
            CancelbeepButton = new TheTechIdea.Beep.Winform.Controls.BeepButton();
            SavebeepButton = new TheTechIdea.Beep.Winform.Controls.BeepButton();
            //MainTemplatePanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dataConnectionViewModelBindingSource).BeginInit();
            beepPanel1.SuspendLayout();
            beepTabs1.SuspendLayout();
            tabPage1.SuspendLayout();
            SuspendLayout();
            // 
            // MainTemplatePanel
            // 
            //MainTemplatePanel.Controls.Add(beepPanel1);
            //MainTemplatePanel.Size = new Size(636, 723);
            // 
            // dataConnectionViewModelBindingSource
            // 
            dataConnectionViewModelBindingSource.DataMember = "DataConnections";
            dataConnectionViewModelBindingSource.DataSource = typeof(MVVM.ViewModels.BeepConfig.DataConnectionViewModel);
            // 
            // beepPanel1
            // 
            beepPanel1.AnimationDuration = 500;
            beepPanel1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepPanel1.ApplyThemeToChilds = true;
            beepPanel1.AutoDrawHitListComponents = true;
            beepPanel1.BackColor = Color.FromArgb(245, 245, 245);
            beepPanel1.BadgeBackColor = Color.FromArgb(33, 150, 243);
            beepPanel1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepPanel1.BadgeForeColor = Color.White;
            beepPanel1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepPanel1.BadgeText = "";
            beepPanel1.BlockID = null;
            beepPanel1.BorderColor = Color.FromArgb(200, 200, 200);
            beepPanel1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepPanel1.BorderRadius = 6;
            beepPanel1.BorderStyle = BorderStyle.FixedSingle;
            beepPanel1.BorderThickness = 1;
            beepPanel1.BottomoffsetForDrawingRect = 0;
            beepPanel1.BoundProperty = null;
            beepPanel1.CanBeFocused = false;
            beepPanel1.CanBeHovered = true;
            beepPanel1.CanBePressed = true;
            beepPanel1.Category = Utilities.DbFieldCategory.String;
            beepPanel1.ComponentName = "BaseControl";
            beepPanel1.Controls.Add(beepTabs1);
            beepPanel1.Controls.Add(CancelbeepButton);
            beepPanel1.Controls.Add(SavebeepButton);
            beepPanel1.DataSourceProperty = null;
            beepPanel1.DisabledBackColor = Color.FromArgb(200, 200, 200);
            beepPanel1.DisabledBorderColor = Color.LightGray;
            beepPanel1.DisabledForeColor = Color.Gray;
            //beepPanel1.DisableDpiAndScaling = false;
            beepPanel1.Dock = DockStyle.Fill;
            beepPanel1.DrawingRect = new Rectangle(8, 0, 620, 723);
            beepPanel1.Easing = Vis.Modules.EasingType.Linear;
            beepPanel1.EnableHighQualityRendering = true;
            beepPanel1.EnableRippleEffect = false;
            beepPanel1.EnableSplashEffect = false;
            beepPanel1.ErrorColor = Color.FromArgb(176, 0, 32);
            beepPanel1.ErrorText = "";
            beepPanel1.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            beepPanel1.FieldID = null;
            beepPanel1.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            beepPanel1.FloatingLabel = true;
            beepPanel1.FocusBackColor = Color.LightYellow;
            beepPanel1.FocusBorderColor = Color.RoyalBlue;
            beepPanel1.FocusForeColor = Color.Black;
            beepPanel1.FocusIndicatorColor = Color.RoyalBlue;
            beepPanel1.ForeColor = Color.FromArgb(33, 37, 41);
            beepPanel1.Form = null;
            beepPanel1.GlassmorphismBlur = 10F;
            beepPanel1.GlassmorphismOpacity = 0.1F;
            beepPanel1.GradientAngle = 0F;
            beepPanel1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepPanel1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepPanel1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepPanel1.GridMode = false;
            beepPanel1.GuidID = "1aacb14f-e3a5-43aa-87cb-44d23c04eada";
            beepPanel1.HasError = false;
            beepPanel1.HelperText = "";
            beepPanel1.HitAreaEventOn = false;
            beepPanel1.HitTestControl = null;
            beepPanel1.HoverBackColor = Color.LightBlue;
            beepPanel1.HoverBorderColor = Color.Blue;
            beepPanel1.HoveredBackcolor = Color.LightBlue;
            beepPanel1.HoverForeColor = Color.Black;
            beepPanel1.IconSize = 20;
            beepPanel1.Id = -1;
            beepPanel1.InactiveBorderColor = Color.Gray;
            graphicsPath7.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            beepPanel1.InnerShape = graphicsPath7;
            beepPanel1.IsAcceptButton = false;
            beepPanel1.IsBorderAffectedByTheme = true;
            beepPanel1.IsCancelButton = false;
            beepPanel1.IsChild = true;
            beepPanel1.IsCustomeBorder = false;
            beepPanel1.IsDefault = false;
            beepPanel1.IsDeleted = false;
            beepPanel1.IsDirty = false;
            beepPanel1.IsEditable = true;
            beepPanel1.IsFocused = false;
           
            beepPanel1.IsFrameless = false;
            beepPanel1.IsHovered = false;
          
            beepPanel1.IsNew = false;
            beepPanel1.IsPressed = false;
            
            beepPanel1.IsReadOnly = false;
            beepPanel1.IsRequired = false;
            beepPanel1.IsRounded = true;
            beepPanel1.IsRoundedAffectedByTheme = true;
            beepPanel1.IsSelected = false;
            
            beepPanel1.IsSelectedOptionOn = false;
            beepPanel1.IsShadowAffectedByTheme = true;
            beepPanel1.IsValid = true;
            beepPanel1.IsVisible = true;
            beepPanel1.Items = (List<object>)resources.GetObject("beepPanel1.Items");
            beepPanel1.LabelText = "";
            beepPanel1.LeadingIconPath = "";
            beepPanel1.LeadingImagePath = "";
            beepPanel1.LeftoffsetForDrawingRect = 0;
            beepPanel1.LinkedProperty = null;
            beepPanel1.Location = new Point(0, 0);
         
            beepPanel1.MaxHitListDrawPerFrame = 0;
            beepPanel1.MinimumSize = new Size(161, 56);
            beepPanel1.ModernGradientType = Vis.Modules.ModernGradientType.None;
            beepPanel1.Name = "beepPanel1";
            beepPanel1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepPanel1.ParentBackColor = Color.Empty;
            beepPanel1.ParentControl = null;
            beepPanel1.PressedBackColor = Color.Gray;
            beepPanel1.PressedBorderColor = Color.DarkGray;
            beepPanel1.PressedForeColor = Color.White;
            beepPanel1.RadialCenter = (PointF)resources.GetObject("beepPanel1.RadialCenter");
            beepPanel1.RightoffsetForDrawingRect = 0;
            beepPanel1.SavedGuidID = null;
            beepPanel1.SavedID = null;
            beepPanel1.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            beepPanel1.SelectedBackColor = Color.LightGreen;
            beepPanel1.SelectedBorderColor = Color.Green;
            beepPanel1.SelectedForeColor = Color.Black;
            beepPanel1.SelectedValue = null;
            beepPanel1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepPanel1.ShadowOffset = 3;
            beepPanel1.ShadowOpacity = 0.25F;
            beepPanel1.ShowAllBorders = false;
            beepPanel1.ShowBottomBorder = false;
            beepPanel1.ShowFocusIndicator = false;
            beepPanel1.ShowLeftBorder = false;
            beepPanel1.ShowRightBorder = false;
            beepPanel1.ShowShadow = false;
            beepPanel1.ShowTitle = false;
            beepPanel1.ShowTitleLine = false;
            beepPanel1.ShowTitleLineinFullWidth = true;
            beepPanel1.ShowTopBorder = false;
            beepPanel1.Size = new Size(636, 723);
            beepPanel1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepPanel1.StaticNotMoving = false;
            beepPanel1.TabIndex = 0;
          
            beepPanel1.Text = "beepPanel1";
            beepPanel1.TextFont = new Font("Arial", 16F);
            beepPanel1.Theme = "DefaultType";
            beepPanel1.TitleAlignment = ContentAlignment.TopLeft;
            beepPanel1.TitleBottomY = 0;
            beepPanel1.TitleLineColor = Color.FromArgb(33, 33, 33);
            beepPanel1.TitleLineThickness = 2;
            beepPanel1.TitleText = "Panel Title";
            beepPanel1.ToolTipText = null;
            beepPanel1.TopoffsetForDrawingRect = 0;
            beepPanel1.TrailingIconPath = "";
            beepPanel1.TrailingImagePath = "";
            beepPanel1.UseExternalBufferedGraphics = false;
            beepPanel1.UseGlassmorphism = false;
            beepPanel1.UseGradientBackground = false;
            beepPanel1.UseRichToolTip = true;
            beepPanel1.UseThemeFont = true;
            // 
            // beepTabs1
            // 
            beepTabs1.AccessibleName = "Beep Tabs";
            beepTabs1.AccessibleRole = AccessibleRole.PageTabList;
            beepTabs1.AllowDrop = true;
            beepTabs1.Appearance = TabAppearance.FlatButtons;
            beepTabs1.Controls.Add(tabPage1);
            beepTabs1.DrawMode = TabDrawMode.OwnerDrawFixed;
            beepTabs1.ForeColor = Color.DimGray;
            beepTabs1.HeaderHeight = 30;
            beepTabs1.HeaderPosition = Winform.Controls.TabHeaderPosition.Top;
            beepTabs1.ItemSize = new Size(0, 1);
            beepTabs1.Location = new Point(13, 7);
            beepTabs1.Name = "beepTabs1";
            beepTabs1.Padding = new Point(5, 5);
            beepTabs1.SelectedIndex = 0;
            beepTabs1.SelectTab = tabPage1;
            beepTabs1.ShowCloseButtons = false;
            beepTabs1.Size = new Size(610, 642);
            beepTabs1.SizeMode = TabSizeMode.Fixed;
            beepTabs1.TabIndex = 9;
            beepTabs1.Theme = "DefaultType";
            // 
            // tabPage1
            // 
            tabPage1.BackColor = Color.White;
            tabPage1.Controls.Add(ConnectionNamebeepTextBox);
            tabPage1.Controls.Add(DriverbeepComboBox);
            tabPage1.Controls.Add(ConnectionStringbeepTextBox);
            tabPage1.Controls.Add(DriverVersionbeepComboBox);
            tabPage1.ForeColor = Color.DimGray;
            tabPage1.Location = new Point(0, 30);
            tabPage1.Name = "tabPage1";
            tabPage1.Padding = new Padding(3);
            tabPage1.Size = new Size(610, 612);
            tabPage1.TabIndex = 0;
            tabPage1.Text = "Connection";
            // 
            // ConnectionNamebeepTextBox
            // 
            ConnectionNamebeepTextBox.AcceptsReturn = false;
            ConnectionNamebeepTextBox.AcceptsTab = false;
            ConnectionNamebeepTextBox.Anchor = AnchorStyles.None;
            ConnectionNamebeepTextBox.AnimationDuration = 500;
            ConnectionNamebeepTextBox.AnimationType = Vis.Modules.DisplayAnimationType.None;
            ConnectionNamebeepTextBox.ApplyThemeOnImage = false;
            ConnectionNamebeepTextBox.ApplyThemeToChilds = true;
            ConnectionNamebeepTextBox.AutoCompleteMode = AutoCompleteMode.None;
            ConnectionNamebeepTextBox.AutoCompleteSource = AutoCompleteSource.None;
            ConnectionNamebeepTextBox.AutoDrawHitListComponents = true;
            ConnectionNamebeepTextBox.BackColor = Color.White;
            ConnectionNamebeepTextBox.BadgeBackColor = Color.FromArgb(33, 150, 243);
            ConnectionNamebeepTextBox.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            ConnectionNamebeepTextBox.BadgeForeColor = Color.White;
            ConnectionNamebeepTextBox.BadgeShape = Vis.Modules.BadgeShape.Circle;
            ConnectionNamebeepTextBox.BadgeText = "";
            ConnectionNamebeepTextBox.BlockID = null;
            ConnectionNamebeepTextBox.BorderColor = Color.FromArgb(200, 200, 200);
            ConnectionNamebeepTextBox.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            ConnectionNamebeepTextBox.BorderRadius = 8;
            ConnectionNamebeepTextBox.BorderStyle = BorderStyle.FixedSingle;
            ConnectionNamebeepTextBox.BorderThickness = 1;
            ConnectionNamebeepTextBox.BottomoffsetForDrawingRect = 0;
            ConnectionNamebeepTextBox.BoundProperty = "Text";
            ConnectionNamebeepTextBox.CanBeFocused = false;
            ConnectionNamebeepTextBox.CanBeHovered = true;
            ConnectionNamebeepTextBox.CanBePressed = true;
            ConnectionNamebeepTextBox.Category = Utilities.DbFieldCategory.String;
            ConnectionNamebeepTextBox.ComponentName = "BaseControl";
            ConnectionNamebeepTextBox.CustomMask = "";
            ConnectionNamebeepTextBox.DataBindings.Add(new Binding("Text", dataConnectionViewModelBindingSource, "UserID", true));
            ConnectionNamebeepTextBox.DataSourceProperty = null;
            ConnectionNamebeepTextBox.DateFormat = "MM/dd/yyyy";
            ConnectionNamebeepTextBox.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            ConnectionNamebeepTextBox.DisabledBackColor = Color.FromArgb(200, 200, 200);
            ConnectionNamebeepTextBox.DisabledBorderColor = Color.LightGray;
            ConnectionNamebeepTextBox.DisabledForeColor = Color.Gray;
            //ConnectionNamebeepTextBox.DisableDpiAndScaling = false;
            ConnectionNamebeepTextBox.DrawingRect = new Rectangle(24, 8, 368, 33);
            ConnectionNamebeepTextBox.Easing = Vis.Modules.EasingType.Linear;
            ConnectionNamebeepTextBox.EnableHighQualityRendering = true;
            ConnectionNamebeepTextBox.EnableRippleEffect = false;
            ConnectionNamebeepTextBox.EnableSplashEffect = false;
            ConnectionNamebeepTextBox.ErrorColor = Color.FromArgb(176, 0, 32);
            ConnectionNamebeepTextBox.ErrorText = "";
            ConnectionNamebeepTextBox.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            ConnectionNamebeepTextBox.FieldID = null;
            ConnectionNamebeepTextBox.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            ConnectionNamebeepTextBox.FloatingLabel = true;
            ConnectionNamebeepTextBox.FocusBackColor = Color.LightYellow;
            ConnectionNamebeepTextBox.FocusBorderColor = Color.FromArgb(0, 120, 215);
            ConnectionNamebeepTextBox.FocusForeColor = Color.Black;
            ConnectionNamebeepTextBox.FocusIndicatorColor = Color.RoyalBlue;
            ConnectionNamebeepTextBox.ForeColor = Color.Black;
            ConnectionNamebeepTextBox.Form = null;
            ConnectionNamebeepTextBox.GlassmorphismBlur = 10F;
            ConnectionNamebeepTextBox.GlassmorphismOpacity = 0.1F;
            ConnectionNamebeepTextBox.GradientAngle = 0F;
            ConnectionNamebeepTextBox.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            ConnectionNamebeepTextBox.GradientEndColor = Color.FromArgb(230, 230, 230);
            ConnectionNamebeepTextBox.GradientStartColor = Color.FromArgb(255, 255, 255);
            ConnectionNamebeepTextBox.GridMode = false;
            ConnectionNamebeepTextBox.GuidID = "6a775781-9235-439e-ad07-561179b20e15";
            ConnectionNamebeepTextBox.HasError = false;
            ConnectionNamebeepTextBox.HelperText = "";
            ConnectionNamebeepTextBox.HideSelection = true;
            ConnectionNamebeepTextBox.HitAreaEventOn = false;
            ConnectionNamebeepTextBox.HitTestControl = null;
            ConnectionNamebeepTextBox.HoverBackColor = Color.WhiteSmoke;
            ConnectionNamebeepTextBox.HoverBorderColor = Color.Blue;
            ConnectionNamebeepTextBox.HoveredBackcolor = Color.WhiteSmoke;
            ConnectionNamebeepTextBox.HoverForeColor = Color.Black;
            ConnectionNamebeepTextBox.IconSize = 20;
            ConnectionNamebeepTextBox.Id = -1;
            ConnectionNamebeepTextBox.ImageAlign = ContentAlignment.MiddleLeft;
            ConnectionNamebeepTextBox.ImagePath = "";
            ConnectionNamebeepTextBox.InactiveBorderColor = Color.Gray;
            graphicsPath1.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            ConnectionNamebeepTextBox.InnerShape = graphicsPath1;
            ConnectionNamebeepTextBox.IsAcceptButton = false;
            ConnectionNamebeepTextBox.IsBorderAffectedByTheme = true;
            ConnectionNamebeepTextBox.IsCancelButton = false;
            ConnectionNamebeepTextBox.IsChild = true;
            ConnectionNamebeepTextBox.IsCustomeBorder = false;
            ConnectionNamebeepTextBox.IsDefault = false;
            ConnectionNamebeepTextBox.IsDeleted = false;
            ConnectionNamebeepTextBox.IsDirty = false;
            ConnectionNamebeepTextBox.IsEditable = true;
            ConnectionNamebeepTextBox.IsFocused = false;
          
            ConnectionNamebeepTextBox.IsFrameless = false;
            ConnectionNamebeepTextBox.IsHovered = false;
            
            ConnectionNamebeepTextBox.IsNew = false;
            ConnectionNamebeepTextBox.IsPressed = false;
           
            ConnectionNamebeepTextBox.IsReadOnly = false;
            ConnectionNamebeepTextBox.IsRequired = false;
            ConnectionNamebeepTextBox.IsRounded = true;
            ConnectionNamebeepTextBox.IsRoundedAffectedByTheme = true;
            ConnectionNamebeepTextBox.IsSelected = false;
          
            ConnectionNamebeepTextBox.IsSelectedOptionOn = false;
            ConnectionNamebeepTextBox.IsShadowAffectedByTheme = true;
            ConnectionNamebeepTextBox.IsValid = true;
            ConnectionNamebeepTextBox.IsVisible = true;
            ConnectionNamebeepTextBox.Items = (List<object>)resources.GetObject("ConnectionNamebeepTextBox.Items");
            ConnectionNamebeepTextBox.LabelText = "";
            ConnectionNamebeepTextBox.LeadingIconPath = "";
            ConnectionNamebeepTextBox.LeadingImagePath = "";
            ConnectionNamebeepTextBox.LeftoffsetForDrawingRect = 0;
            ConnectionNamebeepTextBox.LineNumberBackColor = Color.FromArgb(248, 248, 248);
            ConnectionNamebeepTextBox.LineNumberFont = new Font("Arial", 10F);
            ConnectionNamebeepTextBox.LineNumberForeColor = Color.Gray;
            ConnectionNamebeepTextBox.LinkedProperty = null;
            ConnectionNamebeepTextBox.Location = new Point(105, 85);
            ConnectionNamebeepTextBox.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            ConnectionNamebeepTextBox.MaxHitListDrawPerFrame = 0;
            ConnectionNamebeepTextBox.MaxImageSize = new Size(20, 20);
            ConnectionNamebeepTextBox.MinimumSize = new Size(0, 22);
            ConnectionNamebeepTextBox.ModernGradientType = Vis.Modules.ModernGradientType.None;
            ConnectionNamebeepTextBox.Modified = true;
            ConnectionNamebeepTextBox.Multiline = false;
            ConnectionNamebeepTextBox.Name = "ConnectionNamebeepTextBox";
            ConnectionNamebeepTextBox.OnlyCharacters = false;
            ConnectionNamebeepTextBox.OnlyDigits = false;
            ConnectionNamebeepTextBox.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            ConnectionNamebeepTextBox.ParentBackColor = Color.White;
            ConnectionNamebeepTextBox.ParentControl = null;
            ConnectionNamebeepTextBox.PasswordChar = '\0';
            ConnectionNamebeepTextBox.PlaceholderText = "Connection Name";
            ConnectionNamebeepTextBox.PlaceholderTextColor = Color.Gray;
            ConnectionNamebeepTextBox.PressedBackColor = Color.Gray;
            ConnectionNamebeepTextBox.PressedBorderColor = Color.DarkGray;
            ConnectionNamebeepTextBox.PressedForeColor = Color.White;
            ConnectionNamebeepTextBox.RadialCenter = (PointF)resources.GetObject("ConnectionNamebeepTextBox.RadialCenter");
            ConnectionNamebeepTextBox.ReadOnly = false;
            ConnectionNamebeepTextBox.RightoffsetForDrawingRect = 0;
            ConnectionNamebeepTextBox.SavedGuidID = null;
            ConnectionNamebeepTextBox.SavedID = null;
            ConnectionNamebeepTextBox.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            ConnectionNamebeepTextBox.ScrollBars = ScrollBars.Both;
            ConnectionNamebeepTextBox.SelectedBackColor = Color.White;
            ConnectionNamebeepTextBox.SelectedBorderColor = Color.Green;
            ConnectionNamebeepTextBox.SelectedForeColor = Color.Black;
            ConnectionNamebeepTextBox.SelectedValue = null;
            ConnectionNamebeepTextBox.SelectionBackColor = SystemColors.Highlight;
            ConnectionNamebeepTextBox.SelectionLength = 0;
            ConnectionNamebeepTextBox.SelectionStart = 0;
            ConnectionNamebeepTextBox.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            ConnectionNamebeepTextBox.ShadowOffset = 3;
            ConnectionNamebeepTextBox.ShadowOpacity = 0.25F;
            ConnectionNamebeepTextBox.ShowAllBorders = true;
            ConnectionNamebeepTextBox.ShowBottomBorder = false;
            ConnectionNamebeepTextBox.ShowFocusIndicator = false;
            ConnectionNamebeepTextBox.ShowLeftBorder = false;
            ConnectionNamebeepTextBox.ShowRightBorder = false;
            ConnectionNamebeepTextBox.ShowScrollbars = true;
            ConnectionNamebeepTextBox.ShowShadow = false;
            ConnectionNamebeepTextBox.ShowTopBorder = false;
            ConnectionNamebeepTextBox.Size = new Size(416, 49);
            ConnectionNamebeepTextBox.SlideFrom = Vis.Modules.SlideDirection.Left;
            ConnectionNamebeepTextBox.StaticNotMoving = false;
            ConnectionNamebeepTextBox.TabIndex = 0;
            ConnectionNamebeepTextBox.Tag = tabPage1;
           
            ConnectionNamebeepTextBox.TextAlignment = HorizontalAlignment.Left;
            ConnectionNamebeepTextBox.TextFont = new Font("Arial", 10F);
            ConnectionNamebeepTextBox.TextImageRelation = TextImageRelation.ImageBeforeText;
            ConnectionNamebeepTextBox.Theme = "DefaultType";
            ConnectionNamebeepTextBox.TimeFormat = "HH:mm:ss";
            ConnectionNamebeepTextBox.ToolTipText = null;
            ConnectionNamebeepTextBox.TopoffsetForDrawingRect = 0;
            ConnectionNamebeepTextBox.TrailingIconPath = "";
            ConnectionNamebeepTextBox.TrailingImagePath = "";
            ConnectionNamebeepTextBox.UseExternalBufferedGraphics = false;
            ConnectionNamebeepTextBox.UseGlassmorphism = false;
            ConnectionNamebeepTextBox.UseGradientBackground = false;
            ConnectionNamebeepTextBox.UseRichToolTip = true;
            ConnectionNamebeepTextBox.UseSystemPasswordChar = false;
            ConnectionNamebeepTextBox.UseThemeFont = true;
            ConnectionNamebeepTextBox.WordWrap = false;
            // 
            // DriverbeepComboBox
            // 
            DriverbeepComboBox.Anchor = AnchorStyles.None;
            DriverbeepComboBox.AnimationDuration = 500;
            DriverbeepComboBox.AnimationType = Vis.Modules.DisplayAnimationType.None;
            DriverbeepComboBox.ApplyThemeToChilds = true;
            DriverbeepComboBox.AutoDrawHitListComponents = true;
            DriverbeepComboBox.BackColor = Color.White;
            DriverbeepComboBox.BadgeBackColor = Color.FromArgb(33, 150, 243);
            DriverbeepComboBox.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            DriverbeepComboBox.BadgeForeColor = Color.White;
            DriverbeepComboBox.BadgeShape = Vis.Modules.BadgeShape.Circle;
            DriverbeepComboBox.BadgeText = "";
            DriverbeepComboBox.BlockID = null;
            DriverbeepComboBox.BorderColor = Color.FromArgb(189, 189, 189);
            DriverbeepComboBox.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            DriverbeepComboBox.BorderRadius = 3;
            DriverbeepComboBox.BorderStyle = BorderStyle.FixedSingle;
            DriverbeepComboBox.BorderThickness = 1;
            DriverbeepComboBox.BottomoffsetForDrawingRect = 0;
            DriverbeepComboBox.BoundProperty = null;
            DriverbeepComboBox.CanBeFocused = false;
            DriverbeepComboBox.CanBeHovered = true;
            DriverbeepComboBox.CanBePressed = true;
            DriverbeepComboBox.Category = Utilities.DbFieldCategory.Numeric;
     
            DriverbeepComboBox.ComponentName = "BaseControl";
            DriverbeepComboBox.DataSourceProperty = null;
            DriverbeepComboBox.DisabledBackColor = Color.FromArgb(200, 200, 200);
            DriverbeepComboBox.DisabledBorderColor = Color.LightGray;
            DriverbeepComboBox.DisabledForeColor = Color.Gray;
            //DriverbeepComboBox.DisableDpiAndScaling = false;
            DriverbeepComboBox.DrawingRect = new Rectangle(24, 8, 336, 40);
            DriverbeepComboBox.Easing = Vis.Modules.EasingType.Linear;
            DriverbeepComboBox.EnableHighQualityRendering = true;
            DriverbeepComboBox.EnableRippleEffect = false;
            DriverbeepComboBox.EnableSplashEffect = false;
            DriverbeepComboBox.ErrorColor = Color.FromArgb(211, 47, 47);
            DriverbeepComboBox.ErrorText = "";
            DriverbeepComboBox.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            DriverbeepComboBox.FieldID = null;
            DriverbeepComboBox.FilledBackgroundColor = Color.White;
            DriverbeepComboBox.FloatingLabel = true;
            DriverbeepComboBox.FocusBackColor = Color.LightYellow;
            DriverbeepComboBox.FocusBorderColor = Color.RoyalBlue;
            DriverbeepComboBox.FocusForeColor = Color.Black;
            DriverbeepComboBox.FocusIndicatorColor = Color.RoyalBlue;
            DriverbeepComboBox.Font = new Font("Arial", 10F);
            DriverbeepComboBox.ForeColor = Color.FromArgb(33, 33, 33);
            DriverbeepComboBox.Form = null;
            DriverbeepComboBox.GlassmorphismBlur = 10F;
            DriverbeepComboBox.GlassmorphismOpacity = 0.1F;
            DriverbeepComboBox.GradientAngle = 0F;
            DriverbeepComboBox.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            DriverbeepComboBox.GradientEndColor = Color.FromArgb(230, 230, 230);
            DriverbeepComboBox.GradientStartColor = Color.FromArgb(255, 255, 255);
            DriverbeepComboBox.GridMode = false;
            DriverbeepComboBox.GuidID = "84d8db30-1719-4850-8657-fd67f353ee73";
            DriverbeepComboBox.HasError = false;
            DriverbeepComboBox.HelperText = "";
            DriverbeepComboBox.HitAreaEventOn = false;
            DriverbeepComboBox.HitTestControl = null;
            DriverbeepComboBox.HoverBackColor = Color.FromArgb(232, 240, 254);
            DriverbeepComboBox.HoverBorderColor = Color.FromArgb(33, 150, 243);
            DriverbeepComboBox.HoveredBackcolor = Color.FromArgb(232, 240, 254);
            DriverbeepComboBox.HoverForeColor = Color.FromArgb(33, 33, 33);
            DriverbeepComboBox.IconSize = 20;
            DriverbeepComboBox.Id = -1;
            DriverbeepComboBox.InactiveBorderColor = Color.Gray;
            graphicsPath2.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            DriverbeepComboBox.InnerShape = graphicsPath2;
            DriverbeepComboBox.IsAcceptButton = false;
            DriverbeepComboBox.IsBorderAffectedByTheme = true;
            DriverbeepComboBox.IsCancelButton = false;
            DriverbeepComboBox.IsChild = true;
            DriverbeepComboBox.IsCustomeBorder = false;
            DriverbeepComboBox.IsDefault = false;
            DriverbeepComboBox.IsDeleted = false;
            DriverbeepComboBox.IsDirty = false;
            DriverbeepComboBox.IsEditable = true;
            DriverbeepComboBox.IsFocused = false;
         
            DriverbeepComboBox.IsFrameless = false;
            DriverbeepComboBox.IsHovered = false;
          
            DriverbeepComboBox.IsNew = false;
        
            DriverbeepComboBox.IsPressed = false;
           
            DriverbeepComboBox.IsReadOnly = false;
            DriverbeepComboBox.IsRequired = false;
            DriverbeepComboBox.IsRounded = true;
            DriverbeepComboBox.IsRoundedAffectedByTheme = true;
            DriverbeepComboBox.IsSelected = false;
           
            DriverbeepComboBox.IsSelectedOptionOn = false;
            DriverbeepComboBox.IsShadowAffectedByTheme = true;
            DriverbeepComboBox.IsValid = true;
            DriverbeepComboBox.IsVisible = true;
            DriverbeepComboBox.Items = (List<object>)resources.GetObject("DriverbeepComboBox.Items");
            DriverbeepComboBox.LabelText = "";
            DriverbeepComboBox.LeadingIconPath = "";
            DriverbeepComboBox.LeadingImagePath = "";
            DriverbeepComboBox.LeftoffsetForDrawingRect = 0;
            DriverbeepComboBox.LinkedProperty = null;
            DriverbeepComboBox.Location = new Point(120, 140);
         
            DriverbeepComboBox.MaxHitListDrawPerFrame = 0;
            DriverbeepComboBox.MinimumSize = new Size(150, 56);
            DriverbeepComboBox.ModernGradientType = Vis.Modules.ModernGradientType.None;
            DriverbeepComboBox.Name = "DriverbeepComboBox";
            DriverbeepComboBox.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            DriverbeepComboBox.ParentBackColor = Color.Empty;
            DriverbeepComboBox.ParentControl = null;
            DriverbeepComboBox.PlaceholderText = "Select an Driver...";
            DriverbeepComboBox.PressedBackColor = Color.Gray;
            DriverbeepComboBox.PressedBorderColor = Color.DarkGray;
            DriverbeepComboBox.PressedForeColor = Color.White;
            DriverbeepComboBox.RadialCenter = (PointF)resources.GetObject("DriverbeepComboBox.RadialCenter");
            DriverbeepComboBox.RightoffsetForDrawingRect = 0;
            DriverbeepComboBox.SavedGuidID = null;
            DriverbeepComboBox.SavedID = null;
            DriverbeepComboBox.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            DriverbeepComboBox.SelectedBackColor = Color.FromArgb(33, 150, 243);
            DriverbeepComboBox.SelectedBorderColor = Color.FromArgb(25, 118, 210);
            DriverbeepComboBox.SelectedForeColor = Color.White;
            DriverbeepComboBox.SelectedIndex = -1;
            DriverbeepComboBox.SelectedItem = null;
            DriverbeepComboBox.SelectedValue = null;
            DriverbeepComboBox.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            DriverbeepComboBox.ShadowOffset = 3;
            DriverbeepComboBox.ShadowOpacity = 0.25F;
            DriverbeepComboBox.ShowAllBorders = true;
            DriverbeepComboBox.ShowBottomBorder = false;
            DriverbeepComboBox.ShowFocusIndicator = false;
            DriverbeepComboBox.ShowLeftBorder = false;
            DriverbeepComboBox.ShowRightBorder = false;
            DriverbeepComboBox.ShowShadow = false;
            DriverbeepComboBox.ShowTopBorder = false;
            DriverbeepComboBox.Size = new Size(384, 56);
            DriverbeepComboBox.SlideFrom = Vis.Modules.SlideDirection.Left;
            DriverbeepComboBox.StaticNotMoving = false;
            DriverbeepComboBox.TabIndex = 2;
            DriverbeepComboBox.Tag = tabPage1;
            DriverbeepComboBox.TempBackColor = Color.Empty;
            DriverbeepComboBox.Text = "beepComboBox1";
            DriverbeepComboBox.TextFont = new Font("Arial", 10F);
            DriverbeepComboBox.Theme = "DefaultType";
            DriverbeepComboBox.ToolTipText = null;
            DriverbeepComboBox.TopoffsetForDrawingRect = 0;
            DriverbeepComboBox.TrailingIconPath = "";
            DriverbeepComboBox.TrailingImagePath = "";
            DriverbeepComboBox.UseExternalBufferedGraphics = false;
            DriverbeepComboBox.UseGlassmorphism = false;
            DriverbeepComboBox.UseGradientBackground = false;
            DriverbeepComboBox.UseRichToolTip = true;
            DriverbeepComboBox.UseThemeFont = true;
            // 
            // ConnectionStringbeepTextBox
            // 
            ConnectionStringbeepTextBox.AcceptsReturn = true;
            ConnectionStringbeepTextBox.AcceptsTab = false;
            ConnectionStringbeepTextBox.Anchor = AnchorStyles.None;
            ConnectionStringbeepTextBox.AnimationDuration = 500;
            ConnectionStringbeepTextBox.AnimationType = Vis.Modules.DisplayAnimationType.None;
            ConnectionStringbeepTextBox.ApplyThemeOnImage = false;
            ConnectionStringbeepTextBox.ApplyThemeToChilds = true;
            ConnectionStringbeepTextBox.AutoCompleteMode = AutoCompleteMode.None;
            ConnectionStringbeepTextBox.AutoCompleteSource = AutoCompleteSource.None;
            ConnectionStringbeepTextBox.AutoDrawHitListComponents = true;
            ConnectionStringbeepTextBox.BackColor = Color.White;
            ConnectionStringbeepTextBox.BadgeBackColor = Color.FromArgb(33, 150, 243);
            ConnectionStringbeepTextBox.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            ConnectionStringbeepTextBox.BadgeForeColor = Color.White;
            ConnectionStringbeepTextBox.BadgeShape = Vis.Modules.BadgeShape.Circle;
            ConnectionStringbeepTextBox.BadgeText = "";
            ConnectionStringbeepTextBox.BlockID = null;
            ConnectionStringbeepTextBox.BorderColor = Color.FromArgb(200, 200, 200);
            ConnectionStringbeepTextBox.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            ConnectionStringbeepTextBox.BorderRadius = 8;
            ConnectionStringbeepTextBox.BorderStyle = BorderStyle.FixedSingle;
            ConnectionStringbeepTextBox.BorderThickness = 1;
            ConnectionStringbeepTextBox.BottomoffsetForDrawingRect = 0;
            ConnectionStringbeepTextBox.BoundProperty = "Text";
            ConnectionStringbeepTextBox.CanBeFocused = false;
            ConnectionStringbeepTextBox.CanBeHovered = true;
            ConnectionStringbeepTextBox.CanBePressed = true;
            ConnectionStringbeepTextBox.Category = Utilities.DbFieldCategory.String;
            ConnectionStringbeepTextBox.ComponentName = "BaseControl";
            ConnectionStringbeepTextBox.CustomMask = "";
            ConnectionStringbeepTextBox.DataSourceProperty = null;
            ConnectionStringbeepTextBox.DateFormat = "MM/dd/yyyy";
            ConnectionStringbeepTextBox.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            ConnectionStringbeepTextBox.DisabledBackColor = Color.FromArgb(200, 200, 200);
            ConnectionStringbeepTextBox.DisabledBorderColor = Color.LightGray;
            ConnectionStringbeepTextBox.DisabledForeColor = Color.Gray;
            //ConnectionStringbeepTextBox.DisableDpiAndScaling = false;
            ConnectionStringbeepTextBox.DrawingRect = new Rectangle(24, 8, 336, 258);
            ConnectionStringbeepTextBox.Easing = Vis.Modules.EasingType.Linear;
            ConnectionStringbeepTextBox.EnableHighQualityRendering = true;
            ConnectionStringbeepTextBox.EnableRippleEffect = false;
            ConnectionStringbeepTextBox.EnableSplashEffect = false;
            ConnectionStringbeepTextBox.ErrorColor = Color.FromArgb(176, 0, 32);
            ConnectionStringbeepTextBox.ErrorText = "";
            ConnectionStringbeepTextBox.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            ConnectionStringbeepTextBox.FieldID = null;
            ConnectionStringbeepTextBox.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            ConnectionStringbeepTextBox.FloatingLabel = true;
            ConnectionStringbeepTextBox.FocusBackColor = Color.LightYellow;
            ConnectionStringbeepTextBox.FocusBorderColor = Color.FromArgb(0, 120, 215);
            ConnectionStringbeepTextBox.FocusForeColor = Color.Black;
            ConnectionStringbeepTextBox.FocusIndicatorColor = Color.RoyalBlue;
            ConnectionStringbeepTextBox.ForeColor = Color.Black;
            ConnectionStringbeepTextBox.Form = null;
            ConnectionStringbeepTextBox.GlassmorphismBlur = 10F;
            ConnectionStringbeepTextBox.GlassmorphismOpacity = 0.1F;
            ConnectionStringbeepTextBox.GradientAngle = 0F;
            ConnectionStringbeepTextBox.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            ConnectionStringbeepTextBox.GradientEndColor = Color.FromArgb(230, 230, 230);
            ConnectionStringbeepTextBox.GradientStartColor = Color.FromArgb(255, 255, 255);
            ConnectionStringbeepTextBox.GridMode = false;
            ConnectionStringbeepTextBox.GuidID = "6a775781-9235-439e-ad07-561179b20e15";
            ConnectionStringbeepTextBox.HasError = false;
            ConnectionStringbeepTextBox.HelperText = "";
            ConnectionStringbeepTextBox.HideSelection = true;
            ConnectionStringbeepTextBox.HitAreaEventOn = false;
            ConnectionStringbeepTextBox.HitTestControl = null;
            ConnectionStringbeepTextBox.HoverBackColor = Color.WhiteSmoke;
            ConnectionStringbeepTextBox.HoverBorderColor = Color.Blue;
            ConnectionStringbeepTextBox.HoveredBackcolor = Color.WhiteSmoke;
            ConnectionStringbeepTextBox.HoverForeColor = Color.Black;
            ConnectionStringbeepTextBox.IconSize = 20;
            ConnectionStringbeepTextBox.Id = -1;
            ConnectionStringbeepTextBox.ImageAlign = ContentAlignment.MiddleLeft;
            ConnectionStringbeepTextBox.ImagePath = "";
            ConnectionStringbeepTextBox.InactiveBorderColor = Color.Gray;
            graphicsPath3.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            ConnectionStringbeepTextBox.InnerShape = graphicsPath3;
            ConnectionStringbeepTextBox.IsAcceptButton = false;
            ConnectionStringbeepTextBox.IsBorderAffectedByTheme = true;
            ConnectionStringbeepTextBox.IsCancelButton = false;
            ConnectionStringbeepTextBox.IsChild = true;
            ConnectionStringbeepTextBox.IsCustomeBorder = false;
            ConnectionStringbeepTextBox.IsDefault = false;
            ConnectionStringbeepTextBox.IsDeleted = false;
            ConnectionStringbeepTextBox.IsDirty = false;
            ConnectionStringbeepTextBox.IsEditable = true;
            ConnectionStringbeepTextBox.IsFocused = false;
            
            ConnectionStringbeepTextBox.IsFrameless = false;
            ConnectionStringbeepTextBox.IsHovered = false;
           
            ConnectionStringbeepTextBox.IsNew = false;
            ConnectionStringbeepTextBox.IsPressed = false;
           
            ConnectionStringbeepTextBox.IsReadOnly = false;
            ConnectionStringbeepTextBox.IsRequired = false;
            ConnectionStringbeepTextBox.IsRounded = true;
            ConnectionStringbeepTextBox.IsRoundedAffectedByTheme = true;
            ConnectionStringbeepTextBox.IsSelected = false;
          
            ConnectionStringbeepTextBox.IsSelectedOptionOn = false;
            ConnectionStringbeepTextBox.IsShadowAffectedByTheme = true;
            ConnectionStringbeepTextBox.IsValid = true;
            ConnectionStringbeepTextBox.IsVisible = true;
            ConnectionStringbeepTextBox.Items = (List<object>)resources.GetObject("ConnectionStringbeepTextBox.Items");
            ConnectionStringbeepTextBox.LabelText = "";
            ConnectionStringbeepTextBox.LeadingIconPath = "";
            ConnectionStringbeepTextBox.LeadingImagePath = "";
            ConnectionStringbeepTextBox.LeftoffsetForDrawingRect = 0;
            ConnectionStringbeepTextBox.LineNumberBackColor = Color.FromArgb(248, 248, 248);
            ConnectionStringbeepTextBox.LineNumberFont = new Font("Arial", 10F);
            ConnectionStringbeepTextBox.LineNumberForeColor = Color.Gray;
            ConnectionStringbeepTextBox.LinkedProperty = null;
            ConnectionStringbeepTextBox.Location = new Point(120, 277);
            ConnectionStringbeepTextBox.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            ConnectionStringbeepTextBox.MaxHitListDrawPerFrame = 0;
            ConnectionStringbeepTextBox.MaxImageSize = new Size(20, 20);
            ConnectionStringbeepTextBox.MinimumSize = new Size(0, 22);
            ConnectionStringbeepTextBox.ModernGradientType = Vis.Modules.ModernGradientType.None;
            ConnectionStringbeepTextBox.Modified = true;
            ConnectionStringbeepTextBox.Multiline = true;
            ConnectionStringbeepTextBox.Name = "ConnectionStringbeepTextBox";
            ConnectionStringbeepTextBox.OnlyCharacters = false;
            ConnectionStringbeepTextBox.OnlyDigits = false;
            ConnectionStringbeepTextBox.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            ConnectionStringbeepTextBox.ParentBackColor = Color.White;
            ConnectionStringbeepTextBox.ParentControl = null;
            ConnectionStringbeepTextBox.PasswordChar = '\0';
            ConnectionStringbeepTextBox.PlaceholderText = "Connection String";
            ConnectionStringbeepTextBox.PlaceholderTextColor = Color.Gray;
            ConnectionStringbeepTextBox.PressedBackColor = Color.Gray;
            ConnectionStringbeepTextBox.PressedBorderColor = Color.DarkGray;
            ConnectionStringbeepTextBox.PressedForeColor = Color.White;
            ConnectionStringbeepTextBox.RadialCenter = (PointF)resources.GetObject("ConnectionStringbeepTextBox.RadialCenter");
            ConnectionStringbeepTextBox.ReadOnly = false;
            ConnectionStringbeepTextBox.RightoffsetForDrawingRect = 0;
            ConnectionStringbeepTextBox.SavedGuidID = null;
            ConnectionStringbeepTextBox.SavedID = null;
            ConnectionStringbeepTextBox.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            ConnectionStringbeepTextBox.ScrollBars = ScrollBars.Both;
            ConnectionStringbeepTextBox.SelectedBackColor = Color.White;
            ConnectionStringbeepTextBox.SelectedBorderColor = Color.Green;
            ConnectionStringbeepTextBox.SelectedForeColor = Color.Black;
            ConnectionStringbeepTextBox.SelectedValue = null;
            ConnectionStringbeepTextBox.SelectionBackColor = SystemColors.Highlight;
            ConnectionStringbeepTextBox.SelectionLength = 0;
            ConnectionStringbeepTextBox.SelectionStart = 0;
            ConnectionStringbeepTextBox.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            ConnectionStringbeepTextBox.ShadowOffset = 3;
            ConnectionStringbeepTextBox.ShadowOpacity = 0.25F;
            ConnectionStringbeepTextBox.ShowAllBorders = true;
            ConnectionStringbeepTextBox.ShowBottomBorder = false;
            ConnectionStringbeepTextBox.ShowFocusIndicator = false;
            ConnectionStringbeepTextBox.ShowLeftBorder = false;
            ConnectionStringbeepTextBox.ShowRightBorder = false;
            ConnectionStringbeepTextBox.ShowScrollbars = true;
            ConnectionStringbeepTextBox.ShowShadow = false;
            ConnectionStringbeepTextBox.ShowTopBorder = false;
            ConnectionStringbeepTextBox.Size = new Size(384, 274);
            ConnectionStringbeepTextBox.SlideFrom = Vis.Modules.SlideDirection.Left;
            ConnectionStringbeepTextBox.StaticNotMoving = false;
            ConnectionStringbeepTextBox.TabIndex = 5;
            ConnectionStringbeepTextBox.Tag = tabPage1;
          
            ConnectionStringbeepTextBox.TextAlignment = HorizontalAlignment.Left;
            ConnectionStringbeepTextBox.TextFont = new Font("Arial", 10F);
            ConnectionStringbeepTextBox.TextImageRelation = TextImageRelation.ImageBeforeText;
            ConnectionStringbeepTextBox.Theme = "DefaultType";
            ConnectionStringbeepTextBox.TimeFormat = "HH:mm:ss";
            ConnectionStringbeepTextBox.ToolTipText = null;
            ConnectionStringbeepTextBox.TopoffsetForDrawingRect = 0;
            ConnectionStringbeepTextBox.TrailingIconPath = "";
            ConnectionStringbeepTextBox.TrailingImagePath = "";
            ConnectionStringbeepTextBox.UseExternalBufferedGraphics = false;
            ConnectionStringbeepTextBox.UseGlassmorphism = false;
            ConnectionStringbeepTextBox.UseGradientBackground = false;
            ConnectionStringbeepTextBox.UseRichToolTip = true;
            ConnectionStringbeepTextBox.UseSystemPasswordChar = false;
            ConnectionStringbeepTextBox.UseThemeFont = true;
            ConnectionStringbeepTextBox.WordWrap = false;
            // 
            // DriverVersionbeepComboBox
            // 
            DriverVersionbeepComboBox.Anchor = AnchorStyles.None;
            DriverVersionbeepComboBox.AnimationDuration = 500;
            DriverVersionbeepComboBox.AnimationType = Vis.Modules.DisplayAnimationType.None;
            DriverVersionbeepComboBox.ApplyThemeToChilds = true;
            DriverVersionbeepComboBox.AutoDrawHitListComponents = true;
            DriverVersionbeepComboBox.BackColor = Color.White;
            DriverVersionbeepComboBox.BadgeBackColor = Color.FromArgb(33, 150, 243);
            DriverVersionbeepComboBox.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            DriverVersionbeepComboBox.BadgeForeColor = Color.White;
            DriverVersionbeepComboBox.BadgeShape = Vis.Modules.BadgeShape.Circle;
            DriverVersionbeepComboBox.BadgeText = "";
            DriverVersionbeepComboBox.BlockID = null;
            DriverVersionbeepComboBox.BorderColor = Color.FromArgb(189, 189, 189);
            DriverVersionbeepComboBox.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            DriverVersionbeepComboBox.BorderRadius = 3;
            DriverVersionbeepComboBox.BorderStyle = BorderStyle.FixedSingle;
            DriverVersionbeepComboBox.BorderThickness = 1;
            DriverVersionbeepComboBox.BottomoffsetForDrawingRect = 0;
            DriverVersionbeepComboBox.BoundProperty = null;
            DriverVersionbeepComboBox.CanBeFocused = false;
            DriverVersionbeepComboBox.CanBeHovered = true;
            DriverVersionbeepComboBox.CanBePressed = true;
            DriverVersionbeepComboBox.Category = Utilities.DbFieldCategory.Numeric;
          
            DriverVersionbeepComboBox.ComponentName = "BaseControl";
            DriverVersionbeepComboBox.DataSourceProperty = null;
            DriverVersionbeepComboBox.DisabledBackColor = Color.FromArgb(200, 200, 200);
            DriverVersionbeepComboBox.DisabledBorderColor = Color.LightGray;
            DriverVersionbeepComboBox.DisabledForeColor = Color.Gray;
            //DriverVersionbeepComboBox.DisableDpiAndScaling = false;
            DriverVersionbeepComboBox.DrawingRect = new Rectangle(24, 8, 336, 40);
            DriverVersionbeepComboBox.Easing = Vis.Modules.EasingType.Linear;
            DriverVersionbeepComboBox.EnableHighQualityRendering = true;
            DriverVersionbeepComboBox.EnableRippleEffect = false;
            DriverVersionbeepComboBox.EnableSplashEffect = false;
            DriverVersionbeepComboBox.ErrorColor = Color.FromArgb(211, 47, 47);
            DriverVersionbeepComboBox.ErrorText = "";
            DriverVersionbeepComboBox.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            DriverVersionbeepComboBox.FieldID = null;
            DriverVersionbeepComboBox.FilledBackgroundColor = Color.White;
            DriverVersionbeepComboBox.FloatingLabel = true;
            DriverVersionbeepComboBox.FocusBackColor = Color.LightYellow;
            DriverVersionbeepComboBox.FocusBorderColor = Color.RoyalBlue;
            DriverVersionbeepComboBox.FocusForeColor = Color.Black;
            DriverVersionbeepComboBox.FocusIndicatorColor = Color.RoyalBlue;
            DriverVersionbeepComboBox.Font = new Font("Arial", 10F);
            DriverVersionbeepComboBox.ForeColor = Color.FromArgb(33, 33, 33);
            DriverVersionbeepComboBox.Form = null;
            DriverVersionbeepComboBox.GlassmorphismBlur = 10F;
            DriverVersionbeepComboBox.GlassmorphismOpacity = 0.1F;
            DriverVersionbeepComboBox.GradientAngle = 0F;
            DriverVersionbeepComboBox.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            DriverVersionbeepComboBox.GradientEndColor = Color.FromArgb(230, 230, 230);
            DriverVersionbeepComboBox.GradientStartColor = Color.FromArgb(255, 255, 255);
            DriverVersionbeepComboBox.GridMode = false;
            DriverVersionbeepComboBox.GuidID = "84d8db30-1719-4850-8657-fd67f353ee73";
            DriverVersionbeepComboBox.HasError = false;
            DriverVersionbeepComboBox.HelperText = "";
            DriverVersionbeepComboBox.HitAreaEventOn = false;
            DriverVersionbeepComboBox.HitTestControl = null;
            DriverVersionbeepComboBox.HoverBackColor = Color.FromArgb(232, 240, 254);
            DriverVersionbeepComboBox.HoverBorderColor = Color.FromArgb(33, 150, 243);
            DriverVersionbeepComboBox.HoveredBackcolor = Color.FromArgb(232, 240, 254);
            DriverVersionbeepComboBox.HoverForeColor = Color.FromArgb(33, 33, 33);
            DriverVersionbeepComboBox.IconSize = 20;
            DriverVersionbeepComboBox.Id = -1;
            DriverVersionbeepComboBox.InactiveBorderColor = Color.Gray;
            graphicsPath4.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            DriverVersionbeepComboBox.InnerShape = graphicsPath4;
            DriverVersionbeepComboBox.IsAcceptButton = false;
            DriverVersionbeepComboBox.IsBorderAffectedByTheme = true;
            DriverVersionbeepComboBox.IsCancelButton = false;
            DriverVersionbeepComboBox.IsChild = true;
            DriverVersionbeepComboBox.IsCustomeBorder = false;
            DriverVersionbeepComboBox.IsDefault = false;
            DriverVersionbeepComboBox.IsDeleted = false;
            DriverVersionbeepComboBox.IsDirty = false;
            DriverVersionbeepComboBox.IsEditable = true;
            DriverVersionbeepComboBox.IsFocused = false;
           
            DriverVersionbeepComboBox.IsFrameless = false;
            DriverVersionbeepComboBox.IsHovered = false;
         
            DriverVersionbeepComboBox.IsNew = false;
          
            DriverVersionbeepComboBox.IsPressed = false;
            
            DriverVersionbeepComboBox.IsReadOnly = false;
            DriverVersionbeepComboBox.IsRequired = false;
            DriverVersionbeepComboBox.IsRounded = true;
            DriverVersionbeepComboBox.IsRoundedAffectedByTheme = true;
            DriverVersionbeepComboBox.IsSelected = false;
           
            DriverVersionbeepComboBox.IsSelectedOptionOn = false;
            DriverVersionbeepComboBox.IsShadowAffectedByTheme = true;
            DriverVersionbeepComboBox.IsValid = true;
            DriverVersionbeepComboBox.IsVisible = true;
            DriverVersionbeepComboBox.Items = (List<object>)resources.GetObject("DriverVersionbeepComboBox.Items");
            DriverVersionbeepComboBox.LabelText = "";
            DriverVersionbeepComboBox.LeadingIconPath = "";
            DriverVersionbeepComboBox.LeadingImagePath = "";
            DriverVersionbeepComboBox.LeftoffsetForDrawingRect = 0;
            DriverVersionbeepComboBox.LinkedProperty = null;
            DriverVersionbeepComboBox.Location = new Point(120, 215);
            
         
            DriverVersionbeepComboBox.MaxHitListDrawPerFrame = 0;
            DriverVersionbeepComboBox.MinimumSize = new Size(150, 56);
            DriverVersionbeepComboBox.ModernGradientType = Vis.Modules.ModernGradientType.None;
            DriverVersionbeepComboBox.Name = "DriverVersionbeepComboBox";
            DriverVersionbeepComboBox.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            DriverVersionbeepComboBox.ParentBackColor = Color.Empty;
            DriverVersionbeepComboBox.ParentControl = null;
            DriverVersionbeepComboBox.PlaceholderText = "Select an Version...";
            DriverVersionbeepComboBox.PressedBackColor = Color.Gray;
            DriverVersionbeepComboBox.PressedBorderColor = Color.DarkGray;
            DriverVersionbeepComboBox.PressedForeColor = Color.White;
            DriverVersionbeepComboBox.RadialCenter = (PointF)resources.GetObject("DriverVersionbeepComboBox.RadialCenter");
            DriverVersionbeepComboBox.RightoffsetForDrawingRect = 0;
            DriverVersionbeepComboBox.SavedGuidID = null;
            DriverVersionbeepComboBox.SavedID = null;
            DriverVersionbeepComboBox.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            DriverVersionbeepComboBox.SelectedBackColor = Color.FromArgb(33, 150, 243);
            DriverVersionbeepComboBox.SelectedBorderColor = Color.FromArgb(25, 118, 210);
            DriverVersionbeepComboBox.SelectedForeColor = Color.White;
            DriverVersionbeepComboBox.SelectedIndex = -1;
            DriverVersionbeepComboBox.SelectedItem = null;
            DriverVersionbeepComboBox.SelectedValue = null;
            DriverVersionbeepComboBox.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            DriverVersionbeepComboBox.ShadowOffset = 3;
            DriverVersionbeepComboBox.ShadowOpacity = 0.25F;
            DriverVersionbeepComboBox.ShowAllBorders = true;
            DriverVersionbeepComboBox.ShowBottomBorder = false;
            DriverVersionbeepComboBox.ShowFocusIndicator = false;
            DriverVersionbeepComboBox.ShowLeftBorder = false;
            DriverVersionbeepComboBox.ShowRightBorder = false;
            DriverVersionbeepComboBox.ShowShadow = false;
            DriverVersionbeepComboBox.ShowTopBorder = false;
            DriverVersionbeepComboBox.Size = new Size(384, 56);
            DriverVersionbeepComboBox.SlideFrom = Vis.Modules.SlideDirection.Left;
            DriverVersionbeepComboBox.StaticNotMoving = false;
            DriverVersionbeepComboBox.TabIndex = 3;
            DriverVersionbeepComboBox.Tag = tabPage1;
            DriverVersionbeepComboBox.TempBackColor = Color.Empty;
            DriverVersionbeepComboBox.TextFont = new Font("Arial", 10F);
            DriverVersionbeepComboBox.Theme = "DefaultType";
            DriverVersionbeepComboBox.ToolTipText = null;
            DriverVersionbeepComboBox.TopoffsetForDrawingRect = 0;
            DriverVersionbeepComboBox.TrailingIconPath = "";
            DriverVersionbeepComboBox.TrailingImagePath = "";
            DriverVersionbeepComboBox.UseExternalBufferedGraphics = false;
            DriverVersionbeepComboBox.UseGlassmorphism = false;
            DriverVersionbeepComboBox.UseGradientBackground = false;
            DriverVersionbeepComboBox.UseRichToolTip = true;
            DriverVersionbeepComboBox.UseThemeFont = true;
            // 
            // CancelbeepButton
            // 
            CancelbeepButton.Anchor = AnchorStyles.None;
            CancelbeepButton.AnimationDuration = 500;
            CancelbeepButton.AnimationType = Vis.Modules.DisplayAnimationType.None;
            CancelbeepButton.ApplyThemeOnImage = false;
            CancelbeepButton.ApplyThemeToChilds = true;
            CancelbeepButton.AutoDrawHitListComponents = true;
            CancelbeepButton.AutoSizeContent = false;
            CancelbeepButton.BackColor = Color.White;
            CancelbeepButton.BadgeBackColor = Color.Red;
            CancelbeepButton.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            CancelbeepButton.BadgeForeColor = Color.White;
            CancelbeepButton.BadgeShape = Vis.Modules.BadgeShape.Circle;
            CancelbeepButton.BadgeText = "";
            CancelbeepButton.BlockID = null;
            CancelbeepButton.BorderColor = Color.FromArgb(33, 150, 243);
            CancelbeepButton.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            CancelbeepButton.BorderRadius = 8;
            CancelbeepButton.BorderSize = 1;
            CancelbeepButton.BorderStyle = BorderStyle.FixedSingle;
            CancelbeepButton.BorderThickness = 1;
            CancelbeepButton.BottomoffsetForDrawingRect = 0;
            CancelbeepButton.BoundProperty = null;
            CancelbeepButton.ButtonErrorText = "";
            CancelbeepButton.ButtonHasError = false;
            CancelbeepButton.ButtonHelperText = "";
            CancelbeepButton.ButtonLabel = "";
            CancelbeepButton.ButtonMinSize = new Size(32, 32);
            CancelbeepButton.ButtonType = Vis.Modules.ButtonType.Normal;
            CancelbeepButton.CanBeFocused = true;
            CancelbeepButton.CanBeHovered = true;
            CancelbeepButton.CanBePressed = true;
            CancelbeepButton.Category = Utilities.DbFieldCategory.Boolean;
            CancelbeepButton.ComponentName = "BaseControl";
            CancelbeepButton.DataSourceProperty = null;
            CancelbeepButton.DisabledBackColor = Color.FromArgb(200, 200, 200);
            CancelbeepButton.DisabledBorderColor = Color.Gray;
            CancelbeepButton.DisabledForeColor = Color.Gray;
            //CancelbeepButton.DisableDpiAndScaling = false;
            CancelbeepButton.DrawingRect = new Rectangle(24, 8, 82, 44);
            CancelbeepButton.Easing = Vis.Modules.EasingType.Linear;
        
            CancelbeepButton.EnableHighQualityRendering = true;
            CancelbeepButton.EnableRippleEffect = false;
            CancelbeepButton.EnableSplashEffect = false;
            CancelbeepButton.ErrorColor = Color.FromArgb(176, 0, 32);
            CancelbeepButton.ErrorText = "";
            CancelbeepButton.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            CancelbeepButton.FieldID = null;
            CancelbeepButton.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            CancelbeepButton.FloatingLabel = true;
            CancelbeepButton.FocusBackColor = Color.FromArgb(25, 118, 210);
            CancelbeepButton.FocusBorderColor = Color.RoyalBlue;
            CancelbeepButton.FocusForeColor = Color.White;
            CancelbeepButton.FocusIndicatorColor = Color.RoyalBlue;
            CancelbeepButton.Font = new Font("Arial", 15F);
            CancelbeepButton.ForeColor = Color.FromArgb(33, 150, 243);
            CancelbeepButton.Form = null;
            CancelbeepButton.GlassmorphismBlur = 10F;
            CancelbeepButton.GlassmorphismOpacity = 0.1F;
            CancelbeepButton.GradientAngle = 0F;
            CancelbeepButton.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            CancelbeepButton.GradientEndColor = Color.Gray;
            CancelbeepButton.GradientStartColor = Color.LightGray;
            CancelbeepButton.GridMode = false;
            CancelbeepButton.GuidID = "2607c012-f65e-4e44-be59-66fe1d9f6dcd";
            CancelbeepButton.HasError = false;
            CancelbeepButton.HelperText = "";
            CancelbeepButton.HideText = false;
            CancelbeepButton.HitAreaEventOn = false;
            CancelbeepButton.HitTestControl = null;
            CancelbeepButton.HoverBackColor = Color.FromArgb(227, 242, 253);
            CancelbeepButton.HoverBorderColor = Color.Blue;
            CancelbeepButton.HoveredBackcolor = Color.FromArgb(227, 242, 253);
            CancelbeepButton.HoverForeColor = Color.FromArgb(33, 150, 243);
            CancelbeepButton.IconSize = 20;
            CancelbeepButton.Id = -1;
            CancelbeepButton.Image = null;
            CancelbeepButton.ImageAlign = ContentAlignment.MiddleLeft;
            CancelbeepButton.ImageClicked = null;
            CancelbeepButton.ImageEmbededin = Vis.Modules.ImageEmbededin.Button;
            CancelbeepButton.ImagePath = null;
            CancelbeepButton.InactiveBorderColor = Color.Gray;
            graphicsPath5.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            CancelbeepButton.InnerShape = graphicsPath5;
            CancelbeepButton.IsAcceptButton = false;
            CancelbeepButton.IsBorderAffectedByTheme = true;
            CancelbeepButton.IsCancelButton = false;
            CancelbeepButton.IsChild = false;
            CancelbeepButton.IsColorFromTheme = true;
            CancelbeepButton.IsCustomeBorder = false;
            CancelbeepButton.IsDefault = false;
            CancelbeepButton.IsDeleted = false;
            CancelbeepButton.IsDirty = false;
            CancelbeepButton.IsEditable = true;
            CancelbeepButton.IsFocused = false;
           
            CancelbeepButton.IsFrameless = false;
            CancelbeepButton.IsHovered = false;
           
            CancelbeepButton.IsNew = false;
            CancelbeepButton.IsPopupOpen = false;
            CancelbeepButton.IsPressed = false;
           
            CancelbeepButton.IsReadOnly = false;
            CancelbeepButton.IsRequired = false;
            CancelbeepButton.IsRounded = true;
            CancelbeepButton.IsRoundedAffectedByTheme = true;
            CancelbeepButton.IsSelected = false;
           
            CancelbeepButton.IsSelectedOptionOn = false;
            CancelbeepButton.IsShadowAffectedByTheme = true;
            CancelbeepButton.IsSideMenuChild = false;
            CancelbeepButton.IsStillButton = false;
            CancelbeepButton.IsValid = true;
            CancelbeepButton.IsVisible = true;
            CancelbeepButton.Items = (List<object>)resources.GetObject("CancelbeepButton.Items");
            CancelbeepButton.LabelText = "";
            CancelbeepButton.LeadingIconPath = "";
            CancelbeepButton.LeadingImagePath = "";
            CancelbeepButton.LeftoffsetForDrawingRect = 0;
            CancelbeepButton.LinkedProperty = null;
            CancelbeepButton.Location = new Point(90, 652);
            CancelbeepButton.Margin = new Padding(0);
            CancelbeepButton.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Outlined;
            CancelbeepButton.MaterialPreserveContentArea = true;
            CancelbeepButton.MaxHitListDrawPerFrame = 0;
            CancelbeepButton.MaxImageSize = new Size(32, 32);
            CancelbeepButton.ModernGradientType = Vis.Modules.ModernGradientType.None;
            CancelbeepButton.Name = "CancelbeepButton";
            CancelbeepButton.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            CancelbeepButton.ParentBackColor = Color.Empty;
            CancelbeepButton.ParentControl = null;
            CancelbeepButton.PopPosition = Vis.Modules.BeepPopupFormPosition.Bottom;
            CancelbeepButton.PopupListForm = null;
            CancelbeepButton.PopupMode = false;
            CancelbeepButton.PressedBackColor = Color.FromArgb(21, 101, 192);
            CancelbeepButton.PressedBorderColor = Color.DarkGray;
            CancelbeepButton.PressedForeColor = Color.White;
            CancelbeepButton.RadialCenter = (PointF)resources.GetObject("CancelbeepButton.RadialCenter");
            CancelbeepButton.RightoffsetForDrawingRect = 0;
            CancelbeepButton.SavedGuidID = null;
            CancelbeepButton.SavedID = null;
            CancelbeepButton.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            CancelbeepButton.SelectedBackColor = Color.FromArgb(25, 118, 210);
            CancelbeepButton.SelectedBorderColor = Color.Green;
            CancelbeepButton.SelectedForeColor = Color.White;
            CancelbeepButton.SelectedIndex = -1;
            CancelbeepButton.SelectedItem = null;
            CancelbeepButton.SelectedValue = null;
            CancelbeepButton.ShadowColor = Color.Black;
            CancelbeepButton.ShadowOffset = 3;
            CancelbeepButton.ShadowOpacity = 0.25F;
            CancelbeepButton.ShowAllBorders = false;
            CancelbeepButton.ShowBottomBorder = false;
            CancelbeepButton.ShowFocusIndicator = false;
            CancelbeepButton.ShowLeftBorder = false;
            CancelbeepButton.ShowRightBorder = false;
            CancelbeepButton.ShowShadow = false;
            CancelbeepButton.ShowTopBorder = false;
            CancelbeepButton.Size = new Size(130, 60);
            CancelbeepButton.SlideFrom = Vis.Modules.SlideDirection.Left;
            CancelbeepButton.SplashColor = Color.Gray;
            CancelbeepButton.StandardImages = (List<Controls.Models.SimpleItem>)resources.GetObject("CancelbeepButton.StandardImages");
            CancelbeepButton.StaticNotMoving = false;
          
            CancelbeepButton.TabIndex = 7;
            CancelbeepButton.Tag = beepPanel1;
            CancelbeepButton.TempBackColor = Color.Empty;
            CancelbeepButton.Text = "Cancel";
            CancelbeepButton.TextAlign = ContentAlignment.MiddleCenter;
            CancelbeepButton.TextFont = new Font("Arial", 15F);
            CancelbeepButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            CancelbeepButton.Theme = "DefaultType";
            CancelbeepButton.ToolTipText = null;
            CancelbeepButton.TopoffsetForDrawingRect = 0;
            CancelbeepButton.TrailingIconPath = "";
            CancelbeepButton.TrailingImagePath = "";
            CancelbeepButton.UseExternalBufferedGraphics = false;
            CancelbeepButton.UseGlassmorphism = false;
            CancelbeepButton.UseGradientBackground = false;
            CancelbeepButton.UseRichToolTip = true;
            CancelbeepButton.UseScaledFont = false;
            CancelbeepButton.UseThemeFont = true;
            // 
            // SavebeepButton
            // 
            SavebeepButton.Anchor = AnchorStyles.None;
            SavebeepButton.AnimationDuration = 500;
            SavebeepButton.AnimationType = Vis.Modules.DisplayAnimationType.None;
            SavebeepButton.ApplyThemeOnImage = false;
            SavebeepButton.ApplyThemeToChilds = true;
            SavebeepButton.AutoDrawHitListComponents = true;
            SavebeepButton.AutoSizeContent = false;
            SavebeepButton.BackColor = Color.White;
            SavebeepButton.BadgeBackColor = Color.Red;
            SavebeepButton.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            SavebeepButton.BadgeForeColor = Color.White;
            SavebeepButton.BadgeShape = Vis.Modules.BadgeShape.Circle;
            SavebeepButton.BadgeText = "";
            SavebeepButton.BlockID = null;
            SavebeepButton.BorderColor = Color.FromArgb(33, 150, 243);
            SavebeepButton.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            SavebeepButton.BorderRadius = 8;
            SavebeepButton.BorderSize = 1;
            SavebeepButton.BorderStyle = BorderStyle.FixedSingle;
            SavebeepButton.BorderThickness = 1;
            SavebeepButton.BottomoffsetForDrawingRect = 0;
            SavebeepButton.BoundProperty = null;
            SavebeepButton.ButtonErrorText = "";
            SavebeepButton.ButtonHasError = false;
            SavebeepButton.ButtonHelperText = "";
            SavebeepButton.ButtonLabel = "";
            SavebeepButton.ButtonMinSize = new Size(32, 32);
            SavebeepButton.ButtonType = Vis.Modules.ButtonType.Normal;
            SavebeepButton.CanBeFocused = true;
            SavebeepButton.CanBeHovered = true;
            SavebeepButton.CanBePressed = true;
            SavebeepButton.Category = Utilities.DbFieldCategory.Boolean;
            SavebeepButton.ComponentName = "BaseControl";
            SavebeepButton.DataSourceProperty = null;
            SavebeepButton.DisabledBackColor = Color.FromArgb(200, 200, 200);
            SavebeepButton.DisabledBorderColor = Color.Gray;
            SavebeepButton.DisabledForeColor = Color.Gray;
            //SavebeepButton.DisableDpiAndScaling = false;
            SavebeepButton.DrawingRect = new Rectangle(24, 8, 82, 44);
            SavebeepButton.Easing = Vis.Modules.EasingType.Linear;
          
            SavebeepButton.EnableHighQualityRendering = true;
            SavebeepButton.EnableRippleEffect = false;
            SavebeepButton.EnableSplashEffect = false;
            SavebeepButton.ErrorColor = Color.FromArgb(176, 0, 32);
            SavebeepButton.ErrorText = "";
            SavebeepButton.ExternalDrawingLayer = Winform.Controls.Models.DrawingLayer.AfterAll;
            SavebeepButton.FieldID = null;
            SavebeepButton.FilledBackgroundColor = Color.FromArgb(245, 245, 245);
            SavebeepButton.FloatingLabel = true;
            SavebeepButton.FocusBackColor = Color.FromArgb(25, 118, 210);
            SavebeepButton.FocusBorderColor = Color.RoyalBlue;
            SavebeepButton.FocusForeColor = Color.White;
            SavebeepButton.FocusIndicatorColor = Color.RoyalBlue;
            SavebeepButton.Font = new Font("Arial", 15F);
            SavebeepButton.ForeColor = Color.FromArgb(33, 150, 243);
            SavebeepButton.Form = null;
            SavebeepButton.GlassmorphismBlur = 10F;
            SavebeepButton.GlassmorphismOpacity = 0.1F;
            SavebeepButton.GradientAngle = 0F;
            SavebeepButton.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            SavebeepButton.GradientEndColor = Color.Gray;
            SavebeepButton.GradientStartColor = Color.LightGray;
            SavebeepButton.GridMode = false;
            SavebeepButton.GuidID = "2607c012-f65e-4e44-be59-66fe1d9f6dcd";
            SavebeepButton.HasError = false;
            SavebeepButton.HelperText = "";
            SavebeepButton.HideText = false;
            SavebeepButton.HitAreaEventOn = false;
            SavebeepButton.HitTestControl = null;
            SavebeepButton.HoverBackColor = Color.FromArgb(227, 242, 253);
            SavebeepButton.HoverBorderColor = Color.Blue;
            SavebeepButton.HoveredBackcolor = Color.FromArgb(227, 242, 253);
            SavebeepButton.HoverForeColor = Color.FromArgb(33, 150, 243);
            SavebeepButton.IconSize = 20;
            SavebeepButton.Id = -1;
            SavebeepButton.Image = null;
            SavebeepButton.ImageAlign = ContentAlignment.MiddleLeft;
            SavebeepButton.ImageClicked = null;
            SavebeepButton.ImageEmbededin = Vis.Modules.ImageEmbededin.Button;
            SavebeepButton.ImagePath = null;
            SavebeepButton.InactiveBorderColor = Color.Gray;
            graphicsPath6.FillMode = System.Drawing.Drawing2D.FillMode.Alternate;
            SavebeepButton.InnerShape = graphicsPath6;
            SavebeepButton.IsAcceptButton = false;
            SavebeepButton.IsBorderAffectedByTheme = true;
            SavebeepButton.IsCancelButton = false;
            SavebeepButton.IsChild = false;
            SavebeepButton.IsColorFromTheme = true;
            SavebeepButton.IsCustomeBorder = false;
            SavebeepButton.IsDefault = false;
            SavebeepButton.IsDeleted = false;
            SavebeepButton.IsDirty = false;
            SavebeepButton.IsEditable = true;
            SavebeepButton.IsFocused = false;
         
            SavebeepButton.IsFrameless = false;
            SavebeepButton.IsHovered = false;
        
            SavebeepButton.IsNew = false;
            SavebeepButton.IsPopupOpen = false;
            SavebeepButton.IsPressed = false;
           
            SavebeepButton.IsReadOnly = false;
            SavebeepButton.IsRequired = false;
            SavebeepButton.IsRounded = true;
            SavebeepButton.IsRoundedAffectedByTheme = true;
            SavebeepButton.IsSelected = false;
           
            SavebeepButton.IsSelectedOptionOn = false;
            SavebeepButton.IsShadowAffectedByTheme = true;
            SavebeepButton.IsSideMenuChild = false;
            SavebeepButton.IsStillButton = false;
            SavebeepButton.IsValid = true;
            SavebeepButton.IsVisible = true;
            SavebeepButton.Items = (List<object>)resources.GetObject("SavebeepButton.Items");
            SavebeepButton.LabelText = "";
            SavebeepButton.LeadingIconPath = "";
            SavebeepButton.LeadingImagePath = "";
            SavebeepButton.LeftoffsetForDrawingRect = 0;
            SavebeepButton.LinkedProperty = null;
            SavebeepButton.Location = new Point(400, 652);
            SavebeepButton.Margin = new Padding(0);
            SavebeepButton.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Outlined;
            SavebeepButton.MaterialPreserveContentArea = true;
            SavebeepButton.MaxHitListDrawPerFrame = 0;
            SavebeepButton.MaxImageSize = new Size(32, 32);
            SavebeepButton.ModernGradientType = Vis.Modules.ModernGradientType.None;
            SavebeepButton.Name = "SavebeepButton";
            SavebeepButton.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            SavebeepButton.ParentBackColor = Color.Empty;
            SavebeepButton.ParentControl = null;
            SavebeepButton.PopPosition = Vis.Modules.BeepPopupFormPosition.Bottom;
            SavebeepButton.PopupListForm = null;
            SavebeepButton.PopupMode = false;
            SavebeepButton.PressedBackColor = Color.FromArgb(21, 101, 192);
            SavebeepButton.PressedBorderColor = Color.DarkGray;
            SavebeepButton.PressedForeColor = Color.White;
            SavebeepButton.RadialCenter = (PointF)resources.GetObject("SavebeepButton.RadialCenter");
            SavebeepButton.RightoffsetForDrawingRect = 0;
            SavebeepButton.SavedGuidID = null;
            SavebeepButton.SavedID = null;
            SavebeepButton.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            SavebeepButton.SelectedBackColor = Color.FromArgb(25, 118, 210);
            SavebeepButton.SelectedBorderColor = Color.Green;
            SavebeepButton.SelectedForeColor = Color.White;
            SavebeepButton.SelectedIndex = -1;
            SavebeepButton.SelectedItem = null;
            SavebeepButton.SelectedValue = null;
            SavebeepButton.ShadowColor = Color.Black;
            SavebeepButton.ShadowOffset = 3;
            SavebeepButton.ShadowOpacity = 0.25F;
            SavebeepButton.ShowAllBorders = false;
            SavebeepButton.ShowBottomBorder = false;
            SavebeepButton.ShowFocusIndicator = false;
            SavebeepButton.ShowLeftBorder = false;
            SavebeepButton.ShowRightBorder = false;
            SavebeepButton.ShowShadow = false;
            SavebeepButton.ShowTopBorder = false;
            SavebeepButton.Size = new Size(130, 60);
            SavebeepButton.SlideFrom = Vis.Modules.SlideDirection.Left;
            SavebeepButton.SplashColor = Color.Gray;
            SavebeepButton.StandardImages = (List<Controls.Models.SimpleItem>)resources.GetObject("SavebeepButton.StandardImages");
            SavebeepButton.StaticNotMoving = false;
           
            SavebeepButton.TabIndex = 6;
            SavebeepButton.Tag = beepPanel1;
            SavebeepButton.TempBackColor = Color.Empty;
            SavebeepButton.Text = "Save";
            SavebeepButton.TextAlign = ContentAlignment.MiddleCenter;
            SavebeepButton.TextFont = new Font("Arial", 15F);
            SavebeepButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            SavebeepButton.Theme = "DefaultType";
            SavebeepButton.ToolTipText = null;
            SavebeepButton.TopoffsetForDrawingRect = 0;
            SavebeepButton.TrailingIconPath = "";
            SavebeepButton.TrailingImagePath = "";
            SavebeepButton.UseExternalBufferedGraphics = false;
            SavebeepButton.UseGlassmorphism = false;
            SavebeepButton.UseGradientBackground = false;
            SavebeepButton.UseRichToolTip = true;
            SavebeepButton.UseScaledFont = false;
            SavebeepButton.UseThemeFont = true;
            // 
            // uc_DataConnectionBase
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Name = "uc_DataConnectionBase";
            Size = new Size(636, 723);
            //MainTemplatePanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dataConnectionViewModelBindingSource).EndInit();
            beepPanel1.ResumeLayout(false);
            beepTabs1.ResumeLayout(false);
            tabPage1.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        protected BindingSource dataConnectionViewModelBindingSource;
        protected Controls.BeepPanel beepPanel1;
        protected Controls.BeepTextBox ConnectionNamebeepTextBox;
        protected Controls.BeepTextBox ConnectionStringbeepTextBox;
        protected BeepComboBox DriverVersionbeepComboBox;
        protected BeepComboBox DriverbeepComboBox;
        protected BeepButton CancelbeepButton;
        protected BeepButton SavebeepButton;
        public Controls.BeepTabs beepTabs1;
      
        protected TabPage tabPage1;
    }
}
