namespace TheTechIdea.Beep.Winform.Controls
{
    partial class BeepDialogBoxPopUp
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ButtonsPanel = new BeepPanel();
            ContentPanel = new BeepPanel();
            HeaderPanel = new BeepPanel();
            CloseButton = new BeepButton();
            DialogIconImage = new BeepImage();
            TitleLabel = new BeepLabel();
            HeaderPanel.SuspendLayout();
            SuspendLayout();
            // 
            // ButtonsPanel
            // 
            ButtonsPanel.ActiveBackColor = Color.Gray;
            ButtonsPanel.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            ButtonsPanel.AnimationDuration = 500;
            ButtonsPanel.AnimationType = DisplayAnimationType.None;
            ButtonsPanel.ApplyThemeToChilds = true;
            ButtonsPanel.BackColor = Color.FromArgb(245, 245, 245);
            ButtonsPanel.BlockID = null;
            ButtonsPanel.BorderColor = Color.Black;
            ButtonsPanel.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            ButtonsPanel.BorderRadius = 1;
            ButtonsPanel.BorderStyle = BorderStyle.FixedSingle;
            ButtonsPanel.BorderThickness = 1;
            ButtonsPanel.BottomoffsetForDrawingRect = 0;
            ButtonsPanel.BoundProperty = null;
            ButtonsPanel.CanBeFocused = true;
            ButtonsPanel.CanBeHovered = false;
            ButtonsPanel.CanBePressed = true;
            ButtonsPanel.Category = Utilities.DbFieldCategory.String;
            ButtonsPanel.ComponentName = "ButtonsPanel";
            ButtonsPanel.DataContext = null;
            ButtonsPanel.DataSourceProperty = null;
            ButtonsPanel.DisabledBackColor = Color.Gray;
            ButtonsPanel.DisabledForeColor = Color.Empty;
            ButtonsPanel.DrawingRect = new Rectangle(1, 1, 786, 71);
            ButtonsPanel.Easing = EasingType.Linear;
            ButtonsPanel.FieldID = null;
            ButtonsPanel.FocusBackColor = Color.Gray;
            ButtonsPanel.FocusBorderColor = Color.Gray;
            ButtonsPanel.FocusForeColor = Color.Black;
            ButtonsPanel.FocusIndicatorColor = Color.Blue;
            ButtonsPanel.Font = new Font("Segoe UI", 16F);
            ButtonsPanel.ForeColor = Color.FromArgb(44, 62, 80);
            ButtonsPanel.Form = null;
            ButtonsPanel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            ButtonsPanel.GradientEndColor = Color.Gray;
            ButtonsPanel.GradientStartColor = Color.Gray;
            ButtonsPanel.GuidID = "b207d94c-5c91-4361-a315-7f0471bed933";
            ButtonsPanel.HoverBackColor = Color.Gray;
            ButtonsPanel.HoverBorderColor = Color.Gray;
            ButtonsPanel.HoveredBackcolor = Color.Wheat;
            ButtonsPanel.HoverForeColor = Color.Black;
            ButtonsPanel.Id = -1;
            ButtonsPanel.InactiveBackColor = Color.Gray;
            ButtonsPanel.InactiveBorderColor = Color.Gray;
            ButtonsPanel.InactiveForeColor = Color.Black;
            ButtonsPanel.IsAcceptButton = false;
            ButtonsPanel.IsBorderAffectedByTheme = true;
            ButtonsPanel.IsCancelButton = false;
            ButtonsPanel.IsChild = false;
            ButtonsPanel.IsCustomeBorder = false;
            ButtonsPanel.IsDefault = false;
            ButtonsPanel.IsFocused = false;
            ButtonsPanel.IsFramless = false;
            ButtonsPanel.IsHovered = false;
            ButtonsPanel.IsPressed = false;
            ButtonsPanel.IsRounded = true;
            ButtonsPanel.IsRoundedAffectedByTheme = true;
            ButtonsPanel.IsShadowAffectedByTheme = true;
            ButtonsPanel.LeftoffsetForDrawingRect = 0;
            ButtonsPanel.LinkedProperty = null;
            ButtonsPanel.Location = new Point(6, 371);
            ButtonsPanel.Name = "ButtonsPanel";
            ButtonsPanel.OverrideFontSize = TypeStyleFontSize.None;
            ButtonsPanel.ParentBackColor = Color.Empty;
            ButtonsPanel.PressedBackColor = Color.Gray;
            ButtonsPanel.PressedBorderColor = Color.Gray;
            ButtonsPanel.PressedForeColor = Color.Black;
            ButtonsPanel.RightoffsetForDrawingRect = 0;
            ButtonsPanel.SavedGuidID = null;
            ButtonsPanel.SavedID = null;
            ButtonsPanel.ShadowColor = Color.Black;
            ButtonsPanel.ShadowOffset = 0;
            ButtonsPanel.ShadowOpacity = 0.5F;
            ButtonsPanel.ShowAllBorders = true;
            ButtonsPanel.ShowBottomBorder = true;
            ButtonsPanel.ShowFocusIndicator = false;
            ButtonsPanel.ShowLeftBorder = true;
            ButtonsPanel.ShowRightBorder = true;
            ButtonsPanel.ShowShadow = false;
            ButtonsPanel.ShowTitle = false;
            ButtonsPanel.ShowTitleLine = true;
            ButtonsPanel.ShowTitleLineinFullWidth = true;
            ButtonsPanel.ShowTopBorder = true;
            ButtonsPanel.Size = new Size(788, 73);
            ButtonsPanel.SlideFrom = SlideDirection.Left;
            ButtonsPanel.StaticNotMoving = false;
            ButtonsPanel.TabIndex = 0;
            ButtonsPanel.Text = "beepPanel1";
            ButtonsPanel.Theme = Vis.Modules.EnumBeepThemes.FlatDesignTheme;
            ButtonsPanel.TitleAlignment = ContentAlignment.TopLeft;
            ButtonsPanel.TitleBottomY = 0;
            ButtonsPanel.TitleFont = new Font("Segoe UI", 16F);
            ButtonsPanel.TitleLineColor = Color.Gray;
            ButtonsPanel.TitleLineThickness = 2;
            ButtonsPanel.TitleText = "Panel Title";
            ButtonsPanel.ToolTipText = "";
            ButtonsPanel.TopoffsetForDrawingRect = 0;
            ButtonsPanel.UseGradientBackground = false;
            ButtonsPanel.UseThemeFont = true;
            // 
            // ContentPanel
            // 
            ContentPanel.ActiveBackColor = Color.Gray;
            ContentPanel.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            ContentPanel.AnimationDuration = 500;
            ContentPanel.AnimationType = DisplayAnimationType.None;
            ContentPanel.ApplyThemeToChilds = true;
            ContentPanel.BackColor = Color.FromArgb(245, 245, 245);
            ContentPanel.BlockID = null;
            ContentPanel.BorderColor = Color.Black;
            ContentPanel.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            ContentPanel.BorderRadius = 1;
            ContentPanel.BorderStyle = BorderStyle.FixedSingle;
            ContentPanel.BorderThickness = 1;
            ContentPanel.BottomoffsetForDrawingRect = 0;
            ContentPanel.BoundProperty = null;
            ContentPanel.CanBeFocused = true;
            ContentPanel.CanBeHovered = false;
            ContentPanel.CanBePressed = true;
            ContentPanel.Category = Utilities.DbFieldCategory.String;
            ContentPanel.ComponentName = "ButtonsPanel";
            ContentPanel.DataContext = null;
            ContentPanel.DataSourceProperty = null;
            ContentPanel.DisabledBackColor = Color.Gray;
            ContentPanel.DisabledForeColor = Color.Empty;
            ContentPanel.DrawingRect = new Rectangle(1, 1, 786, 267);
            ContentPanel.Easing = EasingType.Linear;
            ContentPanel.FieldID = null;
            ContentPanel.FocusBackColor = Color.Gray;
            ContentPanel.FocusBorderColor = Color.Gray;
            ContentPanel.FocusForeColor = Color.Black;
            ContentPanel.FocusIndicatorColor = Color.Blue;
            ContentPanel.Font = new Font("Segoe UI", 16F);
            ContentPanel.ForeColor = Color.FromArgb(44, 62, 80);
            ContentPanel.Form = null;
            ContentPanel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            ContentPanel.GradientEndColor = Color.Gray;
            ContentPanel.GradientStartColor = Color.Gray;
            ContentPanel.GuidID = "b207d94c-5c91-4361-a315-7f0471bed933";
            ContentPanel.HoverBackColor = Color.Gray;
            ContentPanel.HoverBorderColor = Color.Gray;
            ContentPanel.HoveredBackcolor = Color.Wheat;
            ContentPanel.HoverForeColor = Color.Black;
            ContentPanel.Id = -1;
            ContentPanel.InactiveBackColor = Color.Gray;
            ContentPanel.InactiveBorderColor = Color.Gray;
            ContentPanel.InactiveForeColor = Color.Black;
            ContentPanel.IsAcceptButton = false;
            ContentPanel.IsBorderAffectedByTheme = true;
            ContentPanel.IsCancelButton = false;
            ContentPanel.IsChild = false;
            ContentPanel.IsCustomeBorder = false;
            ContentPanel.IsDefault = false;
            ContentPanel.IsFocused = false;
            ContentPanel.IsFramless = false;
            ContentPanel.IsHovered = false;
            ContentPanel.IsPressed = false;
            ContentPanel.IsRounded = true;
            ContentPanel.IsRoundedAffectedByTheme = true;
            ContentPanel.IsShadowAffectedByTheme = true;
            ContentPanel.LeftoffsetForDrawingRect = 0;
            ContentPanel.LinkedProperty = null;
            ContentPanel.Location = new Point(6, 96);
            ContentPanel.Name = "ContentPanel";
            ContentPanel.OverrideFontSize = TypeStyleFontSize.None;
            ContentPanel.ParentBackColor = Color.Empty;
            ContentPanel.PressedBackColor = Color.Gray;
            ContentPanel.PressedBorderColor = Color.Gray;
            ContentPanel.PressedForeColor = Color.Black;
            ContentPanel.RightoffsetForDrawingRect = 0;
            ContentPanel.SavedGuidID = null;
            ContentPanel.SavedID = null;
            ContentPanel.ShadowColor = Color.Black;
            ContentPanel.ShadowOffset = 0;
            ContentPanel.ShadowOpacity = 0.5F;
            ContentPanel.ShowAllBorders = true;
            ContentPanel.ShowBottomBorder = true;
            ContentPanel.ShowFocusIndicator = false;
            ContentPanel.ShowLeftBorder = true;
            ContentPanel.ShowRightBorder = true;
            ContentPanel.ShowShadow = false;
            ContentPanel.ShowTitle = false;
            ContentPanel.ShowTitleLine = true;
            ContentPanel.ShowTitleLineinFullWidth = true;
            ContentPanel.ShowTopBorder = true;
            ContentPanel.Size = new Size(788, 269);
            ContentPanel.SlideFrom = SlideDirection.Left;
            ContentPanel.StaticNotMoving = false;
            ContentPanel.TabIndex = 1;
            ContentPanel.Text = "beepPanel1";
            ContentPanel.Theme = Vis.Modules.EnumBeepThemes.FlatDesignTheme;
            ContentPanel.TitleAlignment = ContentAlignment.TopLeft;
            ContentPanel.TitleBottomY = 0;
            ContentPanel.TitleFont = new Font("Segoe UI", 16F);
            ContentPanel.TitleLineColor = Color.Gray;
            ContentPanel.TitleLineThickness = 2;
            ContentPanel.TitleText = "Panel Title";
            ContentPanel.ToolTipText = "";
            ContentPanel.TopoffsetForDrawingRect = 0;
            ContentPanel.UseGradientBackground = false;
            ContentPanel.UseThemeFont = true;
            // 
            // HeaderPanel
            // 
            HeaderPanel.ActiveBackColor = Color.Gray;
            HeaderPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            HeaderPanel.AnimationDuration = 500;
            HeaderPanel.AnimationType = DisplayAnimationType.None;
            HeaderPanel.ApplyThemeToChilds = true;
            HeaderPanel.BackColor = Color.FromArgb(245, 245, 245);
            HeaderPanel.BlockID = null;
            HeaderPanel.BorderColor = Color.Black;
            HeaderPanel.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            HeaderPanel.BorderRadius = 1;
            HeaderPanel.BorderStyle = BorderStyle.FixedSingle;
            HeaderPanel.BorderThickness = 1;
            HeaderPanel.BottomoffsetForDrawingRect = 0;
            HeaderPanel.BoundProperty = null;
            HeaderPanel.CanBeFocused = true;
            HeaderPanel.CanBeHovered = false;
            HeaderPanel.CanBePressed = true;
            HeaderPanel.Category = Utilities.DbFieldCategory.String;
            HeaderPanel.ComponentName = "ButtonsPanel";
            HeaderPanel.Controls.Add(CloseButton);
            HeaderPanel.Controls.Add(DialogIconImage);
            HeaderPanel.Controls.Add(TitleLabel);
            HeaderPanel.DataContext = null;
            HeaderPanel.DataSourceProperty = null;
            HeaderPanel.DisabledBackColor = Color.Gray;
            HeaderPanel.DisabledForeColor = Color.Empty;
            HeaderPanel.DrawingRect = new Rectangle(1, 1, 786, 82);
            HeaderPanel.Easing = EasingType.Linear;
            HeaderPanel.FieldID = null;
            HeaderPanel.FocusBackColor = Color.Gray;
            HeaderPanel.FocusBorderColor = Color.Gray;
            HeaderPanel.FocusForeColor = Color.Black;
            HeaderPanel.FocusIndicatorColor = Color.Blue;
            HeaderPanel.Font = new Font("Segoe UI", 16F);
            HeaderPanel.ForeColor = Color.FromArgb(44, 62, 80);
            HeaderPanel.Form = null;
            HeaderPanel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            HeaderPanel.GradientEndColor = Color.Gray;
            HeaderPanel.GradientStartColor = Color.Gray;
            HeaderPanel.GuidID = "b207d94c-5c91-4361-a315-7f0471bed933";
            HeaderPanel.HoverBackColor = Color.Gray;
            HeaderPanel.HoverBorderColor = Color.Gray;
            HeaderPanel.HoveredBackcolor = Color.Wheat;
            HeaderPanel.HoverForeColor = Color.Black;
            HeaderPanel.Id = -1;
            HeaderPanel.InactiveBackColor = Color.Gray;
            HeaderPanel.InactiveBorderColor = Color.Gray;
            HeaderPanel.InactiveForeColor = Color.Black;
            HeaderPanel.IsAcceptButton = false;
            HeaderPanel.IsBorderAffectedByTheme = true;
            HeaderPanel.IsCancelButton = false;
            HeaderPanel.IsChild = false;
            HeaderPanel.IsCustomeBorder = false;
            HeaderPanel.IsDefault = false;
            HeaderPanel.IsFocused = false;
            HeaderPanel.IsFramless = false;
            HeaderPanel.IsHovered = false;
            HeaderPanel.IsPressed = false;
            HeaderPanel.IsRounded = true;
            HeaderPanel.IsRoundedAffectedByTheme = true;
            HeaderPanel.IsShadowAffectedByTheme = true;
            HeaderPanel.LeftoffsetForDrawingRect = 0;
            HeaderPanel.LinkedProperty = null;
            HeaderPanel.Location = new Point(6, 6);
            HeaderPanel.Name = "HeaderPanel";
            HeaderPanel.OverrideFontSize = TypeStyleFontSize.None;
            HeaderPanel.ParentBackColor = Color.Empty;
            HeaderPanel.PressedBackColor = Color.Gray;
            HeaderPanel.PressedBorderColor = Color.Gray;
            HeaderPanel.PressedForeColor = Color.Black;
            HeaderPanel.RightoffsetForDrawingRect = 0;
            HeaderPanel.SavedGuidID = null;
            HeaderPanel.SavedID = null;
            HeaderPanel.ShadowColor = Color.Black;
            HeaderPanel.ShadowOffset = 0;
            HeaderPanel.ShadowOpacity = 0.5F;
            HeaderPanel.ShowAllBorders = true;
            HeaderPanel.ShowBottomBorder = true;
            HeaderPanel.ShowFocusIndicator = false;
            HeaderPanel.ShowLeftBorder = true;
            HeaderPanel.ShowRightBorder = true;
            HeaderPanel.ShowShadow = false;
            HeaderPanel.ShowTitle = false;
            HeaderPanel.ShowTitleLine = true;
            HeaderPanel.ShowTitleLineinFullWidth = true;
            HeaderPanel.ShowTopBorder = true;
            HeaderPanel.Size = new Size(788, 84);
            HeaderPanel.SlideFrom = SlideDirection.Left;
            HeaderPanel.StaticNotMoving = false;
            HeaderPanel.TabIndex = 2;
            HeaderPanel.Text = "beepPanel1";
            HeaderPanel.Theme = Vis.Modules.EnumBeepThemes.FlatDesignTheme;
            HeaderPanel.TitleAlignment = ContentAlignment.TopLeft;
            HeaderPanel.TitleBottomY = 0;
            HeaderPanel.TitleFont = new Font("Segoe UI", 16F);
            HeaderPanel.TitleLineColor = Color.Gray;
            HeaderPanel.TitleLineThickness = 2;
            HeaderPanel.TitleText = "Panel Title";
            HeaderPanel.ToolTipText = "";
            HeaderPanel.TopoffsetForDrawingRect = 0;
            HeaderPanel.UseGradientBackground = false;
            HeaderPanel.UseThemeFont = true;
            // 
            // CloseButton
            // 
            CloseButton.ActiveBackColor = Color.Gray;
            CloseButton.AnimationDuration = 500;
            CloseButton.AnimationType = DisplayAnimationType.None;
            CloseButton.ApplyThemeOnImage = false;
            CloseButton.ApplyThemeToChilds = true;
            CloseButton.BackColor = Color.LightSkyBlue;
            CloseButton.BlockID = null;
            CloseButton.BorderColor = Color.Black;
            CloseButton.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            CloseButton.BorderRadius = 1;
            CloseButton.BorderSize = 1;
            CloseButton.BorderStyle = BorderStyle.FixedSingle;
            CloseButton.BorderThickness = 1;
            CloseButton.BottomoffsetForDrawingRect = 0;
            CloseButton.BoundProperty = null;
            CloseButton.CanBeFocused = true;
            CloseButton.CanBeHovered = true;
            CloseButton.CanBePressed = true;
            CloseButton.Category = Utilities.DbFieldCategory.Boolean;
            CloseButton.ComponentName = "CloseButton";
            CloseButton.DataContext = null;
            CloseButton.DataSourceProperty = null;
            CloseButton.DisabledBackColor = Color.Gray;
            CloseButton.DisabledForeColor = Color.Empty;
            CloseButton.DrawingRect = new Rectangle(1, 1, 47, 40);
            CloseButton.Easing = EasingType.Linear;
            CloseButton.FieldID = null;
          
            CloseButton.FocusBackColor = Color.Gray;
            CloseButton.FocusBorderColor = Color.Gray;
            CloseButton.FocusForeColor = Color.Black;
            CloseButton.FocusIndicatorColor = Color.Blue;
            CloseButton.Font = new Font("Segoe UI Black", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            CloseButton.ForeColor = Color.White;
            CloseButton.Form = null;
            CloseButton.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            CloseButton.GradientEndColor = Color.Gray;
            CloseButton.GradientStartColor = Color.Gray;
            CloseButton.GuidID = "ec132010-2148-432d-853b-e357af88df17";
            CloseButton.HideText = false;
            CloseButton.HoverBackColor = Color.FromArgb(41, 128, 185);
            CloseButton.HoverBorderColor = Color.Gray;
            CloseButton.HoveredBackcolor = Color.Wheat;
            CloseButton.HoverForeColor = Color.White;
            CloseButton.Id = -1;
            CloseButton.Image = null;
            CloseButton.ImageAlign = ContentAlignment.MiddleLeft;
            CloseButton.ImageClicked = null;
            CloseButton.ImagePath = null;
            CloseButton.InactiveBackColor = Color.Gray;
            CloseButton.InactiveBorderColor = Color.Gray;
            CloseButton.InactiveForeColor = Color.Black;
            CloseButton.IsAcceptButton = false;
            CloseButton.IsBorderAffectedByTheme = true;
            CloseButton.IsCancelButton = false;
            CloseButton.IsChild = false;
            CloseButton.IsCustomeBorder = false;
            CloseButton.IsDefault = false;
            CloseButton.IsFocused = false;
            CloseButton.IsFramless = false;
            CloseButton.IsHovered = false;
            CloseButton.IsPopupOpen = false;
            CloseButton.IsPressed = false;
            CloseButton.IsRounded = true;
            CloseButton.IsRoundedAffectedByTheme = true;
            CloseButton.IsSelected = false;
            CloseButton.IsSelectedAuto = true;
            CloseButton.IsShadowAffectedByTheme = true;
            CloseButton.IsSideMenuChild = false;
            CloseButton.IsStillButton = false;
            CloseButton.LeftoffsetForDrawingRect = 0;
            CloseButton.LinkedProperty = null;
            CloseButton.Location = new Point(723, 23);
            CloseButton.Margin = new Padding(0);
            CloseButton.MaxImageSize = new Size(32, 32);
            CloseButton.Name = "CloseButton";
            CloseButton.OverrideFontSize = TypeStyleFontSize.None;
            CloseButton.ParentBackColor = Color.Empty;
            CloseButton.PopupMode = false;
            CloseButton.PressedBackColor = Color.Gray;
            CloseButton.PressedBorderColor = Color.Gray;
            CloseButton.PressedForeColor = Color.Black;
            CloseButton.RightoffsetForDrawingRect = 0;
            CloseButton.SavedGuidID = null;
            CloseButton.SavedID = null;
            CloseButton.SelectedBorderColor = Color.Blue;
            CloseButton.SelectedIndex = -1;
            CloseButton.ShadowColor = Color.Black;
            CloseButton.ShadowOffset = 0;
            CloseButton.ShadowOpacity = 0.5F;
            CloseButton.ShowAllBorders = true;
            CloseButton.ShowBottomBorder = true;
            CloseButton.ShowFocusIndicator = false;
            CloseButton.ShowLeftBorder = true;
            CloseButton.ShowRightBorder = true;
            CloseButton.ShowShadow = false;
            CloseButton.ShowTopBorder = true;
            CloseButton.Size = new Size(49, 42);
            CloseButton.SlideFrom = SlideDirection.Left;
            CloseButton.StaticNotMoving = false;
            CloseButton.TabIndex = 2;
            CloseButton.Text = "X";
            CloseButton.TextAlign = ContentAlignment.MiddleCenter;
            CloseButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            CloseButton.Theme = Vis.Modules.EnumBeepThemes.FlatDesignTheme;
            CloseButton.ToolTipText = "";
            CloseButton.TopoffsetForDrawingRect = 0;
            CloseButton.UseGradientBackground = false;
            CloseButton.UseScaledFont = false;
            CloseButton.UseThemeFont = false;
            // 
            // DialogIconImage
            // 
            DialogIconImage.ActiveBackColor = Color.FromArgb(41, 128, 185);
            DialogIconImage.AllowManualRotation = true;
            DialogIconImage.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            DialogIconImage.AnimationDuration = 500;
            DialogIconImage.AnimationType = DisplayAnimationType.None;
            DialogIconImage.ApplyThemeOnImage = false;
            DialogIconImage.ApplyThemeToChilds = true;
            DialogIconImage.BlockID = null;
            DialogIconImage.BorderColor = Color.FromArgb(189, 195, 199);
            DialogIconImage.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            DialogIconImage.BorderRadius = 1;
            DialogIconImage.BorderStyle = BorderStyle.FixedSingle;
            DialogIconImage.BorderThickness = 1;
            DialogIconImage.BottomoffsetForDrawingRect = 0;
            DialogIconImage.BoundProperty = "ImagePath";
            DialogIconImage.CanBeFocused = true;
            DialogIconImage.CanBeHovered = false;
            DialogIconImage.CanBePressed = true;
            DialogIconImage.Category = Utilities.DbFieldCategory.String;
            DialogIconImage.ComponentName = "DialogIconImage";
            DialogIconImage.DataContext = null;
            DialogIconImage.DataSourceProperty = null;
            DialogIconImage.DisabledBackColor = Color.Gray;
            DialogIconImage.DisabledForeColor = Color.Empty;
            DialogIconImage.DrawingRect = new Rectangle(1, 1, 50, 40);
            DialogIconImage.Easing = EasingType.Linear;
            DialogIconImage.FieldID = null;
            DialogIconImage.FocusBackColor = Color.FromArgb(41, 128, 185);
            DialogIconImage.FocusBorderColor = Color.Gray;
            DialogIconImage.FocusForeColor = Color.White;
            DialogIconImage.FocusIndicatorColor = Color.Blue;
            DialogIconImage.Form = null;
            DialogIconImage.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            DialogIconImage.GradientEndColor = Color.White;
            DialogIconImage.GradientStartColor = Color.White;
            DialogIconImage.GuidID = "6a0575aa-d847-4dd1-8758-a04c9ae1e263";
            DialogIconImage.HoverBackColor = Color.FromArgb(41, 128, 185);
            DialogIconImage.HoverBorderColor = Color.FromArgb(52, 152, 219);
            DialogIconImage.HoveredBackcolor = Color.Wheat;
            DialogIconImage.HoverForeColor = Color.White;
            DialogIconImage.Id = -1;
            DialogIconImage.Image = null;
            DialogIconImage.ImagePath = null;
            DialogIconImage.InactiveBackColor = Color.Gray;
            DialogIconImage.InactiveBorderColor = Color.Gray;
            DialogIconImage.InactiveForeColor = Color.Black;
            DialogIconImage.IsAcceptButton = false;
            DialogIconImage.IsBorderAffectedByTheme = true;
            DialogIconImage.IsCancelButton = false;
            DialogIconImage.IsChild = false;
            DialogIconImage.IsCustomeBorder = false;
            DialogIconImage.IsDefault = false;
            DialogIconImage.IsFocused = false;
            DialogIconImage.IsFramless = false;
            DialogIconImage.IsHovered = false;
            DialogIconImage.IsPressed = false;
            DialogIconImage.IsRounded = true;
            DialogIconImage.IsRoundedAffectedByTheme = true;
            DialogIconImage.IsShadowAffectedByTheme = true;
            DialogIconImage.IsSpinning = false;
            DialogIconImage.IsStillImage = false;
            DialogIconImage.LeftoffsetForDrawingRect = 0;
            DialogIconImage.LinkedProperty = null;
            DialogIconImage.Location = new Point(5, 23);
            DialogIconImage.ManualRotationAngle = 0F;
            DialogIconImage.Name = "DialogIconImage";
            DialogIconImage.OverrideFontSize = TypeStyleFontSize.None;
            DialogIconImage.ParentBackColor = Color.Empty;
            DialogIconImage.PressedBackColor = Color.FromArgb(41, 128, 185);
            DialogIconImage.PressedBorderColor = Color.Gray;
            DialogIconImage.PressedForeColor = Color.White;
            DialogIconImage.RightoffsetForDrawingRect = 0;
            DialogIconImage.SavedGuidID = null;
            DialogIconImage.SavedID = null;
            DialogIconImage.ScaleMode = Vis.Modules.ImageScaleMode.KeepAspectRatio;
            DialogIconImage.ShadowColor = Color.Empty;
            DialogIconImage.ShadowOffset = 0;
            DialogIconImage.ShadowOpacity = 0.5F;
            DialogIconImage.ShowAllBorders = true;
            DialogIconImage.ShowBottomBorder = true;
            DialogIconImage.ShowFocusIndicator = false;
            DialogIconImage.ShowLeftBorder = true;
            DialogIconImage.ShowRightBorder = true;
            DialogIconImage.ShowShadow = false;
            DialogIconImage.ShowTopBorder = true;
            DialogIconImage.Size = new Size(52, 42);
            DialogIconImage.SlideFrom = SlideDirection.Left;
            DialogIconImage.SpinSpeed = 5F;
            DialogIconImage.StaticNotMoving = false;
            DialogIconImage.TabIndex = 1;
            DialogIconImage.Text = "beepImage1";
            DialogIconImage.Theme = Vis.Modules.EnumBeepThemes.FlatDesignTheme;
            DialogIconImage.ToolTipText = "";
            DialogIconImage.TopoffsetForDrawingRect = 0;
            DialogIconImage.UseGradientBackground = false;
            DialogIconImage.UseThemeFont = true;
            // 
            // TitleLabel
            // 
            TitleLabel.ActiveBackColor = Color.Gray;
            TitleLabel.AnimationDuration = 500;
            TitleLabel.AnimationType = DisplayAnimationType.None;
            TitleLabel.ApplyThemeOnImage = false;
            TitleLabel.ApplyThemeToChilds = true;
            TitleLabel.BackColor = Color.FromArgb(245, 245, 245);
            TitleLabel.BlockID = null;
            TitleLabel.BorderColor = Color.Black;
            TitleLabel.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            TitleLabel.BorderRadius = 1;
            TitleLabel.BorderStyle = BorderStyle.FixedSingle;
            TitleLabel.BorderThickness = 1;
            TitleLabel.BottomoffsetForDrawingRect = 0;
            TitleLabel.BoundProperty = "Text";
            TitleLabel.CanBeFocused = true;
            TitleLabel.CanBeHovered = false;
            TitleLabel.CanBePressed = true;
            TitleLabel.Category = Utilities.DbFieldCategory.String;
            TitleLabel.ComponentName = "TitleLabel";
            TitleLabel.DataContext = null;
            TitleLabel.DataSourceProperty = null;
            TitleLabel.DisabledBackColor = Color.Gray;
            TitleLabel.DisabledForeColor = Color.Empty;
            TitleLabel.DrawingRect = new Rectangle(2, 2, 639, 38);
            TitleLabel.Easing = EasingType.Linear;
            TitleLabel.FieldID = null;
            TitleLabel.FocusBackColor = Color.Gray;
            TitleLabel.FocusBorderColor = Color.Gray;
            TitleLabel.FocusForeColor = Color.Black;
            TitleLabel.FocusIndicatorColor = Color.Blue;
            TitleLabel.Font = new Font("Segoe UI", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            TitleLabel.ForeColor = Color.FromArgb(44, 62, 80);
            TitleLabel.Form = null;
            TitleLabel.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            TitleLabel.GradientEndColor = Color.Gray;
            TitleLabel.GradientStartColor = Color.Gray;
            TitleLabel.GuidID = "3590011a-f03c-461e-8a29-158801ea1eba";
            TitleLabel.HideText = false;
            TitleLabel.HoverBackColor = Color.White;
            TitleLabel.HoverBorderColor = Color.Gray;
            TitleLabel.HoveredBackcolor = Color.Wheat;
            TitleLabel.HoverForeColor = Color.White;
            TitleLabel.Id = -1;
            TitleLabel.ImageAlign = ContentAlignment.MiddleLeft;
            TitleLabel.ImagePath = null;
            TitleLabel.InactiveBackColor = Color.Gray;
            TitleLabel.InactiveBorderColor = Color.Gray;
            TitleLabel.InactiveForeColor = Color.Black;
            TitleLabel.IsAcceptButton = false;
            TitleLabel.IsBorderAffectedByTheme = true;
            TitleLabel.IsCancelButton = false;
            TitleLabel.IsChild = true;
            TitleLabel.IsCustomeBorder = false;
            TitleLabel.IsDefault = false;
            TitleLabel.IsFocused = false;
            TitleLabel.IsFramless = true;
            TitleLabel.IsHovered = false;
            TitleLabel.IsPressed = false;
            TitleLabel.IsRounded = true;
            TitleLabel.IsRoundedAffectedByTheme = true;
            TitleLabel.IsShadowAffectedByTheme = true;
            TitleLabel.LabelBackColor = Color.Empty;
            TitleLabel.LeftoffsetForDrawingRect = 0;
            TitleLabel.LinkedProperty = null;
            TitleLabel.Location = new Point(60, 23);
            TitleLabel.Margin = new Padding(0);
            TitleLabel.MaxImageSize = new Size(16, 16);
            TitleLabel.Name = "TitleLabel";
            TitleLabel.OverrideFontSize = TypeStyleFontSize.None;
            TitleLabel.Padding = new Padding(1);
            TitleLabel.ParentBackColor = Color.FromArgb(245, 245, 245);
            TitleLabel.PressedBackColor = Color.Gray;
            TitleLabel.PressedBorderColor = Color.Gray;
            TitleLabel.PressedForeColor = Color.Black;
            TitleLabel.RightoffsetForDrawingRect = 0;
            TitleLabel.SavedGuidID = null;
            TitleLabel.SavedID = null;
            TitleLabel.ShadowColor = Color.Black;
            TitleLabel.ShadowOffset = 0;
            TitleLabel.ShadowOpacity = 0.5F;
            TitleLabel.ShowAllBorders = true;
            TitleLabel.ShowBottomBorder = true;
            TitleLabel.ShowFocusIndicator = false;
            TitleLabel.ShowLeftBorder = true;
            TitleLabel.ShowRightBorder = true;
            TitleLabel.ShowShadow = false;
            TitleLabel.ShowTopBorder = true;
            TitleLabel.Size = new Size(643, 42);
            TitleLabel.SlideFrom = SlideDirection.Left;
            TitleLabel.StaticNotMoving = false;
            TitleLabel.TabIndex = 0;
            TitleLabel.Text = "Dialog";
            TitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            TitleLabel.TextImageRelation = TextImageRelation.ImageBeforeText;
            TitleLabel.Theme = Vis.Modules.EnumBeepThemes.FlatDesignTheme;
            TitleLabel.ToolTipText = "";
            TitleLabel.TopoffsetForDrawingRect = 0;
            TitleLabel.UseGradientBackground = false;
            TitleLabel.UseScaledFont = false;
            TitleLabel.UseThemeFont = false;
            // 
            // BeepDialogBoxPopUp
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(800, 450);
            Controls.Add(HeaderPanel);
            Controls.Add(ContentPanel);
            Controls.Add(ButtonsPanel);
            Name = "BeepDialogBoxPopUp";
            Text = "BeepDialogBoxPopUp";
            HeaderPanel.ResumeLayout(false);
            HeaderPanel.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private BeepPanel ButtonsPanel;
        private BeepPanel ContentPanel;
        private BeepPanel HeaderPanel;
        private BeepLabel TitleLabel;
        private BeepImage DialogIconImage;
        private BeepButton CloseButton;
    }
}