namespace TheTechIdea.Beep.Winform.Controls
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            beepAppBar1 = new BeepAppBar();
            beepSideMenu1 = new BeepSideMenu();
            beepCard1 = new BeepCard();
            panel1 = new Panel();
            beepImage1 = new BeepImage();
            beepButton2 = new BeepButton();
            beepButton1 = new BeepButton();
            beepTree1 = new BeepTree();
            panel1.SuspendLayout();
            SuspendLayout();
            // 
            // beepuiManager1
            // 
            beepuiManager1.BeepAppBar = beepAppBar1;
            beepuiManager1.BeepiForm = this;
            beepuiManager1.BeepSideMenu = beepSideMenu1;
            beepuiManager1.LogoImage = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007852-team-management\\10007852-team-management\\svg\\003-innovation.svg";
            beepuiManager1.ShowBorder = false;
            beepuiManager1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepuiManager1.Title = "Simple Info Apps";
            // 
            // beepAppBar1
            // 
            beepAppBar1.ActiveBackColor = Color.Gray;
            beepAppBar1.AnimationDuration = 500;
            beepAppBar1.AnimationType = DisplayAnimationType.None;
            beepAppBar1.ApplyThemeOnImage = false;
            beepAppBar1.ApplyThemeToChilds = true;
            beepAppBar1.BackColor = Color.FromArgb(75, 0, 130);
            beepAppBar1.BlockID = null;
            beepAppBar1.BorderColor = Color.Black;
            beepAppBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepAppBar1.BorderRadius = 5;
            beepAppBar1.BorderStyle = BorderStyle.FixedSingle;
            beepAppBar1.BorderThickness = 1;
            beepAppBar1.DataContext = null;
            beepAppBar1.DisabledBackColor = Color.Gray;
            beepAppBar1.DisabledForeColor = Color.Empty;
            beepAppBar1.Dock = DockStyle.Top;
            beepAppBar1.DrawingRect = new Rectangle(1, 1, 726, 54);
            beepAppBar1.Easing = EasingType.Linear;
            beepAppBar1.FieldID = null;
            beepAppBar1.FocusBackColor = Color.Gray;
            beepAppBar1.FocusBorderColor = Color.Gray;
            beepAppBar1.FocusForeColor = Color.Black;
            beepAppBar1.FocusIndicatorColor = Color.Blue;
            beepAppBar1.Form = null;
            beepAppBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepAppBar1.GradientEndColor = Color.Gray;
            beepAppBar1.GradientStartColor = Color.Gray;
            beepAppBar1.HoverBackColor = Color.Gray;
            beepAppBar1.HoverBorderColor = Color.Gray;
            beepAppBar1.HoveredBackcolor = Color.Wheat;
            beepAppBar1.HoverForeColor = Color.Black;
            beepAppBar1.Id = -1;
            beepAppBar1.InactiveBackColor = Color.Gray;
            beepAppBar1.InactiveBorderColor = Color.Gray;
            beepAppBar1.InactiveForeColor = Color.Black;
            beepAppBar1.IsAcceptButton = false;
            beepAppBar1.IsBorderAffectedByTheme = true;
            beepAppBar1.IsCancelButton = false;
            beepAppBar1.IsChild = false;
            beepAppBar1.IsCustomeBorder = false;
            beepAppBar1.IsDefault = false;
            beepAppBar1.IsFocused = false;
            beepAppBar1.IsFramless = false;
            beepAppBar1.IsHovered = false;
            beepAppBar1.IsPressed = false;
            beepAppBar1.IsRounded = true;
            beepAppBar1.IsRoundedAffectedByTheme = true;
            beepAppBar1.IsShadowAffectedByTheme = true;
            beepAppBar1.Location = new Point(214, 20);
            beepAppBar1.Name = "beepAppBar1";
            beepAppBar1.OverrideFontSize = TypeStyleFontSize.None;
            beepAppBar1.ParentBackColor = Color.Empty;
            beepAppBar1.PressedBackColor = Color.Gray;
            beepAppBar1.PressedBorderColor = Color.Gray;
            beepAppBar1.PressedForeColor = Color.Black;
            beepAppBar1.SavedGuidID = null;
            beepAppBar1.SavedID = null;
            beepAppBar1.ShadowColor = Color.Black;
            beepAppBar1.ShadowOffset = 0;
            beepAppBar1.ShadowOpacity = 0.5F;
            beepAppBar1.ShowAllBorders = false;
            beepAppBar1.ShowBottomBorder = false;
            beepAppBar1.ShowCloseIcon = true;
            beepAppBar1.ShowFocusIndicator = false;
            beepAppBar1.ShowHamburgerIcon = false;
            beepAppBar1.ShowLeftBorder = false;
            beepAppBar1.ShowLogoIcon = false;
            beepAppBar1.ShowMaximizeIcon = true;
            beepAppBar1.ShowMinimizeIcon = true;
            beepAppBar1.ShowNotificationIcon = true;
            beepAppBar1.ShowProfileIcon = true;
            beepAppBar1.ShowRightBorder = false;
            beepAppBar1.ShowSearchBox = true;
            beepAppBar1.ShowShadow = false;
            beepAppBar1.ShowTopBorder = false;
            beepAppBar1.SideMenu = null;
            beepAppBar1.Size = new Size(728, 56);
            beepAppBar1.SlideFrom = SlideDirection.Left;
            beepAppBar1.StaticNotMoving = false;
            beepAppBar1.TabIndex = 5;
            beepAppBar1.Text = "beepAppBar1";
            beepAppBar1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepAppBar1.ToolTipText = "";
            beepAppBar1.UseGradientBackground = false;
            // 
            // beepSideMenu1
            // 
            beepSideMenu1.ActiveBackColor = Color.FromArgb(72, 61, 139);
            beepSideMenu1.AnimationDuration = 500;
            beepSideMenu1.AnimationStep = 20;
            beepSideMenu1.AnimationType = DisplayAnimationType.None;
            beepSideMenu1.ApplyThemeOnImages = false;
            beepSideMenu1.ApplyThemeToChilds = true;
            beepSideMenu1.BackColor = Color.FromArgb(25, 25, 112);
            beepSideMenu1.BeepAppBar = null;
            beepSideMenu1.BeepForm = this;
            beepSideMenu1.BlockID = null;
            beepSideMenu1.BorderColor = Color.FromArgb(218, 165, 32);
            beepSideMenu1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSideMenu1.BorderRadius = 5;
            beepSideMenu1.BorderStyle = BorderStyle.FixedSingle;
            beepSideMenu1.BorderThickness = 1;
            beepSideMenu1.CollapsedWidth = 64;
            beepSideMenu1.DataContext = null;
            beepSideMenu1.DisabledBackColor = Color.Gray;
            beepSideMenu1.DisabledForeColor = Color.Empty;
            beepSideMenu1.Dock = DockStyle.Left;
            beepSideMenu1.DrawingRect = new Rectangle(1, 1, 202, 751);
            beepSideMenu1.Easing = EasingType.Linear;
            beepSideMenu1.ExpandedWidth = 204;
            beepSideMenu1.FieldID = null;
            beepSideMenu1.FocusBackColor = Color.FromArgb(255, 215, 0);
            beepSideMenu1.FocusBorderColor = Color.Gray;
            beepSideMenu1.FocusForeColor = Color.Black;
            beepSideMenu1.FocusIndicatorColor = Color.Blue;
            beepSideMenu1.Font = new Font("Segoe UI", 9F);
            beepSideMenu1.ForeColor = Color.White;
            beepSideMenu1.Form = null;
            beepSideMenu1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSideMenu1.GradientEndColor = Color.FromArgb(75, 0, 130);
            beepSideMenu1.GradientStartColor = Color.FromArgb(248, 248, 255);
            beepSideMenu1.HilightPanelSize = 5;
            beepSideMenu1.HoverBackColor = Color.FromArgb(85, 26, 139);
            beepSideMenu1.HoverBorderColor = Color.FromArgb(85, 26, 139);
            beepSideMenu1.HoveredBackcolor = Color.Wheat;
            beepSideMenu1.HoverForeColor = Color.Black;
            beepSideMenu1.Id = -1;
            beepSideMenu1.InactiveBackColor = Color.Gray;
            beepSideMenu1.InactiveBorderColor = Color.Gray;
            beepSideMenu1.InactiveForeColor = Color.Black;
            beepSideMenu1.IsAcceptButton = false;
            beepSideMenu1.IsBorderAffectedByTheme = false;
            beepSideMenu1.IsCancelButton = false;
            beepSideMenu1.IsChild = false;
            beepSideMenu1.IsCustomeBorder = false;
            beepSideMenu1.IsDefault = false;
            beepSideMenu1.IsFocused = false;
            beepSideMenu1.IsFramless = false;
            beepSideMenu1.IsHovered = false;
            beepSideMenu1.IsPressed = false;
            beepSideMenu1.IsRounded = true;
            beepSideMenu1.IsRoundedAffectedByTheme = true;
            beepSideMenu1.IsShadowAffectedByTheme = false;
            beepSideMenu1.Location = new Point(10, 20);
            beepSideMenu1.LogoImage = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007852-team-management\\10007852-team-management\\svg\\003-innovation.svg";
            beepSideMenu1.Name = "beepSideMenu1";
            beepSideMenu1.OverrideFontSize = TypeStyleFontSize.None;
            beepSideMenu1.Padding = new Padding(5);
            beepSideMenu1.ParentBackColor = Color.FromArgb(20, 20, 20);
            beepSideMenu1.PressedBackColor = Color.FromArgb(72, 61, 139);
            beepSideMenu1.PressedBorderColor = Color.Gray;
            beepSideMenu1.PressedForeColor = Color.Black;
            beepSideMenu1.SavedGuidID = null;
            beepSideMenu1.SavedID = null;
            beepSideMenu1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepSideMenu1.ShadowOffset = 0;
            beepSideMenu1.ShadowOpacity = 0.5F;
            beepSideMenu1.ShowAllBorders = false;
            beepSideMenu1.ShowBottomBorder = false;
            beepSideMenu1.ShowFocusIndicator = false;
            beepSideMenu1.ShowLeftBorder = false;
            beepSideMenu1.ShowRightBorder = false;
            beepSideMenu1.ShowShadow = false;
            beepSideMenu1.ShowTopBorder = false;
            beepSideMenu1.Size = new Size(204, 753);
            beepSideMenu1.SlideFrom = SlideDirection.Left;
            beepSideMenu1.StaticNotMoving = false;
            beepSideMenu1.TabIndex = 6;
            beepSideMenu1.Text = "beepSideMenu1";
            beepSideMenu1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepSideMenu1.Title = "Simple Info Apps";
            beepSideMenu1.ToolTipText = "";
            beepSideMenu1.UseGradientBackground = false;
            // 
            // beepCard1
            // 
            beepCard1.ActiveBackColor = Color.Gray;
            beepCard1.AnimationDuration = 500;
            beepCard1.AnimationType = DisplayAnimationType.None;
            beepCard1.ApplyThemeToChilds = true;
            beepCard1.BackColor = Color.FromArgb(250, 230, 190);
            beepCard1.BlockID = null;
            beepCard1.BorderColor = Color.Black;
            beepCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCard1.BorderRadius = 5;
            beepCard1.BorderStyle = BorderStyle.FixedSingle;
            beepCard1.BorderThickness = 1;
            beepCard1.DataContext = null;
            beepCard1.DisabledBackColor = Color.Gray;
            beepCard1.DisabledForeColor = Color.Empty;
            beepCard1.DrawingRect = new Rectangle(1, 1, 317, 156);
            beepCard1.Easing = EasingType.Linear;
            beepCard1.FieldID = null;
            beepCard1.FocusBackColor = Color.Gray;
            beepCard1.FocusBorderColor = Color.Gray;
            beepCard1.FocusForeColor = Color.Black;
            beepCard1.FocusIndicatorColor = Color.Blue;
            beepCard1.Form = null;
            beepCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCard1.GradientEndColor = Color.Gray;
            beepCard1.GradientStartColor = Color.Gray;
            beepCard1.HeaderAlignment = ContentAlignment.TopLeft;
            beepCard1.HeaderText = "Success Criteria";
            beepCard1.HoverBackColor = Color.Gray;
            beepCard1.HoverBorderColor = Color.Gray;
            beepCard1.HoveredBackcolor = Color.Wheat;
            beepCard1.HoverForeColor = Color.Black;
            beepCard1.Id = -1;
            beepCard1.ImageAlignment = ContentAlignment.TopRight;
            beepCard1.ImagePath = null;
            beepCard1.InactiveBackColor = Color.Gray;
            beepCard1.InactiveBorderColor = Color.Gray;
            beepCard1.InactiveForeColor = Color.Black;
            beepCard1.IsAcceptButton = false;
            beepCard1.IsBorderAffectedByTheme = true;
            beepCard1.IsCancelButton = false;
            beepCard1.IsChild = false;
            beepCard1.IsCustomeBorder = false;
            beepCard1.IsDefault = false;
            beepCard1.IsFocused = false;
            beepCard1.IsFramless = false;
            beepCard1.IsHovered = false;
            beepCard1.IsPressed = false;
            beepCard1.IsRounded = true;
            beepCard1.IsRoundedAffectedByTheme = true;
            beepCard1.IsShadowAffectedByTheme = true;
            beepCard1.Location = new Point(25, 20);
            beepCard1.MaxImageSize = 64;
            beepCard1.Multiline = true;
            beepCard1.Name = "beepCard1";
            beepCard1.OverrideFontSize = TypeStyleFontSize.None;
            beepCard1.ParagraphText = resources.GetString("beepCard1.ParagraphText");
            beepCard1.ParentBackColor = Color.Empty;
            beepCard1.PressedBackColor = Color.Gray;
            beepCard1.PressedBorderColor = Color.Gray;
            beepCard1.PressedForeColor = Color.Black;
            beepCard1.SavedGuidID = null;
            beepCard1.SavedID = null;
            beepCard1.ShadowColor = Color.Black;
            beepCard1.ShadowOffset = 0;
            beepCard1.ShadowOpacity = 0.5F;
            beepCard1.ShowAllBorders = false;
            beepCard1.ShowBottomBorder = false;
            beepCard1.ShowFocusIndicator = false;
            beepCard1.ShowLeftBorder = false;
            beepCard1.ShowRightBorder = false;
            beepCard1.ShowShadow = false;
            beepCard1.ShowTopBorder = false;
            beepCard1.Size = new Size(319, 158);
            beepCard1.SlideFrom = SlideDirection.Left;
            beepCard1.StaticNotMoving = false;
            beepCard1.TabIndex = 7;
            beepCard1.Text = "beepCard1";
            beepCard1.TextAlignment = ContentAlignment.BottomCenter;
            beepCard1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepCard1.ToolTipText = "";
            beepCard1.UseGradientBackground = false;
            // 
            // panel1
            // 
            panel1.BackColor = Color.FromArgb(248, 248, 255);
            panel1.Controls.Add(beepImage1);
            panel1.Controls.Add(beepButton2);
            panel1.Controls.Add(beepButton1);
            panel1.Controls.Add(beepTree1);
            panel1.Controls.Add(beepCard1);
            panel1.Dock = DockStyle.Fill;
            panel1.Location = new Point(214, 76);
            panel1.Name = "panel1";
            panel1.Size = new Size(728, 697);
            panel1.TabIndex = 8;
            // 
            // beepImage1
            // 
            beepImage1.ActiveBackColor = Color.FromArgb(72, 61, 139);
            beepImage1.AnimationDuration = 500;
            beepImage1.AnimationType = DisplayAnimationType.None;
            beepImage1.ApplyThemeOnImage = false;
            beepImage1.ApplyThemeToChilds = true;
            beepImage1.BackColor = Color.FromArgb(248, 248, 255);
            beepImage1.BlockID = null;
            beepImage1.BorderColor = Color.FromArgb(218, 165, 32);
            beepImage1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepImage1.BorderRadius = 5;
            beepImage1.BorderStyle = BorderStyle.FixedSingle;
            beepImage1.BorderThickness = 1;
            beepImage1.DataContext = null;
            beepImage1.DisabledBackColor = Color.Gray;
            beepImage1.DisabledForeColor = Color.Empty;
            beepImage1.DrawingRect = new Rectangle(1, 1, 98, 98);
            beepImage1.Easing = EasingType.Linear;
            beepImage1.FieldID = null;
            beepImage1.FocusBackColor = Color.FromArgb(72, 61, 139);
            beepImage1.FocusBorderColor = Color.Gray;
            beepImage1.FocusForeColor = Color.FromArgb(255, 215, 0);
            beepImage1.FocusIndicatorColor = Color.Blue;
            beepImage1.Form = null;
            beepImage1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepImage1.GradientEndColor = Color.FromArgb(75, 0, 130);
            beepImage1.GradientStartColor = Color.FromArgb(248, 248, 255);
            beepImage1.HoverBackColor = Color.FromArgb(85, 26, 139);
            beepImage1.HoverBorderColor = Color.FromArgb(85, 26, 139);
            beepImage1.HoveredBackcolor = Color.Wheat;
            beepImage1.HoverForeColor = Color.FromArgb(255, 215, 0);
            beepImage1.Id = -1;
            beepImage1.Image = null;
            beepImage1.ImagePath = null;
            beepImage1.InactiveBackColor = Color.Gray;
            beepImage1.InactiveBorderColor = Color.Gray;
            beepImage1.InactiveForeColor = Color.Black;
            beepImage1.IsAcceptButton = false;
            beepImage1.IsBorderAffectedByTheme = true;
            beepImage1.IsCancelButton = false;
            beepImage1.IsChild = false;
            beepImage1.IsCustomeBorder = false;
            beepImage1.IsDefault = false;
            beepImage1.IsFocused = false;
            beepImage1.IsFramless = false;
            beepImage1.IsHovered = false;
            beepImage1.IsPressed = false;
            beepImage1.IsRounded = true;
            beepImage1.IsRoundedAffectedByTheme = true;
            beepImage1.IsShadowAffectedByTheme = true;
            beepImage1.IsStillImage = false;
            beepImage1.Location = new Point(452, 367);
            beepImage1.Name = "beepImage1";
            beepImage1.OverrideFontSize = TypeStyleFontSize.None;
            beepImage1.ParentBackColor = Color.Empty;
            beepImage1.PressedBackColor = Color.FromArgb(72, 61, 139);
            beepImage1.PressedBorderColor = Color.Gray;
            beepImage1.PressedForeColor = Color.FromArgb(255, 215, 0);
            beepImage1.SavedGuidID = null;
            beepImage1.SavedID = null;
            beepImage1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepImage1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepImage1.ShadowOffset = 0;
            beepImage1.ShadowOpacity = 0.5F;
            beepImage1.ShowAllBorders = true;
            beepImage1.ShowBottomBorder = true;
            beepImage1.ShowFocusIndicator = false;
            beepImage1.ShowLeftBorder = true;
            beepImage1.ShowRightBorder = true;
            beepImage1.ShowShadow = false;
            beepImage1.ShowTopBorder = true;
            beepImage1.Size = new Size(100, 100);
            beepImage1.SlideFrom = SlideDirection.Left;
            beepImage1.StaticNotMoving = false;
            beepImage1.TabIndex = 11;
            beepImage1.Text = "beepImage1";
            beepImage1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepImage1.ToolTipText = "";
            beepImage1.UseGradientBackground = false;
            // 
            // beepButton2
            // 
            beepButton2.ActiveBackColor = Color.Gray;
            beepButton2.AnimationDuration = 500;
            beepButton2.AnimationType = DisplayAnimationType.None;
            beepButton2.ApplyThemeOnImage = false;
            beepButton2.ApplyThemeToChilds = true;
            beepButton2.BackColor = Color.FromArgb(248, 248, 255);
            beepButton2.BlockID = null;
            beepButton2.BorderColor = Color.Black;
            beepButton2.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton2.BorderRadius = 5;
            beepButton2.BorderSize = 1;
            beepButton2.BorderStyle = BorderStyle.FixedSingle;
            beepButton2.BorderThickness = 1;
            beepButton2.DataContext = null;
            beepButton2.DisabledBackColor = Color.Gray;
            beepButton2.DisabledForeColor = Color.Empty;
            beepButton2.DrawingRect = new Rectangle(1, 1, 13, 13);
            beepButton2.Easing = EasingType.Linear;
            beepButton2.FieldID = null;
            beepButton2.FlatAppearance = true;
            beepButton2.FlatStyle = FlatStyle.Standard;
            beepButton2.FocusBackColor = Color.Gray;
            beepButton2.FocusBorderColor = Color.Gray;
            beepButton2.FocusForeColor = Color.Black;
            beepButton2.FocusIndicatorColor = Color.Blue;
            beepButton2.Font = new Font("Segoe UI", 12F);
            beepButton2.ForeColor = Color.FromArgb(255, 215, 0);
            beepButton2.Form = null;
            beepButton2.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton2.GradientEndColor = Color.Gray;
            beepButton2.GradientStartColor = Color.Gray;
            beepButton2.HideText = false;
            beepButton2.HoverBackColor = Color.Gray;
            beepButton2.HoverBorderColor = Color.Gray;
            beepButton2.HoveredBackcolor = Color.Wheat;
            beepButton2.HoverForeColor = Color.Black;
            beepButton2.Id = -1;
            beepButton2.Image = null;
            beepButton2.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton2.ImageClicked = null;
            beepButton2.ImagePath = null;
            beepButton2.InactiveBackColor = Color.Gray;
            beepButton2.InactiveBorderColor = Color.Gray;
            beepButton2.InactiveForeColor = Color.Black;
            beepButton2.IsAcceptButton = false;
            beepButton2.IsBorderAffectedByTheme = true;
            beepButton2.IsCancelButton = false;
            beepButton2.IsChild = true;
            beepButton2.IsCustomeBorder = false;
            beepButton2.IsDefault = false;
            beepButton2.IsFocused = false;
            beepButton2.IsFramless = false;
            beepButton2.IsHovered = false;
            beepButton2.IsPressed = false;
            beepButton2.IsRounded = true;
            beepButton2.IsRoundedAffectedByTheme = true;
            beepButton2.IsSelected = false;
            beepButton2.IsShadowAffectedByTheme = true;
            beepButton2.IsSideMenuChild = false;
            beepButton2.IsStillButton = false;
            beepButton2.Location = new Point(385, 318);
            beepButton2.Margin = new Padding(0);
            beepButton2.MaxImageSize = new Size(32, 32);
            beepButton2.Name = "beepButton2";
            beepButton2.OverrideFontSize = TypeStyleFontSize.None;
            beepButton2.ParentBackColor = Color.FromArgb(248, 248, 255);
            beepButton2.PressedBackColor = Color.Gray;
            beepButton2.PressedBorderColor = Color.Gray;
            beepButton2.PressedForeColor = Color.Black;
            beepButton2.SavedGuidID = null;
            beepButton2.SavedID = null;
            beepButton2.SelectedBorderColor = Color.Blue;
            beepButton2.ShadowColor = Color.Black;
            beepButton2.ShadowOffset = 0;
            beepButton2.ShadowOpacity = 0.5F;
            beepButton2.ShowAllBorders = true;
            beepButton2.ShowBottomBorder = true;
            beepButton2.ShowFocusIndicator = false;
            beepButton2.ShowLeftBorder = true;
            beepButton2.ShowRightBorder = true;
            beepButton2.ShowShadow = false;
            beepButton2.ShowTopBorder = true;
            beepButton2.Size = new Size(15, 15);
            beepButton2.SlideFrom = SlideDirection.Left;
            beepButton2.StaticNotMoving = false;
            beepButton2.TabIndex = 10;
            beepButton2.Text = "+";
            beepButton2.TextAlign = ContentAlignment.MiddleCenter;
            beepButton2.TextImageRelation = TextImageRelation.TextAboveImage;
            beepButton2.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepButton2.ToolTipText = "";
            beepButton2.UseGradientBackground = false;
            // 
            // beepButton1
            // 
            beepButton1.ActiveBackColor = Color.Gray;
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.ApplyThemeToChilds = true;
            beepButton1.BackColor = Color.FromArgb(248, 248, 255);
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.Black;
            beepButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton1.BorderRadius = 5;
            beepButton1.BorderSize = 1;
            beepButton1.BorderStyle = BorderStyle.FixedSingle;
            beepButton1.BorderThickness = 1;
            beepButton1.DataContext = null;
            beepButton1.DisabledBackColor = Color.Gray;
            beepButton1.DisabledForeColor = Color.Empty;
            beepButton1.DrawingRect = new Rectangle(1, 1, 139, 38);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.FieldID = null;
            beepButton1.FlatAppearance = true;
            beepButton1.FlatStyle = FlatStyle.Standard;
            beepButton1.FocusBackColor = Color.Gray;
            beepButton1.FocusBorderColor = Color.Gray;
            beepButton1.FocusForeColor = Color.Black;
            beepButton1.FocusIndicatorColor = Color.Blue;
            beepButton1.Font = new Font("Segoe UI", 12F);
            beepButton1.ForeColor = Color.FromArgb(255, 215, 0);
            beepButton1.Form = null;
            beepButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.Gray;
            beepButton1.GradientStartColor = Color.Gray;
            beepButton1.HideText = false;
            beepButton1.HoverBackColor = Color.Gray;
            beepButton1.HoverBorderColor = Color.Gray;
            beepButton1.HoveredBackcolor = Color.Wheat;
            beepButton1.HoverForeColor = Color.Black;
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleCenter;
            beepButton1.ImageClicked = null;
            beepButton1.ImagePath = null;
            beepButton1.InactiveBackColor = Color.Gray;
            beepButton1.InactiveBorderColor = Color.Gray;
            beepButton1.InactiveForeColor = Color.Black;
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = true;
            beepButton1.IsCustomeBorder = false;
            beepButton1.IsDefault = false;
            beepButton1.IsFocused = false;
            beepButton1.IsFramless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsPressed = false;
            beepButton1.IsRounded = true;
            beepButton1.IsRoundedAffectedByTheme = true;
            beepButton1.IsSelected = false;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.Location = new Point(390, 250);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaxImageSize = new Size(32, 32);
            beepButton1.Name = "beepButton1";
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.ParentBackColor = Color.FromArgb(248, 248, 255);
            beepButton1.PressedBackColor = Color.Gray;
            beepButton1.PressedBorderColor = Color.Gray;
            beepButton1.PressedForeColor = Color.Black;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.SelectedBorderColor = Color.Blue;
            beepButton1.ShadowColor = Color.Black;
            beepButton1.ShadowOffset = 0;
            beepButton1.ShadowOpacity = 0.5F;
            beepButton1.ShowAllBorders = false;
            beepButton1.ShowBottomBorder = false;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowLeftBorder = false;
            beepButton1.ShowRightBorder = false;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = false;
            beepButton1.Size = new Size(141, 40);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 9;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleLeft;
            beepButton1.TextImageRelation = TextImageRelation.TextBeforeImage;
            beepButton1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepButton1.ToolTipText = "";
            beepButton1.UseGradientBackground = false;
            // 
            // beepTree1
            // 
            beepTree1.ActiveBackColor = Color.FromArgb(72, 61, 139);
            beepTree1.AnimationDuration = 500;
            beepTree1.AnimationType = DisplayAnimationType.None;
            beepTree1.ApplyThemeToChilds = false;
            beepTree1.BackColor = Color.FromArgb(72, 61, 139);
            beepTree1.BlockID = null;
            beepTree1.BorderColor = Color.FromArgb(218, 165, 32);
            beepTree1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepTree1.BorderRadius = 5;
            beepTree1.BorderStyle = BorderStyle.FixedSingle;
            beepTree1.BorderThickness = 1;
            beepTree1.DataContext = null;
            beepTree1.DisabledBackColor = Color.Gray;
            beepTree1.DisabledForeColor = Color.Empty;
            beepTree1.DrawingRect = new Rectangle(1, 1, 190, 422);
            beepTree1.Easing = EasingType.Linear;
            beepTree1.FieldID = null;
            beepTree1.FocusBackColor = Color.FromArgb(255, 215, 0);
            beepTree1.FocusBorderColor = Color.Gray;
            beepTree1.FocusForeColor = Color.Black;
            beepTree1.FocusIndicatorColor = Color.Blue;
            beepTree1.Form = null;
            beepTree1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepTree1.GradientEndColor = Color.FromArgb(75, 0, 130);
            beepTree1.GradientStartColor = Color.FromArgb(248, 248, 255);
            beepTree1.HoverBackColor = Color.FromArgb(85, 26, 139);
            beepTree1.HoverBorderColor = Color.FromArgb(85, 26, 139);
            beepTree1.HoveredBackcolor = Color.Wheat;
            beepTree1.HoverForeColor = Color.Black;
            beepTree1.Id = -1;
            beepTree1.InactiveBackColor = Color.Gray;
            beepTree1.InactiveBorderColor = Color.Gray;
            beepTree1.InactiveForeColor = Color.Black;
            beepTree1.IsAcceptButton = false;
            beepTree1.IsBorderAffectedByTheme = true;
            beepTree1.IsCancelButton = false;
            beepTree1.IsChild = false;
            beepTree1.IsCustomeBorder = false;
            beepTree1.IsDefault = false;
            beepTree1.IsFocused = false;
            beepTree1.IsFramless = false;
            beepTree1.IsHovered = false;
            beepTree1.IsPressed = false;
            beepTree1.IsRounded = true;
            beepTree1.IsRoundedAffectedByTheme = true;
            beepTree1.IsShadowAffectedByTheme = true;
            beepTree1.Location = new Point(133, 184);
            beepTree1.Name = "beepTree1";
            beepTree1.NodeHeight = 20;
            beepTree1.Nodes.Add((Template.SimpleItem)resources.GetObject("beepTree1.Nodes"));
            beepTree1.Nodes.Add((Template.SimpleItem)resources.GetObject("beepTree1.Nodes1"));
            beepTree1.Nodes.Add((Template.SimpleItem)resources.GetObject("beepTree1.Nodes2"));
            beepTree1.Nodes.Add((Template.SimpleItem)resources.GetObject("beepTree1.Nodes3"));
            beepTree1.NodeWidth = 100;
            beepTree1.OverrideFontSize = TypeStyleFontSize.None;
            beepTree1.ParentBackColor = Color.Empty;
            beepTree1.PressedBackColor = Color.FromArgb(72, 61, 139);
            beepTree1.PressedBorderColor = Color.Gray;
            beepTree1.PressedForeColor = Color.Black;
            beepTree1.SavedGuidID = null;
            beepTree1.SavedID = null;
            beepTree1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepTree1.ShadowOffset = 0;
            beepTree1.ShadowOpacity = 0.5F;
            beepTree1.ShowAllBorders = true;
            beepTree1.ShowBottomBorder = true;
            beepTree1.ShowFocusIndicator = false;
            beepTree1.ShowLeftBorder = true;
            beepTree1.ShowNodeImage = false;
            beepTree1.ShowRightBorder = true;
            beepTree1.ShowShadow = false;
            beepTree1.ShowTopBorder = true;
            beepTree1.Size = new Size(192, 424);
            beepTree1.SlideFrom = SlideDirection.Left;
            beepTree1.StaticNotMoving = false;
            beepTree1.TabIndex = 8;
            beepTree1.Text = "beepTree1";
            beepTree1.Theme = Vis.Modules.EnumBeepThemes.RoyalTheme;
            beepTree1.ToolTipText = "";
            beepTree1.UseGradientBackground = false;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(952, 783);
            Controls.Add(panel1);
            Controls.Add(beepAppBar1);
            Controls.Add(beepSideMenu1);
            Icon = (Icon)resources.GetObject("$this.Icon");
            Name = "Form1";
            Padding = new Padding(10);
            Text = "Form1";
            Controls.SetChildIndex(beepSideMenu1, 0);
            Controls.SetChildIndex(beepAppBar1, 0);
            Controls.SetChildIndex(panel1, 0);
            panel1.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion
        private BeepSimpleGrid beepSimpleGrid1;
        private BeepDatePicker beepDatePicker1;
        
        private BeepAppBar beepAppBar1;
        private BeepSideMenu beepSideMenu1;
        private BeepCard beepCard1;
        private Panel panel1;
        private BeepTree beepTree1;
        private BeepButton beepButton2;
        private BeepButton beepButton1;
        private BeepImage beepImage1;
    }
}