namespace TheTechIdea.Beep.Winform.Controls
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            beepButton1 = new BeepButton();
            beepLabel1 = new BeepLabel();
            beepMenuBar1 = new BeepMenuBar();
            beepCard1 = new BeepCard();
            beepImage1 = new BeepImage();
            beepButton2 = new BeepButton();
            beepAppBar2 = new BeepAppBar();
            SuspendLayout();
            // 
            // beepuiManager1
            // 
            beepuiManager1.BeepAppBar = beepAppBar2;
            beepuiManager1.ShowBorder = false;
            beepuiManager1.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            // 
            // beepButton1
            // 
            beepButton1.ActiveBackColor = Color.Gray;
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.ApplyThemeToChilds = true;
            beepButton1.BackColor = Color.White;
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.Black;
            beepButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton1.BorderRadius = 1;
            beepButton1.BorderSize = 1;
            beepButton1.BorderStyle = BorderStyle.FixedSingle;
            beepButton1.BorderThickness = 1;
            beepButton1.BottomoffsetForDrawingRect = 0;
            beepButton1.BoundProperty = null;
            beepButton1.CanBeFocused = true;
            beepButton1.CanBeHovered = true;
            beepButton1.CanBePressed = true;
            beepButton1.DataContext = null;
            beepButton1.DisabledBackColor = Color.Gray;
            beepButton1.DisabledForeColor = Color.Empty;
            beepButton1.DrawingRect = new Rectangle(0, 0, 120, 36);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.FieldID = null;
            beepButton1.FlatAppearance = true;
            beepButton1.FlatStyle = FlatStyle.Standard;
            beepButton1.FocusBackColor = Color.Gray;
            beepButton1.FocusBorderColor = Color.Gray;
            beepButton1.FocusForeColor = Color.Black;
            beepButton1.FocusIndicatorColor = Color.Blue;
            beepButton1.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            beepButton1.ForeColor = Color.FromArgb(33, 150, 243);
            beepButton1.Form = null;
            beepButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.Gray;
            beepButton1.GradientStartColor = Color.Gray;
            beepButton1.GuidID = "a1579445-901e-480f-9ecb-3c41caa5f14e";
            beepButton1.HideText = false;
            beepButton1.HoverBackColor = Color.FromArgb(156, 39, 176);
            beepButton1.HoverBorderColor = Color.Gray;
            beepButton1.HoveredBackcolor = Color.Wheat;
            beepButton1.HoverForeColor = Color.White;
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton1.ImageClicked = null;
            beepButton1.ImagePath = null;
            beepButton1.InactiveBackColor = Color.Gray;
            beepButton1.InactiveBorderColor = Color.Gray;
            beepButton1.InactiveForeColor = Color.Black;
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = false;
            beepButton1.IsCustomeBorder = false;
            beepButton1.IsDefault = false;
            beepButton1.IsFocused = false;
            beepButton1.IsFramless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsPopupOpen = false;
            beepButton1.IsPressed = false;
            beepButton1.IsRounded = true;
            beepButton1.IsRoundedAffectedByTheme = true;
            beepButton1.IsSelected = false;
            beepButton1.IsSelectedAuto = true;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.LeftoffsetForDrawingRect = 0;
            beepButton1.LinkedProperty = null;
            beepButton1.Location = new Point(727, 308);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaxImageSize = new Size(32, 32);
            beepButton1.Name = "beepButton1";
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.ParentBackColor = Color.Empty;
            beepButton1.PopupMode = false;
            beepButton1.PressedBackColor = Color.Gray;
            beepButton1.PressedBorderColor = Color.Gray;
            beepButton1.PressedForeColor = Color.Black;
            beepButton1.RightoffsetForDrawingRect = 0;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.SelectedBorderColor = Color.Blue;
            beepButton1.SelectedIndex = -1;
            beepButton1.ShadowColor = Color.Black;
            beepButton1.ShadowOffset = 0;
            beepButton1.ShadowOpacity = 0.5F;
            beepButton1.ShowAllBorders = false;
            beepButton1.ShowBottomBorder = false;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowLeftBorder = false;
            beepButton1.ShowRightBorder = false;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = false;
            beepButton1.Size = new Size(120, 36);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 1;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepButton1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton1.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepButton1.ToolTipText = "";
            beepButton1.TopoffsetForDrawingRect = 0;
            beepButton1.UseGradientBackground = false;
            beepButton1.UseScaledFont = false;
            // 
            // beepLabel1
            // 
            beepLabel1.ActiveBackColor = Color.Gray;
            beepLabel1.AnimationDuration = 500;
            beepLabel1.AnimationType = DisplayAnimationType.None;
            beepLabel1.ApplyThemeOnImage = false;
            beepLabel1.ApplyThemeToChilds = true;
            beepLabel1.BackColor = Color.White;
            beepLabel1.BlockID = null;
            beepLabel1.BorderColor = Color.Black;
            beepLabel1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepLabel1.BorderRadius = 1;
            beepLabel1.BorderStyle = BorderStyle.FixedSingle;
            beepLabel1.BorderThickness = 1;
            beepLabel1.BottomoffsetForDrawingRect = 0;
            beepLabel1.BoundProperty = "Text";
            beepLabel1.CanBeFocused = true;
            beepLabel1.CanBeHovered = false;
            beepLabel1.CanBePressed = true;
            beepLabel1.DataContext = null;
            beepLabel1.DisabledBackColor = Color.Gray;
            beepLabel1.DisabledForeColor = Color.Empty;
            beepLabel1.DrawingRect = new Rectangle(0, 0, 119, 26);
            beepLabel1.Easing = EasingType.Linear;
            beepLabel1.FieldID = null;
            beepLabel1.FocusBackColor = Color.Gray;
            beepLabel1.FocusBorderColor = Color.Gray;
            beepLabel1.FocusForeColor = Color.Black;
            beepLabel1.FocusIndicatorColor = Color.Blue;
            beepLabel1.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            beepLabel1.ForeColor = Color.Black;
            beepLabel1.Form = null;
            beepLabel1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepLabel1.GradientEndColor = Color.Gray;
            beepLabel1.GradientStartColor = Color.Gray;
            beepLabel1.GuidID = "167dc2e2-a371-40d8-8bee-a7fd55a6274c";
            beepLabel1.HideText = false;
            beepLabel1.HoverBackColor = Color.White;
            beepLabel1.HoverBorderColor = Color.Gray;
            beepLabel1.HoveredBackcolor = Color.Wheat;
            beepLabel1.HoverForeColor = Color.White;
            beepLabel1.Id = -1;
            beepLabel1.ImageAlign = ContentAlignment.MiddleLeft;
            beepLabel1.ImagePath = null;
            beepLabel1.InactiveBackColor = Color.Gray;
            beepLabel1.InactiveBorderColor = Color.Gray;
            beepLabel1.InactiveForeColor = Color.Black;
            beepLabel1.IsAcceptButton = false;
            beepLabel1.IsBorderAffectedByTheme = true;
            beepLabel1.IsCancelButton = false;
            beepLabel1.IsChild = true;
            beepLabel1.IsCustomeBorder = false;
            beepLabel1.IsDefault = false;
            beepLabel1.IsFocused = false;
            beepLabel1.IsFramless = false;
            beepLabel1.IsHovered = false;
            beepLabel1.IsPressed = false;
            beepLabel1.IsRounded = true;
            beepLabel1.IsRoundedAffectedByTheme = true;
            beepLabel1.IsShadowAffectedByTheme = true;
            beepLabel1.LabelBackColor = Color.White;
            beepLabel1.LeftoffsetForDrawingRect = 0;
            beepLabel1.LinkedProperty = null;
            beepLabel1.Location = new Point(713, 416);
            beepLabel1.Margin = new Padding(0);
            beepLabel1.MaxImageSize = new Size(16, 16);
            beepLabel1.MaximumSize = new Size(0, 26);
            beepLabel1.MinimumSize = new Size(0, 26);
            beepLabel1.Name = "beepLabel1";
            beepLabel1.OverrideFontSize = TypeStyleFontSize.None;
            beepLabel1.ParentBackColor = Color.White;
            beepLabel1.PressedBackColor = Color.Gray;
            beepLabel1.PressedBorderColor = Color.Gray;
            beepLabel1.PressedForeColor = Color.Black;
            beepLabel1.RightoffsetForDrawingRect = 0;
            beepLabel1.SavedGuidID = null;
            beepLabel1.SavedID = null;
            beepLabel1.ShadowColor = Color.Black;
            beepLabel1.ShadowOffset = 0;
            beepLabel1.ShadowOpacity = 0.5F;
            beepLabel1.ShowAllBorders = false;
            beepLabel1.ShowBottomBorder = false;
            beepLabel1.ShowFocusIndicator = false;
            beepLabel1.ShowLeftBorder = false;
            beepLabel1.ShowRightBorder = false;
            beepLabel1.ShowShadow = false;
            beepLabel1.ShowTopBorder = false;
            beepLabel1.Size = new Size(119, 26);
            beepLabel1.SlideFrom = SlideDirection.Left;
            beepLabel1.StaticNotMoving = false;
            beepLabel1.TabIndex = 2;
            beepLabel1.Text = "beepLabel1";
            beepLabel1.TextAlign = ContentAlignment.MiddleLeft;
            beepLabel1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepLabel1.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepLabel1.ToolTipText = "";
            beepLabel1.TopoffsetForDrawingRect = 0;
            beepLabel1.UseGradientBackground = false;
            beepLabel1.UseScaledFont = false;
            // 
            // beepMenuBar1
            // 
            beepMenuBar1.ActiveBackColor = Color.White;
            beepMenuBar1.AnimationDuration = 500;
            beepMenuBar1.AnimationType = DisplayAnimationType.None;
            beepMenuBar1.ApplyThemeToChilds = true;
            beepMenuBar1.BackColor = Color.FromArgb(245, 245, 245);
            beepMenuBar1.BlockID = null;
            beepMenuBar1.BorderColor = Color.LightGray;
            beepMenuBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepMenuBar1.BorderRadius = 1;
            beepMenuBar1.BorderStyle = BorderStyle.FixedSingle;
            beepMenuBar1.BorderThickness = 1;
            beepMenuBar1.BottomoffsetForDrawingRect = 0;
            beepMenuBar1.BoundProperty = "SelectedItem";
            beepMenuBar1.CanBeFocused = true;
            beepMenuBar1.CanBeHovered = false;
            beepMenuBar1.CanBePressed = true;
            beepMenuBar1.DataContext = null;
            beepMenuBar1.DisabledBackColor = Color.Gray;
            beepMenuBar1.DisabledForeColor = Color.Empty;
            beepMenuBar1.Dock = DockStyle.Top;
            beepMenuBar1.DrawingRect = new Rectangle(0, 0, 956, 25);
            beepMenuBar1.Easing = EasingType.Linear;
            beepMenuBar1.FieldID = null;
            beepMenuBar1.FocusBackColor = Color.FromArgb(33, 150, 243);
            beepMenuBar1.FocusBorderColor = Color.Gray;
            beepMenuBar1.FocusForeColor = Color.Black;
            beepMenuBar1.FocusIndicatorColor = Color.Blue;
            beepMenuBar1.Form = null;
            beepMenuBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepMenuBar1.GradientEndColor = Color.White;
            beepMenuBar1.GradientStartColor = Color.White;
            beepMenuBar1.GuidID = "e80474e6-58a7-48f3-a509-03d4d80fa984";
            beepMenuBar1.HoverBackColor = Color.FromArgb(156, 39, 176);
            beepMenuBar1.HoverBorderColor = Color.FromArgb(30, 136, 229);
            beepMenuBar1.HoveredBackcolor = Color.Wheat;
            beepMenuBar1.HoverForeColor = Color.Black;
            beepMenuBar1.Id = -1;
            beepMenuBar1.InactiveBackColor = Color.Gray;
            beepMenuBar1.InactiveBorderColor = Color.Gray;
            beepMenuBar1.InactiveForeColor = Color.Black;
            beepMenuBar1.IsAcceptButton = false;
            beepMenuBar1.IsBorderAffectedByTheme = true;
            beepMenuBar1.IsCancelButton = false;
            beepMenuBar1.IsChild = false;
            beepMenuBar1.IsCustomeBorder = false;
            beepMenuBar1.IsDefault = false;
            beepMenuBar1.IsFocused = false;
            beepMenuBar1.IsFramless = false;
            beepMenuBar1.IsHovered = false;
            beepMenuBar1.IsPressed = false;
            beepMenuBar1.IsRounded = true;
            beepMenuBar1.IsRoundedAffectedByTheme = true;
            beepMenuBar1.IsShadowAffectedByTheme = true;
            beepMenuBar1.LeftoffsetForDrawingRect = 0;
            beepMenuBar1.LinkedProperty = null;
            beepMenuBar1.ListItems.Add((Common.SimpleItem)resources.GetObject("beepMenuBar1.ListItems"));
            beepMenuBar1.ListItems.Add((Common.SimpleItem)resources.GetObject("beepMenuBar1.ListItems1"));
            beepMenuBar1.ListItems.Add((Common.SimpleItem)resources.GetObject("beepMenuBar1.ListItems2"));
            beepMenuBar1.ListItems.Add((Common.SimpleItem)resources.GetObject("beepMenuBar1.ListItems3"));
            beepMenuBar1.Location = new Point(3, 34);
            beepMenuBar1.Name = "beepMenuBar1";
            beepMenuBar1.OverrideFontSize = TypeStyleFontSize.None;
            beepMenuBar1.ParentBackColor = Color.Empty;
            beepMenuBar1.PressedBackColor = Color.White;
            beepMenuBar1.PressedBorderColor = Color.Gray;
            beepMenuBar1.PressedForeColor = Color.Black;
            beepMenuBar1.RightoffsetForDrawingRect = 0;
            beepMenuBar1.SavedGuidID = null;
            beepMenuBar1.SavedID = null;
            beepMenuBar1.SelectedIndex = -1;
            beepMenuBar1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepMenuBar1.ShadowOffset = 0;
            beepMenuBar1.ShadowOpacity = 0.5F;
            beepMenuBar1.ShowAllBorders = false;
            beepMenuBar1.ShowBottomBorder = false;
            beepMenuBar1.ShowFocusIndicator = false;
            beepMenuBar1.ShowLeftBorder = false;
            beepMenuBar1.ShowRightBorder = false;
            beepMenuBar1.ShowShadow = false;
            beepMenuBar1.ShowTopBorder = false;
            beepMenuBar1.Size = new Size(956, 25);
            beepMenuBar1.SlideFrom = SlideDirection.Left;
            beepMenuBar1.StaticNotMoving = false;
            beepMenuBar1.TabIndex = 4;
            beepMenuBar1.Text = "beepMenuBar1";
            beepMenuBar1.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepMenuBar1.ToolTipText = "";
            beepMenuBar1.TopoffsetForDrawingRect = 0;
            beepMenuBar1.UseGradientBackground = false;
            // 
            // beepCard1
            // 
            beepCard1.ActiveBackColor = Color.Gray;
            beepCard1.AnimationDuration = 500;
            beepCard1.AnimationType = DisplayAnimationType.None;
            beepCard1.ApplyThemeToChilds = false;
            beepCard1.BackColor = Color.FromArgb(236, 240, 241);
            beepCard1.BlockID = null;
            beepCard1.BorderColor = Color.Black;
            beepCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCard1.BorderRadius = 1;
            beepCard1.BorderStyle = BorderStyle.FixedSingle;
            beepCard1.BorderThickness = 1;
            beepCard1.BottomoffsetForDrawingRect = 0;
            beepCard1.BoundProperty = "ParagraphText";
            beepCard1.CanBeFocused = true;
            beepCard1.CanBeHovered = false;
            beepCard1.CanBePressed = true;
            beepCard1.DataContext = null;
            beepCard1.DisabledBackColor = Color.Gray;
            beepCard1.DisabledForeColor = Color.Empty;
            beepCard1.DrawingRect = new Rectangle(2, 2, 353, 279);
            beepCard1.Easing = EasingType.Linear;
            beepCard1.FieldID = null;
            beepCard1.FocusBackColor = Color.Gray;
            beepCard1.FocusBorderColor = Color.Gray;
            beepCard1.FocusForeColor = Color.Black;
            beepCard1.FocusIndicatorColor = Color.Blue;
            beepCard1.Form = null;
            beepCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCard1.GradientEndColor = Color.Gray;
            beepCard1.GradientStartColor = Color.Gray;
            beepCard1.GuidID = "fb0c961c-9e60-4cf3-a957-c1846f40e377";
            beepCard1.HeaderAlignment = ContentAlignment.TopLeft;
            beepCard1.HeaderText = "Card Title";
            beepCard1.HoverBackColor = Color.Gray;
            beepCard1.HoverBorderColor = Color.Gray;
            beepCard1.HoveredBackcolor = Color.Wheat;
            beepCard1.HoverForeColor = Color.Black;
            beepCard1.Id = -1;
            beepCard1.ImageAlignment = ContentAlignment.TopRight;
            beepCard1.ImagePath = "H:\\dev\\iconPacks\\9632709-function-button\\9632709-function-button\\svg\\044-equalizer.svg";
            beepCard1.InactiveBackColor = Color.Gray;
            beepCard1.InactiveBorderColor = Color.Gray;
            beepCard1.InactiveForeColor = Color.Black;
            beepCard1.IsAcceptButton = false;
            beepCard1.IsBorderAffectedByTheme = true;
            beepCard1.IsCancelButton = false;
            beepCard1.IsChild = false;
            beepCard1.IsCustomeBorder = false;
            beepCard1.IsDefault = false;
            beepCard1.IsFocused = false;
            beepCard1.IsFramless = false;
            beepCard1.IsHovered = false;
            beepCard1.IsPressed = false;
            beepCard1.IsRounded = true;
            beepCard1.IsRoundedAffectedByTheme = true;
            beepCard1.IsShadowAffectedByTheme = true;
            beepCard1.LeftoffsetForDrawingRect = 0;
            beepCard1.LinkedProperty = null;
            beepCard1.Location = new Point(292, 281);
            beepCard1.MaxImageSize = 64;
            beepCard1.Name = "beepCard1";
            beepCard1.OverrideFontSize = TypeStyleFontSize.None;
            beepCard1.Padding = new Padding(2);
            beepCard1.ParagraphText = "Card Description";
            beepCard1.ParentBackColor = Color.Empty;
            beepCard1.PressedBackColor = Color.Gray;
            beepCard1.PressedBorderColor = Color.Gray;
            beepCard1.PressedForeColor = Color.Black;
            beepCard1.RightoffsetForDrawingRect = 0;
            beepCard1.SavedGuidID = null;
            beepCard1.SavedID = null;
            beepCard1.ShadowColor = Color.Black;
            beepCard1.ShadowOffset = 0;
            beepCard1.ShadowOpacity = 0.5F;
            beepCard1.ShowAllBorders = false;
            beepCard1.ShowBottomBorder = false;
            beepCard1.ShowFocusIndicator = false;
            beepCard1.ShowLeftBorder = false;
            beepCard1.ShowRightBorder = false;
            beepCard1.ShowShadow = false;
            beepCard1.ShowTopBorder = false;
            beepCard1.Size = new Size(357, 283);
            beepCard1.SlideFrom = SlideDirection.Left;
            beepCard1.StaticNotMoving = false;
            beepCard1.TabIndex = 6;
            beepCard1.Text = "beepCard1";
            beepCard1.TextAlignment = ContentAlignment.BottomCenter;
            beepCard1.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepCard1.ToolTipText = "";
            beepCard1.TopoffsetForDrawingRect = 0;
            beepCard1.UseGradientBackground = false;
            // 
            // beepImage1
            // 
            beepImage1.ActiveBackColor = Color.White;
            beepImage1.AllowManualRotation = true;
            beepImage1.AnimationDuration = 500;
            beepImage1.AnimationType = DisplayAnimationType.None;
            beepImage1.ApplyThemeOnImage = false;
            beepImage1.ApplyThemeToChilds = true;
            beepImage1.BlockID = null;
            beepImage1.BorderColor = Color.LightGray;
            beepImage1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepImage1.BorderRadius = 1;
            beepImage1.BorderStyle = BorderStyle.FixedSingle;
            beepImage1.BorderThickness = 1;
            beepImage1.BottomoffsetForDrawingRect = 0;
            beepImage1.BoundProperty = null;
            beepImage1.CanBeFocused = true;
            beepImage1.CanBeHovered = false;
            beepImage1.CanBePressed = true;
            beepImage1.DataContext = null;
            beepImage1.DisabledBackColor = Color.Gray;
            beepImage1.DisabledForeColor = Color.Empty;
            beepImage1.DrawingRect = new Rectangle(0, 0, 61, 60);
            beepImage1.Easing = EasingType.Linear;
            beepImage1.FieldID = null;
            beepImage1.FocusBackColor = Color.White;
            beepImage1.FocusBorderColor = Color.Gray;
            beepImage1.FocusForeColor = Color.FromArgb(33, 150, 243);
            beepImage1.FocusIndicatorColor = Color.Blue;
            beepImage1.Form = null;
            beepImage1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepImage1.GradientEndColor = Color.White;
            beepImage1.GradientStartColor = Color.White;
            beepImage1.GuidID = "e88b27a4-1f4f-4b54-b949-f24ef3a5c03c";
            beepImage1.HoverBackColor = Color.FromArgb(156, 39, 176);
            beepImage1.HoverBorderColor = Color.FromArgb(30, 136, 229);
            beepImage1.HoveredBackcolor = Color.Wheat;
            beepImage1.HoverForeColor = Color.White;
            beepImage1.Id = -1;
            beepImage1.Image = null;
            beepImage1.ImagePath = "H:\\dev\\iconPacks\\9632709-function-button\\9632709-function-button\\svg\\050-No.svg";
            beepImage1.InactiveBackColor = Color.Gray;
            beepImage1.InactiveBorderColor = Color.Gray;
            beepImage1.InactiveForeColor = Color.Black;
            beepImage1.IsAcceptButton = false;
            beepImage1.IsBorderAffectedByTheme = true;
            beepImage1.IsCancelButton = false;
            beepImage1.IsChild = false;
            beepImage1.IsCustomeBorder = false;
            beepImage1.IsDefault = false;
            beepImage1.IsFocused = false;
            beepImage1.IsFramless = false;
            beepImage1.IsHovered = false;
            beepImage1.IsPressed = false;
            beepImage1.IsRounded = true;
            beepImage1.IsRoundedAffectedByTheme = true;
            beepImage1.IsShadowAffectedByTheme = true;
            beepImage1.IsSpinning = false;
            beepImage1.IsStillImage = false;
            beepImage1.LeftoffsetForDrawingRect = 0;
            beepImage1.LinkedProperty = null;
            beepImage1.Location = new Point(561, 160);
            beepImage1.ManualRotationAngle = 0F;
            beepImage1.Name = "beepImage1";
            beepImage1.OverrideFontSize = TypeStyleFontSize.None;
            beepImage1.ParentBackColor = Color.Empty;
            beepImage1.PressedBackColor = Color.White;
            beepImage1.PressedBorderColor = Color.Gray;
            beepImage1.PressedForeColor = Color.FromArgb(33, 150, 243);
            beepImage1.RightoffsetForDrawingRect = 0;
            beepImage1.SavedGuidID = null;
            beepImage1.SavedID = null;
            beepImage1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepImage1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepImage1.ShadowOffset = 0;
            beepImage1.ShadowOpacity = 0.5F;
            beepImage1.ShowAllBorders = false;
            beepImage1.ShowBottomBorder = false;
            beepImage1.ShowFocusIndicator = false;
            beepImage1.ShowLeftBorder = false;
            beepImage1.ShowRightBorder = false;
            beepImage1.ShowShadow = false;
            beepImage1.ShowTopBorder = false;
            beepImage1.Size = new Size(61, 60);
            beepImage1.SlideFrom = SlideDirection.Left;
            beepImage1.SpinSpeed = 5F;
            beepImage1.StaticNotMoving = false;
            beepImage1.TabIndex = 7;
            beepImage1.Text = "beepImage1";
            beepImage1.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepImage1.ToolTipText = "";
            beepImage1.TopoffsetForDrawingRect = 0;
            beepImage1.UseGradientBackground = false;
            // 
            // beepButton2
            // 
            beepButton2.ActiveBackColor = Color.Gray;
            beepButton2.AnimationDuration = 500;
            beepButton2.AnimationType = DisplayAnimationType.None;
            beepButton2.ApplyThemeOnImage = false;
            beepButton2.ApplyThemeToChilds = true;
            beepButton2.BackColor = Color.White;
            beepButton2.BlockID = null;
            beepButton2.BorderColor = Color.Black;
            beepButton2.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton2.BorderRadius = 1;
            beepButton2.BorderSize = 1;
            beepButton2.BorderStyle = BorderStyle.FixedSingle;
            beepButton2.BorderThickness = 1;
            beepButton2.BottomoffsetForDrawingRect = 0;
            beepButton2.BoundProperty = null;
            beepButton2.CanBeFocused = true;
            beepButton2.CanBeHovered = true;
            beepButton2.CanBePressed = true;
            beepButton2.DataContext = null;
            beepButton2.DisabledBackColor = Color.Gray;
            beepButton2.DisabledForeColor = Color.Empty;
            beepButton2.DrawingRect = new Rectangle(0, 0, 120, 40);
            beepButton2.Easing = EasingType.Linear;
            beepButton2.FieldID = null;
            beepButton2.FlatAppearance = true;
            beepButton2.FlatStyle = FlatStyle.Standard;
            beepButton2.FocusBackColor = Color.Gray;
            beepButton2.FocusBorderColor = Color.Gray;
            beepButton2.FocusForeColor = Color.Black;
            beepButton2.FocusIndicatorColor = Color.Blue;
            beepButton2.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            beepButton2.ForeColor = Color.FromArgb(33, 150, 243);
            beepButton2.Form = null;
            beepButton2.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton2.GradientEndColor = Color.Gray;
            beepButton2.GradientStartColor = Color.Gray;
            beepButton2.GuidID = "2fea6ac5-0ace-422d-988a-5aaa5d1dad54";
            beepButton2.HideText = false;
            beepButton2.HoverBackColor = Color.FromArgb(156, 39, 176);
            beepButton2.HoverBorderColor = Color.Gray;
            beepButton2.HoveredBackcolor = Color.Wheat;
            beepButton2.HoverForeColor = Color.White;
            beepButton2.Id = -1;
            beepButton2.Image = null;
            beepButton2.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton2.ImageClicked = null;
            beepButton2.ImagePath = null;
            beepButton2.InactiveBackColor = Color.Gray;
            beepButton2.InactiveBorderColor = Color.Gray;
            beepButton2.InactiveForeColor = Color.Black;
            beepButton2.IsAcceptButton = false;
            beepButton2.IsBorderAffectedByTheme = true;
            beepButton2.IsCancelButton = false;
            beepButton2.IsChild = false;
            beepButton2.IsCustomeBorder = false;
            beepButton2.IsDefault = false;
            beepButton2.IsFocused = false;
            beepButton2.IsFramless = false;
            beepButton2.IsHovered = false;
            beepButton2.IsPopupOpen = false;
            beepButton2.IsPressed = false;
            beepButton2.IsRounded = true;
            beepButton2.IsRoundedAffectedByTheme = true;
            beepButton2.IsSelected = false;
            beepButton2.IsSelectedAuto = true;
            beepButton2.IsShadowAffectedByTheme = true;
            beepButton2.IsSideMenuChild = false;
            beepButton2.IsStillButton = false;
            beepButton2.LeftoffsetForDrawingRect = 0;
            beepButton2.LinkedProperty = null;
            beepButton2.Location = new Point(751, 200);
            beepButton2.Margin = new Padding(0);
            beepButton2.MaxImageSize = new Size(32, 32);
            beepButton2.Name = "beepButton2";
            beepButton2.OverrideFontSize = TypeStyleFontSize.None;
            beepButton2.ParentBackColor = Color.Empty;
            beepButton2.PopupMode = false;
            beepButton2.PressedBackColor = Color.Gray;
            beepButton2.PressedBorderColor = Color.Gray;
            beepButton2.PressedForeColor = Color.Black;
            beepButton2.RightoffsetForDrawingRect = 0;
            beepButton2.SavedGuidID = null;
            beepButton2.SavedID = null;
            beepButton2.SelectedBorderColor = Color.Blue;
            beepButton2.SelectedIndex = -1;
            beepButton2.ShadowColor = Color.Black;
            beepButton2.ShadowOffset = 0;
            beepButton2.ShadowOpacity = 0.5F;
            beepButton2.ShowAllBorders = false;
            beepButton2.ShowBottomBorder = false;
            beepButton2.ShowFocusIndicator = false;
            beepButton2.ShowLeftBorder = false;
            beepButton2.ShowRightBorder = false;
            beepButton2.ShowShadow = false;
            beepButton2.ShowTopBorder = false;
            beepButton2.Size = new Size(120, 40);
            beepButton2.SlideFrom = SlideDirection.Left;
            beepButton2.StaticNotMoving = false;
            beepButton2.TabIndex = 8;
            beepButton2.Text = "beepButton2";
            beepButton2.TextAlign = ContentAlignment.MiddleCenter;
            beepButton2.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton2.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepButton2.ToolTipText = "";
            beepButton2.TopoffsetForDrawingRect = 0;
            beepButton2.UseGradientBackground = false;
            beepButton2.UseScaledFont = false;
            // 
            // beepAppBar2
            // 
            beepAppBar2.ActiveBackColor = Color.White;
            beepAppBar2.AnimationDuration = 500;
            beepAppBar2.AnimationType = DisplayAnimationType.None;
            beepAppBar2.ApplyThemeOnImage = false;
            beepAppBar2.ApplyThemeToChilds = true;
            beepAppBar2.BackColor = Color.FromArgb(224, 224, 224);
            beepAppBar2.BlockID = null;
            beepAppBar2.BorderColor = Color.LightGray;
            beepAppBar2.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepAppBar2.BorderRadius = 1;
            beepAppBar2.BorderStyle = BorderStyle.FixedSingle;
            beepAppBar2.BorderThickness = 1;
            beepAppBar2.BottomoffsetForDrawingRect = 0;
            beepAppBar2.BoundProperty = null;
            beepAppBar2.CanBeFocused = true;
            beepAppBar2.CanBeHovered = false;
            beepAppBar2.CanBePressed = true;
            beepAppBar2.DataContext = null;
            beepAppBar2.DisabledBackColor = Color.Gray;
            beepAppBar2.DisabledForeColor = Color.Empty;
            beepAppBar2.Dock = DockStyle.Top;
            beepAppBar2.DrawingRect = new Rectangle(0, 0, 956, 31);
            beepAppBar2.Easing = EasingType.Linear;
            beepAppBar2.FieldID = null;
            beepAppBar2.FocusBackColor = Color.FromArgb(33, 150, 243);
            beepAppBar2.FocusBorderColor = Color.Gray;
            beepAppBar2.FocusForeColor = Color.Black;
            beepAppBar2.FocusIndicatorColor = Color.Blue;
            beepAppBar2.Form = null;
            beepAppBar2.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepAppBar2.GradientEndColor = Color.White;
            beepAppBar2.GradientStartColor = Color.White;
            beepAppBar2.GuidID = "235c3dd9-3d69-4dbb-b257-bcc8d5102970";
            beepAppBar2.HoverBackColor = Color.FromArgb(156, 39, 176);
            beepAppBar2.HoverBorderColor = Color.FromArgb(30, 136, 229);
            beepAppBar2.HoveredBackcolor = Color.Wheat;
            beepAppBar2.HoverForeColor = Color.Black;
            beepAppBar2.Id = -1;
            beepAppBar2.InactiveBackColor = Color.Gray;
            beepAppBar2.InactiveBorderColor = Color.Gray;
            beepAppBar2.InactiveForeColor = Color.Black;
            beepAppBar2.IsAcceptButton = false;
            beepAppBar2.IsBorderAffectedByTheme = false;
            beepAppBar2.IsCancelButton = false;
            beepAppBar2.IsChild = false;
            beepAppBar2.IsCustomeBorder = false;
            beepAppBar2.IsDefault = false;
            beepAppBar2.IsFocused = false;
            beepAppBar2.IsFramless = true;
            beepAppBar2.IsHovered = false;
            beepAppBar2.IsPressed = false;
            beepAppBar2.IsRounded = true;
            beepAppBar2.IsRoundedAffectedByTheme = false;
            beepAppBar2.IsShadowAffectedByTheme = false;
            beepAppBar2.LeftoffsetForDrawingRect = 0;
            beepAppBar2.LinkedProperty = null;
            beepAppBar2.Location = new Point(3, 3);
            beepAppBar2.Name = "beepAppBar2";
            beepAppBar2.OverrideFontSize = TypeStyleFontSize.None;
            beepAppBar2.ParentBackColor = Color.Empty;
            beepAppBar2.PressedBackColor = Color.White;
            beepAppBar2.PressedBorderColor = Color.Gray;
            beepAppBar2.PressedForeColor = Color.Black;
            beepAppBar2.RightoffsetForDrawingRect = 0;
            beepAppBar2.SavedGuidID = null;
            beepAppBar2.SavedID = null;
            beepAppBar2.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepAppBar2.ShadowOffset = 0;
            beepAppBar2.ShadowOpacity = 0.5F;
            beepAppBar2.ShowAllBorders = false;
            beepAppBar2.ShowBottomBorder = false;
            beepAppBar2.ShowCloseIcon = true;
            beepAppBar2.ShowFocusIndicator = false;
            beepAppBar2.ShowLeftBorder = false;
            beepAppBar2.ShowLogoIcon = true;
            beepAppBar2.ShowMaximizeIcon = true;
            beepAppBar2.ShowMinimizeIcon = true;
            beepAppBar2.ShowNotificationIcon = true;
            beepAppBar2.ShowProfileIcon = true;
            beepAppBar2.ShowRightBorder = false;
            beepAppBar2.ShowSearchBox = true;
            beepAppBar2.ShowShadow = false;
            beepAppBar2.ShowTopBorder = false;
            beepAppBar2.SideMenu = null;
            beepAppBar2.Size = new Size(956, 31);
            beepAppBar2.SlideFrom = SlideDirection.Left;
            beepAppBar2.StaticNotMoving = false;
            beepAppBar2.TabIndex = 9;
            beepAppBar2.Text = "beepAppBar2";
            beepAppBar2.Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            beepAppBar2.ToolTipText = "";
            beepAppBar2.TopoffsetForDrawingRect = 0;
            beepAppBar2.UseGradientBackground = false;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BorderColor = Color.LightGray;
            ClientSize = new Size(962, 705);
            Controls.Add(beepButton2);
            Controls.Add(beepImage1);
            Controls.Add(beepCard1);
            Controls.Add(beepMenuBar1);
            Controls.Add(beepLabel1);
            Controls.Add(beepButton1);
            Controls.Add(beepAppBar2);
            Name = "Form1";
            Text = "Form1";
            Theme = Vis.Modules.EnumBeepThemes.MaterialDesignTheme;
            ResumeLayout(false);
        }

        #endregion
        private BeepButton beepButton1;
        private BeepLabel beepLabel1;
        
        private BeepMenuBar beepMenuBar1;
        private BeepButton beepButtonPopList1;
        private BeepCard beepCard1;
        private BeepImage beepImage1;
        private BeepAppBar beepAppBar1;
        private BeepButton beepButton2;
        private BeepAppBar beepAppBar2;
    }
}