namespace TheTechIdea.Beep.Winform.Controls
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            beepAppBar1 = new BeepAppBar();
            beepTaskCard1 = new BeepTaskCard();
            beepProjectTaskCard1 = new BeepProjectTaskCard();
            SuspendLayout();
            // 
            // beepuiManager1
            // 
            beepuiManager1.BeepAppBar = beepAppBar1;
            beepuiManager1.BeepiForm = this;
            // 
            // beepAppBar1
            // 
            beepAppBar1.AnimationDuration = 500;
            beepAppBar1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepAppBar1.ApplyThemeButtons = true;
            beepAppBar1.ApplyThemeToChilds = false;
            beepAppBar1.AutoCompleteMode = AutoCompleteMode.None;
            beepAppBar1.AutoCompleteSource = AutoCompleteSource.None;
            beepAppBar1.BackColor = Color.FromArgb(33, 150, 243);
            beepAppBar1.BadgeBackColor = Color.Red;
            beepAppBar1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepAppBar1.BadgeForeColor = Color.White;
            beepAppBar1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepAppBar1.BadgeText = "";
            beepAppBar1.BlockID = null;
            beepAppBar1.BorderColor = Color.FromArgb(200, 200, 200);
            beepAppBar1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepAppBar1.BorderRadius = 8;
            beepAppBar1.BorderStyle = BorderStyle.FixedSingle;
            beepAppBar1.BorderThickness = 1;
            beepAppBar1.BottomoffsetForDrawingRect = 0;
            beepAppBar1.BoundProperty = null;
            beepAppBar1.CanBeFocused = true;
            beepAppBar1.CanBeHovered = false;
            beepAppBar1.CanBePressed = true;
            beepAppBar1.Category = Utilities.DbFieldCategory.String;
            beepAppBar1.ComponentName = "BeepControl";
            beepAppBar1.CurrentMenutems = (System.ComponentModel.BindingList<Models.SimpleItem>)resources.GetObject("beepAppBar1.CurrentMenutems");
            beepAppBar1.DataSourceProperty = null;
            beepAppBar1.DisabledBackColor = Color.White;
            beepAppBar1.DisabledBorderColor = Color.Empty;
            beepAppBar1.DisabledForeColor = Color.Black;
            beepAppBar1.DraggableAreas = (List<string>)resources.GetObject("beepAppBar1.DraggableAreas");
            beepAppBar1.DrawingRect = new Rectangle(1, 1, 236, 32);
            beepAppBar1.Easing = Vis.Modules.EasingType.Linear;
            beepAppBar1.EnableFormDragging = true;
            beepAppBar1.EnableRippleEffect = false;
            beepAppBar1.ExternalDrawingLayer = BeepControl.DrawingLayer.AfterAll;
            beepAppBar1.FieldID = null;
            beepAppBar1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepAppBar1.FloatingLabel = true;
            beepAppBar1.FocusBackColor = Color.White;
            beepAppBar1.FocusBorderColor = Color.RoyalBlue;
            beepAppBar1.FocusForeColor = Color.Black;
            beepAppBar1.FocusIndicatorColor = Color.Blue;
            beepAppBar1.ForeColor = Color.White;
            beepAppBar1.Form = null;
            beepAppBar1.GlassmorphismBlur = 10F;
            beepAppBar1.GlassmorphismOpacity = 0.1F;
            beepAppBar1.GradientAngle = 0F;
            beepAppBar1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            beepAppBar1.GradientEndColor = Color.FromArgb(25, 118, 210);
            beepAppBar1.GradientStartColor = Color.FromArgb(33, 150, 243);
            beepAppBar1.GridMode = false;
            beepAppBar1.GuidID = "c7762267-2e57-4d20-8468-edb519030b9d";
            beepAppBar1.HelperText = "";
            beepAppBar1.HitAreaEventOn = false;
            beepAppBar1.HitTestControl = null;
            beepAppBar1.HoverBackColor = Color.White;
            beepAppBar1.HoverBorderColor = Color.Gray;
            beepAppBar1.HoveredBackcolor = Color.Wheat;
            beepAppBar1.HoverForeColor = Color.Black;
            beepAppBar1.Id = -1;
            beepAppBar1.InactiveBorderColor = Color.Gray;
            beepAppBar1.IsAcceptButton = false;
            beepAppBar1.IsBorderAffectedByTheme = false;
            beepAppBar1.IsCancelButton = false;
            beepAppBar1.IsChild = false;
            beepAppBar1.IsCustomeBorder = false;
            beepAppBar1.IsDefault = false;
            beepAppBar1.IsDeleted = false;
            beepAppBar1.IsDirty = false;
            beepAppBar1.IsEditable = false;
            beepAppBar1.IsFocused = false;
            beepAppBar1.IsFrameless = false;
            beepAppBar1.IsHovered = false;
            beepAppBar1.IsNew = false;
            beepAppBar1.IsPressed = false;
            beepAppBar1.IsReadOnly = false;
            beepAppBar1.IsRequired = false;
            beepAppBar1.IsRounded = true;
            beepAppBar1.IsRoundedAffectedByTheme = false;
            beepAppBar1.IsSelected = false;
            beepAppBar1.IsSelectedOptionOn = false;
            beepAppBar1.IsShadowAffectedByTheme = false;
            beepAppBar1.IsVisible = false;
            beepAppBar1.Items = (List<object>)resources.GetObject("beepAppBar1.Items");
            beepAppBar1.LabelText = "";
            beepAppBar1.LeftoffsetForDrawingRect = 0;
            beepAppBar1.LinkedProperty = null;
            beepAppBar1.Location = new Point(185, 292);
            beepAppBar1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepAppBar1.ModernGradientType = Vis.Modules.ModernGradientType.Subtle;
            beepAppBar1.Name = "beepAppBar1";
            beepAppBar1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepAppBar1.ParentBackColor = Color.Empty;
            beepAppBar1.ParentControl = null;
            beepAppBar1.PopupListForm = null;
            beepAppBar1.PressedBackColor = Color.White;
            beepAppBar1.PressedBorderColor = Color.Gray;
            beepAppBar1.PressedForeColor = Color.Gray;
            beepAppBar1.RadialCenter = (PointF)resources.GetObject("beepAppBar1.RadialCenter");
            beepAppBar1.RightoffsetForDrawingRect = 0;
            beepAppBar1.SavedGuidID = null;
            beepAppBar1.SavedID = null;
            beepAppBar1.SearchBoxPlaceholder = " Search...";
            beepAppBar1.SearchBoxText = "";
            beepAppBar1.SelectedBackColor = Color.White;
            beepAppBar1.SelectedBorderColor = Color.Empty;
            beepAppBar1.SelectedForeColor = Color.Black;
            beepAppBar1.SelectedValue = null;
            beepAppBar1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepAppBar1.ShadowOffset = 0;
            beepAppBar1.ShadowOpacity = 0.5F;
            beepAppBar1.ShowAllBorders = true;
            beepAppBar1.ShowBottomBorder = true;
            beepAppBar1.ShowCloseIcon = true;
            beepAppBar1.ShowFocusIndicator = false;
            beepAppBar1.ShowLeftBorder = true;
            beepAppBar1.ShowLogo = true;
            beepAppBar1.ShowMaximizeIcon = true;
            beepAppBar1.ShowMinimizeIcon = true;
            beepAppBar1.ShowNotificationIcon = true;
            beepAppBar1.ShowProfileIcon = true;
            beepAppBar1.ShowRightBorder = true;
            beepAppBar1.ShowSearchBox = true;
            beepAppBar1.ShowShadow = false;
            beepAppBar1.ShowThemeIcon = true;
            beepAppBar1.ShowTitle = true;
            beepAppBar1.ShowTopBorder = true;
            beepAppBar1.Size = new Size(238, 34);
            beepAppBar1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepAppBar1.StaticNotMoving = false;
            beepAppBar1.TabIndex = 0;
            beepAppBar1.Tag = this;
            beepAppBar1.TempBackColor = Color.Empty;
            beepAppBar1.Text = "beepAppBar1";
            beepAppBar1.TextFont = new Font("Arial", 10F);
            beepAppBar1.Theme = "DefaultTheme";
            beepAppBar1.TitleFont = new Font("Arial", 18F);
            beepAppBar1.ToolTipText = "";
            beepAppBar1.TopoffsetForDrawingRect = 0;
            beepAppBar1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepAppBar1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepAppBar1.UICustomElevation = 0;
            beepAppBar1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepAppBar1.UIDisabled = false;
            beepAppBar1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepAppBar1.UIFullWidth = false;
            beepAppBar1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepAppBar1.UISize = Vis.Modules.ReactUISize.Medium;
            beepAppBar1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepAppBar1.UseGlassmorphism = false;
            beepAppBar1.UseGradientBackground = true;
            beepAppBar1.UseThemeFont = true;
            // 
            // beepTaskCard1
            // 
            beepTaskCard1.AnimationDuration = 500;
            beepTaskCard1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepTaskCard1.ApplyThemeToChilds = false;
            beepTaskCard1.AvatarImagePaths = (List<string>)resources.GetObject("beepTaskCard1.AvatarImagePaths");
            beepTaskCard1.BackColor = Color.White;
            beepTaskCard1.BadgeBackColor = Color.Red;
            beepTaskCard1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepTaskCard1.BadgeForeColor = Color.White;
            beepTaskCard1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepTaskCard1.BadgeText = "";
            beepTaskCard1.BlockID = null;
            beepTaskCard1.BorderColor = Color.White;
            beepTaskCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepTaskCard1.BorderRadius = 15;
            beepTaskCard1.BorderStyle = BorderStyle.FixedSingle;
            beepTaskCard1.BorderThickness = 1;
            beepTaskCard1.BottomoffsetForDrawingRect = 0;
            beepTaskCard1.BoundProperty = null;
            beepTaskCard1.CanBeFocused = true;
            beepTaskCard1.CanBeHovered = false;
            beepTaskCard1.CanBePressed = true;
            beepTaskCard1.Category = Utilities.DbFieldCategory.String;
            beepTaskCard1.ComponentName = "BeepControl";
            beepTaskCard1.DataSourceProperty = null;
            beepTaskCard1.DisabledBackColor = Color.White;
            beepTaskCard1.DisabledBorderColor = Color.Empty;
            beepTaskCard1.DisabledForeColor = Color.Black;
            beepTaskCard1.DrawingRect = new Rectangle(1, 1, 178, 238);
            beepTaskCard1.Easing = Vis.Modules.EasingType.Linear;
            beepTaskCard1.EnableRippleEffect = false;
            beepTaskCard1.ExternalDrawingLayer = BeepControl.DrawingLayer.AfterAll;
            beepTaskCard1.FieldID = null;
            beepTaskCard1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepTaskCard1.FloatingLabel = true;
            beepTaskCard1.FocusBackColor = Color.White;
            beepTaskCard1.FocusBorderColor = Color.RoyalBlue;
            beepTaskCard1.FocusForeColor = Color.Black;
            beepTaskCard1.FocusIndicatorColor = Color.Blue;
            beepTaskCard1.ForeColor = Color.FromArgb(33, 33, 33);
            beepTaskCard1.Form = null;
            beepTaskCard1.GlassmorphismBlur = 10F;
            beepTaskCard1.GlassmorphismOpacity = 0.1F;
            beepTaskCard1.GradientAngle = 0F;
            beepTaskCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            beepTaskCard1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepTaskCard1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepTaskCard1.GridMode = false;
            beepTaskCard1.GuidID = "b65b98d6-5a09-4e59-841c-4cc7cdce1847";
            beepTaskCard1.HelperText = "";
            beepTaskCard1.HitAreaEventOn = false;
            beepTaskCard1.HitTestControl = null;
            beepTaskCard1.HoverBackColor = Color.White;
            beepTaskCard1.HoverBorderColor = Color.Gray;
            beepTaskCard1.HoveredBackcolor = Color.Wheat;
            beepTaskCard1.HoverForeColor = Color.Black;
            beepTaskCard1.Id = -1;
            beepTaskCard1.InactiveBorderColor = Color.Gray;
            beepTaskCard1.IsAcceptButton = false;
            beepTaskCard1.IsBorderAffectedByTheme = true;
            beepTaskCard1.IsCancelButton = false;
            beepTaskCard1.IsChild = false;
            beepTaskCard1.IsCustomeBorder = false;
            beepTaskCard1.IsDefault = false;
            beepTaskCard1.IsDeleted = false;
            beepTaskCard1.IsDirty = false;
            beepTaskCard1.IsEditable = false;
            beepTaskCard1.IsFocused = false;
            beepTaskCard1.IsFrameless = false;
            beepTaskCard1.IsHovered = false;
            beepTaskCard1.IsNew = false;
            beepTaskCard1.IsPressed = false;
            beepTaskCard1.IsReadOnly = false;
            beepTaskCard1.IsRequired = false;
            beepTaskCard1.IsRounded = true;
            beepTaskCard1.IsRoundedAffectedByTheme = true;
            beepTaskCard1.IsSelected = false;
            beepTaskCard1.IsSelectedOptionOn = false;
            beepTaskCard1.IsShadowAffectedByTheme = true;
            beepTaskCard1.IsVisible = false;
            beepTaskCard1.Items = (List<object>)resources.GetObject("beepTaskCard1.Items");
            beepTaskCard1.LabelText = "";
            beepTaskCard1.LeftoffsetForDrawingRect = 0;
            beepTaskCard1.LinkedProperty = null;
            beepTaskCard1.Location = new Point(151, 26);
            beepTaskCard1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepTaskCard1.MetricText = "110 hours / 45%";
            beepTaskCard1.ModernGradientType = Vis.Modules.ModernGradientType.Subtle;
            beepTaskCard1.MoreIcon = "TheTechIdea.Beep.Winform.Controls.GFX.SVG.cat.svg";
            beepTaskCard1.Name = "beepTaskCard1";
            beepTaskCard1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepTaskCard1.ParentBackColor = Color.Empty;
            beepTaskCard1.ParentControl = null;
            beepTaskCard1.PressedBackColor = Color.White;
            beepTaskCard1.PressedBorderColor = Color.Gray;
            beepTaskCard1.PressedForeColor = Color.Gray;
            beepTaskCard1.ProgressValue = 45F;
            beepTaskCard1.RadialCenter = (PointF)resources.GetObject("beepTaskCard1.RadialCenter");
            beepTaskCard1.RightoffsetForDrawingRect = 0;
            beepTaskCard1.SavedGuidID = null;
            beepTaskCard1.SavedID = null;
            beepTaskCard1.SelectedBackColor = Color.White;
            beepTaskCard1.SelectedBorderColor = Color.Empty;
            beepTaskCard1.SelectedForeColor = Color.Black;
            beepTaskCard1.SelectedValue = null;
            beepTaskCard1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepTaskCard1.ShadowOffset = 0;
            beepTaskCard1.ShadowOpacity = 0.5F;
            beepTaskCard1.ShowAllBorders = true;
            beepTaskCard1.ShowBottomBorder = true;
            beepTaskCard1.ShowFocusIndicator = false;
            beepTaskCard1.ShowLeftBorder = true;
            beepTaskCard1.ShowRightBorder = true;
            beepTaskCard1.ShowShadow = false;
            beepTaskCard1.ShowTopBorder = true;
            beepTaskCard1.Size = new Size(180, 240);
            beepTaskCard1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepTaskCard1.StaticNotMoving = false;
            beepTaskCard1.SubtitleText = "Cryptocurrency";
            beepTaskCard1.TabIndex = 1;
            beepTaskCard1.Tag = this;
            beepTaskCard1.TempBackColor = Color.Empty;
            beepTaskCard1.Text = "beepTaskCard1";
            beepTaskCard1.Theme = "DefaultTheme";
            beepTaskCard1.TitleText = "Coin calc";
            beepTaskCard1.ToolTipText = "";
            beepTaskCard1.TopoffsetForDrawingRect = 0;
            beepTaskCard1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepTaskCard1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepTaskCard1.UICustomElevation = 0;
            beepTaskCard1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepTaskCard1.UIDisabled = false;
            beepTaskCard1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepTaskCard1.UIFullWidth = false;
            beepTaskCard1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepTaskCard1.UISize = Vis.Modules.ReactUISize.Medium;
            beepTaskCard1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepTaskCard1.UseGlassmorphism = false;
            beepTaskCard1.UseGradientBackground = true;
            beepTaskCard1.UseThemeFont = true;
            // 
            // beepProjectTaskCard1
            // 
            beepProjectTaskCard1.AnimationDuration = 500;
            beepProjectTaskCard1.AnimationType = Vis.Modules.DisplayAnimationType.None;
            beepProjectTaskCard1.ApplyThemeToChilds = false;
            beepProjectTaskCard1.BackColor = Color.White;
            beepProjectTaskCard1.BadgeBackColor = Color.Red;
            beepProjectTaskCard1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepProjectTaskCard1.BadgeForeColor = Color.White;
            beepProjectTaskCard1.BadgeShape = Vis.Modules.BadgeShape.Circle;
            beepProjectTaskCard1.BadgeText = "";
            beepProjectTaskCard1.BlockID = null;
            beepProjectTaskCard1.BorderColor = Color.LightGray;
            beepProjectTaskCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepProjectTaskCard1.BorderRadius = 12;
            beepProjectTaskCard1.BorderStyle = BorderStyle.FixedSingle;
            beepProjectTaskCard1.BorderThickness = 1;
            beepProjectTaskCard1.BottomoffsetForDrawingRect = 0;
            beepProjectTaskCard1.BoundProperty = null;
            beepProjectTaskCard1.CanBeFocused = true;
            beepProjectTaskCard1.CanBeHovered = false;
            beepProjectTaskCard1.CanBePressed = true;
            beepProjectTaskCard1.Category = Utilities.DbFieldCategory.String;
            beepProjectTaskCard1.CompactMode = false;
            beepProjectTaskCard1.CompletedTasks = 5;
            beepProjectTaskCard1.ComponentName = "BeepControl";
            beepProjectTaskCard1.CreatedDate = new DateTime(2025, 8, 17, 7, 5, 22, 142);
            beepProjectTaskCard1.DataSourceProperty = null;
            beepProjectTaskCard1.DisabledBackColor = Color.White;
            beepProjectTaskCard1.DisabledBorderColor = Color.Empty;
            beepProjectTaskCard1.DisabledForeColor = Color.Black;
            beepProjectTaskCard1.DrawingRect = new Rectangle(1, 1, 321, 333);
            beepProjectTaskCard1.DueDate = new DateTime(2025, 8, 24, 7, 5, 22, 142);
            beepProjectTaskCard1.Easing = Vis.Modules.EasingType.Linear;
            beepProjectTaskCard1.EnableRippleEffect = false;
            beepProjectTaskCard1.EstimatedHours = 120;
            beepProjectTaskCard1.ExternalDrawingLayer = BeepControl.DrawingLayer.AfterAll;
            beepProjectTaskCard1.FieldID = null;
            beepProjectTaskCard1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepProjectTaskCard1.FloatingLabel = true;
            beepProjectTaskCard1.FocusBackColor = Color.White;
            beepProjectTaskCard1.FocusBorderColor = Color.RoyalBlue;
            beepProjectTaskCard1.FocusForeColor = Color.Black;
            beepProjectTaskCard1.FocusIndicatorColor = Color.Blue;
            beepProjectTaskCard1.ForeColor = Color.Black;
            beepProjectTaskCard1.Form = null;
            beepProjectTaskCard1.GlassmorphismBlur = 10F;
            beepProjectTaskCard1.GlassmorphismOpacity = 0.1F;
            beepProjectTaskCard1.GradientAngle = 0F;
            beepProjectTaskCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            beepProjectTaskCard1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepProjectTaskCard1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepProjectTaskCard1.GridMode = false;
            beepProjectTaskCard1.GuidID = "583e4440-98a5-436d-ba57-98156ed0c029";
            beepProjectTaskCard1.HelperText = "";
            beepProjectTaskCard1.HitAreaEventOn = false;
            beepProjectTaskCard1.HitTestControl = null;
            beepProjectTaskCard1.HoursSpent = 85;
            beepProjectTaskCard1.HoverBackColor = Color.White;
            beepProjectTaskCard1.HoverBorderColor = Color.Gray;
            beepProjectTaskCard1.HoveredBackcolor = Color.Wheat;
            beepProjectTaskCard1.HoverForeColor = Color.Black;
            beepProjectTaskCard1.Id = -1;
            beepProjectTaskCard1.InactiveBorderColor = Color.Gray;
            beepProjectTaskCard1.IsAcceptButton = false;
            beepProjectTaskCard1.IsBorderAffectedByTheme = true;
            beepProjectTaskCard1.IsCancelButton = false;
            beepProjectTaskCard1.IsChild = false;
            beepProjectTaskCard1.IsCustomeBorder = false;
            beepProjectTaskCard1.IsDefault = false;
            beepProjectTaskCard1.IsDeleted = false;
            beepProjectTaskCard1.IsDirty = false;
            beepProjectTaskCard1.IsEditable = false;
            beepProjectTaskCard1.IsFocused = false;
            beepProjectTaskCard1.IsFrameless = false;
            beepProjectTaskCard1.IsHovered = false;
            beepProjectTaskCard1.IsNew = false;
            beepProjectTaskCard1.IsPressed = false;
            beepProjectTaskCard1.IsReadOnly = false;
            beepProjectTaskCard1.IsRequired = false;
            beepProjectTaskCard1.IsRounded = true;
            beepProjectTaskCard1.IsRoundedAffectedByTheme = true;
            beepProjectTaskCard1.IsSelected = false;
            beepProjectTaskCard1.IsSelectedOptionOn = false;
            beepProjectTaskCard1.IsShadowAffectedByTheme = true;
            beepProjectTaskCard1.IsVisible = false;
            beepProjectTaskCard1.Items = (List<object>)resources.GetObject("beepProjectTaskCard1.Items");
            beepProjectTaskCard1.LabelText = "";
            beepProjectTaskCard1.LeftoffsetForDrawingRect = 0;
            beepProjectTaskCard1.LinkedProperty = null;
            beepProjectTaskCard1.Location = new Point(450, 75);
            beepProjectTaskCard1.MaterialBorderVariant = Vis.Modules.MaterialTextFieldVariant.Standard;
            beepProjectTaskCard1.ModernGradientType = Vis.Modules.ModernGradientType.Subtle;
            beepProjectTaskCard1.Name = "beepProjectTaskCard1";
            beepProjectTaskCard1.OverrideFontSize = Vis.Modules.TypeStyleFontSize.None;
            beepProjectTaskCard1.ParentBackColor = Color.Empty;
            beepProjectTaskCard1.ParentControl = null;
            beepProjectTaskCard1.PressedBackColor = Color.White;
            beepProjectTaskCard1.PressedBorderColor = Color.Gray;
            beepProjectTaskCard1.PressedForeColor = Color.Gray;
            beepProjectTaskCard1.PriorityIconPath = "TheTechIdea.Beep.Winform.Controls.GFX.SVG.triangle-warning.svg";
            beepProjectTaskCard1.ProgressValue = 45F;
            beepProjectTaskCard1.ProjectCategory = "Development";
            beepProjectTaskCard1.ProjectDescription = "Project description goes here";
            beepProjectTaskCard1.ProjectManager = "Unassigned";
            beepProjectTaskCard1.ProjectPriority = "Medium";
            beepProjectTaskCard1.ProjectStatus = "In Progress";
            beepProjectTaskCard1.ProjectTitle = "New Project";
            beepProjectTaskCard1.RadialCenter = (PointF)resources.GetObject("beepProjectTaskCard1.RadialCenter");
            beepProjectTaskCard1.RightoffsetForDrawingRect = 0;
            beepProjectTaskCard1.SavedGuidID = null;
            beepProjectTaskCard1.SavedID = null;
            beepProjectTaskCard1.SelectedBackColor = Color.White;
            beepProjectTaskCard1.SelectedBorderColor = Color.Empty;
            beepProjectTaskCard1.SelectedForeColor = Color.Black;
            beepProjectTaskCard1.SelectedValue = null;
            beepProjectTaskCard1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepProjectTaskCard1.ShadowOffset = 0;
            beepProjectTaskCard1.ShadowOpacity = 0.5F;
            beepProjectTaskCard1.ShowActionButtons = true;
            beepProjectTaskCard1.ShowAllBorders = true;
            beepProjectTaskCard1.ShowBottomBorder = true;
            beepProjectTaskCard1.ShowDueDate = true;
            beepProjectTaskCard1.ShowFocusIndicator = false;
            beepProjectTaskCard1.ShowLeftBorder = true;
            beepProjectTaskCard1.ShowProgressBar = true;
            beepProjectTaskCard1.ShowRightBorder = true;
            beepProjectTaskCard1.ShowShadow = false;
            beepProjectTaskCard1.ShowTaskCount = true;
            beepProjectTaskCard1.ShowTeamAvatars = true;
            beepProjectTaskCard1.ShowTopBorder = true;
            beepProjectTaskCard1.Size = new Size(323, 335);
            beepProjectTaskCard1.SlideFrom = Vis.Modules.SlideDirection.Left;
            beepProjectTaskCard1.StaticNotMoving = false;
            beepProjectTaskCard1.StatusIconPath = "TheTechIdea.Beep.Winform.Controls.GFX.SVG.check-circle.svg";
            beepProjectTaskCard1.TabIndex = 2;
            beepProjectTaskCard1.Tag = this;
            beepProjectTaskCard1.TeamAvatarPaths = (List<string>)resources.GetObject("beepProjectTaskCard1.TeamAvatarPaths");
            beepProjectTaskCard1.TeamCount = "3";
            beepProjectTaskCard1.TempBackColor = Color.Empty;
            beepProjectTaskCard1.Text = "beepProjectTaskCard1";
            beepProjectTaskCard1.Theme = "DefaultTheme";
            beepProjectTaskCard1.ToolTipText = "";
            beepProjectTaskCard1.TopoffsetForDrawingRect = 0;
            beepProjectTaskCard1.TotalTasks = 12;
            beepProjectTaskCard1.UIAnimation = Vis.Modules.ReactUIAnimation.None;
            beepProjectTaskCard1.UIColor = Vis.Modules.ReactUIColor.Primary;
            beepProjectTaskCard1.UICustomElevation = 0;
            beepProjectTaskCard1.UIDensity = Vis.Modules.ReactUIDensity.Standard;
            beepProjectTaskCard1.UIDisabled = false;
            beepProjectTaskCard1.UIElevation = Vis.Modules.ReactUIElevation.None;
            beepProjectTaskCard1.UIFullWidth = false;
            beepProjectTaskCard1.UIShape = Vis.Modules.ReactUIShape.Rounded;
            beepProjectTaskCard1.UISize = Vis.Modules.ReactUISize.Medium;
            beepProjectTaskCard1.UIVariant = Vis.Modules.ReactUIVariant.Default;
            beepProjectTaskCard1.UseGlassmorphism = false;
            beepProjectTaskCard1.UseGradientBackground = true;
            beepProjectTaskCard1.UseThemeFont = true;
            // 
            // Form2
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BorderColor = Color.FromArgb(200, 200, 200);
            ClientSize = new Size(800, 450);
            Controls.Add(beepProjectTaskCard1);
            Controls.Add(beepTaskCard1);
            Controls.Add(beepAppBar1);
            Name = "Form2";
            Padding = new Padding(1);
            Text = "Form2";
            Theme = "DefaultTheme";
            ResumeLayout(false);
        }

        #endregion

        private BeepAppBar beepAppBar1;
        private BeepProjectTaskCard beepProjectTaskCard1;
        private BeepTaskCard beepTaskCard1;
    }
}