namespace TheTechIdea.Beep.Winform.Controls
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            beepSwitch1 = new BeepSwitch();
            beepCheckBox1 = new BeepCheckBox();
            beepButton1 = new BeepButton();
            beepCard1 = new BeepCard();
            beepLabel1 = new BeepLabel();
            SuspendLayout();
            // 
            // beepSwitch1
            // 
            beepSwitch1.ActiveBackColor = Color.FromArgb(128, 0, 0);
            beepSwitch1.AnimationDuration = 500;
            beepSwitch1.AnimationType = DisplayAnimationType.None;
            beepSwitch1.ApplyThemeToChilds = true;
            beepSwitch1.BackColor = Color.FromArgb(245, 222, 179);
            beepSwitch1.BlockID = null;
            beepSwitch1.BorderColor = Color.FromArgb(160, 82, 45);
            beepSwitch1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSwitch1.BorderRadius = 1;
            beepSwitch1.BorderStyle = BorderStyle.FixedSingle;
            beepSwitch1.BorderThickness = 1;
            beepSwitch1.BottomoffsetForDrawingRect = 0;
            beepSwitch1.BoundProperty = "Checked";
            beepSwitch1.CanBeFocused = true;
            beepSwitch1.CanBeHovered = false;
            beepSwitch1.CanBePressed = true;
            beepSwitch1.Category = Utilities.DbFieldCategory.String;
            beepSwitch1.Checked = false;
            beepSwitch1.ComponentName = "beepSwitch1";
            beepSwitch1.DataContext = null;
            beepSwitch1.DataSourceProperty = null;
            beepSwitch1.DisabledBackColor = Color.Gray;
            beepSwitch1.DisabledForeColor = Color.Empty;
            beepSwitch1.DrawingRect = new Rectangle(1, 1, 36, 165);
            beepSwitch1.Easing = EasingType.Linear;
            beepSwitch1.FieldID = null;
            beepSwitch1.FocusBackColor = Color.White;
            beepSwitch1.FocusBorderColor = Color.Gray;
            beepSwitch1.FocusForeColor = Color.Black;
            beepSwitch1.FocusIndicatorColor = Color.Blue;
            beepSwitch1.ForeColor = Color.FromArgb(80, 40, 20);
            beepSwitch1.Form = null;
            beepSwitch1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSwitch1.GradientEndColor = Color.FromArgb(222, 184, 135);
            beepSwitch1.GradientStartColor = Color.FromArgb(245, 222, 179);
            beepSwitch1.GuidID = "2154769f-a264-405d-a5f2-ebd157beb879";
            beepSwitch1.HoverBackColor = Color.FromArgb(139, 69, 19);
            beepSwitch1.HoverBorderColor = Color.FromArgb(205, 133, 63);
            beepSwitch1.HoveredBackcolor = Color.Wheat;
            beepSwitch1.HoverForeColor = Color.Black;
            beepSwitch1.Id = -1;
            beepSwitch1.InactiveBackColor = Color.Gray;
            beepSwitch1.InactiveBorderColor = Color.Gray;
            beepSwitch1.InactiveForeColor = Color.Black;
            beepSwitch1.IsAcceptButton = false;
            beepSwitch1.IsBorderAffectedByTheme = true;
            beepSwitch1.IsCancelButton = false;
            beepSwitch1.IsChild = false;
            beepSwitch1.IsCustomeBorder = false;
            beepSwitch1.IsDefault = false;
            beepSwitch1.IsDeleted = false;
            beepSwitch1.IsDirty = false;
            beepSwitch1.IsEditable = false;
            beepSwitch1.IsFocused = false;
            beepSwitch1.IsFramless = false;
            beepSwitch1.IsHovered = false;
            beepSwitch1.IsNew = false;
            beepSwitch1.IsPressed = false;
            beepSwitch1.IsReadOnly = false;
            beepSwitch1.IsRequired = false;
            beepSwitch1.IsRounded = true;
            beepSwitch1.IsRoundedAffectedByTheme = true;
            beepSwitch1.IsSelected = false;
            beepSwitch1.IsShadowAffectedByTheme = true;
            beepSwitch1.IsVisible = false;
            beepSwitch1.LeftoffsetForDrawingRect = 0;
            beepSwitch1.LinkedProperty = null;
            beepSwitch1.Location = new Point(63, 138);
            beepSwitch1.Name = "beepSwitch1";
            beepSwitch1.OffImage = null;
            beepSwitch1.OffImagePath = null;
            beepSwitch1.OffLabel = "Off";
            beepSwitch1.OnImage = null;
            beepSwitch1.OnImagePath = null;
            beepSwitch1.OnLabel = "On";
            beepSwitch1.Orientation = SwitchOrientation.Vertical;
            beepSwitch1.OverrideFontSize = TypeStyleFontSize.None;
            beepSwitch1.ParentBackColor = Color.Empty;
            beepSwitch1.ParentControl = null;
            beepSwitch1.PressedBackColor = Color.FromArgb(128, 0, 0);
            beepSwitch1.PressedBorderColor = Color.Gray;
            beepSwitch1.PressedForeColor = Color.Black;
            beepSwitch1.RightoffsetForDrawingRect = 0;
            beepSwitch1.SavedGuidID = null;
            beepSwitch1.SavedID = null;
            beepSwitch1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepSwitch1.ShadowOffset = 0;
            beepSwitch1.ShadowOpacity = 0.5F;
            beepSwitch1.ShowAllBorders = true;
            beepSwitch1.ShowBottomBorder = true;
            beepSwitch1.ShowFocusIndicator = false;
            beepSwitch1.ShowLeftBorder = true;
            beepSwitch1.ShowRightBorder = true;
            beepSwitch1.ShowShadow = false;
            beepSwitch1.ShowTopBorder = true;
            beepSwitch1.Size = new Size(38, 167);
            beepSwitch1.SlideFrom = SlideDirection.Left;
            beepSwitch1.StaticNotMoving = false;
            beepSwitch1.TabIndex = 4;
            beepSwitch1.TempBackColor = Color.Empty;
            beepSwitch1.Text = "beepSwitch1";
            beepSwitch1.Theme = Vis.Modules.EnumBeepThemes.RusticTheme;
            beepSwitch1.ToolTipText = "";
            beepSwitch1.TopoffsetForDrawingRect = 0;
            beepSwitch1.UseGradientBackground = false;
            beepSwitch1.UseThemeFont = true;
            // 
            // beepCheckBox1
            // 
            beepCheckBox1.ActiveBackColor = Color.Gray;
            beepCheckBox1.AnimationDuration = 500;
            beepCheckBox1.AnimationType = DisplayAnimationType.None;
            beepCheckBox1.ApplyThemeToChilds = true;
            beepCheckBox1.BackColor = Color.FromArgb(240, 240, 240);
            beepCheckBox1.BlockID = null;
            beepCheckBox1.BorderColor = Color.Black;
            beepCheckBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCheckBox1.BorderRadius = 1;
            beepCheckBox1.BorderStyle = BorderStyle.FixedSingle;
            beepCheckBox1.BorderThickness = 1;
            beepCheckBox1.BottomoffsetForDrawingRect = 0;
            beepCheckBox1.BoundProperty = "State";
            beepCheckBox1.CanBeFocused = true;
            beepCheckBox1.CanBeHovered = false;
            beepCheckBox1.CanBePressed = true;
            beepCheckBox1.Category = Utilities.DbFieldCategory.String;
            beepCheckBox1.ComponentName = "beepCheckBox1";
            beepCheckBox1.DataContext = null;
            beepCheckBox1.DataSourceProperty = null;
            beepCheckBox1.DisabledBackColor = Color.Gray;
            beepCheckBox1.DisabledForeColor = Color.Empty;
            beepCheckBox1.DrawingRect = new Rectangle(2, 2, 153, 49);
            beepCheckBox1.Easing = EasingType.Linear;
            beepCheckBox1.FieldID = null;
            beepCheckBox1.FocusBackColor = Color.Gray;
            beepCheckBox1.FocusBorderColor = Color.Gray;
            beepCheckBox1.FocusForeColor = Color.Black;
            beepCheckBox1.FocusIndicatorColor = Color.Blue;
            beepCheckBox1.ForeColor = Color.FromArgb(0, 0, 0);
            beepCheckBox1.Form = null;
            beepCheckBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCheckBox1.GradientEndColor = Color.Gray;
            beepCheckBox1.GradientStartColor = Color.Gray;
            beepCheckBox1.GuidID = "d8136910-0978-4fdf-8fe7-f3e4426f717a";
            beepCheckBox1.HideText = false;
            beepCheckBox1.HoverBackColor = Color.Gray;
            beepCheckBox1.HoverBorderColor = Color.Gray;
            beepCheckBox1.HoveredBackcolor = Color.Wheat;
            beepCheckBox1.HoverForeColor = Color.Black;
            beepCheckBox1.Id = -1;
            beepCheckBox1.ImagePath = null;
            beepCheckBox1.InactiveBackColor = Color.Gray;
            beepCheckBox1.InactiveBorderColor = Color.Gray;
            beepCheckBox1.InactiveForeColor = Color.Black;
            beepCheckBox1.IsAcceptButton = false;
            beepCheckBox1.IsBorderAffectedByTheme = true;
            beepCheckBox1.IsCancelButton = false;
            beepCheckBox1.IsChild = false;
            beepCheckBox1.IsCustomeBorder = false;
            beepCheckBox1.IsDefault = false;
            beepCheckBox1.IsDeleted = false;
            beepCheckBox1.IsDirty = false;
            beepCheckBox1.IsEditable = false;
            beepCheckBox1.IsFocused = false;
            beepCheckBox1.IsFramless = false;
            beepCheckBox1.IsHovered = false;
            beepCheckBox1.IsNew = false;
            beepCheckBox1.IsPressed = false;
            beepCheckBox1.IsReadOnly = false;
            beepCheckBox1.IsRequired = false;
            beepCheckBox1.IsRounded = true;
            beepCheckBox1.IsRoundedAffectedByTheme = true;
            beepCheckBox1.IsSelected = false;
            beepCheckBox1.IsShadowAffectedByTheme = true;
            beepCheckBox1.IsVisible = false;
            beepCheckBox1.LeftoffsetForDrawingRect = 0;
            beepCheckBox1.LinkedProperty = null;
            beepCheckBox1.Location = new Point(184, 30);
            beepCheckBox1.Name = "beepCheckBox1";
            beepCheckBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepCheckBox1.Padding = new Padding(1);
            beepCheckBox1.ParentBackColor = SystemColors.Control;
            beepCheckBox1.ParentControl = null;
            beepCheckBox1.PressedBackColor = Color.Gray;
            beepCheckBox1.PressedBorderColor = Color.Gray;
            beepCheckBox1.PressedForeColor = Color.Black;
            beepCheckBox1.RightoffsetForDrawingRect = 0;
            beepCheckBox1.SavedGuidID = null;
            beepCheckBox1.SavedID = null;
            beepCheckBox1.ShadowColor = Color.Black;
            beepCheckBox1.ShadowOffset = 0;
            beepCheckBox1.ShadowOpacity = 0.5F;
            beepCheckBox1.ShowAllBorders = true;
            beepCheckBox1.ShowBottomBorder = true;
            beepCheckBox1.ShowFocusIndicator = false;
            beepCheckBox1.ShowLeftBorder = true;
            beepCheckBox1.ShowRightBorder = true;
            beepCheckBox1.ShowShadow = false;
            beepCheckBox1.ShowTopBorder = true;
            beepCheckBox1.Size = new Size(157, 53);
            beepCheckBox1.SlideFrom = SlideDirection.Left;
            beepCheckBox1.Spacing = 5;
            beepCheckBox1.StaticNotMoving = false;
            beepCheckBox1.TabIndex = 5;
            beepCheckBox1.TempBackColor = Color.FromArgb(240, 240, 240);
            beepCheckBox1.Text = "beepCheckBox1";
            beepCheckBox1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepCheckBox1.ToolTipText = "";
            beepCheckBox1.TopoffsetForDrawingRect = 0;
            beepCheckBox1.UseGradientBackground = false;
            beepCheckBox1.UseThemeFont = true;
            // 
            // beepButton1
            // 
            beepButton1.ActiveBackColor = Color.FromArgb(45, 45, 48);
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.ApplyThemeToChilds = true;
            beepButton1.BackColor = Color.FromArgb(51, 51, 51);
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.Black;
            beepButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton1.BorderRadius = 1;
            beepButton1.BorderSize = 1;
            beepButton1.BorderStyle = BorderStyle.FixedSingle;
            beepButton1.BorderThickness = 1;
            beepButton1.BottomoffsetForDrawingRect = 0;
            beepButton1.BoundProperty = null;
            beepButton1.CanBeFocused = true;
            beepButton1.CanBeHovered = true;
            beepButton1.CanBePressed = true;
            beepButton1.Category = Utilities.DbFieldCategory.Boolean;
            beepButton1.ComponentName = "beepButton1";
            beepButton1.DataContext = null;
            beepButton1.DataSourceProperty = null;
            beepButton1.DisabledBackColor = Color.Gray;
            beepButton1.DisabledForeColor = Color.Empty;
            beepButton1.DrawingRect = new Rectangle(1, 1, 200, 32);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.FieldID = null;
            beepButton1.FocusBackColor = Color.Gray;
            beepButton1.FocusBorderColor = Color.Gray;
            beepButton1.FocusForeColor = Color.Black;
            beepButton1.FocusIndicatorColor = Color.Blue;
            beepButton1.Font = new Font("Segoe UI", 9F);
            beepButton1.ForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.Form = null;
            beepButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.Gray;
            beepButton1.GradientStartColor = Color.Gray;
            beepButton1.GuidID = "e15497db-d11e-495a-b901-9eff0cd9e977";
            beepButton1.HideText = false;
            beepButton1.HoverBackColor = Color.FromArgb(28, 151, 234);
            beepButton1.HoverBorderColor = Color.Gray;
            beepButton1.HoveredBackcolor = Color.Wheat;
            beepButton1.HoverForeColor = Color.White;
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton1.ImageClicked = null;
            beepButton1.ImageEmbededin = ImageEmbededin.Button;
            beepButton1.ImagePath = null;
            beepButton1.InactiveBackColor = Color.Gray;
            beepButton1.InactiveBorderColor = Color.Gray;
            beepButton1.InactiveForeColor = Color.Black;
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = false;
            beepButton1.IsCustomeBorder = false;
            beepButton1.IsDefault = false;
            beepButton1.IsDeleted = false;
            beepButton1.IsDirty = false;
            beepButton1.IsEditable = false;
            beepButton1.IsFocused = false;
            beepButton1.IsFramless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsNew = false;
            beepButton1.IsPopupOpen = false;
            beepButton1.IsPressed = false;
            beepButton1.IsReadOnly = false;
            beepButton1.IsRequired = false;
            beepButton1.IsRounded = true;
            beepButton1.IsRoundedAffectedByTheme = true;
            beepButton1.IsSelected = false;
            beepButton1.IsSelectedAuto = false;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.IsVisible = false;
            beepButton1.LeftoffsetForDrawingRect = 0;
            beepButton1.LinkedProperty = null;
            beepButton1.Location = new Point(126, 292);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaxImageSize = new Size(32, 32);
            beepButton1.Name = "beepButton1";
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.ParentBackColor = SystemColors.Control;
            beepButton1.ParentControl = null;
            beepButton1.PopupMode = false;
            beepButton1.PressedBackColor = Color.Gray;
            beepButton1.PressedBorderColor = Color.Gray;
            beepButton1.PressedForeColor = Color.Black;
            beepButton1.RightoffsetForDrawingRect = 0;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.SelectedBorderColor = Color.Blue;
            beepButton1.SelectedIndex = -1;
            beepButton1.SelectedItem = null;
            beepButton1.ShadowColor = Color.Black;
            beepButton1.ShadowOffset = 0;
            beepButton1.ShadowOpacity = 0.5F;
            beepButton1.ShowAllBorders = true;
            beepButton1.ShowBottomBorder = true;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowLeftBorder = true;
            beepButton1.ShowRightBorder = true;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = true;
            beepButton1.Size = new Size(202, 34);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 6;
            beepButton1.TempBackColor = SystemColors.Control;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepButton1.TextFont = new Font("Segoe UI", 9F);
            beepButton1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton1.Theme = Vis.Modules.EnumBeepThemes.DarkTheme;
            beepButton1.ToolTipText = "";
            beepButton1.TopoffsetForDrawingRect = 0;
            beepButton1.UseGradientBackground = false;
            beepButton1.UseScaledFont = false;
            beepButton1.UseThemeFont = true;
            // 
            // beepCard1
            // 
            beepCard1.ActiveBackColor = Color.Gray;
            beepCard1.AnimationDuration = 500;
            beepCard1.AnimationType = DisplayAnimationType.None;
            beepCard1.ApplyThemeToChilds = false;
            beepCard1.BackColor = Color.FromArgb(255, 69, 58);
            beepCard1.BlockID = null;
            beepCard1.BorderColor = Color.Black;
            beepCard1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCard1.BorderRadius = 6;
            beepCard1.BorderStyle = BorderStyle.FixedSingle;
            beepCard1.BorderThickness = 1;
            beepCard1.BottomoffsetForDrawingRect = 0;
            beepCard1.BoundProperty = "ParagraphText";
            beepCard1.CanBeFocused = true;
            beepCard1.CanBeHovered = false;
            beepCard1.CanBePressed = true;
            beepCard1.Category = Utilities.DbFieldCategory.String;
            beepCard1.ComponentName = "beepCard1";
            beepCard1.DataContext = null;
            beepCard1.DataSourceProperty = null;
            beepCard1.DisabledBackColor = Color.Gray;
            beepCard1.DisabledForeColor = Color.Empty;
            beepCard1.DrawingRect = new Rectangle(3, 3, 375, 362);
            beepCard1.Easing = EasingType.Linear;
            beepCard1.FieldID = null;
            beepCard1.FocusBackColor = Color.Gray;
            beepCard1.FocusBorderColor = Color.Gray;
            beepCard1.FocusForeColor = Color.Black;
            beepCard1.FocusIndicatorColor = Color.Blue;
            beepCard1.Form = null;
            beepCard1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCard1.GradientEndColor = Color.Gray;
            beepCard1.GradientStartColor = Color.Gray;
            beepCard1.GuidID = "63ac1278-7f25-4ebd-bc53-bccb01fb815c";
            beepCard1.HeaderAlignment = ContentAlignment.TopLeft;
            beepCard1.HeaderText = "Card Title";
            beepCard1.HoverBackColor = Color.Gray;
            beepCard1.HoverBorderColor = Color.Gray;
            beepCard1.HoveredBackcolor = Color.Wheat;
            beepCard1.HoverForeColor = Color.Black;
            beepCard1.Id = -1;
            beepCard1.ImageAlignment = ContentAlignment.TopRight;
            beepCard1.ImagePath = "";
            beepCard1.InactiveBackColor = Color.Gray;
            beepCard1.InactiveBorderColor = Color.Gray;
            beepCard1.InactiveForeColor = Color.Black;
            beepCard1.IsAcceptButton = false;
            beepCard1.IsBorderAffectedByTheme = true;
            beepCard1.IsCancelButton = false;
            beepCard1.IsChild = false;
            beepCard1.IsCustomeBorder = false;
            beepCard1.IsDefault = false;
            beepCard1.IsDeleted = false;
            beepCard1.IsDirty = false;
            beepCard1.IsEditable = false;
            beepCard1.IsFocused = false;
            beepCard1.IsFramless = false;
            beepCard1.IsHovered = false;
            beepCard1.IsNew = false;
            beepCard1.IsPressed = false;
            beepCard1.IsReadOnly = false;
            beepCard1.IsRequired = false;
            beepCard1.IsRounded = true;
            beepCard1.IsRoundedAffectedByTheme = true;
            beepCard1.IsSelected = false;
            beepCard1.IsShadowAffectedByTheme = true;
            beepCard1.IsVisible = false;
            beepCard1.LeftoffsetForDrawingRect = 0;
            beepCard1.LinkedProperty = null;
            beepCard1.Location = new Point(408, 12);
            beepCard1.MaxImageSize = 64;
            beepCard1.Name = "beepCard1";
            beepCard1.OverrideFontSize = TypeStyleFontSize.None;
            beepCard1.Padding = new Padding(2);
            beepCard1.ParagraphText = "Card Description";
            beepCard1.ParentBackColor = Color.Empty;
            beepCard1.ParentControl = null;
            beepCard1.PressedBackColor = Color.Gray;
            beepCard1.PressedBorderColor = Color.Gray;
            beepCard1.PressedForeColor = Color.Black;
            beepCard1.RightoffsetForDrawingRect = 0;
            beepCard1.SavedGuidID = null;
            beepCard1.SavedID = null;
            beepCard1.ShadowColor = Color.Black;
            beepCard1.ShadowOffset = 0;
            beepCard1.ShadowOpacity = 0.5F;
            beepCard1.ShowAllBorders = true;
            beepCard1.ShowBottomBorder = true;
            beepCard1.ShowFocusIndicator = false;
            beepCard1.ShowLeftBorder = true;
            beepCard1.ShowRightBorder = true;
            beepCard1.ShowShadow = false;
            beepCard1.ShowTopBorder = true;
            beepCard1.Size = new Size(381, 368);
            beepCard1.SlideFrom = SlideDirection.Left;
            beepCard1.StaticNotMoving = false;
            beepCard1.TabIndex = 7;
            beepCard1.TempBackColor = Color.Empty;
            beepCard1.Text = "beepCard1";
            beepCard1.TextAlignment = ContentAlignment.BottomCenter;
            beepCard1.Theme = Vis.Modules.EnumBeepThemes.DefaultTheme;
            beepCard1.ToolTipText = "";
            beepCard1.TopoffsetForDrawingRect = 0;
            beepCard1.UseGradientBackground = false;
            beepCard1.UseThemeFont = true;
            // 
            // beepLabel1
            // 
            beepLabel1.ActiveBackColor = Color.Gray;
            beepLabel1.AnimationDuration = 500;
            beepLabel1.AnimationType = DisplayAnimationType.None;
            beepLabel1.ApplyThemeOnImage = false;
            beepLabel1.ApplyThemeToChilds = true;
            beepLabel1.BackColor = Color.White;
            beepLabel1.BlockID = null;
            beepLabel1.BorderColor = Color.Black;
            beepLabel1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepLabel1.BorderRadius = 3;
            beepLabel1.BorderStyle = BorderStyle.FixedSingle;
            beepLabel1.BorderThickness = 1;
            beepLabel1.BottomoffsetForDrawingRect = 0;
            beepLabel1.BoundProperty = "Text";
            beepLabel1.CanBeFocused = true;
            beepLabel1.CanBeHovered = false;
            beepLabel1.CanBePressed = true;
            beepLabel1.Category = Utilities.DbFieldCategory.String;
            beepLabel1.ComponentName = "beepLabel1";
            beepLabel1.DataContext = null;
            beepLabel1.DataSourceProperty = null;
            beepLabel1.DisabledBackColor = Color.Gray;
            beepLabel1.DisabledForeColor = Color.Empty;
            beepLabel1.DrawingRect = new Rectangle(2, 2, 232, 23);
            beepLabel1.Easing = EasingType.Linear;
            beepLabel1.FieldID = null;
            beepLabel1.FocusBackColor = Color.Gray;
            beepLabel1.FocusBorderColor = Color.Gray;
            beepLabel1.FocusForeColor = Color.Black;
            beepLabel1.FocusIndicatorColor = Color.Blue;
            beepLabel1.Font = new Font("Comic Sans MS", 9F);
            beepLabel1.ForeColor = Color.FromArgb(139, 0, 139);
            beepLabel1.Form = null;
            beepLabel1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepLabel1.GradientEndColor = Color.Gray;
            beepLabel1.GradientStartColor = Color.Gray;
            beepLabel1.GuidID = "4c49b0fd-a575-4d90-a056-255b4540565b";
            beepLabel1.HideText = false;
            beepLabel1.HoverBackColor = Color.FromArgb(255, 105, 180);
            beepLabel1.HoverBorderColor = Color.Gray;
            beepLabel1.HoveredBackcolor = Color.Wheat;
            beepLabel1.HoverForeColor = Color.White;
            beepLabel1.Id = -1;
            beepLabel1.ImageAlign = ContentAlignment.MiddleLeft;
            beepLabel1.ImagePath = null;
            beepLabel1.InactiveBackColor = Color.Gray;
            beepLabel1.InactiveBorderColor = Color.Gray;
            beepLabel1.InactiveForeColor = Color.Black;
            beepLabel1.IsAcceptButton = false;
            beepLabel1.IsBorderAffectedByTheme = true;
            beepLabel1.IsCancelButton = false;
            beepLabel1.IsChild = false;
            beepLabel1.IsCustomeBorder = false;
            beepLabel1.IsDefault = false;
            beepLabel1.IsDeleted = false;
            beepLabel1.IsDirty = false;
            beepLabel1.IsEditable = false;
            beepLabel1.IsFocused = false;
            beepLabel1.IsFramless = false;
            beepLabel1.IsHovered = false;
            beepLabel1.IsNew = false;
            beepLabel1.IsPressed = false;
            beepLabel1.IsReadOnly = false;
            beepLabel1.IsRequired = false;
            beepLabel1.IsRounded = true;
            beepLabel1.IsRoundedAffectedByTheme = true;
            beepLabel1.IsSelected = false;
            beepLabel1.IsShadowAffectedByTheme = true;
            beepLabel1.IsVisible = false;
            beepLabel1.LabelBackColor = Color.Empty;
            beepLabel1.LeftoffsetForDrawingRect = 0;
            beepLabel1.LinkedProperty = null;
            beepLabel1.Location = new Point(105, 390);
            beepLabel1.Margin = new Padding(0);
            beepLabel1.MaxImageSize = new Size(16, 16);
            beepLabel1.Name = "beepLabel1";
            beepLabel1.OverrideFontSize = TypeStyleFontSize.None;
            beepLabel1.Padding = new Padding(1);
            beepLabel1.ParentBackColor = Color.Empty;
            beepLabel1.ParentControl = null;
            beepLabel1.PressedBackColor = Color.Gray;
            beepLabel1.PressedBorderColor = Color.Gray;
            beepLabel1.PressedForeColor = Color.Black;
            beepLabel1.RightoffsetForDrawingRect = 0;
            beepLabel1.SavedGuidID = null;
            beepLabel1.SavedID = null;
            beepLabel1.ShadowColor = Color.Black;
            beepLabel1.ShadowOffset = 0;
            beepLabel1.ShadowOpacity = 0.5F;
            beepLabel1.ShowAllBorders = true;
            beepLabel1.ShowBottomBorder = true;
            beepLabel1.ShowFocusIndicator = false;
            beepLabel1.ShowLeftBorder = true;
            beepLabel1.ShowRightBorder = true;
            beepLabel1.ShowShadow = false;
            beepLabel1.ShowTopBorder = true;
            beepLabel1.Size = new Size(236, 27);
            beepLabel1.SlideFrom = SlideDirection.Left;
            beepLabel1.StaticNotMoving = false;
            beepLabel1.TabIndex = 8;
            beepLabel1.TempBackColor = Color.Empty;
            beepLabel1.Text = "beepLabel1";
            beepLabel1.TextAlign = ContentAlignment.MiddleLeft;
            beepLabel1.TextFont = new Font("Comic Sans MS", 9F);
            beepLabel1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepLabel1.Theme = Vis.Modules.EnumBeepThemes.CandyTheme;
            beepLabel1.ToolTipText = "";
            beepLabel1.TopoffsetForDrawingRect = 0;
            beepLabel1.UseGradientBackground = false;
            beepLabel1.UseScaledFont = false;
            beepLabel1.UseThemeFont = true;
            // 
            // Form2
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(832, 475);
            Controls.Add(beepLabel1);
            Controls.Add(beepCard1);
            Controls.Add(beepButton1);
            Controls.Add(beepCheckBox1);
            Controls.Add(beepSwitch1);
            Name = "Form2";
            Text = "Form2";
            ResumeLayout(false);
        }

        #endregion

        private Grid.BeepGrid beepGrid1;
        private BeepSwitch beepSwitch1;
        private BeepCheckBox beepCheckBox1;
        private BeepButton beepButton1;
        private BeepCard beepCard1;
        private BeepLabel beepLabel1;
    }
}