namespace TheTechIdea.Beep.Winform.Controls
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            beepSideMenu1 = new BeepSideMenu();
            beepLabel1 = new BeepLabel();
            beepImage1 = new BeepImage();
            beepButton1 = new BeepButton();
            beepCircularButton1 = new BeepCircularButton();
            beepListBox1 = new BeepListBox();
            beepFlyMenu1 = new BeepDropDownMenu();
            beepFlyoutMenu1 = new BeepFlyoutMenu();
            beepExtendedButton1 = new BeepExtendedButton();
            beepButton2 = new BeepButton();
            beepPanel1.SuspendLayout();
            SuspendLayout();
            // 
            // CloseButton
            // 
            CloseButton.ApplyThemeOnImage = true;
            CloseButton.BackColor = Color.White;
            CloseButton.Font = new Font("Segoe UI", 12F);
            CloseButton.ForeColor = Color.FromArgb(0, 120, 215);
            CloseButton.Location = new Point(654, 0);
            CloseButton.ParentBackColor = Color.White;
            CloseButton.ShowAllBorders = false;
            CloseButton.ShowBottomBorder = false;
            CloseButton.ShowLeftBorder = false;
            CloseButton.ShowRightBorder = false;
            CloseButton.ShowTopBorder = false;
            CloseButton.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            CloseButton.ToolTipText = "Close";
            // 
            // MaximizeButton
            // 
            MaximizeButton.ApplyThemeOnImage = true;
            MaximizeButton.BackColor = Color.White;
            MaximizeButton.Font = new Font("Segoe UI", 12F);
            MaximizeButton.ForeColor = Color.FromArgb(0, 120, 215);
            MaximizeButton.Location = new Point(624, 0);
            MaximizeButton.MaxImageSize = new Size(20, 20);
            MaximizeButton.ParentBackColor = Color.White;
            MaximizeButton.ShowAllBorders = false;
            MaximizeButton.ShowBottomBorder = false;
            MaximizeButton.ShowLeftBorder = false;
            MaximizeButton.ShowRightBorder = false;
            MaximizeButton.ShowTopBorder = false;
            MaximizeButton.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            MaximizeButton.ToolTipText = "Maximize";
            // 
            // MinimizeButton
            // 
            MinimizeButton.ApplyThemeOnImage = true;
            MinimizeButton.BackColor = Color.White;
            MinimizeButton.Font = new Font("Segoe UI", 12F);
            MinimizeButton.ForeColor = Color.FromArgb(0, 120, 215);
            MinimizeButton.Location = new Point(594, 0);
            MinimizeButton.MaxImageSize = new Size(20, 20);
            MinimizeButton.ParentBackColor = Color.White;
            MinimizeButton.ShowAllBorders = false;
            MinimizeButton.ShowBottomBorder = false;
            MinimizeButton.ShowLeftBorder = false;
            MinimizeButton.ShowRightBorder = false;
            MinimizeButton.ShowTopBorder = false;
            MinimizeButton.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            MinimizeButton.ToolTipText = "Minimize";
            // 
            // beepuiManager1
            // 
            beepuiManager1.BeepiForm = this;
            beepuiManager1.BeepSideMenu = beepSideMenu1;
            beepuiManager1.LogoImage = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\016-admin.svg";
            beepuiManager1.ShowBorder = false;
            beepuiManager1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepuiManager1.Title = "Asset HR Digital Space";
            // 
            // beepPanel1
            // 
            beepPanel1.BackColor = Color.White;
            beepPanel1.DrawingRect = new Rectangle(1, 1, 682, 28);
            beepPanel1.ForeColor = Color.FromArgb(0, 120, 215);
            beepPanel1.Location = new Point(354, 10);
            beepPanel1.ParentBackColor = Color.White;
            beepPanel1.ShowLeftBorder = false;
            beepPanel1.ShowRightBorder = false;
            beepPanel1.ShowTopBorder = false;
            beepPanel1.Size = new Size(684, 30);
            beepPanel1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            // 
            // TitleLabel
            // 
            TitleLabel.BackColor = Color.White;
            TitleLabel.DrawingRect = new Rectangle(1, 1, 560, 26);
            TitleLabel.Font = new Font("Segoe UI", 12F);
            TitleLabel.ForeColor = Color.FromArgb(0, 120, 215);
            TitleLabel.ImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\016-admin.svg";
            TitleLabel.ShowAllBorders = false;
            TitleLabel.ShowBottomBorder = false;
            TitleLabel.ShowLeftBorder = false;
            TitleLabel.ShowRightBorder = false;
            TitleLabel.ShowTopBorder = false;
            TitleLabel.Size = new Size(562, 28);
            TitleLabel.Text = "Asset HR Digital Space";
            TitleLabel.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            // 
            // FunctionsPanel1
            // 
            FunctionsPanel1.BackColor = Color.White;
            FunctionsPanel1.Location = new Point(993, 63);
            FunctionsPanel1.ParentBackColor = Color.White;
            FunctionsPanel1.ShowAllBorders = false;
            FunctionsPanel1.ShowBottomBorder = false;
            FunctionsPanel1.ShowLeftBorder = false;
            FunctionsPanel1.ShowRightBorder = false;
            FunctionsPanel1.ShowTopBorder = false;
            FunctionsPanel1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            // 
            // beepSideMenu1
            // 
            beepSideMenu1.ActiveBackColor = Color.FromArgb(0, 153, 188);
            beepSideMenu1.AnimationDuration = 500;
            beepSideMenu1.AnimationStep = 20;
            beepSideMenu1.AnimationType = DisplayAnimationType.None;
            beepSideMenu1.ApplyThemeOnImages = false;
            beepSideMenu1.BackColor = Color.FromArgb(0, 120, 215);
            beepSideMenu1.BeepForm = this;
            beepSideMenu1.BlockID = null;
            beepSideMenu1.BorderColor = Color.FromArgb(204, 204, 204);
            beepSideMenu1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSideMenu1.BorderRadius = 5;
            beepSideMenu1.BorderStyle = BorderStyle.FixedSingle;
            beepSideMenu1.BorderThickness = 1;
            beepSideMenu1.CollapsedWidth = 64;
            beepSideMenu1.DataContext = null;
            beepSideMenu1.DisabledBackColor = Color.Gray;
            beepSideMenu1.DisabledForeColor = Color.Empty;
            beepSideMenu1.Dock = DockStyle.Left;
            beepSideMenu1.DrawingRect = new Rectangle(1, 1, 342, 659);
            beepSideMenu1.Easing = EasingType.Linear;
            beepSideMenu1.ExpandedWidth = 344;
            beepSideMenu1.FieldID = null;
            beepSideMenu1.FocusBackColor = Color.White;
            beepSideMenu1.FocusBorderColor = Color.Gray;
            beepSideMenu1.FocusForeColor = Color.Black;
            beepSideMenu1.FocusIndicatorColor = Color.Blue;
            beepSideMenu1.Font = new Font("Segoe UI", 9F);
            beepSideMenu1.ForeColor = Color.White;
            beepSideMenu1.Form = null;
            beepSideMenu1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSideMenu1.GradientEndColor = Color.FromArgb(0, 120, 215);
            beepSideMenu1.GradientStartColor = Color.White;
            beepSideMenu1.HilightPanelSize = 5;
            beepSideMenu1.HoverBackColor = Color.FromArgb(0, 99, 177);
            beepSideMenu1.HoverBorderColor = Color.FromArgb(0, 153, 188);
            beepSideMenu1.HoveredBackcolor = Color.Wheat;
            beepSideMenu1.HoverForeColor = Color.Black;
            beepSideMenu1.Id = -1;
            beepSideMenu1.InactiveBackColor = Color.Gray;
            beepSideMenu1.InactiveBorderColor = Color.Gray;
            beepSideMenu1.InactiveForeColor = Color.Black;
            beepSideMenu1.IsAcceptButton = false;
            beepSideMenu1.IsBorderAffectedByTheme = false;
            beepSideMenu1.IsCancelButton = false;
            beepSideMenu1.IsChild = false;
            beepSideMenu1.IsDefault = false;
            beepSideMenu1.IsFocused = false;
            beepSideMenu1.IsFramless = false;
            beepSideMenu1.IsHovered = false;
            beepSideMenu1.IsPressed = false;
            beepSideMenu1.IsRounded = false;
            beepSideMenu1.IsShadowAffectedByTheme = false;
            beepSideMenu1.Items.Add((Template.SimpleMenuItem)resources.GetObject("beepSideMenu1.Items"));
            beepSideMenu1.Items.Add((Template.SimpleMenuItem)resources.GetObject("beepSideMenu1.Items1"));
            beepSideMenu1.Location = new Point(10, 10);
            beepSideMenu1.LogoImage = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\016-admin.svg";
            beepSideMenu1.Name = "beepSideMenu1";
            beepSideMenu1.OverrideFontSize = TypeStyleFontSize.None;
            beepSideMenu1.Padding = new Padding(2);
            beepSideMenu1.ParentBackColor = Color.White;
            beepSideMenu1.PressedBackColor = Color.FromArgb(0, 153, 188);
            beepSideMenu1.PressedBorderColor = Color.Gray;
            beepSideMenu1.PressedForeColor = Color.Black;
            beepSideMenu1.SavedGuidID = null;
            beepSideMenu1.SavedID = null;
            beepSideMenu1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepSideMenu1.ShadowOffset = 0;
            beepSideMenu1.ShadowOpacity = 0.5F;
            beepSideMenu1.ShowAllBorders = false;
            beepSideMenu1.ShowBottomBorder = false;
            beepSideMenu1.ShowFocusIndicator = false;
            beepSideMenu1.ShowLeftBorder = false;
            beepSideMenu1.ShowRightBorder = false;
            beepSideMenu1.ShowShadow = false;
            beepSideMenu1.ShowTopBorder = false;
            beepSideMenu1.Size = new Size(344, 661);
            beepSideMenu1.SlideFrom = SlideDirection.Left;
            beepSideMenu1.StaticNotMoving = false;
            beepSideMenu1.TabIndex = 0;
            beepSideMenu1.Text = "beepSideMenu1";
            beepSideMenu1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepSideMenu1.Title = "Asset HR Digital Space";
            beepSideMenu1.ToolTipText = "";
            beepSideMenu1.UseGradientBackground = false;
            // 
            // beepLabel1
            // 
            beepLabel1.ActiveBackColor = Color.Gray;
            beepLabel1.AnimationDuration = 500;
            beepLabel1.AnimationType = DisplayAnimationType.None;
            beepLabel1.ApplyThemeOnImage = false;
            beepLabel1.BackColor = Color.White;
            beepLabel1.BlockID = null;
            beepLabel1.BorderColor = Color.Black;
            beepLabel1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepLabel1.BorderRadius = 5;
            beepLabel1.BorderStyle = BorderStyle.FixedSingle;
            beepLabel1.BorderThickness = 1;
            beepLabel1.DataContext = null;
            beepLabel1.DisabledBackColor = Color.Gray;
            beepLabel1.DisabledForeColor = Color.Empty;
            beepLabel1.DrawingRect = new Rectangle(1, 1, 142, 35);
            beepLabel1.Easing = EasingType.Linear;
            beepLabel1.FieldID = null;
            beepLabel1.FocusBackColor = Color.Gray;
            beepLabel1.FocusBorderColor = Color.Gray;
            beepLabel1.FocusForeColor = Color.Black;
            beepLabel1.FocusIndicatorColor = Color.Blue;
            beepLabel1.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            beepLabel1.ForeColor = Color.FromArgb(0, 0, 0);
            beepLabel1.Form = null;
            beepLabel1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepLabel1.GradientEndColor = Color.Gray;
            beepLabel1.GradientStartColor = Color.Gray;
            beepLabel1.HideText = false;
            beepLabel1.HoverBackColor = Color.Gray;
            beepLabel1.HoverBorderColor = Color.Gray;
            beepLabel1.HoveredBackcolor = Color.Wheat;
            beepLabel1.HoverForeColor = Color.Black;
            beepLabel1.Id = -1;
            beepLabel1.ImageAlign = ContentAlignment.MiddleLeft;
            beepLabel1.ImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\018-puzzle.svg";
            beepLabel1.InactiveBackColor = Color.Gray;
            beepLabel1.InactiveBorderColor = Color.Gray;
            beepLabel1.InactiveForeColor = Color.Black;
            beepLabel1.IsAcceptButton = false;
            beepLabel1.IsBorderAffectedByTheme = true;
            beepLabel1.IsCancelButton = false;
            beepLabel1.IsChild = false;
            beepLabel1.IsDefault = false;
            beepLabel1.IsFocused = false;
            beepLabel1.IsFramless = false;
            beepLabel1.IsHovered = false;
            beepLabel1.IsPressed = false;
            beepLabel1.IsRounded = false;
            beepLabel1.IsShadowAffectedByTheme = true;
            beepLabel1.Location = new Point(470, 216);
            beepLabel1.Margin = new Padding(0);
            beepLabel1.MaxImageSize = new Size(16, 16);
            beepLabel1.Name = "beepLabel1";
            beepLabel1.OverrideFontSize = TypeStyleFontSize.None;
            beepLabel1.ParentBackColor = Color.Empty;
            beepLabel1.PressedBackColor = Color.Gray;
            beepLabel1.PressedBorderColor = Color.Gray;
            beepLabel1.PressedForeColor = Color.Black;
            beepLabel1.SavedGuidID = null;
            beepLabel1.SavedID = null;
            beepLabel1.ShadowColor = Color.Black;
            beepLabel1.ShadowOffset = 0;
            beepLabel1.ShadowOpacity = 0.5F;
            beepLabel1.ShowAllBorders = false;
            beepLabel1.ShowBottomBorder = false;
            beepLabel1.ShowFocusIndicator = false;
            beepLabel1.ShowLeftBorder = false;
            beepLabel1.ShowRightBorder = false;
            beepLabel1.ShowShadow = false;
            beepLabel1.ShowTopBorder = false;
            beepLabel1.Size = new Size(144, 37);
            beepLabel1.SlideFrom = SlideDirection.Left;
            beepLabel1.StaticNotMoving = false;
            beepLabel1.TabIndex = 6;
            beepLabel1.Text = "beepLabel1";
            beepLabel1.TextAlign = ContentAlignment.MiddleLeft;
            beepLabel1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepLabel1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepLabel1.ToolTipText = "";
            beepLabel1.UseGradientBackground = false;
            // 
            // beepImage1
            // 
            beepImage1.ActiveBackColor = Color.FromArgb(0, 153, 188);
            beepImage1.AnimationDuration = 500;
            beepImage1.AnimationType = DisplayAnimationType.None;
            beepImage1.ApplyThemeOnImage = false;
            beepImage1.BlockID = null;
            beepImage1.BorderColor = Color.FromArgb(204, 204, 204);
            beepImage1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepImage1.BorderRadius = 5;
            beepImage1.BorderStyle = BorderStyle.FixedSingle;
            beepImage1.BorderThickness = 1;
            beepImage1.DataContext = null;
            beepImage1.DisabledBackColor = Color.Gray;
            beepImage1.DisabledForeColor = Color.Empty;
            beepImage1.DrawingRect = new Rectangle(1, 1, 147, 87);
            beepImage1.Easing = EasingType.Linear;
            beepImage1.FieldID = null;
            beepImage1.FocusBackColor = Color.FromArgb(0, 153, 188);
            beepImage1.FocusBorderColor = Color.Gray;
            beepImage1.FocusForeColor = Color.White;
            beepImage1.FocusIndicatorColor = Color.Blue;
            beepImage1.Form = null;
            beepImage1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepImage1.GradientEndColor = Color.FromArgb(0, 120, 215);
            beepImage1.GradientStartColor = Color.White;
            beepImage1.HoverBackColor = Color.FromArgb(0, 99, 177);
            beepImage1.HoverBorderColor = Color.FromArgb(0, 153, 188);
            beepImage1.HoveredBackcolor = Color.Wheat;
            beepImage1.HoverForeColor = Color.White;
            beepImage1.Id = -1;
            beepImage1.Image = null;
            beepImage1.ImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\020-organization.svg";
            beepImage1.InactiveBackColor = Color.Gray;
            beepImage1.InactiveBorderColor = Color.Gray;
            beepImage1.InactiveForeColor = Color.Black;
            beepImage1.IsAcceptButton = false;
            beepImage1.IsBorderAffectedByTheme = true;
            beepImage1.IsCancelButton = false;
            beepImage1.IsChild = false;
            beepImage1.IsDefault = false;
            beepImage1.IsFocused = false;
            beepImage1.IsFramless = false;
            beepImage1.IsHovered = false;
            beepImage1.IsPressed = false;
            beepImage1.IsRounded = false;
            beepImage1.IsShadowAffectedByTheme = true;
            beepImage1.IsStillImage = false;
            beepImage1.Location = new Point(501, 358);
            beepImage1.Name = "beepImage1";
            beepImage1.OverrideFontSize = TypeStyleFontSize.None;
            beepImage1.ParentBackColor = Color.Empty;
            beepImage1.PressedBackColor = Color.FromArgb(0, 153, 188);
            beepImage1.PressedBorderColor = Color.Gray;
            beepImage1.PressedForeColor = Color.White;
            beepImage1.SavedGuidID = null;
            beepImage1.SavedID = null;
            beepImage1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepImage1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepImage1.ShadowOffset = 0;
            beepImage1.ShadowOpacity = 0.5F;
            beepImage1.ShowAllBorders = false;
            beepImage1.ShowBottomBorder = false;
            beepImage1.ShowFocusIndicator = false;
            beepImage1.ShowLeftBorder = false;
            beepImage1.ShowRightBorder = false;
            beepImage1.ShowShadow = false;
            beepImage1.ShowTopBorder = false;
            beepImage1.Size = new Size(149, 89);
            beepImage1.SlideFrom = SlideDirection.Left;
            beepImage1.StaticNotMoving = false;
            beepImage1.TabIndex = 4;
            beepImage1.Text = "beepImage1";
            beepImage1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepImage1.ToolTipText = "";
            beepImage1.UseGradientBackground = false;
            // 
            // beepButton1
            // 
            beepButton1.ActiveBackColor = Color.Gray;
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.BackColor = Color.White;
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.Black;
            beepButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton1.BorderRadius = 5;
            beepButton1.BorderSize = 1;
            beepButton1.BorderStyle = BorderStyle.FixedSingle;
            beepButton1.BorderThickness = 1;
            beepButton1.DataContext = null;
            beepButton1.DisabledBackColor = Color.Gray;
            beepButton1.DisabledForeColor = Color.Empty;
            beepButton1.DrawingRect = new Rectangle(1, 1, 54, 43);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.FieldID = null;
            beepButton1.FlatAppearance = true;
            beepButton1.FlatStyle = FlatStyle.Standard;
            beepButton1.FocusBackColor = Color.Gray;
            beepButton1.FocusBorderColor = Color.Gray;
            beepButton1.FocusForeColor = Color.Black;
            beepButton1.FocusIndicatorColor = Color.Blue;
            beepButton1.Font = new Font("Segoe UI", 12F);
            beepButton1.ForeColor = Color.White;
            beepButton1.Form = null;
            beepButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.Gray;
            beepButton1.GradientStartColor = Color.Gray;
            beepButton1.HideText = true;
            beepButton1.HoverBackColor = Color.Gray;
            beepButton1.HoverBorderColor = Color.Gray;
            beepButton1.HoveredBackcolor = Color.Wheat;
            beepButton1.HoverForeColor = Color.Black;
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleRight;
            beepButton1.ImageClicked = null;
            beepButton1.ImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\016-admin.svg";
            beepButton1.InactiveBackColor = Color.Gray;
            beepButton1.InactiveBorderColor = Color.Gray;
            beepButton1.InactiveForeColor = Color.Black;
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = false;
            beepButton1.IsDefault = false;
            beepButton1.IsFocused = false;
            beepButton1.IsFramless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsPressed = false;
            beepButton1.IsRounded = false;
            beepButton1.IsSelected = false;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.Location = new Point(501, 295);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaxImageSize = new Size(32, 32);
            beepButton1.Name = "beepButton1";
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.ParentBackColor = Color.Empty;
            beepButton1.PressedBackColor = Color.Gray;
            beepButton1.PressedBorderColor = Color.Gray;
            beepButton1.PressedForeColor = Color.Black;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.SelectedBorderColor = Color.Blue;
            beepButton1.ShadowColor = Color.Black;
            beepButton1.ShadowOffset = 0;
            beepButton1.ShadowOpacity = 0.5F;
            beepButton1.ShowAllBorders = false;
            beepButton1.ShowBottomBorder = false;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowLeftBorder = false;
            beepButton1.ShowRightBorder = false;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = false;
            beepButton1.Size = new Size(56, 45);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 7;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleLeft;
            beepButton1.TextImageRelation = TextImageRelation.Overlay;
            beepButton1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepButton1.ToolTipText = "";
            beepButton1.UseGradientBackground = false;
            // 
            // beepCircularButton1
            // 
            beepCircularButton1.ActiveBackColor = Color.Gray;
            beepCircularButton1.AnimationDuration = 500;
            beepCircularButton1.AnimationType = DisplayAnimationType.None;
            beepCircularButton1.ApplyThemeOnImage = false;
            beepCircularButton1.BackColor = Color.White;
            beepCircularButton1.BlockID = null;
            beepCircularButton1.BorderColor = Color.Black;
            beepCircularButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepCircularButton1.BorderRadius = 5;
            beepCircularButton1.BorderStyle = BorderStyle.FixedSingle;
            beepCircularButton1.BorderThickness = 1;
            beepCircularButton1.DataContext = null;
            beepCircularButton1.DisabledBackColor = Color.Gray;
            beepCircularButton1.DisabledForeColor = Color.Empty;
            beepCircularButton1.DrawingRect = new Rectangle(1, 1, 131, 103);
            beepCircularButton1.Easing = EasingType.Linear;
            beepCircularButton1.FieldID = null;
            beepCircularButton1.FocusBackColor = Color.Gray;
            beepCircularButton1.FocusBorderColor = Color.Gray;
            beepCircularButton1.FocusForeColor = Color.Black;
            beepCircularButton1.FocusIndicatorColor = Color.Blue;
            beepCircularButton1.Font = new Font("Segoe UI", 12F);
            beepCircularButton1.ForeColor = Color.White;
            beepCircularButton1.Form = null;
            beepCircularButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepCircularButton1.GradientEndColor = Color.Gray;
            beepCircularButton1.GradientStartColor = Color.Gray;
            beepCircularButton1.HideText = false;
            beepCircularButton1.HoverBackColor = Color.Gray;
            beepCircularButton1.HoverBorderColor = Color.Gray;
            beepCircularButton1.HoveredBackcolor = Color.Wheat;
            beepCircularButton1.HoverForeColor = Color.Black;
            beepCircularButton1.Id = -1;
            beepCircularButton1.ImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\018-puzzle.svg";
            beepCircularButton1.InactiveBackColor = Color.Gray;
            beepCircularButton1.InactiveBorderColor = Color.Gray;
            beepCircularButton1.InactiveForeColor = Color.Black;
            beepCircularButton1.IsAcceptButton = false;
            beepCircularButton1.IsBorderAffectedByTheme = true;
            beepCircularButton1.IsCancelButton = false;
            beepCircularButton1.IsChild = true;
            beepCircularButton1.IsDefault = false;
            beepCircularButton1.IsFocused = false;
            beepCircularButton1.IsForColorSet = false;
            beepCircularButton1.IsFramless = true;
            beepCircularButton1.IsHovered = false;
            beepCircularButton1.IsPressed = false;
            beepCircularButton1.IsRounded = false;
            beepCircularButton1.IsShadowAffectedByTheme = true;
            beepCircularButton1.Location = new Point(391, 504);
            beepCircularButton1.Name = "beepCircularButton1";
            beepCircularButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepCircularButton1.ParentBackColor = Color.White;
            beepCircularButton1.PressedBackColor = Color.Gray;
            beepCircularButton1.PressedBorderColor = Color.Gray;
            beepCircularButton1.PressedForeColor = Color.Black;
            beepCircularButton1.SavedGuidID = null;
            beepCircularButton1.SavedID = null;
            beepCircularButton1.ShadowColor = Color.Black;
            beepCircularButton1.ShadowOffset = 0;
            beepCircularButton1.ShadowOpacity = 0.5F;
            beepCircularButton1.ShowAllBorders = false;
            beepCircularButton1.ShowBorder = true;
            beepCircularButton1.ShowBottomBorder = false;
            beepCircularButton1.ShowFocusIndicator = false;
            beepCircularButton1.ShowLeftBorder = false;
            beepCircularButton1.ShowRightBorder = false;
            beepCircularButton1.ShowShadow = false;
            beepCircularButton1.ShowTopBorder = false;
            beepCircularButton1.Size = new Size(133, 105);
            beepCircularButton1.SlideFrom = SlideDirection.Left;
            beepCircularButton1.StaticNotMoving = false;
            beepCircularButton1.TabIndex = 8;
            beepCircularButton1.Text = "beepCircularButton1";
            beepCircularButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepCircularButton1.TextLocation = TextLocation.Below;
            beepCircularButton1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepCircularButton1.ToolTipText = "";
            beepCircularButton1.UseGradientBackground = false;
            // 
            // beepListBox1
            // 
            beepListBox1.ActiveBackColor = Color.Gray;
            beepListBox1.AnimationDuration = 500;
            beepListBox1.AnimationType = DisplayAnimationType.None;
            beepListBox1.BackColor = Color.FromArgb(0, 120, 215);
            beepListBox1.BlockID = null;
            beepListBox1.BorderColor = Color.Black;
            beepListBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepListBox1.BorderRadius = 5;
            beepListBox1.BorderStyle = BorderStyle.FixedSingle;
            beepListBox1.BorderThickness = 1;
            beepListBox1.DataContext = null;
            beepListBox1.DisabledBackColor = Color.Gray;
            beepListBox1.DisabledForeColor = Color.Empty;
            beepListBox1.DrawingRect = new Rectangle(1, 1, 182, 124);
            beepListBox1.Easing = EasingType.Linear;
            beepListBox1.FieldID = null;
            beepListBox1.FocusBackColor = Color.Gray;
            beepListBox1.FocusBorderColor = Color.Gray;
            beepListBox1.FocusForeColor = Color.Black;
            beepListBox1.FocusIndicatorColor = Color.Blue;
            beepListBox1.Form = null;
            beepListBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepListBox1.GradientEndColor = Color.Gray;
            beepListBox1.GradientStartColor = Color.Gray;
            beepListBox1.HoverBackColor = Color.Gray;
            beepListBox1.HoverBorderColor = Color.Gray;
            beepListBox1.HoveredBackcolor = Color.Wheat;
            beepListBox1.HoverForeColor = Color.Black;
            beepListBox1.Id = -1;
            beepListBox1.InactiveBackColor = Color.Gray;
            beepListBox1.InactiveBorderColor = Color.Gray;
            beepListBox1.InactiveForeColor = Color.Black;
            beepListBox1.IsAcceptButton = false;
            beepListBox1.IsBorderAffectedByTheme = false;
            beepListBox1.IsCancelButton = false;
            beepListBox1.IsChild = false;
            beepListBox1.IsDefault = false;
            beepListBox1.IsFocused = false;
            beepListBox1.IsFramless = true;
            beepListBox1.IsHovered = false;
            beepListBox1.IsPressed = false;
            beepListBox1.IsRounded = false;
            beepListBox1.IsShadowAffectedByTheme = false;
            beepListBox1.ListItems.Add((Template.SimpleMenuItem)resources.GetObject("beepListBox1.ListItems"));
            beepListBox1.ListItems.Add((Template.SimpleMenuItem)resources.GetObject("beepListBox1.ListItems1"));
            beepListBox1.Location = new Point(456, 63);
            beepListBox1.MenuItemHeight = 20;
            beepListBox1.Name = "beepListBox1";
            beepListBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepListBox1.Padding = new Padding(5);
            beepListBox1.ParentBackColor = Color.Empty;
            beepListBox1.PressedBackColor = Color.Gray;
            beepListBox1.PressedBorderColor = Color.Gray;
            beepListBox1.PressedForeColor = Color.Black;
            beepListBox1.SavedGuidID = null;
            beepListBox1.SavedID = null;
            beepListBox1.SelectedIndex = -1;
            beepListBox1.ShadowColor = Color.Black;
            beepListBox1.ShadowOffset = 0;
            beepListBox1.ShadowOpacity = 0.5F;
            beepListBox1.ShowAllBorders = false;
            beepListBox1.ShowBottomBorder = false;
            beepListBox1.ShowFocusIndicator = false;
            beepListBox1.ShowLeftBorder = false;
            beepListBox1.ShowRightBorder = false;
            beepListBox1.ShowShadow = false;
            beepListBox1.ShowTitle = true;
            beepListBox1.ShowTitleLine = true;
            beepListBox1.ShowTitleLineinFullWidth = true;
            beepListBox1.ShowTopBorder = false;
            beepListBox1.Size = new Size(184, 126);
            beepListBox1.SlideFrom = SlideDirection.Left;
            beepListBox1.StaticNotMoving = false;
            beepListBox1.TabIndex = 9;
            beepListBox1.Text = "beepListBox1";
            beepListBox1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepListBox1.TitleAlignment = ContentAlignment.TopLeft;
            beepListBox1.TitleBottomY = 40;
            beepListBox1.TitleLineColor = Color.Gray;
            beepListBox1.TitleLineThickness = 2;
            beepListBox1.TitleText = "List Box";
            beepListBox1.ToolTipText = "";
            beepListBox1.UseGradientBackground = false;
            // 
            // beepFlyMenu1
            // 
            beepFlyMenu1.ActiveBackColor = Color.Gray;
            beepFlyMenu1.AnimationDuration = 500;
            beepFlyMenu1.AnimationType = DisplayAnimationType.None;
            beepFlyMenu1.BackColor = Color.FromArgb(0, 120, 215);
            beepFlyMenu1.BlockID = null;
            beepFlyMenu1.BorderColor = Color.Black;
            beepFlyMenu1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepFlyMenu1.BorderRadius = 5;
            beepFlyMenu1.BorderStyle = BorderStyle.FixedSingle;
            beepFlyMenu1.BorderThickness = 1;
            beepFlyMenu1.DataContext = null;
            beepFlyMenu1.DisabledBackColor = Color.Gray;
            beepFlyMenu1.DisabledForeColor = Color.Empty;
            beepFlyMenu1.DrawingRect = new Rectangle(1, 1, 146, 23);
            beepFlyMenu1.Easing = EasingType.Linear;
            beepFlyMenu1.FieldID = null;
            beepFlyMenu1.FocusBackColor = Color.Gray;
            beepFlyMenu1.FocusBorderColor = Color.Gray;
            beepFlyMenu1.FocusForeColor = Color.Black;
            beepFlyMenu1.FocusIndicatorColor = Color.Blue;
            beepFlyMenu1.Form = null;
            beepFlyMenu1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepFlyMenu1.GradientEndColor = Color.Gray;
            beepFlyMenu1.GradientStartColor = Color.Gray;
            beepFlyMenu1.HoverBackColor = Color.Gray;
            beepFlyMenu1.HoverBorderColor = Color.Gray;
            beepFlyMenu1.HoveredBackcolor = Color.Wheat;
            beepFlyMenu1.HoverForeColor = Color.Black;
            beepFlyMenu1.Id = -1;
            beepFlyMenu1.InactiveBackColor = Color.Gray;
            beepFlyMenu1.InactiveBorderColor = Color.Gray;
            beepFlyMenu1.InactiveForeColor = Color.Black;
            beepFlyMenu1.IsAcceptButton = false;
            beepFlyMenu1.IsBorderAffectedByTheme = true;
            beepFlyMenu1.IsCancelButton = false;
            beepFlyMenu1.IsChild = false;
            beepFlyMenu1.IsDefault = false;
            beepFlyMenu1.IsFocused = false;
            beepFlyMenu1.IsFramless = false;
            beepFlyMenu1.IsHovered = false;
            beepFlyMenu1.IsPressed = false;
            beepFlyMenu1.IsRounded = false;
            beepFlyMenu1.IsShadowAffectedByTheme = true;
            beepFlyMenu1.ListItems.Add((Template.SimpleMenuItem)resources.GetObject("beepFlyMenu1.ListItems"));
            beepFlyMenu1.ListItems.Add((Template.SimpleMenuItem)resources.GetObject("beepFlyMenu1.ListItems1"));
            beepFlyMenu1.Location = new Point(391, 460);
            beepFlyMenu1.MenuItemHeight = 20;
            beepFlyMenu1.Name = "beepFlyMenu1";
            beepFlyMenu1.OverrideFontSize = TypeStyleFontSize.None;
            beepFlyMenu1.ParentBackColor = Color.Empty;
            beepFlyMenu1.PressedBackColor = Color.Gray;
            beepFlyMenu1.PressedBorderColor = Color.Gray;
            beepFlyMenu1.PressedForeColor = Color.Black;
            beepFlyMenu1.SavedGuidID = null;
            beepFlyMenu1.SavedID = null;
            beepFlyMenu1.SelectedIndex = -1;
            beepFlyMenu1.ShadowColor = Color.Black;
            beepFlyMenu1.ShadowOffset = 0;
            beepFlyMenu1.ShadowOpacity = 0.5F;
            beepFlyMenu1.ShowAllBorders = false;
            beepFlyMenu1.ShowBottomBorder = false;
            beepFlyMenu1.ShowFocusIndicator = false;
            beepFlyMenu1.ShowLeftBorder = false;
            beepFlyMenu1.ShowRightBorder = false;
            beepFlyMenu1.ShowShadow = false;
            beepFlyMenu1.ShowTitle = true;
            beepFlyMenu1.ShowTitleLine = true;
            beepFlyMenu1.ShowTitleLineinFullWidth = true;
            beepFlyMenu1.ShowTopBorder = false;
            beepFlyMenu1.Size = new Size(148, 25);
            beepFlyMenu1.SlideFrom = SlideDirection.Left;
            beepFlyMenu1.StaticNotMoving = false;
            beepFlyMenu1.TabIndex = 13;
            beepFlyMenu1.Text = "beepFlyMenu1";
            beepFlyMenu1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepFlyMenu1.TitleAlignment = ContentAlignment.TopLeft;
            beepFlyMenu1.TitleBottomY = 40;
            beepFlyMenu1.TitleLineColor = Color.Gray;
            beepFlyMenu1.TitleLineThickness = 2;
            beepFlyMenu1.TitleText = "List Box";
            beepFlyMenu1.ToolTipText = "";
            beepFlyMenu1.UseGradientBackground = false;
            // 
            // beepFlyoutMenu1
            // 
            beepFlyoutMenu1.ActiveBackColor = Color.FromArgb(0, 153, 188);
            beepFlyoutMenu1.AnimationDuration = 500;
            beepFlyoutMenu1.AnimationType = DisplayAnimationType.SlideAndFade;
            beepFlyoutMenu1.BlockID = null;
            beepFlyoutMenu1.BorderColor = Color.FromArgb(204, 204, 204);
            beepFlyoutMenu1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepFlyoutMenu1.BorderRadius = 5;
            beepFlyoutMenu1.BorderStyle = BorderStyle.FixedSingle;
            beepFlyoutMenu1.BorderThickness = 1;
            beepFlyoutMenu1.DataContext = null;
            beepFlyoutMenu1.DisabledBackColor = Color.Gray;
            beepFlyoutMenu1.DisabledForeColor = Color.Empty;
            beepFlyoutMenu1.DrawingRect = new Rectangle(1, 1, 129, 23);
            beepFlyoutMenu1.Easing = EasingType.Linear;
            beepFlyoutMenu1.FieldID = null;
            beepFlyoutMenu1.FlyoutDirection = SlideDirection.Left;
            beepFlyoutMenu1.FocusBackColor = Color.White;
            beepFlyoutMenu1.FocusBorderColor = Color.Gray;
            beepFlyoutMenu1.FocusForeColor = Color.Black;
            beepFlyoutMenu1.FocusIndicatorColor = Color.Blue;
            beepFlyoutMenu1.Form = null;
            beepFlyoutMenu1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepFlyoutMenu1.GradientEndColor = Color.FromArgb(0, 120, 215);
            beepFlyoutMenu1.GradientStartColor = Color.White;
            beepFlyoutMenu1.HoverBackColor = Color.FromArgb(0, 99, 177);
            beepFlyoutMenu1.HoverBorderColor = Color.FromArgb(0, 153, 188);
            beepFlyoutMenu1.HoveredBackcolor = Color.Wheat;
            beepFlyoutMenu1.HoverForeColor = Color.Black;
            beepFlyoutMenu1.Id = -1;
            beepFlyoutMenu1.InactiveBackColor = Color.Gray;
            beepFlyoutMenu1.InactiveBorderColor = Color.Gray;
            beepFlyoutMenu1.InactiveForeColor = Color.Black;
            beepFlyoutMenu1.IsAcceptButton = false;
            beepFlyoutMenu1.IsBorderAffectedByTheme = true;
            beepFlyoutMenu1.IsCancelButton = false;
            beepFlyoutMenu1.IsChild = false;
            beepFlyoutMenu1.IsDefault = false;
            beepFlyoutMenu1.IsFocused = false;
            beepFlyoutMenu1.IsFramless = false;
            beepFlyoutMenu1.IsHovered = false;
            beepFlyoutMenu1.IsPressed = false;
            beepFlyoutMenu1.IsRounded = false;
            beepFlyoutMenu1.IsShadowAffectedByTheme = true;
            beepFlyoutMenu1.LabelPosition = LabelPosition.Left;
            beepFlyoutMenu1.ListItems.Add((Template.SimpleMenuItem)resources.GetObject("beepFlyoutMenu1.ListItems"));
            beepFlyoutMenu1.ListItems.Add((Template.SimpleMenuItem)resources.GetObject("beepFlyoutMenu1.ListItems1"));
            beepFlyoutMenu1.Location = new Point(408, 267);
            beepFlyoutMenu1.Name = "beepFlyoutMenu1";
            beepFlyoutMenu1.OverrideFontSize = TypeStyleFontSize.None;
            beepFlyoutMenu1.ParentBackColor = Color.Empty;
            beepFlyoutMenu1.PressedBackColor = Color.FromArgb(0, 153, 188);
            beepFlyoutMenu1.PressedBorderColor = Color.Gray;
            beepFlyoutMenu1.PressedForeColor = Color.Black;
            beepFlyoutMenu1.SavedGuidID = null;
            beepFlyoutMenu1.SavedID = null;
            beepFlyoutMenu1.SelectedIndex = 0;
            beepFlyoutMenu1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepFlyoutMenu1.ShadowOffset = 0;
            beepFlyoutMenu1.ShadowOpacity = 0.5F;
            beepFlyoutMenu1.ShowAllBorders = false;
            beepFlyoutMenu1.ShowBottomBorder = false;
            beepFlyoutMenu1.ShowFocusIndicator = false;
            beepFlyoutMenu1.ShowLeftBorder = false;
            beepFlyoutMenu1.ShowRightBorder = false;
            beepFlyoutMenu1.ShowShadow = false;
            beepFlyoutMenu1.ShowTopBorder = false;
            beepFlyoutMenu1.Size = new Size(131, 25);
            beepFlyoutMenu1.SlideFrom = SlideDirection.Bottom;
            beepFlyoutMenu1.StaticNotMoving = false;
            beepFlyoutMenu1.TabIndex = 14;
            beepFlyoutMenu1.Text = "beepFlyoutMenu1";
            beepFlyoutMenu1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepFlyoutMenu1.ToolTipText = "";
            beepFlyoutMenu1.UseGradientBackground = false;
            // 
            // beepExtendedButton1
            // 
            beepExtendedButton1.ActiveBackColor = Color.FromArgb(0, 153, 188);
            beepExtendedButton1.AnimationDuration = 500;
            beepExtendedButton1.AnimationType = DisplayAnimationType.None;
            beepExtendedButton1.ApplyThemeOnImage = false;
            beepExtendedButton1.BackColor = Color.White;
            beepExtendedButton1.BlockID = null;
            beepExtendedButton1.BorderColor = Color.FromArgb(204, 204, 204);
            beepExtendedButton1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepExtendedButton1.BorderRadius = 5;
            beepExtendedButton1.BorderStyle = BorderStyle.FixedSingle;
            beepExtendedButton1.BorderThickness = 1;
            beepExtendedButton1.ButtonWidth = 173;
            beepExtendedButton1.DataContext = null;
            beepExtendedButton1.DisabledBackColor = Color.Gray;
            beepExtendedButton1.DisabledForeColor = Color.Empty;
            beepExtendedButton1.DrawingRect = new Rectangle(1, 1, 193, 31);
            beepExtendedButton1.Easing = EasingType.Linear;
            beepExtendedButton1.ExtendButtonImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\021-flowchart.svg";
            beepExtendedButton1.FieldID = null;
            beepExtendedButton1.FocusBackColor = Color.White;
            beepExtendedButton1.FocusBorderColor = Color.Gray;
            beepExtendedButton1.FocusForeColor = Color.Black;
            beepExtendedButton1.FocusIndicatorColor = Color.Blue;
            beepExtendedButton1.Form = null;
            beepExtendedButton1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepExtendedButton1.GradientEndColor = Color.FromArgb(0, 120, 215);
            beepExtendedButton1.GradientStartColor = Color.White;
            beepExtendedButton1.HoverBackColor = Color.FromArgb(0, 99, 177);
            beepExtendedButton1.HoverBorderColor = Color.FromArgb(0, 153, 188);
            beepExtendedButton1.HoveredBackcolor = Color.Wheat;
            beepExtendedButton1.HoverForeColor = Color.Black;
            beepExtendedButton1.Id = -1;
            beepExtendedButton1.ImagePath = "H:\\dev\\iconPacks\\10007852-team-management (2) (1)\\10007856-team-management\\10007856-team-management\\svg\\018-puzzle.svg";
            beepExtendedButton1.ImageSize = 20;
            beepExtendedButton1.InactiveBackColor = Color.Gray;
            beepExtendedButton1.InactiveBorderColor = Color.Gray;
            beepExtendedButton1.InactiveForeColor = Color.Black;
            beepExtendedButton1.IsAcceptButton = false;
            beepExtendedButton1.IsBorderAffectedByTheme = true;
            beepExtendedButton1.IsCancelButton = false;
            beepExtendedButton1.IsChild = false;
            beepExtendedButton1.IsDefault = false;
            beepExtendedButton1.IsFocused = false;
            beepExtendedButton1.IsFramless = false;
            beepExtendedButton1.IsHovered = false;
            beepExtendedButton1.IsPressed = false;
            beepExtendedButton1.IsRounded = false;
            beepExtendedButton1.IsShadowAffectedByTheme = true;
            beepExtendedButton1.Location = new Point(576, 478);
            beepExtendedButton1.MenuItem = null;
            beepExtendedButton1.Name = "beepExtendedButton1";
            beepExtendedButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepExtendedButton1.ParentBackColor = Color.Empty;
            beepExtendedButton1.PressedBackColor = Color.FromArgb(0, 153, 188);
            beepExtendedButton1.PressedBorderColor = Color.Gray;
            beepExtendedButton1.PressedForeColor = Color.Black;
            beepExtendedButton1.SavedGuidID = null;
            beepExtendedButton1.SavedID = null;
            beepExtendedButton1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            beepExtendedButton1.ShadowOffset = 0;
            beepExtendedButton1.ShadowOpacity = 0.5F;
            beepExtendedButton1.ShowAllBorders = false;
            beepExtendedButton1.ShowBottomBorder = false;
            beepExtendedButton1.ShowFocusIndicator = false;
            beepExtendedButton1.ShowLeftBorder = false;
            beepExtendedButton1.ShowRightBorder = false;
            beepExtendedButton1.ShowShadow = false;
            beepExtendedButton1.ShowTopBorder = false;
            beepExtendedButton1.Size = new Size(195, 33);
            beepExtendedButton1.SlideFrom = SlideDirection.Left;
            beepExtendedButton1.StaticNotMoving = false;
            beepExtendedButton1.TabIndex = 15;
            beepExtendedButton1.Text = "fdfghgh";
            beepExtendedButton1.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepExtendedButton1.ToolTipText = "";
            beepExtendedButton1.UseGradientBackground = false;
            // 
            // beepButton2
            // 
            beepButton2.ActiveBackColor = Color.Gray;
            beepButton2.AnimationDuration = 500;
            beepButton2.AnimationType = DisplayAnimationType.None;
            beepButton2.ApplyThemeOnImage = false;
            beepButton2.BackColor = Color.White;
            beepButton2.BlockID = null;
            beepButton2.BorderColor = Color.Black;
            beepButton2.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepButton2.BorderRadius = 5;
            beepButton2.BorderSize = 1;
            beepButton2.BorderStyle = BorderStyle.FixedSingle;
            beepButton2.BorderThickness = 1;
            beepButton2.DataContext = null;
            beepButton2.DisabledBackColor = Color.Gray;
            beepButton2.DisabledForeColor = Color.Empty;
            beepButton2.DrawingRect = new Rectangle(1, 1, 118, 38);
            beepButton2.Easing = EasingType.Linear;
            beepButton2.FieldID = null;
            beepButton2.FlatAppearance = true;
            beepButton2.FlatStyle = FlatStyle.Standard;
            beepButton2.FocusBackColor = Color.Gray;
            beepButton2.FocusBorderColor = Color.Gray;
            beepButton2.FocusForeColor = Color.Black;
            beepButton2.FocusIndicatorColor = Color.Blue;
            beepButton2.Font = new Font("Segoe UI", 12F);
            beepButton2.ForeColor = Color.White;
            beepButton2.Form = null;
            beepButton2.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepButton2.GradientEndColor = Color.Gray;
            beepButton2.GradientStartColor = Color.Gray;
            beepButton2.HideText = false;
            beepButton2.HoverBackColor = Color.Gray;
            beepButton2.HoverBorderColor = Color.Gray;
            beepButton2.HoveredBackcolor = Color.Wheat;
            beepButton2.HoverForeColor = Color.Black;
            beepButton2.Id = -1;
            beepButton2.Image = null;
            beepButton2.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton2.ImageClicked = null;
            beepButton2.ImagePath = null;
            beepButton2.InactiveBackColor = Color.Gray;
            beepButton2.InactiveBorderColor = Color.Gray;
            beepButton2.InactiveForeColor = Color.Black;
            beepButton2.IsAcceptButton = false;
            beepButton2.IsBorderAffectedByTheme = true;
            beepButton2.IsCancelButton = false;
            beepButton2.IsChild = false;
            beepButton2.IsDefault = false;
            beepButton2.IsFocused = false;
            beepButton2.IsFramless = false;
            beepButton2.IsHovered = false;
            beepButton2.IsPressed = false;
            beepButton2.IsRounded = false;
            beepButton2.IsSelected = false;
            beepButton2.IsShadowAffectedByTheme = true;
            beepButton2.IsSideMenuChild = false;
            beepButton2.IsStillButton = false;
            beepButton2.Location = new Point(705, 400);
            beepButton2.Margin = new Padding(0);
            beepButton2.MaxImageSize = new Size(32, 32);
            beepButton2.Name = "beepButton2";
            beepButton2.OverrideFontSize = TypeStyleFontSize.None;
            beepButton2.ParentBackColor = Color.Empty;
            beepButton2.PressedBackColor = Color.Gray;
            beepButton2.PressedBorderColor = Color.Gray;
            beepButton2.PressedForeColor = Color.Black;
            beepButton2.SavedGuidID = null;
            beepButton2.SavedID = null;
            beepButton2.SelectedBorderColor = Color.Blue;
            beepButton2.ShadowColor = Color.Black;
            beepButton2.ShadowOffset = 0;
            beepButton2.ShadowOpacity = 0.5F;
            beepButton2.ShowAllBorders = false;
            beepButton2.ShowBottomBorder = false;
            beepButton2.ShowFocusIndicator = false;
            beepButton2.ShowLeftBorder = false;
            beepButton2.ShowRightBorder = false;
            beepButton2.ShowShadow = false;
            beepButton2.ShowTopBorder = false;
            beepButton2.Size = new Size(120, 40);
            beepButton2.SlideFrom = SlideDirection.Left;
            beepButton2.StaticNotMoving = false;
            beepButton2.TabIndex = 16;
            beepButton2.Text = "beepButton2";
            beepButton2.TextAlign = ContentAlignment.MiddleCenter;
            beepButton2.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton2.Theme = Vis.Modules.EnumBeepThemes.HighlightTheme;
            beepButton2.ToolTipText = "";
            beepButton2.UseGradientBackground = false;
            // 
            // Form2
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1048, 681);
            Controls.Add(beepButton2);
            Controls.Add(beepExtendedButton1);
            Controls.Add(beepFlyoutMenu1);
            Controls.Add(beepFlyMenu1);
            Controls.Add(beepListBox1);
            Controls.Add(beepCircularButton1);
            Controls.Add(beepButton1);
            Controls.Add(beepImage1);
            Controls.Add(beepLabel1);
            Controls.Add(beepSideMenu1);
            DoubleBuffered = true;
            Name = "Form2";
            Padding = new Padding(10);
            Text = "Asset HR Digital Space";
            Controls.SetChildIndex(beepSideMenu1, 0);
            Controls.SetChildIndex(FunctionsPanel1, 0);
            Controls.SetChildIndex(beepLabel1, 0);
            Controls.SetChildIndex(beepImage1, 0);
            Controls.SetChildIndex(beepButton1, 0);
            Controls.SetChildIndex(beepCircularButton1, 0);
            Controls.SetChildIndex(beepListBox1, 0);
            Controls.SetChildIndex(beepFlyMenu1, 0);
            Controls.SetChildIndex(beepFlyoutMenu1, 0);
            Controls.SetChildIndex(beepExtendedButton1, 0);
            Controls.SetChildIndex(beepButton2, 0);
            Controls.SetChildIndex(beepPanel1, 0);
            beepPanel1.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private BeepSideMenu beepSideMenu1;
        private BeepLabel beepLabel1;
        private BeepImage beepImage1;
        private BeepButton beepButton1;
        private BeepCircularButton beepCircularButton1;
        private BeepListBox beepListBox1;
        private BeepDropDownMenu beepFlyMenu1;
        private BeepFlyoutMenu beepFlyoutMenu1;
        private BeepExtendedButton beepExtendedButton1;
        private BeepButton beepButton2;
    }
}