global using System;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Windows.Forms;
global using TheTechIdea.Beep.Winform.Controls.Common;
global using TheTechIdea.Beep.Winform.Controls.Helpers;
global using TheTechIdea.Beep.Winform.Controls.BaseImage;
global using TheTechIdea.Beep.Vis.Modules;
global using TheTechIdea.Beep.Winform.Controls.Models;
global using Timer = System.Windows.Forms.Timer;
global using TheTechIdea.Beep.Winform.Controls.ThemeManagement;
global using TheTechIdea.Beep.Winform.Controls.ImageManagement;
global using TheTechIdea.Beep.Winform.Controls.FontManagement;
global using ArrowDirection = TheTechIdea.Beep.Winform.Controls.Models.ArrowDirection;
global using TheTechIdea.Beep.Winform.Controls.Styling;
global using  TheTechIdea.Beep.Icons;
global using TheTechIdea.Beep.Winform.Controls.Trees.Helpers;
global using TheTechIdea.Beep.Winform.Controls.Trees.Models;
global using TheTechIdea.Beep.Winform.Controls.Forms.Helpers;
global using TheTechIdea.Beep.Winform.Controls.Common;