namespace TheTechIdea.Beep.Winform.Controls.DialogsManagers.Forms
{
    partial class TestDialogForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            GraphicsPath graphicsPath4 = new GraphicsPath();
            GraphicsPath graphicsPath5 = new GraphicsPath();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TestDialogForm));
            GraphicsPath graphicsPath6 = new GraphicsPath();
            GraphicsPath graphicsPath1 = new GraphicsPath();
            GraphicsPath graphicsPath2 = new GraphicsPath();
            GraphicsPath graphicsPath3 = new GraphicsPath();
            beepChart1 = new TheTechIdea.Beep.Winform.Controls.Charts.BeepChart();
            beepCircularButton1 = new TheTechIdea.Beep.Winform.Controls.Buttons.BeepCircularButton();
            SuspendLayout();
            // 
            // beepChart1
            // 
            beepChart1.AccentColor = Color.FromArgb(0, 150, 136);
            beepChart1.AnimationDuration = 500;
            beepChart1.AnimationType = DisplayAnimationType.None;
            beepChart1.ApplyThemeToChilds = true;
            beepChart1.AutoDrawHitListComponents = true;
            beepChart1.BackColor = Color.FromArgb(255, 255, 255);
            beepChart1.BadgeBackColor = Color.Red;
            beepChart1.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            beepChart1.BadgeForeColor = Color.White;
            beepChart1.BadgeShape = BadgeShape.Circle;
            beepChart1.BlockID = null;
            beepChart1.BorderColor = Color.FromArgb(209, 213, 219);
            beepChart1.BorderDashStyle = DashStyle.Solid;
            beepChart1.BorderPainter = BeepControlStyle.Modern;
            graphicsPath4.FillMode = FillMode.Alternate;
            beepChart1.BorderPath = graphicsPath4;
            beepChart1.BorderRadius = 8;
            beepChart1.BorderRect = new Rectangle(1, 1, 397, 297);
            beepChart1.BorderStyle = BorderStyle.FixedSingle;
            beepChart1.BorderThickness = 2;
            beepChart1.BottomAxisType = AxisType.Numeric;
            beepChart1.BottomoffsetForDrawingRect = 0;
            beepChart1.BoundProperty = null;
            beepChart1.CanBeFocused = false;
            beepChart1.CanBeHovered = true;
            beepChart1.CanBePressed = true;
            beepChart1.CanBeSelected = true;
            beepChart1.Category = Utilities.DbFieldCategory.String;
            beepChart1.ChartAxisColor = Color.FromArgb(92, 139, 255);
            beepChart1.ChartBackColor = Color.FromArgb(255, 255, 255);
            beepChart1.ChartFillColor = Color.FromArgb(40, 92, 139, 255);
            beepChart1.ChartGridLineColor = Color.FromArgb(229, 230, 231);
            beepChart1.ChartLegendBackColor = Color.FromArgb(255, 255, 255);
            beepChart1.ChartLegendShapeColor = Color.FromArgb(38, 44, 57);
            beepChart1.ChartLegendTextColor = Color.FromArgb(38, 44, 57);
            beepChart1.ChartLineColor = Color.FromArgb(92, 139, 255);
            beepChart1.ChartSubtitle = "Subtitle or Description";
            beepChart1.ChartSubtitleFont = new Font("Consolas", 12F);
            beepChart1.ChartTextColor = Color.FromArgb(38, 44, 57);
            beepChart1.ChartTitle = "Chart Title";
            beepChart1.ChartTitleColor = Color.FromArgb(38, 44, 57);
            beepChart1.ChartTitleFont = new Font("Segoe UI", 14F, FontStyle.Bold);
            beepChart1.ChartTitleForeColor = Color.FromArgb(38, 44, 57);
            beepChart1.ChartType = ChartType.Line;
            beepChart1.ChartValue = "$12,000,000";
            beepChart1.ChartValueFont = new Font("Segoe UI", 8F);
            beepChart1.ComponentName = "BaseControl";
            beepChart1.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath5.FillMode = FillMode.Alternate;
            beepChart1.ContentShape = graphicsPath5;
            beepChart1.ControlStyle = BeepControlStyle.Modern;
            beepChart1.CurrentVisualPreset = Charts.ChartVisualPreset.Dashboard;
            beepChart1.CustomDraw = false;
            beepChart1.CustomIconColor = Color.Black;
            beepChart1.CustomIconPath = "";
            beepChart1.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            beepChart1.CustomPadding = new Padding(0);
            beepChart1.DataContext = null;
            beepChart1.DataSourceProperty = null;
            beepChart1.DisabledBackColor = Color.LightGray;
            beepChart1.DisabledBorderColor = Color.Gray;
            beepChart1.DisabledForeColor = Color.DarkGray;
            beepChart1.DrawingRect = new Rectangle(15, 15, 369, 269);
            beepChart1.Easing = EasingType.Linear;
            beepChart1.EnableHighQualityRendering = true;
            beepChart1.EnableRippleEffect = false;
            beepChart1.EnableSplashEffect = false;
            beepChart1.ErrorColor = Color.Empty;
            beepChart1.ErrorText = "";
            beepChart1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepChart1.FieldID = null;
            beepChart1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepChart1.FloatingLabel = "";
            beepChart1.FloatingLabelOn = false;
            beepChart1.FocusBackColor = Color.LightYellow;
            beepChart1.FocusBorderColor = Color.RoyalBlue;
            beepChart1.FocusForeColor = Color.Black;
            beepChart1.FocusIndicatorColor = Color.RoyalBlue;
            beepChart1.ForeColor = Color.FromArgb(38, 44, 57);
            beepChart1.Form = null;
            beepChart1.GlassmorphismBlur = 10F;
            beepChart1.GlassmorphismOpacity = 0.1F;
            beepChart1.GradientAngle = 0F;
            beepChart1.GradientDirection = LinearGradientMode.Horizontal;
            beepChart1.GradientEndColor = Color.Gray;
            beepChart1.GradientStartColor = Color.LightGray;
            beepChart1.GridMode = false;
            beepChart1.GuidID = "fbe8b27f-08e1-465f-8636-4f006dfee428";
            beepChart1.HasError = false;
            beepChart1.HelperText = "";
            beepChart1.HelperTextOn = false;
            beepChart1.HitAreaEventOn = false;
            beepChart1.HitTestControl = null;
            beepChart1.HoverBackColor = Color.LightBlue;
            beepChart1.HoverBorderColor = Color.Blue;
            beepChart1.HoveredBackcolor = Color.LightBlue;
            beepChart1.HoverForeColor = Color.Black;
            beepChart1.IconKey = "";
            beepChart1.IconSize = 20;
            beepChart1.Id = -1;
            beepChart1.InactiveBorderColor = Color.Gray;
            beepChart1.IndicatorLineColor = Color.Red;
            beepChart1.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath6.FillMode = FillMode.Alternate;
            beepChart1.InnerShape = graphicsPath6;
            beepChart1.IsAcceptButton = false;
            beepChart1.IsBorderAffectedByTheme = true;
            beepChart1.IsCancelButton = false;
            beepChart1.IsChild = true;
            beepChart1.IsCustomeBorder = false;
            beepChart1.IsDefault = false;
            beepChart1.IsDeleted = false;
            beepChart1.IsDirty = false;
            beepChart1.IsEditable = true;
            beepChart1.IsFocused = false;
            beepChart1.IsFrameless = false;
            beepChart1.IsHovered = false;
            beepChart1.IsNew = false;
            beepChart1.IsPressed = false;
            beepChart1.IsReadOnly = false;
            beepChart1.IsRequired = false;
            beepChart1.IsRounded = true;
            beepChart1.IsRoundedAffectedByTheme = true;
            beepChart1.IsSelected = false;
            beepChart1.IsSelectedOptionOn = false;
            beepChart1.IsShadowAffectedByTheme = true;
            beepChart1.IsTransparentBackground = false;
            beepChart1.IsValid = true;
            beepChart1.IsVisible = true;
            beepChart1.LabelPosition = LabelPosition.Left;
            beepChart1.LabelText = "";
            beepChart1.LabelTextOn = false;
            beepChart1.LeadingIconPath = "";
            beepChart1.LeadingImagePath = "";
            beepChart1.LeftAxisType = AxisType.Numeric;
            beepChart1.LeftoffsetForDrawingRect = 0;
            beepChart1.LegendPlacement = Charts.Helpers.LegendPlacement.InsideTopRight;
            beepChart1.LinkedProperty = null;
            beepChart1.Location = new Point(74, 42);
            beepChart1.MaxHitListDrawPerFrame = 0;
            beepChart1.MinimumSize = new Size(132, 88);
            beepChart1.ModernGradientType = ModernGradientType.None;
            beepChart1.Name = "beepChart1";
            beepChart1.OuterShape = null;
            beepChart1.OverrideFontSize = TypeStyleFontSize.None;
            beepChart1.PainterKind = BaseControlPainterKind.Classic;
            beepChart1.ParentBackColor = Color.FromArgb(255, 255, 255);
            beepChart1.ParentControl = null;
            beepChart1.PressedBackColor = Color.Gray;
            beepChart1.PressedBorderColor = Color.DarkGray;
            beepChart1.PressedForeColor = Color.White;
            beepChart1.RadialCenter = (PointF)resources.GetObject("beepChart1.RadialCenter");
            beepChart1.RightoffsetForDrawingRect = 0;
            beepChart1.SavedGuidID = null;
            beepChart1.SavedID = null;
            beepChart1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepChart1.SelectedBackColor = Color.LightGreen;
            beepChart1.SelectedBorderColor = Color.Green;
            beepChart1.SelectedForeColor = Color.Black;
            beepChart1.SelectedValue = null;
            beepChart1.SelectionBorderColor = Color.FromArgb(200, 100, 0);
            beepChart1.SelectionColor = Color.FromArgb(255, 200, 50);
            beepChart1.ShadowColor = Color.Black;
            beepChart1.ShadowOffset = 3;
            beepChart1.ShadowOpacity = 0.25F;
            beepChart1.ShowAllBorders = false;
            beepChart1.ShowBottomBorder = false;
            beepChart1.ShowFocusIndicator = false;
            beepChart1.ShowIndicatorLine = false;
            beepChart1.ShowLabelAboveBorder = false;
            beepChart1.ShowLeftBorder = false;
            beepChart1.ShowLegend = true;
            beepChart1.ShowMarkers = true;
            beepChart1.ShowRightBorder = false;
            beepChart1.ShowShadow = false;
            beepChart1.ShowTitle = true;
            beepChart1.ShowTopBorder = false;
            beepChart1.Size = new Size(400, 300);
            beepChart1.SlideFrom = SlideDirection.Left;
            beepChart1.SmoothLines = false;
            beepChart1.Stacked = false;
            beepChart1.StackedMode = Charts.Helpers.StackedMode.None;
            beepChart1.StaticNotMoving = false;
            beepChart1.SurfaceStyle = Charts.ChartSurfaceStyle.Card;
            beepChart1.TabIndex = 0;
            beepChart1.TempBackColor = Color.LightGray;
            beepChart1.Text = "beepChart1";
            beepChart1.TextFont = new Font("Arial", 10F);
            beepChart1.Theme = "ModernTheme";
            beepChart1.TooltipFont = null;
            beepChart1.TooltipMaxSize = null;
            beepChart1.ToolTipText = "";
            beepChart1.TopoffsetForDrawingRect = 0;
            beepChart1.TrackballCrosshairColor = Color.FromArgb(180, 200, 200, 200);
            beepChart1.TrackballTooltipBackColor = Color.FromArgb(240, 240, 240);
            beepChart1.TrackballTooltipBorderColor = Color.FromArgb(200, 200, 200);
            beepChart1.TrailingIconPath = "";
            beepChart1.TrailingImagePath = "";
            beepChart1.UseExternalBufferedGraphics = true;
            beepChart1.UseFormStylePaint = true;
            beepChart1.UseGlassmorphism = false;
            beepChart1.UseGradientBackground = false;
            beepChart1.UseThemeFont = true;
            beepChart1.ValidationIcon = Badges.ValidationState.None;
            beepChart1.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            beepChart1.ViewportXMax = 0F;
            beepChart1.ViewportXMin = 0F;
            beepChart1.ViewportYMax = 0F;
            beepChart1.ViewportYMin = 0F;
            beepChart1.XAxisTitle = "";
            beepChart1.XLabelAngle = 0F;
            beepChart1.XTimeGranularity = Charts.Helpers.TimeTickGranularity.Auto;
            beepChart1.YAxisTitle = "";
            beepChart1.YLabelAngle = 0F;
            beepChart1.YTimeGranularity = Charts.Helpers.TimeTickGranularity.Auto;
            // 
            // beepCircularButton1
            // 
            beepCircularButton1.AnimationDuration = 500;
            beepCircularButton1.AnimationType = DisplayAnimationType.None;
            beepCircularButton1.ApplyThemeToChilds = true;
            beepCircularButton1.AutoDrawHitListComponents = true;
            beepCircularButton1.BackColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.BadgeBackColor = Color.FromArgb(92, 139, 255);
            beepCircularButton1.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            beepCircularButton1.BadgeForeColor = Color.FromArgb(58, 58, 58);
            beepCircularButton1.BadgeShape = BadgeShape.Circle;
            beepCircularButton1.BlockID = null;
            beepCircularButton1.BorderColor = Color.FromArgb(209, 213, 219);
            beepCircularButton1.BorderDashStyle = DashStyle.Solid;
            beepCircularButton1.BorderPainter = BeepControlStyle.Modern;
            graphicsPath1.FillMode = FillMode.Alternate;
            beepCircularButton1.BorderPath = graphicsPath1;
            beepCircularButton1.BorderRadius = 8;
            beepCircularButton1.BorderRect = new Rectangle(1, 1, 97, 97);
            beepCircularButton1.BorderStyle = BorderStyle.FixedSingle;
            beepCircularButton1.BorderThickness = 2;
            beepCircularButton1.BottomoffsetForDrawingRect = 0;
            beepCircularButton1.BoundProperty = null;
            beepCircularButton1.CanBeFocused = false;
            beepCircularButton1.CanBeHovered = true;
            beepCircularButton1.CanBePressed = true;
            beepCircularButton1.CanBeSelected = true;
            beepCircularButton1.Category = Utilities.DbFieldCategory.String;
            beepCircularButton1.ComponentName = "BaseControl";
            beepCircularButton1.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath2.FillMode = FillMode.Alternate;
            beepCircularButton1.ContentShape = graphicsPath2;
            beepCircularButton1.ControlStyle = BeepControlStyle.Modern;
            beepCircularButton1.CustomIconColor = Color.Black;
            beepCircularButton1.CustomIconPath = "";
            beepCircularButton1.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            beepCircularButton1.CustomPadding = new Padding(0);
            beepCircularButton1.DataContext = null;
            beepCircularButton1.DataSourceProperty = null;
            beepCircularButton1.DisabledBackColor = Color.FromArgb(244, 246, 252);
            beepCircularButton1.DisabledBorderColor = Color.FromArgb(220, 227, 240);
            beepCircularButton1.DisabledForeColor = Color.FromArgb(222, 223, 229);
            beepCircularButton1.DrawingRect = new Rectangle(15, 15, 69, 69);
            beepCircularButton1.Easing = EasingType.Linear;
            beepCircularButton1.EnableHighQualityRendering = true;
            beepCircularButton1.EnableRippleEffect = false;
            beepCircularButton1.EnableSplashEffect = false;
            beepCircularButton1.ErrorColor = Color.Empty;
            beepCircularButton1.ErrorText = "";
            beepCircularButton1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepCircularButton1.FieldID = null;
            beepCircularButton1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepCircularButton1.FloatingLabel = "";
            beepCircularButton1.FloatingLabelOn = false;
            beepCircularButton1.FocusBackColor = Color.FromArgb(31, 95, 255);
            beepCircularButton1.FocusBorderColor = Color.RoyalBlue;
            beepCircularButton1.FocusForeColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.FocusIndicatorColor = Color.RoyalBlue;
            beepCircularButton1.Font = new Font("Segoe UI", 8F);
            beepCircularButton1.ForeColor = Color.FromArgb(38, 44, 57);
            beepCircularButton1.Form = null;
            beepCircularButton1.GlassmorphismBlur = 10F;
            beepCircularButton1.GlassmorphismOpacity = 0.1F;
            beepCircularButton1.GradientAngle = 0F;
            beepCircularButton1.GradientDirection = LinearGradientMode.Horizontal;
            beepCircularButton1.GradientEndColor = Color.FromArgb(242, 245, 252);
            beepCircularButton1.GradientStartColor = Color.FromArgb(251, 252, 255);
            beepCircularButton1.GridMode = false;
            beepCircularButton1.GuidID = "0660f3ae-3f76-4800-a3e9-9c47ee1d1843";
            beepCircularButton1.HasError = false;
            beepCircularButton1.HelperText = "";
            beepCircularButton1.HelperTextOn = false;
            beepCircularButton1.HideText = false;
            beepCircularButton1.HitAreaEventOn = false;
            beepCircularButton1.HitTestControl = null;
            beepCircularButton1.HoverBackColor = Color.FromArgb(220, 229, 242);
            beepCircularButton1.HoverBorderColor = Color.Blue;
            beepCircularButton1.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            beepCircularButton1.HoverForeColor = Color.FromArgb(38, 44, 57);
            beepCircularButton1.IconKey = "";
            beepCircularButton1.IconSize = 20;
            beepCircularButton1.Id = -1;
            beepCircularButton1.ImagePath = "";
            beepCircularButton1.InactiveBorderColor = Color.Gray;
            beepCircularButton1.IndicatorLineColor = Color.Red;
            beepCircularButton1.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath3.FillMode = FillMode.Alternate;
            beepCircularButton1.InnerShape = graphicsPath3;
            beepCircularButton1.IsAcceptButton = false;
            beepCircularButton1.IsBorderAffectedByTheme = true;
            beepCircularButton1.IsCancelButton = false;
            beepCircularButton1.IsChild = true;
            beepCircularButton1.IsCustomeBorder = false;
            beepCircularButton1.IsCustomShape = true;
            beepCircularButton1.IsDefault = false;
            beepCircularButton1.IsDeleted = false;
            beepCircularButton1.IsDirty = false;
            beepCircularButton1.IsEditable = true;
            beepCircularButton1.IsFocused = false;
            beepCircularButton1.IsForColorSet = false;
            beepCircularButton1.IsFrameless = false;
            beepCircularButton1.IsHovered = false;
            beepCircularButton1.IsNew = false;
            beepCircularButton1.IsPressed = false;
            beepCircularButton1.IsReadOnly = false;
            beepCircularButton1.IsRequired = false;
            beepCircularButton1.IsRounded = true;
            beepCircularButton1.IsRoundedAffectedByTheme = false;
            beepCircularButton1.IsSelected = false;
            beepCircularButton1.IsSelectedOptionOn = false;
            beepCircularButton1.IsShadowAffectedByTheme = false;
            beepCircularButton1.IsTransparentBackground = false;
            beepCircularButton1.IsValid = true;
            beepCircularButton1.IsVisible = true;
            beepCircularButton1.LabelPosition = LabelPosition.Left;
            beepCircularButton1.LabelText = "";
            beepCircularButton1.LabelTextOn = false;
            beepCircularButton1.LeadingIconPath = "";
            beepCircularButton1.LeadingImagePath = "";
            beepCircularButton1.LeftoffsetForDrawingRect = 0;
            beepCircularButton1.LinkedProperty = null;
            beepCircularButton1.Location = new Point(570, 191);
            beepCircularButton1.MaxHitListDrawPerFrame = 0;
            beepCircularButton1.ModernGradientType = ModernGradientType.None;
            beepCircularButton1.Name = "beepCircularButton1";
            beepCircularButton1.OuterShape = null;
            beepCircularButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepCircularButton1.PainterKind = BaseControlPainterKind.Classic;
            beepCircularButton1.ParentBackColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.ParentControl = null;
            beepCircularButton1.PressedBackColor = Color.FromArgb(205, 218, 236);
            beepCircularButton1.PressedBorderColor = Color.DarkGray;
            beepCircularButton1.PressedForeColor = Color.FromArgb(38, 44, 57);
            beepCircularButton1.RadialCenter = (PointF)resources.GetObject("beepCircularButton1.RadialCenter");
            beepCircularButton1.RightoffsetForDrawingRect = 0;
            beepCircularButton1.SavedGuidID = null;
            beepCircularButton1.SavedID = null;
            beepCircularButton1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepCircularButton1.SelectedBackColor = Color.FromArgb(31, 95, 255);
            beepCircularButton1.SelectedBorderColor = Color.Green;
            beepCircularButton1.SelectedForeColor = Color.FromArgb(255, 255, 255);
            beepCircularButton1.SelectedValue = null;
            beepCircularButton1.ShadowColor = Color.FromArgb(40, 38, 44, 57);
            beepCircularButton1.ShadowOffset = 3;
            beepCircularButton1.ShadowOpacity = 0.25F;
            beepCircularButton1.ShowAllBorders = false;
            beepCircularButton1.ShowBorder = true;
            beepCircularButton1.ShowBottomBorder = false;
            beepCircularButton1.ShowFocusIndicator = false;
            beepCircularButton1.ShowIndicatorLine = false;
            beepCircularButton1.ShowLabelAboveBorder = false;
            beepCircularButton1.ShowLeftBorder = false;
            beepCircularButton1.ShowRightBorder = false;
            beepCircularButton1.ShowShadow = false;
            beepCircularButton1.ShowTopBorder = false;
            beepCircularButton1.Size = new Size(100, 100);
            beepCircularButton1.SlideFrom = SlideDirection.Left;
            beepCircularButton1.StaticNotMoving = false;
            beepCircularButton1.TabIndex = 1;
            beepCircularButton1.TempBackColor = Color.LightGray;
            beepCircularButton1.Text = "beepCircularButton1";
            beepCircularButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepCircularButton1.TextFont = new Font("Consolas", 12F);
            beepCircularButton1.TextLocation = Buttons.TextLocation.Below;
            beepCircularButton1.Theme = "ModernTheme";
            beepCircularButton1.TooltipFont = null;
            beepCircularButton1.TooltipMaxSize = null;
            beepCircularButton1.ToolTipText = "";
            beepCircularButton1.TopoffsetForDrawingRect = 0;
            beepCircularButton1.TrailingIconPath = "";
            beepCircularButton1.TrailingImagePath = "";
            beepCircularButton1.UseExternalBufferedGraphics = true;
            beepCircularButton1.UseFormStylePaint = true;
            beepCircularButton1.UseGlassmorphism = false;
            beepCircularButton1.UseGradientBackground = false;
            beepCircularButton1.UseThemeFont = false;
            beepCircularButton1.ValidationIcon = Badges.ValidationState.None;
            beepCircularButton1.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            // 
            // TestDialogForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(800, 450);
            Controls.Add(beepCircularButton1);
            Controls.Add(beepChart1);
            Name = "TestDialogForm";
            Text = "TestDialogForm";
            ResumeLayout(false);
        }

        #endregion

        private Charts.BeepChart beepChart1;
        private Buttons.BeepCircularButton beepCircularButton1;
    }
}