//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class ASHAL
    {
        
public System.String UWI  { get; set; }
public System.String FIELD  { get; set; }
public System.String FIELD_ID  { get; set; }
public System.String GC  { get; set; }
public System.DateTime? GC_CONN_DATE  { get; set; }
public System.String HEADER  { get; set; }
public System.DateTime? HEADER_CONN_DATE  { get; set; }
public System.String SLOT  { get; set; }
public System.DateTime? SLOT_CONN_DATE  { get; set; }
public System.String LIFT_METHOD  { get; set; }
public System.Decimal? ALLOWABLE  { get; set; }
public System.String OPERATION_STATUS  { get; set; }
public System.DateTime? OPERATION_STATUS_DATE  { get; set; }
public System.String AL_STATUS  { get; set; }
public System.String CURRENT_STATUS  { get; set; }
public System.DateTime? AL_STATUS_DATE  { get; set; }
public System.String FACILITY_NAME  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.String RESERVOIR_ID  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.String COMPLETION_OBJECTIVE  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.String LEFT_CHOKE_SIZE  { get; set; }
public System.String RIGHT_CHOKE_SIZE  { get; set; }
public System.Decimal? LIQUID_RATE  { get; set; }
public System.Decimal? WHP  { get; set; }
public System.Decimal? FLOW_LINE_PRESSURE  { get; set; }
public System.Decimal? WC  { get; set; }
public System.Decimal? TOTAL_GOR  { get; set; }
public System.String LQ_HISTORY  { get; set; }
public System.String WC_HISTORY  { get; set; }
public System.String WHP_HISTORY  { get; set; }
public System.String FLP_HISTORY  { get; set; }
public System.String CHOKE_HISTORY  { get; set; }
public System.String AL_HISTORY  { get; set; }
public System.String GCCONN_HISTORY  { get; set; }
public System.String GOR_HISTORY  { get; set; }
public System.String FBHP_HISTORY  { get; set; }
public System.String SBHP_HISTORY  { get; set; }
public System.String WHT_HISTORY  { get; set; }
public System.String H2S_HISTORY  { get; set; }
public System.Decimal? H2S  { get; set; }
public System.DateTime? H2S_DATE  { get; set; }
public System.Decimal? WHT  { get; set; }
public System.String WHT_DATE  { get; set; }
public System.String PROD_HISTORY  { get; set; }
public System.String WIRELINE_HISTORY  { get; set; }
public System.String OPERATION_HISTORY  { get; set; }
public System.String AREA  { get; set; }
public System.String WELL_OWNERSHIP  { get; set; }
public System.DateTime? WELL_OWNERSHIP_DATE  { get; set; }
public System.String LATEST_WELL_REVIEW  { get; set; }
public System.Decimal? OIL_API  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.Decimal? SHRINKAGE_FACTOR  { get; set; }
public System.Decimal? GAS_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? WATER_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? BSW  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S_IN_OIL  { get; set; }
public System.Decimal? H2S_IN_GAS  { get; set; }
public System.Decimal? CHLORIDE  { get; set; }
public System.Decimal? GAS_RATE  { get; set; }
public System.Decimal? FBHP_DEPTH  { get; set; }
public System.Decimal? FBHP_PRESSURE  { get; set; }
public System.String FBHP_PRESSURE_DATUM  { get; set; }
public System.Decimal? SBHP_DEPTH  { get; set; }
public System.Decimal? SBHP_PRESSURE  { get; set; }
public System.String SBHP_PRESSURE_DATUM  { get; set; }
public System.Decimal? WCS_FINDER  { get; set; }
public System.String WORKOVER_HISTORY  { get; set; }
public System.String ESP_OPR_HIST  { get; set; }
public System.String ESP_READ_HIST  { get; set; }
public System.Decimal? BOPD  { get; set; }
public System.Decimal? BWPD  { get; set; }
public System.Decimal? COND  { get; set; }
public System.Decimal? PRODDAYS  { get; set; }
public System.String DOWNHOLE_FACILITIES  { get; set; }
public System.String WELL_DEVIATION  { get; set; }
public System.DateTime? SPUD_DATE  { get; set; }
public System.DateTime? COMPLETION_DATE  { get; set; }
public System.Decimal? DRILLERS_TD  { get; set; }
public System.Decimal? GROUND_ELEVATION  { get; set; }
public System.Decimal? ELEVATION  { get; set; }
public System.String ELEVATION_REF  { get; set; }
public System.DateTime? PRODUCTION_DATE  { get; set; }
public System.Decimal? OIL_VOLUME  { get; set; }
public System.Decimal? CONDENSATE_VOLUME  { get; set; }
public System.Decimal? GAS_VOLUME  { get; set; }
public System.Decimal? WATER_VOLUME  { get; set; }
public System.Decimal? PRODUCTIVE_DAYS  { get; set; }
public System.DateTime? PROD_LAST_UPDATE  { get; set; }
public System.Decimal? LATITUDE  { get; set; }
public System.Decimal? LONGITUDE  { get; set; }
public System.String WLA_ACTIVITY_NAME  { get; set; }
public System.DateTime? WLA_START_TIME  { get; set; }
public System.String CONTRACTOR  { get; set; }
public System.String WLA_STATUS  { get; set; }
public System.String WLA_REMARKS  { get; set; }
public System.DateTime? WLA_LAST_UPDATE  { get; set; }
public System.String WT_ACTIVITY_TYPE  { get; set; }
public System.String WT_ACTIVITY_NAME  { get; set; }
public System.String WT_ACTIVITY_ID  { get; set; }
public System.Decimal? DURATION  { get; set; }
public System.String GOR_FLAG  { get; set; }
public System.String PRESSURE_FLAG  { get; set; }
public System.String WC_FLAG  { get; set; }
public System.String PREFFERED_FLAG  { get; set; }
public System.DateTime? WT_START_TIME  { get; set; }
public System.DateTime? WT_END_TIME  { get; set; }
public System.DateTime? WT_LAST_UPDATE  { get; set; }
public System.Decimal? WELL_HEAD_TEMP  { get; set; }
public System.String REASON  { get; set; }
public System.String MFL  { get; set; }
public System.String ZONES  { get; set; }
public System.Int64 RN  { get; set; }
        
        public ASHAL()
        {
        }
    }
}
