//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class BUSINESSUNITS_MEMBERS
    {
        
public System.Decimal? ID  { get; set; }
public System.String KOCNO  { get; set; }
public System.String DISPLAYNAME  { get; set; }
public System.Decimal? MEMBERSTATUS  { get; set; }
public System.DateTime? CREATEDDATE  { get; set; }
public System.DateTime? UPDATEDDATE  { get; set; }
public System.Decimal? BUSINESSUNITS_HDR_ID  { get; set; }
public System.Decimal? ROLEID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public BUSINESSUNITS_MEMBERS()
        {
        }
    }
}
