//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_DOWNTIME
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? DURATION  { get; set; }
public System.String DURATION_UOM  { get; set; }
public System.String DOWNTIME_TYPE  { get; set; }
public System.String DOWNTIME_TYPE_TEXT  { get; set; }
public System.String COMMENT  { get; set; }
public System.String COMMENT_1  { get; set; }
public System.DateTime? END_DATETIME  { get; set; }
public System.String CLOSE_CODE  { get; set; }
public System.String CLOSE_CODE_TEXT  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_DOWNTIME()
        {
        }
    }
}
