//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_OTGS_READ_DAY
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? TEMPERATURE  { get; set; }
public System.String TEMPERATURE_UOM  { get; set; }
public System.Decimal? PRESSURE  { get; set; }
public System.String PRESSURE_UOM  { get; set; }
public System.Decimal? STEAM_QLTY  { get; set; }
public System.String STEAM_QLTY_UOM  { get; set; }
public System.Decimal? FLOW_TIME  { get; set; }
public System.String FLOW_TIME_UOM  { get; set; }
public System.Decimal? WATER_RATE  { get; set; }
public System.String WATER_RATE_UOM  { get; set; }
public System.Decimal? WATER_RATE2  { get; set; }
public System.String WATER_RATE2_UOM  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_OTGS_READ_DAY()
        {
        }
    }
}
