//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_WELL_EVENT_OTS
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.String JOB_STATUS  { get; set; }
public System.String ACT_TYPE  { get; set; }
public System.String ACTIVITY  { get; set; }
public System.String CONTRACTOR  { get; set; }
public System.DateTime? EVENT_START  { get; set; }
public System.Decimal? REQUEST_ID  { get; set; }
public System.DateTime? WSPLAN_DATE  { get; set; }
public System.DateTime? FDPLAN_DATE  { get; set; }
public System.String REQUESTER  { get; set; }
public System.String SUPERVISER  { get; set; }
public System.DateTime? END_DATETIME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_WELL_EVENT_OTS()
        {
        }
    }
}
