//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_COMMENT
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.String COMMENT_1  { get; set; }
public System.String COMMENT_2  { get; set; }
public System.String COMMENT_3  { get; set; }
public System.String COMMENT_4  { get; set; }
public System.String SHIFT  { get; set; }
public System.String CONTR_NAME  { get; set; }
public System.String KOC_NO  { get; set; }
public System.String ITEM_ID  { get; set; }
public System.String PERIOD  { get; set; }
public System.DateTime? END_DATETIME  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_COMMENT()
        {
        }
    }
}
