//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class DEV_VT_HO_PROD_TEST
    {
        
public System.String ITEM_NAME  { get; set; }
public System.DateTime? START_DATETIME  { get; set; }
public System.Decimal? DURATION  { get; set; }
public System.String DURATION_UOM  { get; set; }
public System.String ACTIVITY_NAME  { get; set; }
public System.Decimal? PERIOD_NO  { get; set; }
public System.Decimal? WHP  { get; set; }
public System.String WHP_UOM  { get; set; }
public System.Decimal? WHT  { get; set; }
public System.String WHT_UOM  { get; set; }
public System.Decimal? CHOKE_LA  { get; set; }
public System.String CHOKE_LA_UOM  { get; set; }
public System.Decimal? CHOKE_LT  { get; set; }
public System.String CHOKE_LT_UOM  { get; set; }
public System.Decimal? CHOKE_RA  { get; set; }
public System.String CHOKE_RA_UOM  { get; set; }
public System.Decimal? CHOKE_RT  { get; set; }
public System.String CHOKE_RT_UOM  { get; set; }
public System.Decimal? LIQ_VOL_RT  { get; set; }
public System.String LIQ_VOL_RT_UOM  { get; set; }
public System.Decimal? GOR_HP  { get; set; }
public System.String GOR_HP_UOM  { get; set; }
public System.Decimal? GOR_TV  { get; set; }
public System.String GOR_TV_UOM  { get; set; }
public System.Decimal? GLR_TOT  { get; set; }
public System.String GLR_TOT_UOM  { get; set; }
public System.Decimal? GOR_TOT  { get; set; }
public System.String GOR_TOT_UOM  { get; set; }
public System.Decimal? OIL_VOL_RT  { get; set; }
public System.String OIL_VOL_RT_UOM  { get; set; }
public System.Decimal? WAT_VOL_RT  { get; set; }
public System.String WAT_VOL_RT_UOM  { get; set; }
public System.String IS_REPORTABLE  { get; set; }
public System.Decimal? GAS_VOL_RT  { get; set; }
public System.String GAS_VOL_RT_UOM  { get; set; }
public System.Decimal? BSW  { get; set; }
public System.String BSW_UOM  { get; set; }
public System.Decimal? BSW_VOL_FRAC  { get; set; }
public System.String BSW_VOL_FRAC_UOM  { get; set; }
public System.String CRITICAL_FLOW  { get; set; }
public System.String OF_OPER_S  { get; set; }
public System.Decimal? FLOWLINE_PRESS  { get; set; }
public System.String FLOWLINE_PRESS_UOM  { get; set; }
public System.Decimal? PUMP_BHFP  { get; set; }
public System.String PUMP_BHFP_UOM  { get; set; }
public System.Decimal? PUMP_CURRENT  { get; set; }
public System.String PUMP_CURRENT_UOM  { get; set; }
public System.Decimal? PUMP_FREQ  { get; set; }
public System.String PUMP_FREQ_UOM  { get; set; }
public System.Decimal? PUMP_RPM  { get; set; }
public System.String PUMP_RPM_UOM  { get; set; }
public System.String VALID_H2S_GAS  { get; set; }
public System.String VALID_LR  { get; set; }
public System.String COMMENT  { get; set; }
public System.Decimal? OIL_DENSITY  { get; set; }
public System.String OIL_DENSITY_UOM  { get; set; }
public System.Decimal? OIL_SHRINK  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.String SALINITY_UOM  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.String SALT_UOM  { get; set; }
public System.Decimal? SULPHUR  { get; set; }
public System.String SULPHUR_UOM  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.String CO2_UOM  { get; set; }
public System.Decimal? GAS_DENSITY  { get; set; }
public System.Decimal? H2S_IN_GAS  { get; set; }
public System.String H2S_IN_GAS_UOM  { get; set; }
public System.Decimal? H2S_IN_OIL  { get; set; }
public System.String H2S_IN_OIL_UOM  { get; set; }
public System.Decimal? WATER_SG  { get; set; }
public System.Decimal? WELL_ALLOWABLE  { get; set; }
public System.String WELL_ALLOWABLE_UOM  { get; set; }
public System.String PO_COMMENT  { get; set; }
public System.DateTime? FNDR_LAST_DATE  { get; set; }
public System.String CONTRACTOR  { get; set; }
public System.Decimal? SHRINKFACTOR  { get; set; }
public System.String UPDT_USER  { get; set; }
public System.DateTime? UPDT_DATE  { get; set; }
public System.String ITEM_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public DEV_VT_HO_PROD_TEST()
        {
        }
    }
}
