//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class FAVOUR_LIST
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? KOCNO  { get; set; }
public System.String FAV_TYPE  { get; set; }
public System.String FAV_VALUE_C  { get; set; }
public System.Decimal? FAV_VALUE_N  { get; set; }
public System.DateTime? FAV_VALUE_FROM_DATE  { get; set; }
public System.DateTime? FAV_VALUE_TO_DATE  { get; set; }
public System.Decimal? WCS  { get; set; }
public System.Decimal? FACILITYID  { get; set; }
public System.String FIELDID  { get; set; }
public System.String RESERVOIRID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public FAVOUR_LIST()
        {
        }
    }
}
