//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class FBHP_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.String SOURCE  { get; set; }
public System.Decimal? PRESSURE_DATUM  { get; set; }
public System.Decimal? EXTRAPOLATED_PRESSURE  { get; set; }
public System.Decimal? PRODUCTIVITY_INDEX  { get; set; }
public System.Decimal? GRADIENT  { get; set; }
public System.Decimal? STABILIZED_FLOW_PERIOD  { get; set; }
public System.Decimal? FLOWING_GRADIENT  { get; set; }
public System.Decimal? LEFT_CHOKE_SIZE  { get; set; }
public System.Decimal? RIGHT_CHOKE_SIZE  { get; set; }
public System.Decimal? DEPTH  { get; set; }
public System.Decimal? PRESSURE  { get; set; }
public System.Decimal? TEMPERATURE  { get; set; }
public System.Decimal? TEMPERATURE_GRADIENT  { get; set; }
public System.Decimal? TUBING_PRESSURE  { get; set; }
public System.Decimal? CASING_PRESSURE  { get; set; }
public System.Decimal? WELL_HEAD_TEMP  { get; set; }
public System.String PREFERRED_FLAG  { get; set; }
public System.String TS_REMARKS  { get; set; }
public System.String BUSINESS_ASSOC_ID  { get; set; }
public System.String OPERATION_NUMBER  { get; set; }
public System.String GAUGE_NUMBER  { get; set; }
public System.String EQUIPMENT_ROLE  { get; set; }
public System.String EQUIPMENT_TYPE  { get; set; }
public System.String ENGINEER  { get; set; }
public System.String REMARKS  { get; set; }
public System.Decimal? DEPTH_TVD  { get; set; }
public System.Decimal? GRADIENT_TVD  { get; set; }
public System.Decimal? OIL_FIELD_OPERATION_S  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERTED_BY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.String UPDATED_BY  { get; set; }
public System.String WC_NAME  { get; set; }
public System.Decimal? TOP_INTERVAL_MD  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.Decimal? WELL_TEST_ID  { get; set; }
public System.Decimal? WELL_TEST_STAGE_ID  { get; set; }
public System.Decimal? WELL_TEST_INTERPRETATION_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public FBHP_VW()
        {
        }
    }
}
