//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class GC_COMP_CONNECTION_VW
    {
        
public System.String GC  { get; set; }
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String FACILITY_TYPE  { get; set; }
public System.String STRING_NAME  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.String ACTIVITY_ID  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.Decimal? PORT_CONNECTION_S  { get; set; }
public System.Decimal? GC_SURFACE_FACILITY_S  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.Decimal? STRING_S  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERTED_BY  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.String UPDATED_BY  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public GC_COMP_CONNECTION_VW()
        {
        }
    }
}
