//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_ADDITIONALSERVICES
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String PVT  { get; set; }
public System.String RCI_MDT  { get; set; }
public System.String MRIL_CMR  { get; set; }
public System.String CBIL_EI_UBI_OBMI  { get; set; }
public System.String FORMATION_INTERVAL  { get; set; }
public System.String COMMENTS  { get; set; }
public System.String ECS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_ADDITIONALSERVICES()
        {
        }
    }
}
