//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_CASINGPROGRAM
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String HOLESIZEINCH  { get; set; }
public System.String CASINGSIZEINCH  { get; set; }
public System.String WEIGHTPPF  { get; set; }
public System.String DEPTHFTDD  { get; set; }
public System.String FORMATION  { get; set; }
public System.String COMMENTS  { get; set; }
public System.String GRADEAPITYPE  { get; set; }
public System.String CASINGTYPE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_CASINGPROGRAM()
        {
        }
    }
}
