//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_WELL_TYPE
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String WELLTYPE  { get; set; }
public System.String PREDRILLTARGETID  { get; set; }
public System.String PRIMARYTARGETFORMATION  { get; set; }
public System.String SECONDARYTARGETFORMATION  { get; set; }
public System.Decimal? SURFACEUTMWGS84EAST  { get; set; }
public System.Decimal? SURFACEUTMWGS84NORTH  { get; set; }
public System.Decimal? TARGETUTMWGS84EAST  { get; set; }
public System.Decimal? TARGETUTMWGS84NORTH  { get; set; }
public System.String WELLPROFILETYPE  { get; set; }
public System.Decimal? LATERALDISPLACEMENT  { get; set; }
public System.Decimal? WELLAZIMUTH  { get; set; }
public System.Decimal? WELLDEVIATION  { get; set; }
public System.String DRILLINGRIG  { get; set; }
public System.Decimal? RH_FT  { get; set; }
public System.Decimal? KBE_FT  { get; set; }
public System.Decimal? GLE_FT  { get; set; }
public System.String PRIMARYTARGETDEPTH  { get; set; }
public System.String PRIMARYTARGETTHICKNESS  { get; set; }
public System.String SECONDARYTARGETDEPTH  { get; set; }
public System.String SECONDARYTARGETTHICKNESS  { get; set; }
public System.Decimal? TOTALDEPTH  { get; set; }
public System.String EXPECTEDCOMPLETIONTYPE  { get; set; }
public System.String COMMENTS  { get; set; }
public System.String TARGETRESTRICTIONS  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_WELL_TYPE()
        {
        }
    }
}
