//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PDDP_MUDLOGUNIT
    {
        
public System.Decimal? ID  { get; set; }
public System.Decimal? PDDP_HDR_ID  { get; set; }
public System.Decimal? INSERT_BY  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.Decimal? UPDATE_BY  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String FSAMPLING_UNWASHEDBULK_FROMDD  { get; set; }
public System.Decimal? FSAMPLING_UNWASHEDBULK_FREQ  { get; set; }
public System.String FSAMPLING_WASHEDDRIED_FROMDD  { get; set; }
public System.Decimal? FSAMPLING_WASHEDDRIED_FREQ  { get; set; }
public System.String PCOMPLETION_COMPLETIONTYPE  { get; set; }
public System.String PCOMPLETION_PRODLINERSIZE  { get; set; }
public System.String PCOMPLETION_TUBINGSIZE  { get; set; }
public System.String PCOMPLETION_TUBINGTYPE  { get; set; }
public System.String DUNCERTAINTY_NORTHSOUTH  { get; set; }
public System.String DUNCERTAINTY_EASTWEST  { get; set; }
public System.String DUNCERTAINTY_VERTICAL  { get; set; }
public System.String SURVEY_INSTRUMENT  { get; set; }
public System.String SURVEY_INTERVAL  { get; set; }
public System.String SURVEY_FREQUENCY  { get; set; }
public System.Decimal? PCOMPLETION_SETINGDEPTH  { get; set; }
public System.String PCOMPLETION_WELLTYPE  { get; set; }
public System.String PCOMPLETION_TUBINGSIZE1  { get; set; }
public System.Decimal? PCOMPLETION_SETINGDEPTH1  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PDDP_MUDLOGUNIT()
        {
        }
    }
}
