//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PL_BALANCESCORECARD
    {
        
public System.Decimal? ID  { get; set; }
public System.String OBJECTIVES_CODE  { get; set; }
public System.String UNITS  { get; set; }
public System.Decimal? THRESHOLD  { get; set; }
public System.Decimal? TARGET  { get; set; }
public System.Decimal? STRETCH  { get; set; }
public System.Decimal? PRIMARY_ACCT  { get; set; }
public System.Decimal? SEC_ACCT  { get; set; }
public System.Decimal? KPM_OWNER  { get; set; }
public System.Decimal? KPM_DATASOURCE  { get; set; }
public System.String KPM_DESCRIPTION  { get; set; }
public System.String KPM_FORMULA  { get; set; }
public System.String KPM_COMMENTS  { get; set; }
public System.String REPT_FREQ  { get; set; }
public System.String CREATE_BY  { get; set; }
public System.String UPDATE_BY  { get; set; }
public System.DateTime? CREATE_DATE  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String ADMINROW  { get; set; }
public System.Decimal? PARENT_ID  { get; set; }
public System.Decimal? KOCTREEID  { get; set; }
public System.String BALANCECARD_ID  { get; set; }
public System.String RECORDTYPE  { get; set; }
public System.String PERCENTCOMPLETE  { get; set; }
public System.String ACTIVE  { get; set; }
public System.String GRP_CODE  { get; set; }
public System.String TEAM_CODE  { get; set; }
public System.Decimal? PROJECT_ID  { get; set; }
public System.Decimal? LOV_ID  { get; set; }
public System.Decimal? LAST_EVENT_ID  { get; set; }
public System.String BAL_TYPE  { get; set; }
public System.String KOCNO  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PL_BALANCESCORECARD()
        {
        }
    }
}
