//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PORTABLE_TEST_LATEST_VW
    {
        
public System.Decimal? SHRINKAGE_FACTOR  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.Decimal? GAS_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? WATER_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? BSW  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S_IN_OIL  { get; set; }
public System.Decimal? H2S_IN_GAS  { get; set; }
public System.Decimal? CHLORIDE  { get; set; }
public System.Decimal? CURRENT_ESP  { get; set; }
public System.Decimal? ESP_PI  { get; set; }
public System.Decimal? CURRENT_PCP  { get; set; }
public System.Decimal? FREQUENCY  { get; set; }
public System.Decimal? RPM  { get; set; }
public System.Decimal? PCP_DISCHARGE_PRESS  { get; set; }
public System.Decimal? PCP_INTAKE_TEMP  { get; set; }
public System.Decimal? PCP_MOTOR_TEMP  { get; set; }
public System.Decimal? PCP_TORQUE  { get; set; }
public System.Decimal? ESP_FREQUENCY  { get; set; }
public System.Decimal? ESP_DISCHARGE_PRESS  { get; set; }
public System.Decimal? ESP_INTAKE_TEMP  { get; set; }
public System.Decimal? ESP_MOTOR_TEMP  { get; set; }
public System.Decimal? ESP_TORQUE  { get; set; }
public System.Decimal? ESP_VOLTAGE  { get; set; }
public System.Decimal? ESP_SRP  { get; set; }
public System.Decimal? GAS_LIFT_PRESSURE  { get; set; }
public System.Decimal? GAS_LIFT_RATE  { get; set; }
public System.Decimal? GAS_LIFT_TEMP  { get; set; }
public System.Decimal? GAS_LIFT_CHOKE  { get; set; }
public System.Decimal? WELL_HEAD_TEMP  { get; set; }
public System.Decimal? WHP  { get; set; }
public System.Decimal? LIQUID_RATE  { get; set; }
public System.Decimal? WC  { get; set; }
public System.Decimal? TOTAL_GOR  { get; set; }
public System.Decimal? WELL_COMPLETION_ID  { get; set; }
public System.DateTime? START_DATE  { get; set; }
public System.Decimal? RNK  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PORTABLE_TEST_LATEST_VW()
        {
        }
    }
}
