//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PRODUCTION_FACILITY_VW
    {
        
public System.String NAME  { get; set; }
public System.String OPERATOR  { get; set; }
public System.String GC  { get; set; }
public System.String DATA_SOURCE  { get; set; }
public System.DateTime? START_DATE  { get; set; }
public System.DateTime? END_DATE  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PRODUCTION_FACILITY_VW()
        {
        }
    }
}
