//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class PROJECT_HDR
    {
        
public System.Decimal? ID  { get; set; }
public System.String PROJECTNAME  { get; set; }
public System.String PROJECTDESCRIPTION  { get; set; }
public System.Decimal? PARENTID  { get; set; }
public System.DateTime? CREATEDATE  { get; set; }
public System.DateTime? UPDATEDATE  { get; set; }
public System.String CREATEBY  { get; set; }
public System.String UPDATEBY  { get; set; }
public System.DateTime? FROMDATE  { get; set; }
public System.DateTime? TODATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public PROJECT_HDR()
        {
        }
    }
}
