//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class TEST_TBL
    {
        
public System.Decimal? COL1  { get; set; }
public System.String COL2  { get; set; }
public System.Int64 RN  { get; set; }
        
        public TEST_TBL()
        {
        }
    }
}
