//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class USER_ACCESS
    {
        
public System.Decimal? ID  { get; set; }
public System.String USER_ID  { get; set; }
public System.String USER_NAME  { get; set; }
public System.String ASSET  { get; set; }
public System.String KOC_NO  { get; set; }
public System.String TITLE  { get; set; }
public System.String TEAM_CODE  { get; set; }
public System.String TEAM_NAME  { get; set; }
public System.String PROJ_NAME  { get; set; }
public System.String PROJECT_GROUP_NAME  { get; set; }
public System.String ACTIVE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public USER_ACCESS()
        {
        }
    }
}
