//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WC_F2S_MAP_VW
    {
        
public System.Decimal? FINDER_WELL_COMPLETION_S  { get; set; }
public System.Decimal? SEABED_WELL_COMPLETION_S  { get; set; }
public System.String UBHI  { get; set; }
public System.String WC_NAME  { get; set; }
public System.Double TOP_INTERVAL_MD  { get; set; }
public System.Decimal? ID  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.DateTime? SYNC_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WC_F2S_MAP_VW()
        {
        }
    }
}
