//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WELLBORE_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.DateTime? SPUD_DATE  { get; set; }
public System.DateTime? COMP_DATE  { get; set; }
public System.Decimal? DRILLERS_TD  { get; set; }
public System.Decimal? GROUND_ELEVATION  { get; set; }
public System.Decimal? ELEVATION  { get; set; }
public System.String ELEVATION_REF  { get; set; }
public System.Decimal? LATITUDE  { get; set; }
public System.Decimal? LONGITUDE  { get; set; }
public System.DateTime? LAST_UPDATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELLBORE_VW()
        {
        }
    }
}
