//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WELL_COMPLETION_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String COMPLETION_TYPE  { get; set; }
public System.Decimal? WELL_COMPLETION_S  { get; set; }
public System.String COMPLETION_OBJECTIVE  { get; set; }
public System.String WELL_OWNER  { get; set; }
public System.DateTime? WELL_OWNER_DATE  { get; set; }
public System.String FIELD_CODE  { get; set; }
public System.String FIELD_NAME  { get; set; }
public System.Decimal? FIELD_ID  { get; set; }
public System.String AREA  { get; set; }
public System.Decimal? KB_ELEVATION  { get; set; }
public System.DateTime? BH_COMPLETION_DATE  { get; set; }
public System.DateTime? COMPLETION_DATE  { get; set; }
public System.DateTime? SPUD_DATE  { get; set; }
public System.String CURRENT_STATUS  { get; set; }
public System.Decimal? DRILLERS_TD  { get; set; }
public System.Decimal? GROUND_ELEVATION  { get; set; }
public System.Decimal? ELEVATION  { get; set; }
public System.String ELEVATION_REF  { get; set; }
public System.Decimal? LONGITUDE  { get; set; }
public System.Decimal? LATITUDE  { get; set; }
public System.Decimal? TOP_X  { get; set; }
public System.Decimal? TOP_Y  { get; set; }
public System.Decimal? PLUGBACK_TD  { get; set; }
public System.String ZONES  { get; set; }
public System.String REASON  { get; set; }
public System.String MFL  { get; set; }
public System.Decimal? TOP_DEPTH  { get; set; }
public System.Decimal? BOTTOM_DEPTH  { get; set; }
public System.String GC  { get; set; }
public System.DateTime? GC_CONN_DATE  { get; set; }
public System.String HEADER  { get; set; }
public System.DateTime? HEADER_CONN_DATE  { get; set; }
public System.String SLOT  { get; set; }
public System.DateTime? SLOT_CONN_DATE  { get; set; }
public System.String LIFT_METHOD  { get; set; }
public System.String ESP  { get; set; }
public System.Decimal? ALLOWABLE  { get; set; }
public System.String OPERATION_STATUS  { get; set; }
public System.DateTime? OPERATION_STATUS_DATE  { get; set; }
public System.String AL_STATUS  { get; set; }
public System.String WELL_DEVIATION  { get; set; }
public System.DateTime? AL_STATUS_DATE  { get; set; }
public System.String COMPLETION_CODE  { get; set; }
public System.String RESERVOIR_ID  { get; set; }
public System.String RESERVOIR_NAME  { get; set; }
public System.String LAYER_NAME  { get; set; }
public System.String LAYER_TYPE  { get; set; }
public System.String FACILITY_NAME  { get; set; }
public System.DateTime? START_TIME  { get; set; }
public System.DateTime? END_TIME  { get; set; }
public System.String OBJECTIVE  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Decimal? STRING_ID  { get; set; }
public System.String FACILITY_ID  { get; set; }
public System.Decimal? LATEST_RATE  { get; set; }
public System.String RATE_TYPE  { get; set; }
public System.DateTime? RATE_DATE  { get; set; }
public System.Decimal? LATEST_WC  { get; set; }
public System.String WC_CHANGE_TYPE  { get; set; }
public System.DateTime? WC_CHANGE_DATE  { get; set; }
public System.Decimal? LATEST_GOR  { get; set; }
public System.DateTime? GOR_CHANGE_DATE  { get; set; }
public System.Decimal? RIGHT_CHOKE  { get; set; }
public System.Decimal? LEFT_CHOKE  { get; set; }
public System.DateTime? CHOKE_CHANGE_DATE  { get; set; }
public System.String CHOKE_CHANGE_TYPE  { get; set; }
public System.Decimal? LATEST_FLP  { get; set; }
public System.Decimal? LATEST_WHP  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_COMPLETION_VW()
        {
        }
    }
}
