//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WELL_LATEST_DATA_ERROR_LOG
    {
        
public System.Decimal? ID  { get; set; }
public System.String ERROR_DESCR  { get; set; }
public System.String UWI  { get; set; }
public System.Decimal? WCS  { get; set; }
public System.DateTime? ERROR_DATE  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_LATEST_DATA_ERROR_LOG()
        {
        }
    }
}
