//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTechIdea.ProjectClasses
{
    
    
    public class WELL_TEST_DETAIL_VW
    {
        
public System.String UWI  { get; set; }
public System.String UBHI  { get; set; }
public System.String TEST_NAME  { get; set; }
public System.String TEST_TYPE  { get; set; }
public System.DateTime? START_DATE  { get; set; }
public System.DateTime? END_DATE  { get; set; }
public System.Decimal? HP_GOR  { get; set; }
public System.String HP_GOR_FLAG  { get; set; }
public System.Decimal? MP_GOR  { get; set; }
public System.String MP_GOR_FLAG  { get; set; }
public System.Decimal? LP_GOR  { get; set; }
public System.String LP_GOR_FLAG  { get; set; }
public System.Decimal? EHP_GOR  { get; set; }
public System.String EHP_GOR_FLAG  { get; set; }
public System.Decimal? TV_GOR  { get; set; }
public System.String TV_GOR_FLAG  { get; set; }
public System.Decimal? FORMATION_GOR  { get; set; }
public System.String FORMATION_GOR_FLAG  { get; set; }
public System.Decimal? GL_GOR  { get; set; }
public System.String GL_GOR_FLAG  { get; set; }
public System.Decimal? TOTAL_GLR  { get; set; }
public System.String TOTAL_GLR_FLAG  { get; set; }
public System.Decimal? INJECTION_GLR  { get; set; }
public System.String INJECTION_GLR_FLAG  { get; set; }
public System.Decimal? SEPARATOR_PRESSURE  { get; set; }
public System.Decimal? SEPARATOR_TEMPERATURE  { get; set; }
public System.Decimal? API  { get; set; }
public System.Decimal? SALINITY  { get; set; }
public System.Decimal? SHRINKAGE_FACTOR  { get; set; }
public System.Decimal? GAS_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? WATER_SPECIFIC_GRAVITY  { get; set; }
public System.Decimal? OIL_VISCOSITY  { get; set; }
public System.Decimal? GAS_DENSITY  { get; set; }
public System.Decimal? SALT  { get; set; }
public System.Decimal? BSW  { get; set; }
public System.Decimal? CO2  { get; set; }
public System.Decimal? H2S_IN_OIL  { get; set; }
public System.Decimal? H2S_IN_GAS  { get; set; }
public System.Decimal? CHLORIDE  { get; set; }
public System.Decimal? SULPHUR  { get; set; }
public System.Decimal? HP_AVG_PRESSURE  { get; set; }
public System.Decimal? HP_AVG_TEMPERATURE  { get; set; }
public System.Decimal? HP_AVG_GAS_RATE  { get; set; }
public System.Decimal? LP_AVG_PRESSURE  { get; set; }
public System.Decimal? LP_AVG_TEMPERATURE  { get; set; }
public System.Decimal? LP_AVG_GAS_RATE  { get; set; }
public System.Decimal? MP_AVG_PRESSURE  { get; set; }
public System.Decimal? MP_AVG_TEMPERATURE  { get; set; }
public System.Decimal? MP_AVG_GAS_RATE  { get; set; }
public System.Decimal? HP_ORIFICE  { get; set; }
public System.String HP_GAS_METER  { get; set; }
public System.Decimal? MP_ORIFICE  { get; set; }
public System.String MP_GAS_METER  { get; set; }
public System.Decimal? LP_ORIFICE  { get; set; }
public System.String LP_GAS_METER  { get; set; }
public System.DateTime? INSERT_DATE  { get; set; }
public System.String INSERT_USER  { get; set; }
public System.DateTime? UPDATE_DATE  { get; set; }
public System.String UPDATE_USER  { get; set; }
public System.DateTime? SYNC_DATE  { get; set; }
public System.Decimal? ID  { get; set; }
public System.Decimal? WELL_TEST_ID  { get; set; }
public System.Decimal? WELL_ID  { get; set; }
public System.Decimal? BOREHOLE_ID  { get; set; }
public System.Decimal? WELL_COMPLETION_ID  { get; set; }
public System.Int64 RN  { get; set; }
        
        public WELL_TEST_DETAIL_VW()
        {
        }
    }
}
