using System.Windows.Forms;
using TheTechIdea.Beep.Winform.Controls.Buttons;
using TheTechIdea.Beep.Winform.Controls.Wizards.Helpers;

namespace TheTechIdea.Beep.Winform.Controls.Wizards.Forms
{
    partial class MinimalWizardForm
    {
        private System.ComponentModel.IContainer components = null;

        // ── Layout ────────────────────────────────────────────────────────────────
        private TableLayoutPanel _root;
        private Panel _headerPanel;
        private Panel _errorPanel;
        private Label _lblError;
        private BufferedPanel _contentPanel;
        private TableLayoutPanel _buttonPanel;

        // ── Navigation ────────────────────────────────────────────────────────────
        private BeepButton _btnCancel;
        private BeepButton _btnSkip;
        private BeepButton _btnHelp;
        private BeepButton _btnBack;
        private BeepButton _btnNext;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        /// <summary>
        /// Builds the form's layout. Visible on the design surface, because everything here is
        /// plain construction and <c>Controls.Add</c> - no loops, no conditionals, no method calls
        /// the designer cannot serialise.
        /// </summary>
        /// <remarks>
        /// This replaced a runtime <c>InitializeControls</c> + <c>LayoutControls</c> pair. Two
        /// things came with the move:
        /// <list type="bullet">
        /// <item>The form showed nothing at design time - every control was built in the
        /// constructor, so the designer surface was blank.</item>
        /// <item><c>LayoutControls</c> positioned the buttons from
        /// <c>_buttonPanel.ClientSize.Width</c> **before the panel had been added to the form**, so
        /// the panel still had its default width and every button landed in the wrong place until
        /// the first resize. A <see cref="TableLayoutPanel"/> has no such ordering hazard.</item>
        /// </list>
        /// The optional Skip and Help buttons are created unconditionally here and their
        /// <c>Visible</c> is set from the config at runtime - a conditional in this method would
        /// break the designer.
        /// </remarks>
        private void InitializeComponent()
        {
            GraphicsPath graphicsPath1 = new GraphicsPath();
            GraphicsPath graphicsPath2 = new GraphicsPath();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MinimalWizardForm));
            GraphicsPath graphicsPath3 = new GraphicsPath();
            GraphicsPath graphicsPath4 = new GraphicsPath();
            GraphicsPath graphicsPath5 = new GraphicsPath();
            GraphicsPath graphicsPath6 = new GraphicsPath();
            GraphicsPath graphicsPath7 = new GraphicsPath();
            GraphicsPath graphicsPath8 = new GraphicsPath();
            GraphicsPath graphicsPath9 = new GraphicsPath();
            GraphicsPath graphicsPath10 = new GraphicsPath();
            GraphicsPath graphicsPath11 = new GraphicsPath();
            GraphicsPath graphicsPath12 = new GraphicsPath();
            GraphicsPath graphicsPath13 = new GraphicsPath();
            GraphicsPath graphicsPath14 = new GraphicsPath();
            GraphicsPath graphicsPath15 = new GraphicsPath();
            _root = new TableLayoutPanel();
            _headerPanel = new Panel();
            _errorPanel = new Panel();
            _lblError = new Label();
            _contentPanel = new BufferedPanel();
            _buttonPanel = new TableLayoutPanel();
            _btnCancel = new BeepButton();
            _btnSkip = new BeepButton();
            _btnHelp = new BeepButton();
            _btnBack = new BeepButton();
            _btnNext = new BeepButton();
            _root.SuspendLayout();
            _errorPanel.SuspendLayout();
            _buttonPanel.SuspendLayout();
            SuspendLayout();
            // 
            // _root
            // 
            _root.ColumnCount = 1;
            _root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _root.Controls.Add(_headerPanel, 0, 0);
            _root.Controls.Add(_errorPanel, 0, 1);
            _root.Controls.Add(_contentPanel, 0, 2);
            _root.Controls.Add(_buttonPanel, 0, 3);
            _root.Dock = DockStyle.Fill;
            _root.Location = new Point(0, 40);
            _root.Name = "_root";
            _root.RowCount = 4;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 72F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 60F));
            _root.Size = new Size(752, 549);
            _root.TabIndex = 0;
            // 
            // _headerPanel
            // 
            _headerPanel.BackColor = Color.Transparent;
            _headerPanel.Dock = DockStyle.Fill;
            _headerPanel.Location = new Point(0, 0);
            _headerPanel.Margin = new Padding(0);
            _headerPanel.Name = "_headerPanel";
            _headerPanel.Size = new Size(752, 72);
            _headerPanel.TabIndex = 0;
            _headerPanel.Paint += HeaderPanel_Paint;
            // 
            // _errorPanel
            // 
            _errorPanel.Controls.Add(_lblError);
            _errorPanel.Dock = DockStyle.Fill;
            _errorPanel.Location = new Point(0, 72);
            _errorPanel.Margin = new Padding(0);
            _errorPanel.Name = "_errorPanel";
            _errorPanel.Padding = new Padding(16, 0, 16, 0);
            _errorPanel.Size = new Size(752, 40);
            _errorPanel.TabIndex = 1;
            _errorPanel.Visible = false;
            // 
            // _lblError
            // 
            _lblError.AutoEllipsis = true;
            _lblError.Dock = DockStyle.Fill;
            _lblError.Location = new Point(16, 0);
            _lblError.Name = "_lblError";
            _lblError.Size = new Size(720, 40);
            _lblError.TabIndex = 0;
            _lblError.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _contentPanel
            // 
            _contentPanel.Dock = DockStyle.Fill;
            _contentPanel.Location = new Point(0, 112);
            _contentPanel.Margin = new Padding(0);
            _contentPanel.Name = "_contentPanel";
            _contentPanel.Padding = new Padding(40, 20, 40, 20);
            _contentPanel.Size = new Size(752, 377);
            _contentPanel.TabIndex = 2;
            // 
            // _buttonPanel
            // 
            _buttonPanel.ColumnCount = 6;
            _buttonPanel.ColumnStyles.Add(new ColumnStyle());
            _buttonPanel.ColumnStyles.Add(new ColumnStyle());
            _buttonPanel.ColumnStyles.Add(new ColumnStyle());
            _buttonPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            _buttonPanel.ColumnStyles.Add(new ColumnStyle());
            _buttonPanel.ColumnStyles.Add(new ColumnStyle());
            _buttonPanel.Controls.Add(_btnCancel, 0, 0);
            _buttonPanel.Controls.Add(_btnSkip, 1, 0);
            _buttonPanel.Controls.Add(_btnHelp, 2, 0);
            _buttonPanel.Controls.Add(_btnBack, 4, 0);
            _buttonPanel.Controls.Add(_btnNext, 5, 0);
            _buttonPanel.Dock = DockStyle.Fill;
            _buttonPanel.Location = new Point(0, 489);
            _buttonPanel.Margin = new Padding(0);
            _buttonPanel.Name = "_buttonPanel";
            _buttonPanel.Padding = new Padding(20, 10, 20, 10);
            _buttonPanel.RowCount = 1;
            _buttonPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            _buttonPanel.Size = new Size(752, 60);
            _buttonPanel.TabIndex = 3;
            // 
            // _btnCancel
            // 
            _btnCancel.Anchor = AnchorStyles.Left;
            _btnCancel.AnimationDuration = 500;
            _btnCancel.AnimationType = DisplayAnimationType.None;
            _btnCancel.ApplyThemeOnImage = false;
            _btnCancel.ApplyThemeToChilds = true;
            _btnCancel.AutoDrawHitListComponents = true;
            _btnCancel.AutoSizeContent = false;
            _btnCancel.BackColor = Color.FromArgb(232, 238, 248);
            _btnCancel.BadgeBackColor = Color.Red;
            _btnCancel.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            _btnCancel.BadgeForeColor = Color.White;
            _btnCancel.BadgeShape = BadgeShape.Circle;
            _btnCancel.BlockID = null;
            _btnCancel.BorderColor = Color.FromArgb(200, 200, 200);
            _btnCancel.BorderDashStyle = DashStyle.Solid;
            _btnCancel.BorderPainter = BeepControlStyle.Modern;
            graphicsPath1.FillMode = FillMode.Alternate;
            _btnCancel.BorderPath = graphicsPath1;
            _btnCancel.BorderRadius = 8;
            _btnCancel.BorderRect = new Rectangle(1, 1, 97, 33);
            _btnCancel.BorderStyle = BorderStyle.FixedSingle;
            _btnCancel.BorderThickness = 2;
            _btnCancel.BottomoffsetForDrawingRect = 0;
            _btnCancel.BoundProperty = null;
            _btnCancel.ButtonMinSize = new Size(32, 32);
            _btnCancel.ButtonType = ButtonType.Normal;
            _btnCancel.CanBeFocused = true;
            _btnCancel.CanBeHovered = true;
            _btnCancel.CanBePressed = true;
            _btnCancel.CanBeSelected = true;
            _btnCancel.Category = Utilities.DbFieldCategory.Boolean;
            _btnCancel.ComponentName = "BaseControl";
            _btnCancel.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath2.FillMode = FillMode.Alternate;
            _btnCancel.ContentShape = graphicsPath2;
            _btnCancel.ControlStyle = BeepControlStyle.Modern;
            _btnCancel.CustomIconColor = Color.Black;
            _btnCancel.CustomIconPath = "";
            _btnCancel.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            _btnCancel.CustomPadding = new Padding(0);
            _btnCancel.DataContext = null;
            _btnCancel.DataSourceProperty = null;
            _btnCancel.DisabledBackColor = Color.FromArgb(244, 246, 252);
            _btnCancel.DisabledBorderColor = Color.Gray;
            _btnCancel.DisabledForeColor = Color.FromArgb(222, 223, 229);
            _btnCancel.DrawingRect = new Rectangle(3, 3, 93, 29);
            _btnCancel.Easing = EasingType.Linear;
            _btnCancel.EnableHighQualityRendering = true;
            _btnCancel.EnableRippleEffect = false;
            _btnCancel.EnableSplashEffect = false;
            _btnCancel.ErrorColor = Color.FromArgb(211, 47, 47);
            _btnCancel.ErrorText = "";
            _btnCancel.ExternalDrawingLayer = DrawingLayer.AfterAll;
            _btnCancel.FieldID = null;
            _btnCancel.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            _btnCancel.FloatingLabel = "";
            _btnCancel.FloatingLabelOn = false;
            _btnCancel.FocusBackColor = Color.FromArgb(31, 95, 255);
            _btnCancel.FocusBorderColor = Color.RoyalBlue;
            _btnCancel.FocusForeColor = Color.FromArgb(255, 255, 255);
            _btnCancel.FocusIndicatorColor = Color.RoyalBlue;
            _btnCancel.ForeColor = Color.FromArgb(38, 44, 57);
            _btnCancel.Form = null;
            _btnCancel.GlassmorphismBlur = 10F;
            _btnCancel.GlassmorphismOpacity = 0.1F;
            _btnCancel.GradientAngle = 0F;
            _btnCancel.GradientDirection = LinearGradientMode.Horizontal;
            _btnCancel.GradientEndColor = Color.Gray;
            _btnCancel.GradientStartColor = Color.LightGray;
            _btnCancel.GridMode = false;
            _btnCancel.GuidID = "b2e5d470-d6af-43d6-a0b9-873ae8530667";
            _btnCancel.HasError = false;
            _btnCancel.HelperText = "";
            _btnCancel.HelperTextOn = false;
            _btnCancel.HideText = false;
            _btnCancel.HitAreaEventOn = false;
            _btnCancel.HitTestControl = null;
            _btnCancel.HoverBackColor = Color.FromArgb(220, 229, 242);
            _btnCancel.HoverBorderColor = Color.Blue;
            _btnCancel.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            _btnCancel.HoverForeColor = Color.FromArgb(38, 44, 57);
            _btnCancel.IconKey = "";
            _btnCancel.IconSize = 20;
            _btnCancel.Id = -1;
            _btnCancel.Image = null;
            _btnCancel.ImageAlign = ContentAlignment.MiddleLeft;
            _btnCancel.ImageClicked = null;
            _btnCancel.ImageEmbededin = ImageEmbededin.Button;
            _btnCancel.ImagePath = "";
            _btnCancel.InactiveBorderColor = Color.Gray;
            _btnCancel.IndicatorLineColor = Color.Red;
            _btnCancel.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath3.FillMode = FillMode.Alternate;
            _btnCancel.InnerShape = graphicsPath3;
            _btnCancel.IsAcceptButton = false;
            _btnCancel.IsBorderAffectedByTheme = true;
            _btnCancel.IsCancelButton = false;
            _btnCancel.IsChild = false;
            _btnCancel.IsColorFromTheme = true;
            _btnCancel.IsCustomeBorder = false;
            _btnCancel.IsDefault = false;
            _btnCancel.IsDeleted = false;
            _btnCancel.IsDirty = false;
            _btnCancel.IsEditable = true;
            _btnCancel.IsFocused = false;
            _btnCancel.IsFrameless = false;
            _btnCancel.IsHovered = false;
            _btnCancel.IsNew = false;
            _btnCancel.IsPopupOpen = false;
            _btnCancel.IsPressed = false;
            _btnCancel.IsReadOnly = false;
            _btnCancel.IsRequired = false;
            _btnCancel.IsRounded = true;
            _btnCancel.IsRoundedAffectedByTheme = true;
            _btnCancel.IsSelected = false;
            _btnCancel.IsSelectedOptionOn = false;
            _btnCancel.IsShadowAffectedByTheme = true;
            _btnCancel.IsSideMenuChild = false;
            _btnCancel.IsStillButton = false;
            _btnCancel.IsTransparentBackground = false;
            _btnCancel.IsValid = true;
            _btnCancel.IsVisible = true;
            _btnCancel.LabelPosition = LabelPosition.Left;
            _btnCancel.LabelText = "";
            _btnCancel.LabelTextOn = false;
            _btnCancel.LeadingIconPath = "";
            _btnCancel.LeadingImagePath = "";
            _btnCancel.LeftoffsetForDrawingRect = 0;
            _btnCancel.LinkedProperty = null;
            _btnCancel.Location = new Point(20, 12);
            _btnCancel.Margin = new Padding(0);
            _btnCancel.MaxHitListDrawPerFrame = 0;
            _btnCancel.MaxImageSize = new Size(16, 16);
            _btnCancel.ModernGradientType = ModernGradientType.None;
            _btnCancel.Name = "_btnCancel";
            _btnCancel.OuterShape = null;
            _btnCancel.OverrideFontSize = TypeStyleFontSize.None;
            _btnCancel.PainterKind = BaseControlPainterKind.Classic;
            _btnCancel.ParentBackColor = Color.Empty;
            _btnCancel.ParentControl = null;
            _btnCancel.PopPosition = BeepPopupFormPosition.Bottom;
            _btnCancel.PopupListForm = null;
            _btnCancel.PopupMode = false;
            _btnCancel.PressedBackColor = Color.FromArgb(205, 218, 236);
            _btnCancel.PressedBorderColor = Color.DarkGray;
            _btnCancel.PressedForeColor = Color.FromArgb(38, 44, 57);
            _btnCancel.RadialCenter = (PointF)resources.GetObject("_btnCancel.RadialCenter");
            _btnCancel.RightoffsetForDrawingRect = 0;
            _btnCancel.SavedGuidID = null;
            _btnCancel.SavedID = null;
            _btnCancel.ScaleMode = ImageScaleMode.KeepAspectRatio;
            _btnCancel.SelectedBackColor = Color.FromArgb(31, 95, 255);
            _btnCancel.SelectedBorderColor = Color.Green;
            _btnCancel.SelectedForeColor = Color.FromArgb(255, 255, 255);
            _btnCancel.SelectedIndex = 0;
            _btnCancel.SelectedItem = null;
            _btnCancel.ShadowColor = Color.Black;
            _btnCancel.ShadowOffset = 3;
            _btnCancel.ShadowOpacity = 0.25F;
            _btnCancel.ShowAllBorders = false;
            _btnCancel.ShowBottomBorder = false;
            _btnCancel.ShowFocusIndicator = false;
            _btnCancel.ShowIndicatorLine = false;
            _btnCancel.ShowLabelAboveBorder = false;
            _btnCancel.ShowLeftBorder = false;
            _btnCancel.ShowRightBorder = false;
            _btnCancel.ShowShadow = false;
            _btnCancel.ShowTopBorder = false;
            _btnCancel.Size = new Size(100, 36);
            _btnCancel.SlideFrom = SlideDirection.Left;
            _btnCancel.SplashColor = Color.Empty;
            _btnCancel.StaticNotMoving = false;
            _btnCancel.TabIndex = 0;
            _btnCancel.TempBackColor = Color.LightGray;
            _btnCancel.Text = "Cancel";
            _btnCancel.TextAlign = ContentAlignment.MiddleCenter;
            _btnCancel.TextFont = new Font("Segoe UI", 10F);
            _btnCancel.TextImageRelation = TextImageRelation.ImageBeforeText;
            _btnCancel.Theme = "ModernTheme";
            _btnCancel.TooltipFont = null;
            _btnCancel.TooltipMaxSize = null;
            _btnCancel.ToolTipText = "";
            _btnCancel.TopoffsetForDrawingRect = 0;
            _btnCancel.TrailingIconPath = "";
            _btnCancel.TrailingImagePath = "";
            _btnCancel.UseExternalBufferedGraphics = true;
            _btnCancel.UseFormStylePaint = true;
            _btnCancel.UseGlassmorphism = false;
            _btnCancel.UseGradientBackground = false;
            _btnCancel.UseScaledFont = false;
            _btnCancel.UseThemeFont = true;
            _btnCancel.ValidationIcon = Badges.ValidationState.None;
            _btnCancel.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            _btnCancel.Click += BtnCancel_Click;
            // 
            // _btnSkip
            // 
            _btnSkip.Anchor = AnchorStyles.Left;
            _btnSkip.AnimationDuration = 500;
            _btnSkip.AnimationType = DisplayAnimationType.None;
            _btnSkip.ApplyThemeOnImage = false;
            _btnSkip.ApplyThemeToChilds = true;
            _btnSkip.AutoDrawHitListComponents = true;
            _btnSkip.AutoSizeContent = false;
            _btnSkip.BackColor = Color.FromArgb(232, 238, 248);
            _btnSkip.BadgeBackColor = Color.Red;
            _btnSkip.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            _btnSkip.BadgeForeColor = Color.White;
            _btnSkip.BadgeShape = BadgeShape.Circle;
            _btnSkip.BlockID = null;
            _btnSkip.BorderColor = Color.FromArgb(200, 200, 200);
            _btnSkip.BorderDashStyle = DashStyle.Solid;
            _btnSkip.BorderPainter = BeepControlStyle.Modern;
            graphicsPath4.FillMode = FillMode.Alternate;
            _btnSkip.BorderPath = graphicsPath4;
            _btnSkip.BorderRadius = 8;
            _btnSkip.BorderRect = new Rectangle(1, 1, 97, 31);
            _btnSkip.BorderStyle = BorderStyle.FixedSingle;
            _btnSkip.BorderThickness = 2;
            _btnSkip.BottomoffsetForDrawingRect = 0;
            _btnSkip.BoundProperty = null;
            _btnSkip.ButtonMinSize = new Size(32, 32);
            _btnSkip.ButtonType = ButtonType.Normal;
            _btnSkip.CanBeFocused = true;
            _btnSkip.CanBeHovered = true;
            _btnSkip.CanBePressed = true;
            _btnSkip.CanBeSelected = true;
            _btnSkip.Category = Utilities.DbFieldCategory.Boolean;
            _btnSkip.ComponentName = "BaseControl";
            _btnSkip.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath5.FillMode = FillMode.Alternate;
            _btnSkip.ContentShape = graphicsPath5;
            _btnSkip.ControlStyle = BeepControlStyle.Modern;
            _btnSkip.CustomIconColor = Color.Black;
            _btnSkip.CustomIconPath = "";
            _btnSkip.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            _btnSkip.CustomPadding = new Padding(0);
            _btnSkip.DataContext = null;
            _btnSkip.DataSourceProperty = null;
            _btnSkip.DisabledBackColor = Color.FromArgb(244, 246, 252);
            _btnSkip.DisabledBorderColor = Color.Gray;
            _btnSkip.DisabledForeColor = Color.FromArgb(222, 223, 229);
            _btnSkip.DrawingRect = new Rectangle(3, 3, 93, 27);
            _btnSkip.Easing = EasingType.Linear;
            _btnSkip.EnableHighQualityRendering = true;
            _btnSkip.EnableRippleEffect = false;
            _btnSkip.EnableSplashEffect = false;
            _btnSkip.ErrorColor = Color.FromArgb(211, 47, 47);
            _btnSkip.ErrorText = "";
            _btnSkip.ExternalDrawingLayer = DrawingLayer.AfterAll;
            _btnSkip.FieldID = null;
            _btnSkip.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            _btnSkip.FloatingLabel = "";
            _btnSkip.FloatingLabelOn = false;
            _btnSkip.FocusBackColor = Color.FromArgb(31, 95, 255);
            _btnSkip.FocusBorderColor = Color.RoyalBlue;
            _btnSkip.FocusForeColor = Color.FromArgb(255, 255, 255);
            _btnSkip.FocusIndicatorColor = Color.RoyalBlue;
            _btnSkip.ForeColor = Color.FromArgb(38, 44, 57);
            _btnSkip.Form = null;
            _btnSkip.GlassmorphismBlur = 10F;
            _btnSkip.GlassmorphismOpacity = 0.1F;
            _btnSkip.GradientAngle = 0F;
            _btnSkip.GradientDirection = LinearGradientMode.Horizontal;
            _btnSkip.GradientEndColor = Color.Gray;
            _btnSkip.GradientStartColor = Color.LightGray;
            _btnSkip.GridMode = false;
            _btnSkip.GuidID = "f26f7493-9e9e-4b8b-bac1-4eaf52bb8c22";
            _btnSkip.HasError = false;
            _btnSkip.HelperText = "";
            _btnSkip.HelperTextOn = false;
            _btnSkip.HideText = false;
            _btnSkip.HitAreaEventOn = false;
            _btnSkip.HitTestControl = null;
            _btnSkip.HoverBackColor = Color.FromArgb(220, 229, 242);
            _btnSkip.HoverBorderColor = Color.Blue;
            _btnSkip.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            _btnSkip.HoverForeColor = Color.FromArgb(38, 44, 57);
            _btnSkip.IconKey = "";
            _btnSkip.IconSize = 20;
            _btnSkip.Id = -1;
            _btnSkip.Image = null;
            _btnSkip.ImageAlign = ContentAlignment.MiddleLeft;
            _btnSkip.ImageClicked = null;
            _btnSkip.ImageEmbededin = ImageEmbededin.Button;
            _btnSkip.ImagePath = "";
            _btnSkip.InactiveBorderColor = Color.Gray;
            _btnSkip.IndicatorLineColor = Color.Red;
            _btnSkip.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath6.FillMode = FillMode.Alternate;
            _btnSkip.InnerShape = graphicsPath6;
            _btnSkip.IsAcceptButton = false;
            _btnSkip.IsBorderAffectedByTheme = true;
            _btnSkip.IsCancelButton = false;
            _btnSkip.IsChild = false;
            _btnSkip.IsColorFromTheme = true;
            _btnSkip.IsCustomeBorder = false;
            _btnSkip.IsDefault = false;
            _btnSkip.IsDeleted = false;
            _btnSkip.IsDirty = false;
            _btnSkip.IsEditable = true;
            _btnSkip.IsFocused = false;
            _btnSkip.IsFrameless = false;
            _btnSkip.IsHovered = false;
            _btnSkip.IsNew = false;
            _btnSkip.IsPopupOpen = false;
            _btnSkip.IsPressed = false;
            _btnSkip.IsReadOnly = false;
            _btnSkip.IsRequired = false;
            _btnSkip.IsRounded = true;
            _btnSkip.IsRoundedAffectedByTheme = true;
            _btnSkip.IsSelected = false;
            _btnSkip.IsSelectedOptionOn = false;
            _btnSkip.IsShadowAffectedByTheme = true;
            _btnSkip.IsSideMenuChild = false;
            _btnSkip.IsStillButton = false;
            _btnSkip.IsTransparentBackground = false;
            _btnSkip.IsValid = true;
            _btnSkip.IsVisible = true;
            _btnSkip.LabelPosition = LabelPosition.Left;
            _btnSkip.LabelText = "";
            _btnSkip.LabelTextOn = false;
            _btnSkip.LeadingIconPath = "";
            _btnSkip.LeadingImagePath = "";
            _btnSkip.LeftoffsetForDrawingRect = 0;
            _btnSkip.LinkedProperty = null;
            _btnSkip.Location = new Point(130, 13);
            _btnSkip.Margin = new Padding(10, 3, 3, 3);
            _btnSkip.MaxHitListDrawPerFrame = 0;
            _btnSkip.MaxImageSize = new Size(16, 16);
            _btnSkip.ModernGradientType = ModernGradientType.None;
            _btnSkip.Name = "_btnSkip";
            _btnSkip.OuterShape = null;
            _btnSkip.OverrideFontSize = TypeStyleFontSize.None;
            _btnSkip.PainterKind = BaseControlPainterKind.Classic;
            _btnSkip.ParentBackColor = Color.Empty;
            _btnSkip.ParentControl = null;
            _btnSkip.PopPosition = BeepPopupFormPosition.Bottom;
            _btnSkip.PopupListForm = null;
            _btnSkip.PopupMode = false;
            _btnSkip.PressedBackColor = Color.FromArgb(205, 218, 236);
            _btnSkip.PressedBorderColor = Color.DarkGray;
            _btnSkip.PressedForeColor = Color.FromArgb(38, 44, 57);
            _btnSkip.RadialCenter = (PointF)resources.GetObject("_btnSkip.RadialCenter");
            _btnSkip.RightoffsetForDrawingRect = 0;
            _btnSkip.SavedGuidID = null;
            _btnSkip.SavedID = null;
            _btnSkip.ScaleMode = ImageScaleMode.KeepAspectRatio;
            _btnSkip.SelectedBackColor = Color.FromArgb(31, 95, 255);
            _btnSkip.SelectedBorderColor = Color.Green;
            _btnSkip.SelectedForeColor = Color.FromArgb(255, 255, 255);
            _btnSkip.SelectedIndex = 0;
            _btnSkip.SelectedItem = null;
            _btnSkip.ShadowColor = Color.Black;
            _btnSkip.ShadowOffset = 3;
            _btnSkip.ShadowOpacity = 0.25F;
            _btnSkip.ShowAllBorders = false;
            _btnSkip.ShowBottomBorder = false;
            _btnSkip.ShowFocusIndicator = false;
            _btnSkip.ShowIndicatorLine = false;
            _btnSkip.ShowLabelAboveBorder = false;
            _btnSkip.ShowLeftBorder = false;
            _btnSkip.ShowRightBorder = false;
            _btnSkip.ShowShadow = false;
            _btnSkip.ShowTopBorder = false;
            _btnSkip.Size = new Size(100, 34);
            _btnSkip.SlideFrom = SlideDirection.Left;
            _btnSkip.SplashColor = Color.Empty;
            _btnSkip.StaticNotMoving = false;
            _btnSkip.TabIndex = 1;
            _btnSkip.TempBackColor = Color.LightGray;
            _btnSkip.Text = "Skip";
            _btnSkip.TextAlign = ContentAlignment.MiddleCenter;
            _btnSkip.TextFont = new Font("Segoe UI", 10F);
            _btnSkip.TextImageRelation = TextImageRelation.ImageBeforeText;
            _btnSkip.Theme = "ModernTheme";
            _btnSkip.TooltipFont = null;
            _btnSkip.TooltipMaxSize = null;
            _btnSkip.ToolTipText = "";
            _btnSkip.TopoffsetForDrawingRect = 0;
            _btnSkip.TrailingIconPath = "";
            _btnSkip.TrailingImagePath = "";
            _btnSkip.UseExternalBufferedGraphics = true;
            _btnSkip.UseFormStylePaint = true;
            _btnSkip.UseGlassmorphism = false;
            _btnSkip.UseGradientBackground = false;
            _btnSkip.UseScaledFont = false;
            _btnSkip.UseThemeFont = true;
            _btnSkip.ValidationIcon = Badges.ValidationState.None;
            _btnSkip.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            _btnSkip.Visible = false;
            _btnSkip.Click += BtnSkip_Click;
            // 
            // _btnHelp
            // 
            _btnHelp.Anchor = AnchorStyles.Left;
            _btnHelp.AnimationDuration = 500;
            _btnHelp.AnimationType = DisplayAnimationType.None;
            _btnHelp.ApplyThemeOnImage = false;
            _btnHelp.ApplyThemeToChilds = true;
            _btnHelp.AutoDrawHitListComponents = true;
            _btnHelp.AutoSizeContent = false;
            _btnHelp.BackColor = Color.FromArgb(232, 238, 248);
            _btnHelp.BadgeBackColor = Color.Red;
            _btnHelp.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            _btnHelp.BadgeForeColor = Color.White;
            _btnHelp.BadgeShape = BadgeShape.Circle;
            _btnHelp.BlockID = null;
            _btnHelp.BorderColor = Color.FromArgb(200, 200, 200);
            _btnHelp.BorderDashStyle = DashStyle.Solid;
            _btnHelp.BorderPainter = BeepControlStyle.Modern;
            graphicsPath7.FillMode = FillMode.Alternate;
            _btnHelp.BorderPath = graphicsPath7;
            _btnHelp.BorderRadius = 8;
            _btnHelp.BorderRect = new Rectangle(1, 1, 77, 31);
            _btnHelp.BorderStyle = BorderStyle.FixedSingle;
            _btnHelp.BorderThickness = 2;
            _btnHelp.BottomoffsetForDrawingRect = 0;
            _btnHelp.BoundProperty = null;
            _btnHelp.ButtonMinSize = new Size(32, 32);
            _btnHelp.ButtonType = ButtonType.Normal;
            _btnHelp.CanBeFocused = true;
            _btnHelp.CanBeHovered = true;
            _btnHelp.CanBePressed = true;
            _btnHelp.CanBeSelected = true;
            _btnHelp.Category = Utilities.DbFieldCategory.Boolean;
            _btnHelp.ComponentName = "BaseControl";
            _btnHelp.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath8.FillMode = FillMode.Alternate;
            _btnHelp.ContentShape = graphicsPath8;
            _btnHelp.ControlStyle = BeepControlStyle.Modern;
            _btnHelp.CustomIconColor = Color.Black;
            _btnHelp.CustomIconPath = "";
            _btnHelp.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            _btnHelp.CustomPadding = new Padding(0);
            _btnHelp.DataContext = null;
            _btnHelp.DataSourceProperty = null;
            _btnHelp.DisabledBackColor = Color.FromArgb(244, 246, 252);
            _btnHelp.DisabledBorderColor = Color.Gray;
            _btnHelp.DisabledForeColor = Color.FromArgb(222, 223, 229);
            _btnHelp.DrawingRect = new Rectangle(3, 3, 73, 27);
            _btnHelp.Easing = EasingType.Linear;
            _btnHelp.EnableHighQualityRendering = true;
            _btnHelp.EnableRippleEffect = false;
            _btnHelp.EnableSplashEffect = false;
            _btnHelp.ErrorColor = Color.FromArgb(211, 47, 47);
            _btnHelp.ErrorText = "";
            _btnHelp.ExternalDrawingLayer = DrawingLayer.AfterAll;
            _btnHelp.FieldID = null;
            _btnHelp.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            _btnHelp.FloatingLabel = "";
            _btnHelp.FloatingLabelOn = false;
            _btnHelp.FocusBackColor = Color.FromArgb(31, 95, 255);
            _btnHelp.FocusBorderColor = Color.RoyalBlue;
            _btnHelp.FocusForeColor = Color.FromArgb(255, 255, 255);
            _btnHelp.FocusIndicatorColor = Color.RoyalBlue;
            _btnHelp.ForeColor = Color.FromArgb(38, 44, 57);
            _btnHelp.Form = null;
            _btnHelp.GlassmorphismBlur = 10F;
            _btnHelp.GlassmorphismOpacity = 0.1F;
            _btnHelp.GradientAngle = 0F;
            _btnHelp.GradientDirection = LinearGradientMode.Horizontal;
            _btnHelp.GradientEndColor = Color.Gray;
            _btnHelp.GradientStartColor = Color.LightGray;
            _btnHelp.GridMode = false;
            _btnHelp.GuidID = "adc51855-7634-4e8f-baa2-662540ff0564";
            _btnHelp.HasError = false;
            _btnHelp.HelperText = "";
            _btnHelp.HelperTextOn = false;
            _btnHelp.HideText = false;
            _btnHelp.HitAreaEventOn = false;
            _btnHelp.HitTestControl = null;
            _btnHelp.HoverBackColor = Color.FromArgb(220, 229, 242);
            _btnHelp.HoverBorderColor = Color.Blue;
            _btnHelp.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            _btnHelp.HoverForeColor = Color.FromArgb(38, 44, 57);
            _btnHelp.IconKey = "";
            _btnHelp.IconSize = 20;
            _btnHelp.Id = -1;
            _btnHelp.Image = null;
            _btnHelp.ImageAlign = ContentAlignment.MiddleLeft;
            _btnHelp.ImageClicked = null;
            _btnHelp.ImageEmbededin = ImageEmbededin.Button;
            _btnHelp.ImagePath = "";
            _btnHelp.InactiveBorderColor = Color.Gray;
            _btnHelp.IndicatorLineColor = Color.Red;
            _btnHelp.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath9.FillMode = FillMode.Alternate;
            _btnHelp.InnerShape = graphicsPath9;
            _btnHelp.IsAcceptButton = false;
            _btnHelp.IsBorderAffectedByTheme = true;
            _btnHelp.IsCancelButton = false;
            _btnHelp.IsChild = false;
            _btnHelp.IsColorFromTheme = true;
            _btnHelp.IsCustomeBorder = false;
            _btnHelp.IsDefault = false;
            _btnHelp.IsDeleted = false;
            _btnHelp.IsDirty = false;
            _btnHelp.IsEditable = true;
            _btnHelp.IsFocused = false;
            _btnHelp.IsFrameless = false;
            _btnHelp.IsHovered = false;
            _btnHelp.IsNew = false;
            _btnHelp.IsPopupOpen = false;
            _btnHelp.IsPressed = false;
            _btnHelp.IsReadOnly = false;
            _btnHelp.IsRequired = false;
            _btnHelp.IsRounded = true;
            _btnHelp.IsRoundedAffectedByTheme = true;
            _btnHelp.IsSelected = false;
            _btnHelp.IsSelectedOptionOn = false;
            _btnHelp.IsShadowAffectedByTheme = true;
            _btnHelp.IsSideMenuChild = false;
            _btnHelp.IsStillButton = false;
            _btnHelp.IsTransparentBackground = false;
            _btnHelp.IsValid = true;
            _btnHelp.IsVisible = true;
            _btnHelp.LabelPosition = LabelPosition.Left;
            _btnHelp.LabelText = "";
            _btnHelp.LabelTextOn = false;
            _btnHelp.LeadingIconPath = "";
            _btnHelp.LeadingImagePath = "";
            _btnHelp.LeftoffsetForDrawingRect = 0;
            _btnHelp.LinkedProperty = null;
            _btnHelp.Location = new Point(243, 13);
            _btnHelp.Margin = new Padding(10, 3, 3, 3);
            _btnHelp.MaxHitListDrawPerFrame = 0;
            _btnHelp.MaxImageSize = new Size(16, 16);
            _btnHelp.ModernGradientType = ModernGradientType.None;
            _btnHelp.Name = "_btnHelp";
            _btnHelp.OuterShape = null;
            _btnHelp.OverrideFontSize = TypeStyleFontSize.None;
            _btnHelp.PainterKind = BaseControlPainterKind.Classic;
            _btnHelp.ParentBackColor = Color.Empty;
            _btnHelp.ParentControl = null;
            _btnHelp.PopPosition = BeepPopupFormPosition.Bottom;
            _btnHelp.PopupListForm = null;
            _btnHelp.PopupMode = false;
            _btnHelp.PressedBackColor = Color.FromArgb(205, 218, 236);
            _btnHelp.PressedBorderColor = Color.DarkGray;
            _btnHelp.PressedForeColor = Color.FromArgb(38, 44, 57);
            _btnHelp.RadialCenter = (PointF)resources.GetObject("_btnHelp.RadialCenter");
            _btnHelp.RightoffsetForDrawingRect = 0;
            _btnHelp.SavedGuidID = null;
            _btnHelp.SavedID = null;
            _btnHelp.ScaleMode = ImageScaleMode.KeepAspectRatio;
            _btnHelp.SelectedBackColor = Color.FromArgb(31, 95, 255);
            _btnHelp.SelectedBorderColor = Color.Green;
            _btnHelp.SelectedForeColor = Color.FromArgb(255, 255, 255);
            _btnHelp.SelectedIndex = 0;
            _btnHelp.SelectedItem = null;
            _btnHelp.ShadowColor = Color.Black;
            _btnHelp.ShadowOffset = 3;
            _btnHelp.ShadowOpacity = 0.25F;
            _btnHelp.ShowAllBorders = false;
            _btnHelp.ShowBottomBorder = false;
            _btnHelp.ShowFocusIndicator = false;
            _btnHelp.ShowIndicatorLine = false;
            _btnHelp.ShowLabelAboveBorder = false;
            _btnHelp.ShowLeftBorder = false;
            _btnHelp.ShowRightBorder = false;
            _btnHelp.ShowShadow = false;
            _btnHelp.ShowTopBorder = false;
            _btnHelp.Size = new Size(80, 34);
            _btnHelp.SlideFrom = SlideDirection.Left;
            _btnHelp.SplashColor = Color.Empty;
            _btnHelp.StaticNotMoving = false;
            _btnHelp.TabIndex = 2;
            _btnHelp.TempBackColor = Color.LightGray;
            _btnHelp.Text = "Help";
            _btnHelp.TextAlign = ContentAlignment.MiddleCenter;
            _btnHelp.TextFont = new Font("Segoe UI", 10F);
            _btnHelp.TextImageRelation = TextImageRelation.ImageBeforeText;
            _btnHelp.Theme = "ModernTheme";
            _btnHelp.TooltipFont = null;
            _btnHelp.TooltipMaxSize = null;
            _btnHelp.ToolTipText = "";
            _btnHelp.TopoffsetForDrawingRect = 0;
            _btnHelp.TrailingIconPath = "";
            _btnHelp.TrailingImagePath = "";
            _btnHelp.UseExternalBufferedGraphics = true;
            _btnHelp.UseFormStylePaint = true;
            _btnHelp.UseGlassmorphism = false;
            _btnHelp.UseGradientBackground = false;
            _btnHelp.UseScaledFont = false;
            _btnHelp.UseThemeFont = true;
            _btnHelp.ValidationIcon = Badges.ValidationState.None;
            _btnHelp.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            _btnHelp.Visible = false;
            _btnHelp.Click += BtnHelp_Click;
            // 
            // _btnBack
            // 
            _btnBack.Anchor = AnchorStyles.Right;
            _btnBack.AnimationDuration = 500;
            _btnBack.AnimationType = DisplayAnimationType.None;
            _btnBack.ApplyThemeOnImage = false;
            _btnBack.ApplyThemeToChilds = true;
            _btnBack.AutoDrawHitListComponents = true;
            _btnBack.AutoSizeContent = false;
            _btnBack.BackColor = Color.FromArgb(232, 238, 248);
            _btnBack.BadgeBackColor = Color.Red;
            _btnBack.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            _btnBack.BadgeForeColor = Color.White;
            _btnBack.BadgeShape = BadgeShape.Circle;
            _btnBack.BlockID = null;
            _btnBack.BorderColor = Color.FromArgb(200, 200, 200);
            _btnBack.BorderDashStyle = DashStyle.Solid;
            _btnBack.BorderPainter = BeepControlStyle.Modern;
            graphicsPath10.FillMode = FillMode.Alternate;
            _btnBack.BorderPath = graphicsPath10;
            _btnBack.BorderRadius = 8;
            _btnBack.BorderRect = new Rectangle(1, 1, 97, 33);
            _btnBack.BorderStyle = BorderStyle.FixedSingle;
            _btnBack.BorderThickness = 2;
            _btnBack.BottomoffsetForDrawingRect = 0;
            _btnBack.BoundProperty = null;
            _btnBack.ButtonMinSize = new Size(32, 32);
            _btnBack.ButtonType = ButtonType.Normal;
            _btnBack.CanBeFocused = true;
            _btnBack.CanBeHovered = true;
            _btnBack.CanBePressed = true;
            _btnBack.CanBeSelected = true;
            _btnBack.Category = Utilities.DbFieldCategory.Boolean;
            _btnBack.ComponentName = "BaseControl";
            _btnBack.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath11.FillMode = FillMode.Alternate;
            _btnBack.ContentShape = graphicsPath11;
            _btnBack.ControlStyle = BeepControlStyle.Modern;
            _btnBack.CustomIconColor = Color.Black;
            _btnBack.CustomIconPath = "";
            _btnBack.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            _btnBack.CustomPadding = new Padding(0);
            _btnBack.DataContext = null;
            _btnBack.DataSourceProperty = null;
            _btnBack.DisabledBackColor = Color.FromArgb(244, 246, 252);
            _btnBack.DisabledBorderColor = Color.Gray;
            _btnBack.DisabledForeColor = Color.FromArgb(222, 223, 229);
            _btnBack.DrawingRect = new Rectangle(3, 3, 93, 29);
            _btnBack.Easing = EasingType.Linear;
            _btnBack.Enabled = false;
            _btnBack.EnableHighQualityRendering = true;
            _btnBack.EnableRippleEffect = false;
            _btnBack.EnableSplashEffect = false;
            _btnBack.ErrorColor = Color.FromArgb(211, 47, 47);
            _btnBack.ErrorText = "";
            _btnBack.ExternalDrawingLayer = DrawingLayer.AfterAll;
            _btnBack.FieldID = null;
            _btnBack.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            _btnBack.FloatingLabel = "";
            _btnBack.FloatingLabelOn = false;
            _btnBack.FocusBackColor = Color.FromArgb(31, 95, 255);
            _btnBack.FocusBorderColor = Color.RoyalBlue;
            _btnBack.FocusForeColor = Color.FromArgb(255, 255, 255);
            _btnBack.FocusIndicatorColor = Color.RoyalBlue;
            _btnBack.ForeColor = Color.FromArgb(38, 44, 57);
            _btnBack.Form = null;
            _btnBack.GlassmorphismBlur = 10F;
            _btnBack.GlassmorphismOpacity = 0.1F;
            _btnBack.GradientAngle = 0F;
            _btnBack.GradientDirection = LinearGradientMode.Horizontal;
            _btnBack.GradientEndColor = Color.Gray;
            _btnBack.GradientStartColor = Color.LightGray;
            _btnBack.GridMode = false;
            _btnBack.GuidID = "93c270cd-6bed-4104-bdd2-6571fd33ba50";
            _btnBack.HasError = false;
            _btnBack.HelperText = "";
            _btnBack.HelperTextOn = false;
            _btnBack.HideText = false;
            _btnBack.HitAreaEventOn = false;
            _btnBack.HitTestControl = null;
            _btnBack.HoverBackColor = Color.FromArgb(220, 229, 242);
            _btnBack.HoverBorderColor = Color.Blue;
            _btnBack.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            _btnBack.HoverForeColor = Color.FromArgb(38, 44, 57);
            _btnBack.IconKey = "";
            _btnBack.IconSize = 20;
            _btnBack.Id = -1;
            _btnBack.Image = null;
            _btnBack.ImageAlign = ContentAlignment.MiddleLeft;
            _btnBack.ImageClicked = null;
            _btnBack.ImageEmbededin = ImageEmbededin.Button;
            _btnBack.ImagePath = "";
            _btnBack.InactiveBorderColor = Color.Gray;
            _btnBack.IndicatorLineColor = Color.Red;
            _btnBack.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath12.FillMode = FillMode.Alternate;
            _btnBack.InnerShape = graphicsPath12;
            _btnBack.IsAcceptButton = false;
            _btnBack.IsBorderAffectedByTheme = true;
            _btnBack.IsCancelButton = false;
            _btnBack.IsChild = false;
            _btnBack.IsColorFromTheme = true;
            _btnBack.IsCustomeBorder = false;
            _btnBack.IsDefault = false;
            _btnBack.IsDeleted = false;
            _btnBack.IsDirty = false;
            _btnBack.IsEditable = true;
            _btnBack.IsFocused = false;
            _btnBack.IsFrameless = false;
            _btnBack.IsHovered = false;
            _btnBack.IsNew = false;
            _btnBack.IsPopupOpen = false;
            _btnBack.IsPressed = false;
            _btnBack.IsReadOnly = false;
            _btnBack.IsRequired = false;
            _btnBack.IsRounded = true;
            _btnBack.IsRoundedAffectedByTheme = true;
            _btnBack.IsSelected = false;
            _btnBack.IsSelectedOptionOn = false;
            _btnBack.IsShadowAffectedByTheme = true;
            _btnBack.IsSideMenuChild = false;
            _btnBack.IsStillButton = false;
            _btnBack.IsTransparentBackground = false;
            _btnBack.IsValid = true;
            _btnBack.IsVisible = true;
            _btnBack.LabelPosition = LabelPosition.Left;
            _btnBack.LabelText = "";
            _btnBack.LabelTextOn = false;
            _btnBack.LeadingIconPath = "";
            _btnBack.LeadingImagePath = "";
            _btnBack.LeftoffsetForDrawingRect = 0;
            _btnBack.LinkedProperty = null;
            _btnBack.Location = new Point(499, 12);
            _btnBack.Margin = new Padding(0);
            _btnBack.MaxHitListDrawPerFrame = 0;
            _btnBack.MaxImageSize = new Size(16, 16);
            _btnBack.ModernGradientType = ModernGradientType.None;
            _btnBack.Name = "_btnBack";
            _btnBack.OuterShape = null;
            _btnBack.OverrideFontSize = TypeStyleFontSize.None;
            _btnBack.PainterKind = BaseControlPainterKind.Classic;
            _btnBack.ParentBackColor = Color.Empty;
            _btnBack.ParentControl = null;
            _btnBack.PopPosition = BeepPopupFormPosition.Bottom;
            _btnBack.PopupListForm = null;
            _btnBack.PopupMode = false;
            _btnBack.PressedBackColor = Color.FromArgb(205, 218, 236);
            _btnBack.PressedBorderColor = Color.DarkGray;
            _btnBack.PressedForeColor = Color.FromArgb(38, 44, 57);
            _btnBack.RadialCenter = (PointF)resources.GetObject("_btnBack.RadialCenter");
            _btnBack.RightoffsetForDrawingRect = 0;
            _btnBack.SavedGuidID = null;
            _btnBack.SavedID = null;
            _btnBack.ScaleMode = ImageScaleMode.KeepAspectRatio;
            _btnBack.SelectedBackColor = Color.FromArgb(31, 95, 255);
            _btnBack.SelectedBorderColor = Color.Green;
            _btnBack.SelectedForeColor = Color.FromArgb(255, 255, 255);
            _btnBack.SelectedIndex = 0;
            _btnBack.SelectedItem = null;
            _btnBack.ShadowColor = Color.Black;
            _btnBack.ShadowOffset = 3;
            _btnBack.ShadowOpacity = 0.25F;
            _btnBack.ShowAllBorders = false;
            _btnBack.ShowBottomBorder = false;
            _btnBack.ShowFocusIndicator = false;
            _btnBack.ShowIndicatorLine = false;
            _btnBack.ShowLabelAboveBorder = false;
            _btnBack.ShowLeftBorder = false;
            _btnBack.ShowRightBorder = false;
            _btnBack.ShowShadow = false;
            _btnBack.ShowTopBorder = false;
            _btnBack.Size = new Size(100, 36);
            _btnBack.SlideFrom = SlideDirection.Left;
            _btnBack.SplashColor = Color.Empty;
            _btnBack.StaticNotMoving = false;
            _btnBack.TabIndex = 3;
            _btnBack.TempBackColor = Color.LightGray;
            _btnBack.Text = "Back";
            _btnBack.TextAlign = ContentAlignment.MiddleCenter;
            _btnBack.TextFont = new Font("Segoe UI", 10F);
            _btnBack.TextImageRelation = TextImageRelation.ImageBeforeText;
            _btnBack.Theme = "ModernTheme";
            _btnBack.TooltipFont = null;
            _btnBack.TooltipMaxSize = null;
            _btnBack.ToolTipText = "";
            _btnBack.TopoffsetForDrawingRect = 0;
            _btnBack.TrailingIconPath = "";
            _btnBack.TrailingImagePath = "";
            _btnBack.UseExternalBufferedGraphics = true;
            _btnBack.UseFormStylePaint = true;
            _btnBack.UseGlassmorphism = false;
            _btnBack.UseGradientBackground = false;
            _btnBack.UseScaledFont = false;
            _btnBack.UseThemeFont = true;
            _btnBack.ValidationIcon = Badges.ValidationState.None;
            _btnBack.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            _btnBack.Click += BtnBack_Click;
            // 
            // _btnNext
            // 
            _btnNext.Anchor = AnchorStyles.Right;
            _btnNext.AnimationDuration = 500;
            _btnNext.AnimationType = DisplayAnimationType.None;
            _btnNext.ApplyThemeOnImage = false;
            _btnNext.ApplyThemeToChilds = true;
            _btnNext.AutoDrawHitListComponents = true;
            _btnNext.AutoSizeContent = false;
            _btnNext.BackColor = Color.FromArgb(232, 238, 248);
            _btnNext.BadgeBackColor = Color.Red;
            _btnNext.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            _btnNext.BadgeForeColor = Color.White;
            _btnNext.BadgeShape = BadgeShape.Circle;
            _btnNext.BlockID = null;
            _btnNext.BorderColor = Color.FromArgb(200, 200, 200);
            _btnNext.BorderDashStyle = DashStyle.Solid;
            _btnNext.BorderPainter = BeepControlStyle.Modern;
            graphicsPath13.FillMode = FillMode.Alternate;
            _btnNext.BorderPath = graphicsPath13;
            _btnNext.BorderRadius = 8;
            _btnNext.BorderRect = new Rectangle(1, 1, 117, 31);
            _btnNext.BorderStyle = BorderStyle.FixedSingle;
            _btnNext.BorderThickness = 2;
            _btnNext.BottomoffsetForDrawingRect = 0;
            _btnNext.BoundProperty = null;
            _btnNext.ButtonMinSize = new Size(32, 32);
            _btnNext.ButtonType = ButtonType.Normal;
            _btnNext.CanBeFocused = true;
            _btnNext.CanBeHovered = true;
            _btnNext.CanBePressed = true;
            _btnNext.CanBeSelected = true;
            _btnNext.Category = Utilities.DbFieldCategory.Boolean;
            _btnNext.ComponentName = "BaseControl";
            _btnNext.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath14.FillMode = FillMode.Alternate;
            _btnNext.ContentShape = graphicsPath14;
            _btnNext.ControlStyle = BeepControlStyle.Modern;
            _btnNext.CustomIconColor = Color.Black;
            _btnNext.CustomIconPath = "";
            _btnNext.CustomIconPosition = Badges.BadgeAnchor.TopRight;
            _btnNext.CustomPadding = new Padding(0);
            _btnNext.DataContext = null;
            _btnNext.DataSourceProperty = null;
            _btnNext.DisabledBackColor = Color.FromArgb(244, 246, 252);
            _btnNext.DisabledBorderColor = Color.Gray;
            _btnNext.DisabledForeColor = Color.FromArgb(222, 223, 229);
            _btnNext.DrawingRect = new Rectangle(3, 3, 113, 27);
            _btnNext.Easing = EasingType.Linear;
            _btnNext.EnableHighQualityRendering = true;
            _btnNext.EnableRippleEffect = false;
            _btnNext.EnableSplashEffect = false;
            _btnNext.ErrorColor = Color.FromArgb(211, 47, 47);
            _btnNext.ErrorText = "";
            _btnNext.ExternalDrawingLayer = DrawingLayer.AfterAll;
            _btnNext.FieldID = null;
            _btnNext.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            _btnNext.FloatingLabel = "";
            _btnNext.FloatingLabelOn = false;
            _btnNext.FocusBackColor = Color.FromArgb(31, 95, 255);
            _btnNext.FocusBorderColor = Color.RoyalBlue;
            _btnNext.FocusForeColor = Color.FromArgb(255, 255, 255);
            _btnNext.FocusIndicatorColor = Color.RoyalBlue;
            _btnNext.ForeColor = Color.FromArgb(38, 44, 57);
            _btnNext.Form = null;
            _btnNext.GlassmorphismBlur = 10F;
            _btnNext.GlassmorphismOpacity = 0.1F;
            _btnNext.GradientAngle = 0F;
            _btnNext.GradientDirection = LinearGradientMode.Horizontal;
            _btnNext.GradientEndColor = Color.Gray;
            _btnNext.GradientStartColor = Color.LightGray;
            _btnNext.GridMode = false;
            _btnNext.GuidID = "bdc043d2-5092-4650-ab4b-f88a7efa448f";
            _btnNext.HasError = false;
            _btnNext.HelperText = "";
            _btnNext.HelperTextOn = false;
            _btnNext.HideText = false;
            _btnNext.HitAreaEventOn = false;
            _btnNext.HitTestControl = null;
            _btnNext.HoverBackColor = Color.FromArgb(220, 229, 242);
            _btnNext.HoverBorderColor = Color.Blue;
            _btnNext.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            _btnNext.HoverForeColor = Color.FromArgb(38, 44, 57);
            _btnNext.IconKey = "";
            _btnNext.IconSize = 20;
            _btnNext.Id = -1;
            _btnNext.Image = null;
            _btnNext.ImageAlign = ContentAlignment.MiddleLeft;
            _btnNext.ImageClicked = null;
            _btnNext.ImageEmbededin = ImageEmbededin.Button;
            _btnNext.ImagePath = "";
            _btnNext.InactiveBorderColor = Color.Gray;
            _btnNext.IndicatorLineColor = Color.Red;
            _btnNext.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath15.FillMode = FillMode.Alternate;
            _btnNext.InnerShape = graphicsPath15;
            _btnNext.IsAcceptButton = false;
            _btnNext.IsBorderAffectedByTheme = true;
            _btnNext.IsCancelButton = false;
            _btnNext.IsChild = false;
            _btnNext.IsColorFromTheme = true;
            _btnNext.IsCustomeBorder = false;
            _btnNext.IsDefault = false;
            _btnNext.IsDeleted = false;
            _btnNext.IsDirty = false;
            _btnNext.IsEditable = true;
            _btnNext.IsFocused = false;
            _btnNext.IsFrameless = false;
            _btnNext.IsHovered = false;
            _btnNext.IsNew = false;
            _btnNext.IsPopupOpen = false;
            _btnNext.IsPressed = false;
            _btnNext.IsReadOnly = false;
            _btnNext.IsRequired = false;
            _btnNext.IsRounded = true;
            _btnNext.IsRoundedAffectedByTheme = true;
            _btnNext.IsSelected = false;
            _btnNext.IsSelectedOptionOn = false;
            _btnNext.IsShadowAffectedByTheme = true;
            _btnNext.IsSideMenuChild = false;
            _btnNext.IsStillButton = false;
            _btnNext.IsTransparentBackground = false;
            _btnNext.IsValid = true;
            _btnNext.IsVisible = true;
            _btnNext.LabelPosition = LabelPosition.Left;
            _btnNext.LabelText = "";
            _btnNext.LabelTextOn = false;
            _btnNext.LeadingIconPath = "";
            _btnNext.LeadingImagePath = "";
            _btnNext.LeftoffsetForDrawingRect = 0;
            _btnNext.LinkedProperty = null;
            _btnNext.Location = new Point(609, 13);
            _btnNext.Margin = new Padding(10, 3, 3, 3);
            _btnNext.MaxHitListDrawPerFrame = 0;
            _btnNext.MaxImageSize = new Size(16, 16);
            _btnNext.ModernGradientType = ModernGradientType.None;
            _btnNext.Name = "_btnNext";
            _btnNext.OuterShape = null;
            _btnNext.OverrideFontSize = TypeStyleFontSize.None;
            _btnNext.PainterKind = BaseControlPainterKind.Classic;
            _btnNext.ParentBackColor = Color.Empty;
            _btnNext.ParentControl = null;
            _btnNext.PopPosition = BeepPopupFormPosition.Bottom;
            _btnNext.PopupListForm = null;
            _btnNext.PopupMode = false;
            _btnNext.PressedBackColor = Color.FromArgb(205, 218, 236);
            _btnNext.PressedBorderColor = Color.DarkGray;
            _btnNext.PressedForeColor = Color.FromArgb(38, 44, 57);
            _btnNext.RadialCenter = (PointF)resources.GetObject("_btnNext.RadialCenter");
            _btnNext.RightoffsetForDrawingRect = 0;
            _btnNext.SavedGuidID = null;
            _btnNext.SavedID = null;
            _btnNext.ScaleMode = ImageScaleMode.KeepAspectRatio;
            _btnNext.SelectedBackColor = Color.FromArgb(31, 95, 255);
            _btnNext.SelectedBorderColor = Color.Green;
            _btnNext.SelectedForeColor = Color.FromArgb(255, 255, 255);
            _btnNext.SelectedIndex = 0;
            _btnNext.SelectedItem = null;
            _btnNext.ShadowColor = Color.Black;
            _btnNext.ShadowOffset = 3;
            _btnNext.ShadowOpacity = 0.25F;
            _btnNext.ShowAllBorders = false;
            _btnNext.ShowBottomBorder = false;
            _btnNext.ShowFocusIndicator = false;
            _btnNext.ShowIndicatorLine = false;
            _btnNext.ShowLabelAboveBorder = false;
            _btnNext.ShowLeftBorder = false;
            _btnNext.ShowRightBorder = false;
            _btnNext.ShowShadow = false;
            _btnNext.ShowTopBorder = false;
            _btnNext.Size = new Size(120, 34);
            _btnNext.SlideFrom = SlideDirection.Left;
            _btnNext.SplashColor = Color.Empty;
            _btnNext.StaticNotMoving = false;
            _btnNext.TabIndex = 4;
            _btnNext.TempBackColor = Color.LightGray;
            _btnNext.Text = "Next";
            _btnNext.TextAlign = ContentAlignment.MiddleCenter;
            _btnNext.TextFont = new Font("Segoe UI", 10F);
            _btnNext.TextImageRelation = TextImageRelation.ImageBeforeText;
            _btnNext.Theme = "ModernTheme";
            _btnNext.TooltipFont = null;
            _btnNext.TooltipMaxSize = null;
            _btnNext.ToolTipText = "";
            _btnNext.TopoffsetForDrawingRect = 0;
            _btnNext.TrailingIconPath = "";
            _btnNext.TrailingImagePath = "";
            _btnNext.UseExternalBufferedGraphics = true;
            _btnNext.UseFormStylePaint = true;
            _btnNext.UseGlassmorphism = false;
            _btnNext.UseGradientBackground = false;
            _btnNext.UseScaledFont = false;
            _btnNext.UseThemeFont = true;
            _btnNext.ValidationIcon = Badges.ValidationState.None;
            _btnNext.ValidationIconPosition = Badges.BadgeAnchor.TopRight;
            _btnNext.Click += BtnNext_Click;
            // 
            // MinimalWizardForm
            // 
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(752, 589);
            Controls.Add(_root);
            KeyPreview = true;
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "MinimalWizardForm";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Wizard";
            _root.ResumeLayout(false);
            _errorPanel.ResumeLayout(false);
            _buttonPanel.ResumeLayout(false);
            ResumeLayout(false);
        }
    }
}
